lua/nvim-treesitter.lua
lua/nvim-treesitter/install.lua
parser/.gitignore

this is a work in progress, windows support is not available currently, and we might change the download paths in unix.
this PR adds an 'install_parser' command available through the plugin api:
`:lua require'nvim-treesitter'.install_parser('c')`.
Only javascript and c are configured at the moment, but others can be added quite easily.

feat: add parser installer

---

lua/nvim-treesitter.lua
lua/nvim-treesitter/locals.lua
lua/nvim-treesitter/parsers.lua
lua/nvim-treesitter/query.lua
plugin/nvim-treesitter.vim
queries/lua/locals.scm

Locals are the proposed way to interact with treesitter, through basic functions to get all definitions, references, scopes, etc.
This is a draft of how it should work, the thing that we might discuss is the fact taht locals are refreshed on every buffer update. This could cause some performances issues in some cases, though I didn't encountered any.

Add locals handling

---

lua/nvim-treesitter/install.lua

fixes #9. Use a `repository.location` to compile at certain place. A `compile_location` variable is declared before configuring the commands to launch.
Typescript and Tsx parsers will need to be downloaded one at a time.

feat: enable typescript and tsx install 

---

lua/nvim-treesitter/install.lua

- clone only master at depth 1 to avoid long download from huge repos.
- use ft to specify folder name to clone so csharp can be cloned and
used properly.

refacto/feat: enable csharp install, fix clone

---

lua/nvim-treesitter/install.lua

- fix parser install
- format install.lua
Parser installer was using `unpack(repo.files)` which didn't unpack properly. Using `vim.tbl_flatten({args,repo.files})` allows to expand source files in the command configurations for the compilation process.

fix: parser install unpack > tbl_flatten

---

lua/nvim-treesitter.lua
lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/health.lua
lua/nvim-treesitter/install.lua
plugin/nvim-treesitter.vim

- configs.lua holds the `repositories` data
- install health moved to `health.lua`
- plugins loads _root.setup() on startup
- install and list command are available through vim
> use them with `:TSInstall lang` and `:TSInstallInfo`
note: this is working, but code organization is quite messy in my opinion.
- the `available_parsers` function in `nvim-treesitter.lua` must be moved somewhere else
- the `health.lua` file needs better naming for the health_config function
- the health function in locals might need to be moved inside the health file.

feat/refacto: add configs.lua, setup install cmd

---

lua/nvim-treesitter.lua
lua/nvim-treesitter/highlight.lua
lua/nvim-treesitter/query.lua
queries/lua/highlights.scm

Rought draft of syntax highlighting.
Is uses a `highlights.scm` query file, and an example `lua` query is provided.
One thing to consider is the `ERROR` node, which is built in treesitter and we might want to move it out of the query itself.
Some other things to consider are :
- `is?` and `is-not?` predicates, which would allow us to have really powerful syntax highlighting
- naming conventions for highlight groups
- Do we have to use the builtin `TSHighlighter` or do we use our own highlighter based on a copy of the builtin on ?

Syntax highlighting

---

lua/nvim-treesitter/install.lua

On some of my system, `-fPIC` is required when compiling shared library. Adding `-fPIC` flag should also be fine on other system([reference](https://stackoverflow.com/questions/966960/what-does-fpic-mean-when-building-a-shared-library))

fix: add -fPIC flag to compiling

---

README.md

Properly Capitalized Treesitter and Neovim, removed extra space before exclamation points and fixed spelling errors.

Fix spelling inconsistencies

---

lua/nvim-treesitter.lua
lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/health.lua
lua/nvim-treesitter/highlight.lua
lua/nvim-treesitter/info.lua
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/utils.lua
plugin/nvim-treesitter.vim

- You should now get the configs through functions
- Configs for languages are now inside a local object called parsers
- You can get the parser installation configurations with `get_parser_configs`
- A new object has been initialized inside configs to specify module config (called config).
- Provide functions to enable/disable a module on one buffer
- Provide functions to enable/disable a module on all buffers, and if filetype is
specified, for specific filetype
- Provide function to determine if module is activated for a specified filetype
- new functions to enable and disable filetypes on modules.
to setup the plugin:
```vim
lua<<EOF
require'nvim-treesitter.configs'.setup {
highlight = {
enable = true,
disable = {'c', 'rust'},
}
}
EOF
```
**TODO**
**NOTE**
Every module must provide …

feat/refacto: add user interactions, improve configurations

---

lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/install.lua

Hello,
I was trying to create a function that users could put into their config to ensure that their favorite languages are parsers installed or get installed if not yet available.
Currently, you can do:
```
require'nvim-treesitter/install'.ensure_installed({'html', 'python'})
```
or just one language
```
require'nvim-treesitter/install'.ensure_installed('cpp')
```
or all available languages
```
require'nvim-treesitter/install'.ensure_installed('all')
```
I am not sure where to put this function in your repo structure and whether really all requested parsers get installed (the status only shows when a particular languages got installed). So I am looking forward for feedback!

Add function 'nvim-treesitter/install'.ensure_installed

---

README.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/node_movement.lua
lua/nvim-treesitter/utils.lua

First draft for tree-sitter-base movement:
Those mappings let you move in the documents node hierarchy:
```
nmap <a-k> :lua require'nvim-treesitter/node-movement'.move_up()<cr>
nmap <a-h> :lua require'nvim-treesitter/node-movement'.move_left()<cr>
nmap <a-l> :lua require'nvim-treesitter/node-movement'.move_right()<cr>
nmap <a-j> :lua require'nvim-treesitter/node-movement'.move_down()<cr>
```

Add 'nvim-treesitter/node-movement'

---

README.md
autoload/nvim_treesitter.vim
doc/nvim-treesitter.txt
doc/tags
lua/nvim-treesitter.lua
lua/nvim-treesitter/parsers.lua

It will show the current branch at the cursor going the tree as such.
root->node->subnode->leaf
If an argument is provided to `statusline`, then the tree will be
truncated as follows :
..->subnode->subnode
Also fixes an issue with `expression_at_point`.

Provide a statusline indicator

---

CONTRIBUTING.md
lua/nvim-treesitter/highlight.lua
lua/nvim-treesitter/locals.lua
queries/lua/highlights.scm
queries/lua/locals.scm

Some things are still left to do :
A question remains for `highiligts.scm` though, we may want to change a bit how it is done upstream and thus rewrite a highlighter of our own. I'll investigate a way to solve this when I have some time.

Add CONTRIBUTING.md

---

queries/ruby/highlights.scm
queries/ruby/locals.scm

I've replaced the generic highlight groups with the ones that we've defined, and made a few of the capture groups more specific based on what we've made available.

Update ruby highlights and locals to conform to contributing.md

---

README.md
doc/nvim-treesitter.txt
lua/nvim-treesitter.lua
lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/health.lua
lua/nvim-treesitter/highlight.lua
lua/nvim-treesitter/incremental_selection.lua
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/locals.lua
lua/nvim-treesitter/node_movement.lua
lua/nvim-treesitter/query.lua
lua/nvim-treesitter/state.lua
lua/nvim-treesitter/ts_utils.lua
lua/nvim-treesitter/utils.lua

Notes:
I didn't add the textobj module because i want this to be merged first.
Also the node_movement now works by moving between scopes, but will be disabled for languages without locals definitions.
To move with node movement, you need to define `parent_scope` `child_scope` `next_scope` and `previous_scope`.
For the node_movement to work as expected, the `locals.scm` should be describing the scopes as properly as they can, otherwise, it might be confusing for users to move around (right now, lua scopes are not complete at all). Also this will probably make it easier to create scopes as you can see what happens when you move from scope to scope.
I will add the documentation once this will be reviewed and tested properly.
features:
improvements:
```lua
{
cursor_pos = { row=row, col=col }, …
```

refacto/feat: better handling of parser updates

---

doc/nvim-treesitter.txt

`README.md` has it, but the doc text file is missing `EOF` at the end of the block.

docs: missing EOF for init.vim

---

queries/c/locals.scm

- Fix function scope (was declaration only without body)
- Use @definition.var like the other local files (lua, ruby)
- Add translation_unit scope
~~- Add variable definitions by function parameters~~ not necessary! Already included in available queries.
I was experimenting with resolving variables for GCC and accidentally adapted the C locals.scm a bit. @vigoux, maybe some changes of this PR are useful...

Some improvements to c/locals.scm

---

README.md
autoload/nvim_treesitter.vim
doc/nvim-treesitter.txt
doc/tags
lua/nvim-treesitter/fold.lua

This PR brings a new lightweight `fold` module. As folding is only line based for now, how folding works can be quite distrurbing for now (but useful in many cases). When https://github.com/neovim/neovim/pull/12194 will land and some further lua apis will be available, it will be easy to have syntax-based column folding.

Treesitter based code folding.

---

queries/python/highlights.scm

- Highlight types in attributes as @type (**Foo**.a)
- Highlight superclasses @type
- Highlight ^[A-Z] as @type
- Highlight isinstance(*, type) as @type
- Highlight default_parameter and keyword_argument as @parameter
- Highlight *args, **kwargs as @parameter
- Highlight -> as @operator (my PR for this was merged to upstream tree-sitter-python)

Improve Python highlights

---

README.md
doc/nvim-treesitter.txt

This is node_decremental as in
https://github.com/nvim-treesitter/nvim-treesitter/blob/d73988a90782decafa0115e0e935bf86256f43b7/lua/nvim-treesitter/configs.lua#L226
I was trying to figure out why my mapping wasn't working.

Fix example mappings

---

README.md
queries/css/highlights.scm

Adds basic queries for highlighting standard css files. Some of the captures will most likely need changing in the future for better uniformity with other filetypes

Add css highlight queries

---

README.md
queries/html/highlights.scm

Add basic html highlight queries, in the future I would like to add the injections for css and javascript

Add html highlight queries

---

queries/html/highlights.scm

This will also highlight the quotes of attributes. @TravonteD 
Before:
After:

html: Highlight (quoted_attribute_value) as @string

---

CONTRIBUTING.md
README.md
queries/go/highlights.scm
queries/go/locals.scm

I never do anything in Go, but when I looked at the syntax highlighting of random Go file in vim I had to do something. Mostly copied from tree-sitter-go.
Right now most tree-sitter-repos get a file `tags.scm` added. They include information on how to extract documentation #58 and defininition for call references. The question is whether we want to have call references.

Go highlights

---

README.md
lua/nvim-treesitter/query.lua

This allows the users to override built in queries. The use can provide their own file in their configuration at `queries/<filetype>/<query_name>.scm`. These files extend the existing query file, not replace it.

feat(queries): allow user query overrides

---

README.md
lua/nvim-treesitter/query.lua
queries/c/highlights.scm
queries/c/locals.scm
queries/cpp/highlights.scm
queries/cpp/locals.scm

This PR should wait for #62 .
Some treesitter grammars just extend another treesitter grammar.
This enables us to use the C queries also for C++.
We only need to put additional queries in the C++ files to support additional C++ features (#52 ).
I would also like to include those additional queries for C++ in this PR to see whether this concept works well. Right now, C++ files have out-of-the-box syntax hightlighting from the C queries.

 Introduce base languages for queries (for C++ locals)

---

lua/nvim-treesitter/query.lua

Use same argument for nvim_get_runtime_file for base language.
Oops, didn't see that the second argument for nvim_get_runtime_file changed. Change it also for the base languages.

Fixup: Introduce base languages for queries

---

queries/javascript/highlights.scm

I missed this in my original pr.

fix(javascript): set booleans to boolean highlights

---

lua/nvim-treesitter.lua
lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/health.lua
lua/nvim-treesitter/highlight.lua
lua/nvim-treesitter/info.lua
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/parsers.lua
lua/nvim-treesitter/query.lua
plugin/nvim-treesitter.vim

fixes #84.
- move parser list in `parsers.lua`. All the code related to the parser is now basically in parsers.lua
- most `ft` variables have been renamed to `lang`, and the switch between those is easier to do with two function:
- `parsers.ft_to_lang(ft) -> lang`
- `parsers.lang_to_ft(lang) -> ft`
- filetypes are now only used when binding autocmd to Filetype on start and on commands like `TSBufEnable` and such. Otherwise, we use the `lang` to match the parser name we want. In the parser list, if a parser name does not match its filetype, we define a key `filetype`.

refacto/fix: filetype / parser name distinction

---

README.md

Should we add some kind of disclaimer to the README to warn users that development of TS highlighting in nvim is not finished?
I am unsure about the text.

WIP: Add disclaimer to README.md

---

queries/ruby/highlights.scm

Fixes the highlighting of symbols when used in pairs with the short hand `symbol: true`

Fix highlighting of symbols used in pairs

---

queries/python/highlights.scm
queries/python/locals.scm

#76
Maybe we should add `@defintion.class`. It's now also in the `tags.scm` of many treesitter repos.

Adapt Python highlights to new query syntax

---

lua/nvim-treesitter/locals.lua

I ran into this when using nvim-treesitter for completion-treesitter. Seems like this is reversed, since the tick is incrementing every time the file changes.

fix(locals): compute locals after later tick

---

lua/nvim-treesitter/install.lua

fixes #108.
TsInstall can take 'all' as parameter and in this case, existing parsers are reinstalled.
Also continues installing parsers when refusing to install existing parsers.

TSInstall can take 'all' as parameter

---

queries/cpp/highlights.scm

Maybe we should create a PR to Nvims query code to have a warning when this happening.

Fix cpp-highlights: wrong capture name used in regex

---

lua/nvim-treesitter.lua
lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/parsers.lua

Enables the use of multiple filetypes for one parser.
You can now say that `zsh` uses the parser for `bash`, or any other ones.
This way you can setup parsers like
```lua
local parserlist = require'nvim-treesitter.parsers'.list
parserlist.some_parser.used_by = {'some_filetype', 'some_other_filetype'}
```
this doesn't fix any issue that i'm aware of, there is still work to do around the language integrations.
this could also be used as a temporary fix to #94 by disabling the typescript parser and use only the tsx one by commenting the typescript parser and adding the `used_by` key in the tsx config with `{ 'typescript' }` in it.

add used_by key to parsers

---

lua/nvim-treesitter/query.lua

Allows using another query file for a language, or use a query file from another language.
fixes #94

Define multiple query for a language

---

queries/c/highlights.scm

Question: Should ":" also be highlighted as an operator if used in the context of "?"? For me, `@delimiter` is also ok.

C highlights: Make ? an operator in c highlights

---

queries/c/highlights.scm
queries/c/locals.scm
queries/cpp/highlights.scm
queries/cpp/locals.scm

This changed the highlight of "switch" to conditional and of "break" to repeat.

C/C++ highlights: update to new syntax

---

.travis.yml
CONTRIBUTING.md
scripts/pre-push
scripts/style-check.sh

It denies pushing when you're not passing luacheck. Has to be copied to `.git/hooks` to activate.

Add pre-push script

---

.github/ISSUE_TEMPLATE/bug_report.md

The output of checkhealth can be quite lengthy.
Preview: https://github.com/theHamsta/nvim-treesitter/blob/details-bug-report/.github/ISSUE_TEMPLATE/bug_report.md

Use <details> for checkhealth output in bug report template

---

README.md
lua/nvim-treesitter.lua
lua/nvim-treesitter/configs.lua

This reworks the module system to allow module definitions to be rendered dynamically.
The module system takes care of a lot of boilerplate (language detection, enable/disable, query detection, buffer attachment, etc...) that could be leveraged if made public. These are the benefits this feature provides:
* Another way to consume this plugin. Plugin authors can just use the utils or right a module to take advantage of the interface this plugin provides.
* Module definitions no longer depend on the ordering of files that are loaded. We can load modules after the plugin is initialized and before or after the user has configured it (setup call). For example, if a plugin creates a module, that plugin could be loaded dynamically (vim-plug or others) without any issues and still get registered …

feat(configs): dynamic module defintions

---

lua/nvim-treesitter/locals.lua
lua/nvim-treesitter/ts_utils.lua

The key api change here was adding the ability to run the locals query on a subset of the tree instead of from the root. This saves us from having to check against all references.

fix(refactor): highlight def perf issue fix

---

queries/python/highlights.scm
queries/python/locals.scm

Parameters can be optionally typed in Python

Python locals: typed_parameter -> @definition.var

---

CONTRIBUTING.md
queries/javascript/locals.scm
queries/python/locals.scm

We could introduce a new kind of definition: `import`
Alternatively, I could also declare Pythons imports as `@definition.var`
Problem: `import skimage.io` defines `skimage` and `io` where it should only define `skimage.io`. 
Edit: maybe this can be solved by a new query for reference.

Introduce @definition.import for Python/Javascript

---

queries/python/highlights.scm

Python highlights: Surround type subscript query with (type ...)

---

queries/c/locals.scm
queries/cpp/locals.scm

Definition of types by:
- using (C++)
- plain struct
Reference of types

C/C++ highlights: Small improvements for type definitions

---

lua/nvim-treesitter/refactor/highlight_definitions.lua

I accidentally changed the highlighting of all other usages to a highlighting of the current node.

Fix highlight of usages after merging highlight_current_scope

---

README.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/incremental_selection.lua
lua/nvim-treesitter/query.lua
lua/nvim-treesitter/textobjects.lua
lua/nvim-treesitter/ts_utils.lua
lua/nvim-treesitter/utils.lua
queries/c/textobjects.scm
queries/cpp/textobjects.scm
queries/python/textobjects.scm
scripts/check-queries.lua

I thought it would be cool if users could define their own text object by queries.
Everything in this PR is not implemented the proper way. The module is just activated for easier review and faster testing.
With the given hard-coded config you can delete a function text object in Python/C++. Maybe the queries should also come from `locals.scm` but this is a more direct way for a user to achieve that for a specific query.
PS: Why was the operator pending mapping removed from `incremental_selection`?

User textobj

---

lua/nvim-treesitter/refactor/navigation.lua

Push a jumplist item when using `goto_definition`.
Fixes #166

feat(refactor.navigation): update jumplist on jump

---

lua/nvim-treesitter/locals.lua
lua/nvim-treesitter/textobjects.lua
lua/nvim-treesitter/ts_utils.lua
queries/cpp/textobjects.scm

Idea shamelessly stolen from: https://github.com/nvim-treesitter/nvim-tree-docs
This allows to include starting positions for textobjects like:
```scheme
(template_declaration
(function_definition
body:  (compound_statement) @function.inner) @function.outer) @function.outer.start
```
when we have
```cpp
template <typename T>
T* givePtr( T& t )
{
return &t;
}
```
also the following c query will match
```scheme
(function_definition
body:  (compound_statement) @function.inner) @function.outer
```
both matches have the same length, though refer to the same thing.
We prefer the query that has earliest start (if any).
Users can use this to attach documentation to text objects.

feat(textobjects): Add `start` to include preceding things like documentation

---

queries/python/textobjects.scm

Include decorators to functions and improve @conditional.inner for conditions of elif statements

Python textobjects: Include @decorators and improve @conditional.inner

---

lua/nvim-treesitter/ts_utils.lua

Be sure to call `parser:parser()` to get a tree instead of getting the
tree directly. This will not cost anything is the buffer is freshly
parsed.
Fixes #181

fix(ts_utils): be sure to parse to get root

---

lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/highlight.lua
lua/nvim-treesitter/incremental_selection.lua
lua/nvim-treesitter/locals.lua
lua/nvim-treesitter/parsers.lua
lua/nvim-treesitter/query.lua
lua/nvim-treesitter/refactor/highlight_current_scope.lua
lua/nvim-treesitter/refactor/highlight_definitions.lua
lua/nvim-treesitter/refactor/navigation.lua
lua/nvim-treesitter/refactor/smart_rename.lua
lua/nvim-treesitter/textobjects.lua
lua/nvim-treesitter/ts_utils.lua

Currently based on #100 
Clean up some stuff after #100 to separate adding a new feature from a refactoring API change

Post user textobject refactor

---

queries/ruby/locals.scm

The highlighting when highlighting references and definitions in ruby
were off. This corrects that by assigning them to their correct properties.

ruby: fix references and definitions in locals

---

queries/c/locals.scm
queries/cpp/locals.scm
queries/rust/locals.scm

This makes smart_rename work also for types out of the box and we don't
need to search for the path of actual node.

Attach kind of reference to query result instead of using subfields

---

queries/go/highlights.scm

Method highlights is overwritten by property because of the ordering.
something like:
Before:
After:
Possibly connected to #198 but on golang instead of python

fixes golang method highlights

---

README.md
lua/nvim-treesitter/highlight.lua
plugin/nvim-treesitter.vim
queries/dart/highlights.scm

This PR adds a few more highlights for dart files, most notably tweaking the regex to match more classes, adding operators and punctuation.
I'd at some later date like to see if the upstream grammar can provide nodes/groups (is that the terminology) for methods calls and class instantiation properly but with these changes the highlighting is much improved (at least when working in flutter, it's already pretty good for a standard dart file)

Improve dart highlights

---

queries/go/locals.scm

```go
for _, num := range numbers {
fmt.Print(num, " ")
}
```

Go locals: range_clause can define variables

---

queries/go/locals.scm

We really have to decide whether or not adopt tree-sitter's `@reference.thing` captures. If yes, we need to update smart refactor to support it.

Go locals: use reference.kind for calls

---

queries/dart/highlights.scm

Dart highlights currently break our CI. Apparently, the grammar has changed upstream. I did some bisecting to deactivate all invalid nodes: @Akin909 
Related: #222 @ray-x

Dart highlighs: disable invalid nodes after parser update to fix CI

---

queries/java/highlights.scm
queries/java/locals.scm

This #204 by @PitcherTear22 , rebased (was very outdate), squashed and extended.
Now, imports are also definitions. The online playground cannot be fully trusted for Java. The parsers version seems to be outdated. The parsed tree for imports was drastically different. Stupid me was testing `first?` `last?` on this :-(
Using the `highlight_current_scope` with this scopes hints for a bug in finding the current scope (e.g. )... Need to investigate more, it works fine for the other languages.
Maybe we need to wait for a simple version of submatch that only requires a specific parent node.

Java locals

---

queries/cpp/locals.scm

C++: locals template_declaration must define their own scope in which their template arguments are valid

Template scope

---

queries/lua/highlights.scm
queries/lua/textobjects.scm

I'm not a lua programmer myself, but these seemed to be missing while reading some lua code. Wasn't able to figure out how to select the inner of the function, maybe it needs to be included in the grammar?.
- Basic textobjects
- Highlighting punctuation symbols

Lua: update some queries

---

README.md
doc/nvim-treesitter.txt

- Fix some typos
- Remove some unnecessary text that was taking space
- Use double quotes in lua examples (this seems to be the convention in
the source code)
- Sort list of languages, so they are easy to find.
Also moved the image after the title, it felt weird having the title below

Docs: rework readme

---

queries/php/highlights.scm
queries/php/locals.scm

Reference and definition queries have been improved as follows
Added definitions for methods, functions, and classes, and all specific names are now referenced.

PHP: Update locals query

---

lua/nvim-treesitter/incremental_selection.lua
lua/nvim-treesitter/refactor/navigation.lua
lua/nvim-treesitter/refactor/smart_rename.lua
lua/nvim-treesitter/textobjects.lua

Mappings shouldn't be affected by other users mappings. For example by: 
```
nnoremap ; :
nnoremap : ;
```

Add noremap option to mappings

---

queries/rust/highlights.scm

* Adds `async` and `await` keywords.
* Fixes some type highlights.

rust: various fixes in highlights

---

lua/nvim-treesitter/locals.lua
lua/nvim-treesitter/parsers.lua

This contains most of the content from https://github.com/nvim-treesitter/nvim-treesitter/pull/264 minus the `is` predicate. This will fix https://github.com/nvim-treesitter/nvim-treesitter/issues/142

fix(locals): fix find definition implementation

---

README.md

We moved to zulip, we will stay on gitter partially but if you want to help in the dev process, or ask questions, it will be better there than on gitter.

docs: advertise zulip instead of gitter

---

queries/rst/textobjects.scm

So, these aren't really classes, but is mostly to make use of https://github.com/nvim-treesitter/nvim-treesitter/pull/218 without creating another mapping (and not sure if there is a way to override a mapping per filetype?).
Anyway, let me know if this makes sense or if you have a suggestion for introducing another group name.

RST: update textobjects

---

plugin/nvim-treesitter.vim

After some discussion in #280 , we came to the conslusion that `Normal` should be use to highlight variables instead of `Identifier`.
@akinsho , as you were the previous commiter there, can you give us your opinion on this too ?

fix(highlight): link TSVariable to Normal

---

README.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/query.lua

Starting now, runtime queries will be sourced in this order :
- Queries that are not in any `after` folder, will serve as a base, with
each occurence overwriting the others (that is, .config/nvim/queries has
the highest priority)
- Queries within the `after` directory will be sourced one after the
other.
The rationale is that this reminds all the `.vim` files (ftplugin) for
example, and this allows both to experiment and to override queries
easily.

feat: intuitive runtime queries

---

lua/nvim-treesitter/query.lua

`after` directory is third parent (not second) of query extension files. 
For example:
```lua
local path = "/home/user/.config/nvim/after/queries/lua/highlights.scm"
print(vim.fn.fnamemodify(path, ":p:h:h:t") ) -- queries
print(vim.fn.fnamemodify(path, ":p:h:h:h:t")) -- after
```

fix: check 'after' against third directory

---

queries/java/highlights.scm

[java] Add label highlight

---

doc/nvim-treesitter.txt

Fix #304 
TSVariable, TSVariableBuiltin are not documented, since they are not used at the moment.
- TSVariable is planned for normal identifiers (currently have no queries)
- TSVariableBuiltin is planned for most stuff that is currently `@constant.builtin` like self, this etc.
See #307

docs(hlgroups): document TSAnnotation, TSCurrentScope, TSDefinition,TSDefinitionUsage

---

queries/python/highlights.scm

- Get rid of @self
- Highlight methods correctly
- Highlight self as the first parameter of a method
- Use new syntax (# for predicates, (_) instead of (*) for wildcards)
I would like to help to maintain the python queries

Python: update highlights

---

doc/nvim-treesitter.txt
lua/nvim-treesitter/parsers.lua
lua/nvim-treesitter/query.lua
queries/javascript/highlights.scm
queries/javascript/jsx.scm

- compute query language extensions *after* default ones
(jsx after javascript)
- remove outdated ts_utils functions from docs
- add better regex detection to javascript
- javascriptreact to use javascript queries
- add javascript.jsx to javascript queries
- write jsx.scm hl file

some refacto, doc fixes and jsx queries

---

README.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/query.lua
lua/nvim-treesitter/refactor/navigation.lua
lua/nvim-treesitter/textobjects.lua
lua/nvim-treesitter/ts_utils.lua
lua/nvim-treesitter/utils.lua
queries/c/textobjects.scm
queries/cpp/textobjects.scm

Swap textobject (thinking mainly of function parameters, statements and functions).
What needs to be done first:
- add @object.inner.end (to catch the big enemy of this feature: line comments)
- don't swap with next node but next textobject of same kind (e.g. also a parameter), take documentation and line comments with it.
- to include adjacent comments into the textobject we need the `adjacent?` predicate
But if you want to swap just parameters it already works now (only failure case: there's a line comment behind a parameter)

Swap textobject

---

queries/javascript/highlights.scm

`queries/javascript/highlights.scm` has a few references to `@function.method`, which is not mentioned at all in `hlmap`. I figured it'd make sense to consolidate these references to `@method`, so they can be highlighted properly.

Rename @function.method to @method

---

README.md
doc/nvim-treesitter.txt

- Replace usage of tabs to spaces
- Document each submodule by separate instead of  having one big example
- Don't duplicate some content from the docs in the readme
- Move some sections (like languages)
- Change headers so quickstart doesn't include the whole readme. 
- Document all capture groups used in {hightlights,textobjects,locals}.scm
- Improve docs for contributing

Docs: documentation for modules/submodules

---

queries/c/highlights.scm
queries/cpp/highlights.scm

This highlights `void foo(int* a);` and `int& a`, `int&&&& a` as parameters.

feat(c/cpp highlights): highlight pointer/reference parameters

---

queries/ocaml/hightlights.scm

It's missing function usages and arguments, but they are represented by the same type of node in the same list, it wasn't clear to me how to match the first item of the list only, and the others.
For the rest it should be pretty complete but I might have missed some advanced syntax, especially regarding types.

Add highlights for OCaml.

---

lua/nvim-treesitter/health.lua

This is to avoid awfully long checkhealths. And not installed parsers can be infered from the fact that they are not listed.

fix(health): only check installed parsers

---

README.md
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/utils.lua

This PR adds Windows support for parser installation.
What did I do?
-   install git
-  open powershell (admin)
-   install chocoletey by pasting the following line
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
```
- open powershell (admin)
- run `choco install mingw`
- `refreshenv`
- run Nvim-qt from nightly neovim releases
- google how to install vim plug
- `TSInstall cpp` installs stuff. *.so is loaded and plugin functionality works (highlighting, go to definition, list locals).
It was a lot of pain to program this on Windows. Will fix lua style on Linux …

Add Windows support (mingw)

---

lua/nvim-treesitter/utils.lua

This function is not working with paths with trailing slash
so the :p modifier will add path serparator in the end (if missing) but only if directory exists
:h modifier will remove trailing path serparator

fix get_package_path function for paths with trailing slash

---

README.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/refactor/navigation.lua
lua/nvim-treesitter/textobjects/move.lua
lua/nvim-treesitter/ts_utils.lua
lua/nvim-treesitter/utils.lua

I like `*` and `#` to consider only other usages of the identifier under cursor (if it's an identifier). Overwriting the default mappings is however not a good idea. Any suggestion what default key mapping we could use for this? We could also not set any default mappings.
TODO:

feat(refactor.navigation): add navigation.goto_{next,previous}_usage

---

lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/refactor/highlight_current_scope.lua

This PR tries to simplify `configs.setup` to avoid a few problems. The main problem: attach/detach should be strictly inverse to each other and if they are not it shouldn't cause a problem for disabled modules.
- try to avoid enabling modules just to disable them afterwards for languages in `disable`. This could avoid problems when attach/detach of certain modules are not inverse to each other
- make attach/detach of `highlight_current_scope` inverse to each other
- avoid calling `enable_all` with disable/enable data that is actually for a different module
This solves the bug that executing this lua file (once all modules are loaded) automatically activates `highlight_current_scope` though it's deactivated. Happens with every top-level module set to true.
```lua
require …
```

Simplify configs.setup

---

lua/nvim-treesitter/parsers.lua

I added a `scanner.c` to tree-sitter-fennel, so I'm updating things here so that it compiles correctly.

add scanner.c to fennel compilation

---

doc/nvim-treesitter.txt

This pull request adds a "Performance" section to docs stating that the way nvim-treesitter checks `rtp` might result in slow startup times.

Add a "Performance" section to docs

---

lua/nvim-treesitter.lua

I am not sure how to tackle #322 since `lua-match?` will introduce the next breaking change. But maybe we can catch with this people who try the plugin with Neovim stable.

Add warning about required Neovim version

---

plugin/nvim-treesitter.vim

Neovim uses this hl group `:h group-name`
> 	*Underlined	text that stands out, HTML links
Let me know what you think

Highlights: use underlined for TSURI

---

lua/nvim-treesitter/install.lua

I've made some changes to the install script so tree sitter languages can be installed on Windows with the clang compiler installed. I had some trouble getting #347 to work I think due to the cl compiler being quite a bit different from the gcc/clang counterparts. With clang most commands remain the same only some considerations have to be made like path separators atleast when using cmd.exe. Maybe it'd be preferable to write the command_list changes with powershell instead, not sure. 
Either way this PR works on my Windows 10 machine.

Support TSInstall on Windows with Clang

---

lua/nvim-treesitter/configs.lua

The first function is faster and more common.

Text objects: check for query files first

---

queries/typescript/highlights.scm

This fixes an error that's thrown when highlighting TS files, since `variable.parameter` is not an actual capture.

fix(highlights): fix ts parameter highlights

---

queries/lua/highlights.scm

Function calls were missing. The grammar identifies the whole node as a function call, but we only care about the "final call", so that's why `. (arguments)`

Lua: update highlights

---

queries/ocaml/highlights.scm

The string.special group was removed from highlight.lua, replace its
uses by the string group.
The issue was detected in https://github.com/nvim-treesitter/nvim-treesitter/issues/387

fix: ocaml highlight

---

queries/go/locals.scm

The unused `#strip!` now causes an error.

go locals: remove unused strip! directive

---

lua/nvim-treesitter/query.lua

Even if it's an empty iterator.

Fix #418: iterator function should always return an iterator

---

queries/cpp/highlights.scm

when you're overloading operators...

feat(C++ highlights): highlight operator_name as function

---

lua/nvim-treesitter/parsers.lua

This is a duplicate of #430, using the subpath method.
This should be merged asap to fix CI.

Update path for ocaml

---

queries/lua/fold.scm

I noticed that local functions weren't folding with the current head, so I poked around a bit and came up with this.

Add folding for local functions in lua

---

lua/nvim-treesitter/install.lua
lua/nvim-treesitter/utils.lua

This is more robust compared to the previous method where we walked
up the tree and matched on the directory name, which also required
that the repository was cloned in a directory named `nvim-treesitter`.
Also see previous discussion at https://github.com/nvim-treesitter/nvim-treesitter/issues/363#issuecomment-687211730

Find package path based on the Lua source file

---

lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/parsers.lua

- Don't load everything at startup
- Don't define an autocomand for each module and for each supported lang
(this creates nxm autocomands!). Just define one per module.
Still need to test this more, but here are some numbers :D
```
044.113: sourcing .../nvim-treesitter/plugin/nvim-treesitter.vim
```
```
000.632: sourcing .../nvim-treesitter/plugin/nvim-treesitter.vim
```

Improve startuptime

---

CONTRIBUTING.md
queries/bash/highlights.scm
queries/cpp/highlights.scm
queries/dart/highlights.scm
queries/go/highlights.scm
queries/go/locals.scm
queries/java/locals.scm
queries/jsx/highlights.scm
queries/php/locals.scm
queries/python/highlights.scm
queries/regex/highlights.scm
scripts/check-queries.lua

This will avoid using invalid captures in queries, and avoid typos.

ci: check capture names in queries

---

queries/ruby/highlights.scm

Move class and module names to `@type` to be consistent with the other languages. (fixes #448)
Use `@punction.special` for interpolation brackets. (fixes #449)

Fix TSType and TSPunctuationSpecial

---

lua/nvim-treesitter/textobjects/shared.lua

Reading the code, these functions should be named differently
https://github.com/nvim-treesitter/nvim-treesitter/blob/a755017dd52947672af458743b88e59a59cd592f/lua/nvim-treesitter/query.lua#L203-L203

TextObjects: refactor wrong func names

---

queries/ocaml/highlights.scm

Function matching was wrongly parenthesized, parameter detection was too
eager and it was wrongly matching all + and - as delimiters.
Now it marks tuple values as variables when they are being defined

fix ocaml highlights

---

queries/c/highlights.scm

fix(cpp highlights): Use `@include` for preproc_include

---

CONTRIBUTING.md
lua/nvim-treesitter/highlight.lua
plugin/nvim-treesitter.vim
queries/jsx/highlights.scm
queries/python/highlights.scm

highlighting with `@Normal` is conflicting with other groups, because normal also highlights the background color.
What happens then is that the CursorLine don't get properly highlighted on nodes where `@Normal` is applied.

do not highlight jsx_text as normal

---

CONTRIBUTING.md
queries/go/locals.scm
queries/python/locals.scm

These aren't really definitions and are being show in the definitions
list. We aren't using them at the moment, we could use another group or
query file.

Remove @definition.doc captures

---

.gitignore
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/utils.lua

_Disclaimer: I'm a Lua beginner and new to this repository_
This PR solves #436 by adding more logic to determine the correct installation directory for `*.so` files with `:TSInstall`. The logic is to first try the package directory (the way it was before) and then try `$XDG_DATA_HOME/nvim/site/parser/*.so`. The `site` folder will be created if it doesn't exist. The reason I chose this folder is that it is already in `runtimepath`
I also added this logic for the `:TSUninstall` command.
So far I tested the PR in two ways:
1. Follow the install instructions by running `git clone` and using the native packages feature. The expected result is for the `*.so` files to appear in `$XDG_DATA_HOME/site/pack/nvim-treesitter/start/nvim-treesitter/parser/*.so`
2. Install `nvim-treesitter` with Nix. …

Make :TSInstall work in Nix by adding a second module installation target

---

queries/ruby/highlights.scm

This fixes an issue with #448 where the types highlights were being overriden by the generic constant match.

move the generic "constant" capture to the top of the query list

---

CONTRIBUTING.md
lua/nvim-treesitter/highlight.lua
plugin/nvim-treesitter.vim
queries/html/highlights.scm

These groups will be added for use with xml-like tags such as html and
jsx.
Addresses #465

Add TSTag and TSTagDelimiter groups

---

lua/nvim-treesitter/highlight.lua
plugin/nvim-treesitter.vim
queries/dart/highlights.scm

Based on https://github.com/UserNobody14/tree-sitter-dart/pull/10 to unhide the `case` node
This PR also shows `Function` as a type rather than a keyword. `Function` is used as a type annotation but I've previously incorrectly included it as a keyword which isn't correct.
Lastly switch to using the existing annotation highlight for annotations (duh) rather than the no longer existing `attribute` annotation

Add case builtin for dart

---

lua/nvim-treesitter/install.lua

This should ensure that `:TSUpdate` replaces already existing files when moving the compiled libraries.

Ensure that updated files are replaced w/o warning

---

queries/bash/highlights.scm

Following some of our conventions and some bits from atom
https://github.com/atom/language-shellscript/blob/master/grammars/tree-sitter-bash.cson:
- Uppercase var are constants
- `$` is a special symbol, not part of the name
- Builtin constants and functions
Closes https://github.com/nvim-treesitter/nvim-treesitter/issues/444

Bash: update highlights

---

README.md
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/parsers.lua
lua/nvim-treesitter/query.lua
queries/ocaml/highlights.scm

Currently ocaml interface files (.mli) are interpreted as standard ml files, which generates erroneous trees.
This PR activates the correct parsing of mli files when using the filetype `ocamlinterface`. This filetype does not exist in vim or neovim out of the box. The filetyppe can be manually set, there is a branch of [vim-ocaml](https://github.com/undu/vim-ocaml/tree/ocaml_interface) sets it out of the box.
Some upstream changes for the ocaml highlights are included. These currently don't provide the best highlighting possible because captures rule precedence in neovim doesn't work the same way as treesitter assumes.
I'd like to get some comments on what do people think it's the best approach for adding a new parser that neovim doesn't support out of the box because parser selection is …

feat: add parser for ocaml interface files

---

queries/python/highlights.scm

We really want to reset all potential highlighting from the string here.
An alternative would be to add explicit highlighting of `@variable` but this wouldn't reset potential background highlighting of the string.

fix(python): use `@Normal` again for f-strings `@none` is not aggressive enough

---

queries/jsx/highlights.scm

use @tag and @type directives for jsx highlights

---

lua/nvim-treesitter/health.lua

Before:
```
health#nvim_treesitter#check
========================================================================
- ERROR: Failed to run healthcheck for "nvim_treesitter" plugin. Exception:
function health#check[21]..health#nvim_treesitter#check, line 1
Vim(lua):E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:20: query: invalid node type at position 170
... output of checkhealth stops
```
After:
```
- OK: c parser found.
- ERROR: Error in `highlights.scm` query found for c
/usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:20: query: invalid node type at position 170
- ADVICE:
- Try `:TSUpdate` (queries might have been adapted for a upstream parser change)
- Try to find the syntax error/invalid node type in above file.
- OK: `locals.scm` …
```

fix(checkhealth): use pcall to check for syntax errors in query files

---

lua/nvim-treesitter/install.lua

More and more Github repos are switching to "main" branch.
Example: `tree-sitter-wasm`

feat(parsers): add possibility to install from other branches

---

queries/ruby/highlights.scm

This enhancement, provided by @theHamsta in [this comment](https://github.com/nvim-treesitter/nvim-treesitter/issues/463#issuecomment-695357859) fixes issue #463 
Top level `require` / `require_relative` / `load` will be highlighted as `TSInclude`, however other usages of those functions, such as Rails strong-params will be highlighted as Method/Function instead.

Highlight top-level 'require' as TSInclude (fix #463)

---

queries/dart/highlights.scm

So it finds `_HiddenClasses` as well as `OtherClasses`.
This also adds highlighting for the punctuation in a template literal, previously this wasn't working when specifying `"${"` as one node which causes the parser to error but if each character is captured separately that works 🤷🏿‍♂️. I've asked on the upstream repo but it's pretty inactive.

dart: improve the highlighting for class instantiation

---

README.md
lua/nvim-treesitter/parsers.lua
queries/ocaml/highlights.scm
queries/ocamllex/highlights.scm

The parser emits opaque `ocaml` nodes, since these are not yet handled to the ocaml parser they remain unhighlighted. The ocaml nodes appear inside action nodes. I've tagged those with `@embedded` since that's how it seems to be handled in other scm files. is this how it's supposed to be used?
I've added the hash to the lockfile, although it's not clear in the diff since it's all in the same line.
Like it happens to highlight mli files, this PR is needed: https://github.com/ocaml/vim-ocaml/pull/61 (or set manually the filetype to ocamllex)

Add ocamllex highlights

---

README.md

Hey! Really interesting work going on here, been following and updating regularly. Saw that `textobjects` was moved to a new module and found a small typo while updating my dotfiles.

fix: readme link to nvim-treesitter-textobjects

---

plugin/nvim-treesitter.vim
queries/dart/highlights.scm
queries/python/highlights.scm

Seeing the screenshot of @akinsho (https://github.com/neovim/neovim/issues/12967#issuecomment-702701918), I had the idea that we could reset highlight in Dart string interpolations similar to how we treat Python f-strings.
If someone can tell me what to change that it works with `TSNone` we would not have to change it to `@Normal`.

Dart highlights: Reset highlight in interpolation

---

lua/nvim-treesitter/install.lua
lua/nvim-treesitter/shell_command_selectors.lua

Currently `unzip` is needed to extract the parsers after download. `unzip` may not be available by default on some OSes/Distros. `tar` will be a better choice here due to it being available by default on many UNIXes and Windows.
This PR also changes over the download format from zip to tar.gz. `bsdtar` which is available by default on Windows (since build 17063) , supports extracting zip files while GNU tar which is default on most Linux distros does not (as far as I can see).

Remove dependency on unzip

---

CONTRIBUTING.md
README.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/highlight.lua
plugin/nvim-treesitter.vim
queries/cpp/highlights.scm
queries/javascript/highlights.scm
queries/ocaml/highlights.scm
queries/rust/highlights.scm

Start adding highlights for
- C++
- Rust (including other scoped_identifier/scoped_type_identifier fixes)
- JS (only namespace_import)
Addresses #516
Vim has no dedicated hl-group for modules/namespace continued to use Constant (open for better suggestions)
#453 could be useful for Rust highlights. In the queries it can almost always be `scoped_identifier` or `scoped_type_identifier` as a parent.

fix(highlights): Add TSNamespace highlight

---

CONTRIBUTING.md
lua/nvim-treesitter/query.lua
queries/cpp/folds.scm
queries/cpp/highlights.scm
queries/cpp/locals.scm
queries/javascript/folds.scm
queries/javascript/highlights.scm
queries/javascript/locals.scm
queries/ocaml_interface/folds.scm
queries/ocaml_interface/highlights.scm
queries/ocaml_interface/locals.scm
queries/tsx/folds.scm
queries/tsx/highlights.scm
queries/tsx/locals.scm
queries/typescript/folds.scm
queries/typescript/highlights.scm
queries/typescript/locals.scm

This implements neovim/neovim#13059 (comment)
This behaves like modelines and remove the use of the base_language map.
Also, this allows to fine-tune what we actually want to include per
query, which is better IMO.
One other thing to note to is that using this mechanism, one can just write queries for his language, without knowing anything about lua, which is great.
I would really like everyone's approval on this, to be sure I don't break anything.

Implement inheritance using in-file modelines

---

README.md
plugin/nvim-treesitter.vim

This fixes the issue where colors highlighted as TSNone were not
reverting to the background and foreground color. It follow us up #551.

Add background and foreground colors to TSNone

---

queries/ruby/highlights.scm

@TravonteD
Before:
After:
May require #567

Ruby highlights: reset highlight on interpolation

---

lua/nvim-treesitter/highlight.lua

Should be merged after https://github.com/neovim/neovim/pull/12953.
I'll try my best to port breaking changes before they actually land on nvim master, and merge them at the same time to limit breakage.

fix(highlights): use new highlighter interface

---

queries/cpp/highlights.scm

declarator can be a identifier, a reference or a pointer
This is a intended mirco-improvement to highlight parameters like `foo(TypeT* t = nullptr)` except that it doesn't.
All reference, pointer and member highlights (`m_foo`) do not work on my machine for a longer time. I don't understand why.

C++ highlights: highlight all kinds of optional parameters

---

README.md

https://www.reddit.com/r/neovim/comments/jbsfx2/cant_install_treesitter_error_during_compilation/
At the moment we require `libstdc++` I guess it's easier to stay with this dependency than to say only some parsers may require C++.
Also updated the Windows wiki that git is not required on up-to-date Windows 10.

Update README requirements for parser download/compilation

---

lua/nvim-treesitter/parsers.lua

upstream now handles parsers by itself, so we don't need to do it in this repo.
fixes #582

Remove get_parser logic

---

lua/nvim-treesitter/query.lua

The following query will result in matches with only one node though it
requires two nodes to be a match.
```scheme
(function_definition
(comment) @function.inner.start
body: (block) @function.inner)
```
Why? First `insert_to_path` is called for `@function.inner.start` which
will result int the following table.
```lua
{ function = { inner = { start = { node =  <userdata1>} } } }
```
`insert_to_path` will overwrite the result
```lua
{ function = { inner = { node = <userdata2>  } } }
```
instead of having
```
{ function = { inner = { start = { node =  <userdata1>}, node = <userdata2>} } }
```
This can either be solved by avoiding to insert tables (this PR) or by trying to perform a `tbl_merge`
```
if type(curr_obj[path[#path]]) == 'table' and type(value) == 'table' then …
```

Fix: avoid overwriting tables in insert_to_path

---

README.md

Basic alternative to [context.vim](https://github.com/wellle/context.vim) with `nvim-treesitter`: https://github.com/romgrk/nvim-treesitter-context

readme: add nvim-treesitter-context

---

README.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/highlight.lua
lua/nvim-treesitter/languagetree.lua
queries/markdown/highlights.scm
queries/markdown/injections.scm

Based on #540 
Here we finally are, language injection is coming.
This is the very first implementation, soon to be upstreamed as the future way to manage parsers within a buffer.
For now this does not do anything appart from actually creating the language tree, in the future we will use this as as way to highlight buffers, with native syntax highlighting.
Even crazier, we might be able to change "filetype" depending on the current cursor position, which I find cool.
Steps to take:
- https://github.com/neovim/neovim/pull/12953
- Move `TSHighlighter` using multi-luahl https://github.com/neovim/neovim/pull/12963 to be able to have multiple highlighters per buffer
- Implement highlighting multiplexing (that is, pick the appropriate highlighter for a range of text)
Next steps :
- Remove …

Feature: Languagetree

---

autoload/nvim_treesitter.vim
lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/indent.lua
lua/nvim-treesitter/query.lua
lua/nvim-treesitter/ts_utils.lua
queries/lua/indents.scm

fixes #332.
This is the first indent draft for nvim-treesitter, we might need to look for more in depth edge cases in next implementations.
I also changed the memoize_by_buf_tick function to use the on_changedtick callback for the nvim_buf_attach callbacks.

treesitter indentation

---

plugin/nvim-treesitter.vim

Users can still link it to a highlight group.
```viml
TSError link Error
```

Fix #595, #583: do not set defaults for highlights that have no default highlighting

---

queries/ocamllex/highlights.scm
queries/ocamllex/injections.scm

This allows the big blocks of ocaml code to be highlighted correctly.
Example:

feat(ocamllex): use injections for ocaml

---

lua/nvim-treesitter/languagetree.lua

This avoids some stack overflows when a language includes itself.
This is a temporary solution, and will be addressed later when actually
managing our own parsers.
Fixes #604

fix(languagetree): avoid language self-injection

---

README.md
lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/parsers.lua

The markdown scanner errors out far too often to be usable, disabling it
by default would avoid many issues until those assertion errors are
fixed.
I know it is sad to come to such solutions, but I think everybody agrees that this is just too buggy.
Partialy fixes #602

fix(markdown): disable highlighting

---

CONTRIBUTING.md

Another thing that went wrong when merging remove-refactor and remove-textobjects.

Remove textobjects from contributing

---

queries/javascript/highlights.scm

Hey!
I found that in JavaScript, the `@constant` query gets overwritten by the `@constructor` query. They both query for variables starting with an uppercase letter, but the `@constant` query took effect first.
Here's how it looks like:
**Before:**
**After:**

fix(javascript): fix constant variable highlight

---

queries/jsx/highlights.scm

I noticed some issues with components that had `.` in them - SUI React has a lot of components defined in this way, such as [Table](https://react.semantic-ui.com/collections/table/) etc.
Before:
After:

handle jsx components with dot in them

---

lua/nvim-treesitter/install.lua

it can be disturbing on startup when treesitter is updating, you don't really know which plugin is printing the [Compiling], so i added [nvim-treesitter] to inform users treesitter parser is being updated/installed.

show [nvim-treesitter] during install

---

README.md
autoload/nvim_treesitter.vim
doc/nvim-treesitter.txt
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/parsers.lua

Unmaintained parsers only give users little benefit but take sometimes a
a long time to install (e.g. Markdown, Julia, Haskell parser). We could
recommend to only install maintained parsers by default.
So instead of `ensure_installed = 'all'` or `:TSInstall all` you can now also install `'maintained'` parsers only.
This PR is on top of #351

Installation of maintained parsers only

---

lua/nvim-treesitter/query.lua
lua/nvim-treesitter/query_predicates.lua
lua/nvim-treesitter/tsrange.lua

#521 
Capturing range that are not equal to the range of exactly one node via queries is not easy right now. But is some times necessary e.g. for textobjects, setting ranges for language injection, getting the doc-strings for @steelsojka 's docgen plugin.
[This PR](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/14) enables defining multi-node textobjects defined defined by start/end node pairs. But this makes the code unnecessary complicated because we have to check a lot of cases.
This PR enables defining range object that implement the same API as regular nodes by queries. Then, multiple-node textobjects just work without any code change. A similar directive could be introduced that trims away `// ` from comments or similar tasks that require range not equal not …

Add virtual range for creating node-like objects from multiple nodes

---

queries/javascript/highlights.scm

Before:
After:
Only second case is left

js: add query for @parameter

---

queries/javascript/injections.scm
queries/jsdoc/highlights.scm
queries/typescript/injections.scm

Add jsdoc highlight injections for javascript and typescript.

feat(js): add jsdoc lang injection

---

lua/nvim-treesitter/install.lua

Pretty much what it says on the tin.
If the language specified in the `TSUpdate` command is `all`, then the plugin should update all installed parsers.

fix(#620): Fall into the "update-all" branch if lang is "all"

---

queries/go/folds.scm

The default behavior in which `@scope` captures were folded resulted in
toplevel fold for an entire source file, which was mildly irritating.
related: #597

Add folds for Go

---

lua/nvim-treesitter/incremental_selection.lua
lua/nvim-treesitter/locals.lua
lua/nvim-treesitter/parsers.lua
lua/nvim-treesitter/tsrange.lua

This will avoid using internal data. And maybe avoid crashes when https://github.com/neovim/neovim/pull/13219 will be merged.

parser: only use parse to get a tree

---

README.md
queries/javascript/highlights.scm

I have no idea how to write a function in JS but googling told me that you can have optional parameters that are not highlighted right now https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/19#pullrequestreview-523806600
```javascript
(function connect(hostname = "localhost",
port = 80,
method = "HTTP") {
})
```
The dots of `rest_pattern` `...` are not highlighted right now. How could the be highlighted. Punctuation? Parameter?

JS optional parameters

---

README.md

The setup example in README.md is not precise as is in [:h nvim-treesitter-modules](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/doc/nvim-treesitter.txt) which could mislead new neovim users.

Fix readme setup example

---

queries/typescript/highlights.scm

Updated highlight groups to handle more of the typescript delimiters and some other small changes.
Test code in typescript. Note `&`, `|`, `:`, `?` and argument arguments should now be properly setting the correct group. 
```
type Red = 'red'
type Blue = 'blue
type Colors = Red & Blue
type ColorOpts = Red | Blue
type X = {
y?: undefined
}
const yo = ({y}: X): void => {
return;
}
```

Typescript Delimiter Highlights & | : ? 

---

lua/nvim-treesitter/tsrange.lua

This lets you write queries with an optional end/start node that gets appended if it's there. 
```
((lambda_parameters
[(identifier)
(tuple)
(typed_parameter)
(default_parameter)
(typed_default_parameter)
(list_splat)
(dictionary_splat)] @parameter.inner
. ","? @_end)
(make-range! "parameter.outer" @parameter.inner @_end))
```
In this example `@parameter,outer` will include a following ",". If there is no comma after the parameter then `@parameter.outer` == `@parameter.inner`. This would greatly simplify the logic of including possible attributes and decoration to captures that may be there but not in all cases.
Related: https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/22

Make make-range! more relaxed (one of the arguments may be nil)

---

queries/java/highlights.scm

Looks like a decision has been made for #470 
`highlight link TSConditional DraculaGreenItalic` does this so I think it works?

[java] Ternary

---

queries/c/highlights.scm
queries/cpp/highlights.scm

After a recent fix for #446, declarations in class/struct definitions stopped being marked as properties or methods. This fix will add property highlights to field declarations, and method highlight to field function declarations.

c/cpp: fix field and initializer highlights

---

queries/verilog/highlights.scm
queries/verilog/locals.scm

Adds some scope and definition queries for systemverilog code.
I still have an issue with the `reference` query.
In the tree-sitter parser, everything that is not a keyword or constant is ultimately parsed into a `simple_identifier`.
This also includes defined types.
I am currently using the `simple_identifier` as a reference, but that means that the refactor plugin also highlights other mentions of the type when the cursor is on one.
Is there a way to exclude certain matches through a query or would I need to list all more cases to exclude these? 
For example, I have a variable defined with a custom type:
``` systemverilog
some_type_t some_variable;    
```
Which parses as:
```
block_item_declaration [124, 4] - [124, 38]                  // line
data_declaration [124, 4] - [124, 38] …
```

Add support for locals in (system)verilog and some highlight fixes

---

queries/c/highlights.scm

This bugged me for a while, the fix is a bit strange, but it'll do the trick hopefully

c highlights: fix define/undef arguments

---

queries/javascript/highlights.scm

Set : to be operator in javascript.
[old-operator-example](https://user-images.githubusercontent.com/15027/99914664-e6ad4e00-2ccc-11eb-8640-df957f6d3a62.png)

javascript: : in pairs as punctuation.delimiter

---

.github/workflows/update-readme.yml
.gitignore
README.md
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/utils.lua
parser-info/.gitignore

I have no idea why Github decided to close #640 but here is an updated version. It should now also work when `lockfile.json` changed after a plugin update and when `parser-info` is not writable.
Please also test. E.g. by
-  `:TSUpdate` (now it should write all installed parser revisions, will run for all parsers a last time)
- Change `lockfile.json` (only one revision -> should only update that parser on TSUpdate, or execute `write-lockfile.json` -> :TSUpdate should  update all parsers with new revision available)

Only update outdated_parsers on TSUpdate

---

queries/javascript/highlights.scm

This currently has no highlights for `/` in division.
This adds `/` for division punctuation. https://tc39.es/ecma262/#prod-DivPunctuator
And doesn't match for `/` in tags (jsx/tsx)

javascript: Add operator to / for division

---

README.md

This adds a brief explanation how to add unsupported parsers to nvim-treesitter (assuming the grammar is already written) via the snippet @theHamsta provided on Gitter.
It might be good to also add more details how to add the corresponding queries; I've left this vague since I don't know the details myself (is it enough to have a `queries` directory somewhere in `rtp`?)

README: Explain how to add unsupported parsers

---

queries/javascript/highlights.scm
queries/typescript/highlights.scm

Move shorthand_property_identifier to javascript.

Javascript shorthand property identifier

---

queries/graphql/highlights.scm

* enum values
* input parameters
* 'implements' keyword
* include '@' in directive name
* fragment definition and spread
I included comments here which is a duplicate of #715 as there seems to still be discussion about merging the injection query. I can remove that if we want.

graphql: add missing highlights

---

queries/css/indents.scm

When you enter a new line after `{` or new line `o` in command mode, it'll enter a new line with auto indent. For example:
```
a {< enter
|
}
```
The indent when enter a new line after properties declaration is also support:
```
a {
color: black;< enter
|
}
```
NOTE: `|` is a cursor.

css: add indent support

---

doc/nvim-treesitter.txt
lua/nvim-treesitter/highlight.lua

- Adding missing groups. TSTag, TSTagDelimiter, TSComment (maybe a couple others)
- Reorder the docs/code to be alphabetical to make it easier to scan.

docs: Update docs for missing groups, re-order alphabetically

---

lockfile.json

Includes fixes for float rationals and keyword parameters
I guess it would be nice to have a highlight for rational.
Maybe operator?
fyi: @TravonteD

Update ruby parser

---

README.md
lua/nvim-treesitter/parsers.lua

Trying to use typescript for **flow typed** [issue related](https://github.com/nvim-treesitter/nvim-treesitter/issues/31) I set up as describes Readme file but as this lines 
https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/parsers.lua#L344-L354 
runs at require, any new setup has no effect because `ft_to_parsername` is not repopulated, and any `used_by` value is not used.

Allow configurations

---

queries/go/highlights.scm

This adds `package_identifier` as `@variable`. Previously had no highlights.

go: Add package_identifier as variable

---

lua/nvim-treesitter/shell_command_selectors.lua

This might be a hard error in future:
https://github.com/neovim/neovim/issues/13485
https://github.com/vim/vim/commit/7bb4e74c38642682cfdd0cb4052adfa5efdd7dd1
Avoids: https://github.com/nvim-treesitter/nvim-treesitter/issues/744
We might have similar problems in other parts of the code.

Add fix for vim.fn.executable(vim.NIL)

---

.github/workflows/update-parsers-pr.yml
lockfile.json
lua/nvim-treesitter/install.lua
scripts/write-lockfile.lua

When we skip javascript/typescript it should be possible to update the parsers automatically.
This is a lazier solution than updating all parsers one after another and test with another nvim instance whether this causes a break.

Enable automatic parser updateing with a hack (skip typescript for now)

---

doc/nvim-treesitter.txt

Found a minor typo in the `ts_utils` section.

Fix doc typo

---

queries/bash/highlights.scm

Reset highlighting in expansion regions
@TravonteD

Bash highlights: reset highlighting in expansion

---

.editorconfig

I found an issue that lua files in the project got indent incorrectly when enabled nvim-treesitter indent. The root cause is that editorconfig set `tab_width` to `8` for every file. I fix that by specific only lua files to be `2`.

editorconfig: set tab_width to 2 for lua files

---

lua/nvim-treesitter/indent.lua

Uses `shiftwidth` for indentation size if `softtabstop` is set to a negative value.
Is there anything more involved to [resolving this issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/704) than this?

fix: support shiftwidth for indents.

---

queries/ruby/highlights.scm

Add the follow ruby builtins:
- [__callee__](https://ruby-doc.org/core-2.7.2/Kernel.html#__callee__-method)
- [__dir__](https://ruby-doc.org/core-2.7.2/Kernel.html#__dir__-method)
- [__method__](https://ruby-doc.org/core-2.7.2/Kernel.html#__method__-method)
- [__id__](https://ruby-doc.org/core-2.7.2/BasicObject.html#__id__-method)
- [__method__](https://ruby-doc.org/core-2.7.2/Kernel.html#__method__-method)
- [__send__](https://ruby-doc.org/core-2.7.2/BasicObject.html#__send__-method)

Add more ruby built-in constants

---

queries/javascript/highlights.scm

Added operators described in [Expressions and operators - JavaScript | MDN][doc].
[doc]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators
```javascript
2 * 3
2 ** 3
2 >>> 3
2 & 3
2 | 3
2 ^ 3
2 ?? 3
let a *= 2
let a >>= 2
let a >>>= 2
let a ^= 2
let a |= 2
let a &&= 2
let a ||= 2
let a ??= 2
a?.b
```
| before | after |
|---|---|
| <img width="102" alt="スクリーンショット 0002-12-21 11 14 15" src="https://user-images.githubusercontent.com/1239245/102732502-40fa0700-437e-11eb-9d66-44dc0c403a85.png"> | <img width="101" alt="スクリーンショット 0002-12-21 11 15 47" src="https://user-images.githubusercontent.com/1239245/102732512-46575180-437e-11eb-9993-9991fba0274d.png"> |

Add lacked Javascript operators

---

doc/nvim-treesitter.txt
lua/nvim-treesitter/highlight.lua
plugin/nvim-treesitter.vim

These definitions exist in highlight.lua, but does not exist here.

Remove TSStructure

---

queries/python/indents.scm

I was testing https://github.com/nvim-treesitter/nvim-treesitter/pull/772 but it does not seem to work well on my machine (nvim-treesitter on master, did `TSUpdate`). It didn't really indent the blocks "else", "elseif", etc. properly. It also missed the indentation of collections (lists, dictionaries, ...). I used https://github.com/nvim-treesitter/playground (especially the query linter) and it seems that e.g. literal "else" matches only the text part. `indent.lua` didn't go through that node and so it didn't apply `@branch`. 
This PR adds the groups that I could find. I tested the changes on the following file: [test-indent.zip](https://github.com/nvim-treesitter/nvim-treesitter/files/5720888/test-indent.zip). I indented the file manually and I'm just testing with `gg=G`. Most of the …

Improve python/indents.scm

---

queries/bash/highlights.scm

Various fixes to the bash highlighting:
- top and tail matches with `^` and `$` so that they don't match more than intended
- switch to lua matches - are these faster? - not sure that this matters
- move capture of number parameters to a separate block: not that I know what I'm doing, but this seems to work where the original did not
- remove a redundant capture (which I suspect may have been compensating for the non-workingness per the other change)
Before:
- `3` is not recognized as a number
- all of `bar=false` is treated as a boolean
- only `baz="baz"` is highlighted as expected
After:

fixes to bash highlighting

---

queries/yaml/highlights.scm

A first draft of highlighting for YAML.  
Some comments:
- This is my first time with treesitter, I've very likely done things wrong, corrections welcome!
- In particular there are a couple of things that aren't working, in ways that I don't understand.
First:
```
(flow_pair key: (flow_node) @field)
```
is supposed to catch the `foo` in `mapping: { foo: bar }`, but seems to have no effect.  I don't see how this is different from the handling of `block_mapping_pair`, which seems to work fine
Second, including `"+"` in the list of punctuation characters causes errors.  I've no idea how this is different from the other punctuation characters.
- I have treated keys as `field`, whereas the JSON highlighter treats them as `label`.  IMO `field` makes more sense both here and in JSON, but if you …

first draft of YAML highlighting

---

lockfile.json
queries/rst/highlights.scm
queries/rst/injections.scm
queries/rst/locals.scm

- The directive type does not longer includes `::`.
- The content of the directives is not longer interpreted as rst,
but it uses language injection for it.
- Fix a query to allow capturing targets without link.
- Reset the content of the math role, so it can be highlighted by the
injection instead.
Problems I found:
- Capturing the same node with `@language` and `@content` will raise an
error.
```
Error detected while processing FileType Autocommands for "*":
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:331: table index is nil
```
Harcoding the language works, Using the offset predicate doesn't work
either `(#offset! 0 0 1 0)` nor `(#offset! 0 0 0 5)`
- Generating the grammar using `tree-sitter-cli@0.17.x` breaks
nvim-treesitter, `@0.16.9` works.

RST: update parser and queries

---

queries/python/folds.scm

Mostly useful for folding docstrings

Python (folds): allow to fold strings

---

lockfile.json
queries/rst/highlights.scm
queries/rst/injections.scm
queries/rst/locals.scm

Finally, highlight for code blocks.
Some directives have the option to interpret the whole body as they want, so that's why some capture `(body)` and others `(content)`

RST: update injection queries

---

CONTRIBUTING.md
queries/python/injections.scm
queries/regex/highlights.scm

This add regex injections for Python expression of type `re.regex_function(r"regex-string")`
Additionally for regex highlighting:
- Give unescaped regex characters normal highlighting. In a normal string escape means special meaning. In regex escaping a special characters means it removes the special meaning and should thus be highlighted with normal regex highlights. This gives the escaped chars a different highlight as normal special chars.
- Give class_character constant highlighting to have a some colors in regexes for different kinds of chars
- add "?" operator

Python regex injection

---

queries/css/folds.scm
queries/json/folds.scm
queries/toml/folds.scm
queries/yaml/folds.scm

Added fold queries for several simple languages. I didn't add HTML because I find it quite inconsistence. Here's an example.
```html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Something</title>
</head>
<body>
<div>  <- cursor on this line
<span>somethin</span>
</div>
</body>
</html>
```
If you try to fold the `div`, it will fold up until the last `</html>`.  But this won't happend if you expand `<span>` tag to this.
```html
<span>
somethin
</span>
```
There might be some stuff that hasn't been covered yet so any advice would be appreciated :)

feat: added more fold queries

---

lua/nvim-treesitter/indent.lua
queries/lua/indents.scm

there is a big issue with indentation: It is not perfect !
this PR is a draft to experiment with indents to find an algorithm that should work for most languages. I feel i'm near the end (at least for lua which is a simple language to indent), but there a still a few glitches.
Also we could potentially drop the indent.scm file to use lua tables because we don't really need to match nodes here.
EDIT: a good point would be to start thinking about language injection for indentations, that would be very much amazing.
TODO:
- fix the issue where adding a new line at the end of a named node will miss one indent
- document the whole algorithm, maybe some refactoring to cleanup the code for ease of understanding because its quite hard to understand
- test this on big python / js / lua files and …

indent draft 2

---

CONTRIBUTING.md
queries/c/highlights.scm
queries/javascript/highlights.scm
queries/python/highlights.scm
queries/ruby/highlights.scm

We have now language injection. No need to have those queries in `highlights.scm`. We could rename `@none` to `@embedded` though.
Also resets the interpolation highlighting in JS.

Remove usages of `@embedded` in highlights

---

queries/rust/folds.scm
queries/rust/highlights.scm
queries/rust/injections.scm

added: 
- rust macro injections
- folds
- highlights for `$metavariable` in macros to distinguish from regular variables

[WIP]: rust macro injections and more queries

---

queries/cpp/highlights.scm

Field is not "name"
or should the highlight be "constructor" or stay "function"?

C++ highlights: Fix destructor highlighting

---

lua/nvim-treesitter/configs.lua

Following issue #838 , https://github.com/nvim-treesitter/nvim-treesitter/pull/824#issuecomment-758056977, I think it is better to revert #824 as we did not gained that much performance.
I'd rather focus on optimizing things than making them async.

Revert "added attach async"

---

lua/nvim-treesitter/indent.lua
queries/python/indents.scm

This PR adds some improvements to indent functionality.
Note that it includes the commit from https://github.com/nvim-treesitter/nvim-treesitter/pull/835.
00a63f0 Uses `vim.fn.prevnonblank` to match indentation of preceding non-blank line after moving to new line with operations like `o` in normal mode or `<cr>` in insert mode. Without this change `root:descendant_for_range` was being used to get the wrapper node. This worked for languages with braces like C, but failed in e.g. Python (now `root:descendant_for_range` is still used as a fallback in some situations, see comments in code).
Following commits add `@return` capture that can be used to mark "last" nodes in a block. It differs from `@branch` in that the `@return` node itself keeps indentation of its block, but when it is the node …

Indent improvements

---

queries/c/indents.scm
queries/cpp/indents.scm
queries/go/indents.scm
queries/graphql/indents.scm
queries/html/indents.scm
queries/javascript/indents.scm
queries/json/indents.scm
queries/jsx/indents.scm
queries/ruby/indents.scm
queries/rust/indents.scm
queries/teal/indents.scm
queries/toml/indents.scm
queries/tsx/indents.scm
queries/typescript/indents.scm
queries/yaml/indents.scm

I've added indent queries for some languages but I might have not covered some cases, would be awesome if anyone would try it and give some advice :)
List of languages that I've added
- HTML
- JSON
- YAML
- TOML
- Javascript
- Typescript
- JSX
- TSX
- Go
- Ruby
- GraphQL
- Rust
- Teal
- C
- C++
Known issues: 
- Last `/>` on self closing HTML tag doesn't get outdented properly **(Fixed after #837)**
- Last `</>` on jsx fragment doesn't get outdented properly
- Last `}` on Rust `else_clause` doesn't get outdented properly **(Fixed)**
- Last `end` on Teal sometimes doesn't get outdented properly. e.g if you use anonymous function for an argument.
- Some block doesn't get indented properly when you press `o` on the first line of the block to add a new line. Hopefully these illustrations make …

feat: added more indent queries

---

queries/go/indents.scm

didn't notice this in my previous PR

feat: add missing golang indent queries

---

lua/nvim-treesitter/query_predicates.lua

- `nth` in Lisps is traditionally 0-based.
- It should check the children of the parent to see if it is itself.
Alternative: remove (might be useful for Lua function bodies, they start at the 3rd node)

Fix "nth?" predicate

---

queries/javascript/indents.scm

Fixes a scenario when we have this.
```javascript
doSomething("foo", {
default: false,
}) <- not indented properly
// rest of the lines after this one got messed up
```

fix: js indent for object inside arguments

---

queries/rust/highlights.scm

The Rust grammar doesn't have a special token for fn, so it has to remain hardcoded, but that's still an improvement.

Use function keyword highlight group for Rust's fn

---

.github/workflows/update-parsers-pr.yml

Currently, this workflow fails if there are no changes to commit.

fix(CI): don't let update-parsers fail if no change is necessary

---

lua/nvim-treesitter/query.lua
plugin/nvim-treesitter.vim

Is putting the cache inside of a `do ... end` block the right choice?

Add cache for get_query function

---

README.md
lua/nvim-treesitter/parsers.lua

Follow https://github.com/tree-sitter/tree-sitter/pull/907
and change the link of the Elm parser to the elm-tooling namespace.

parsers: change repo link of Elm parser to the new official repo

---

after/ftplugin/query.vim

Otherwise the default is `/*%s*/`

Query: set commenstring

---

lua/nvim-treesitter/indent.lua

fixes #630 
Sets a filetype autocmd to set indentexpr when enabled by default. Fixes issue when using telescope or any plugin that runs doautocmd.

Fixes #630: Indentexpr reverts to runtime specified

---

queries/python/injections.scm

Since hasn't been much discussion around https://github.com/nvim-treesitter/nvim-treesitter/issues/806.
I'm just porting the injection queries, if you want to merge it. RST is a very popular format used in dosctrings, but certainly isn't the only format used.
I've been using this for a while now.Things I've noticed:
- Due that rst uses indentation for its syntax,
everything is treated as an block quote (but it looks good).
This can be solved by having a predicate like `#dedent!`.
- Looks like there is a bug in how the injected content is extracted
```
def foo():
"""Foo bar"""
```
That is parsed as a section for some reason,
but it's a paragraph.
In rst it would be a section if the content was:
```
"""
Foo bar
"""
```
If the content is
```
"""Foo bar"""
```
That's just a paragraph.
(also, …

Python: inject rst in docstrings

---

queries/yaml/folds.scm

Fix https://github.com/nvim-treesitter/nvim-treesitter/issues/887
(block_node) includes more nodes to fold, test with:
```yaml
days:
Monday:
- test: example
Tuesday:
- test: example
Wednesday:
- test: example
- test: example
Thursday:
- test: example
Friday:
- test: example
- foo: |
One
Two
Three
```

Yaml: fix folds

---

queries/rust/indents.scm

before
```rust
use term_table::{
row::Row,
table_cell::{Alignment, TableCell},
Table, TableStyle,
};
let stuff = (
1,
2
);
```
after
```rust
use term_table::{
row::Row,
table_cell::{Alignment, TableCell},
Table, TableStyle,
};
let stuff = (
1,
2
);
```

fix: rust use_list + tuple_expression indent

---

CONTRIBUTING.md
README.md
lua/nvim-treesitter/parsers.lua
queries/devicetree/folds.scm
queries/devicetree/highlights.scm
queries/devicetree/indents.scm
queries/devicetree/locals.scm

This adds Linux [Device Tree](https://www.kernel.org/doc/html/latest/devicetree/usage-model.html) files parser (https://github.com/joelspadin/tree-sitter-devicetree).
Fold queries are straightforward. For highlights I'm not entirely sure of the captures that should be used, I tried to select the ones that seemed sensible (and to end up with roughly similar colors as with vim's `syntax/dts.vim`, at least for gruvbox). I am not really sure what `locals.scm` are, maybe someone could check/improve/remove these queries. Indents work fine for me, there is some issue with indenting the first node in the file, but couldn't find what causes it.
Some `.dts`/`.dtsi` files to test these queries can be found e.g. [here](https://github.com/torvalds/linux/tree/master/arch/arm/boot/dts).

Add devicetree parser with queries

---

lua/nvim-treesitter/query.lua

The message does not even provide any context where it's coming from
and what it is exactly doing and has to be acknowledged when printed in
conjunction with the "wrote xxx bytes message"

Remove debug print statement

---

queries/query/highlights.scm

Matches the first comment and the beginning from the pattern
https://github.com/neovim/neovim/blob/52397aaa0d1e2d4ce1320c73761cf316fc608ffb/runtime/lua/vim/treesitter/query.lua#L25

Query: highlight modeline

---

queries/rst/highlights.scm

This resets the string highlight in `doctest_block`s to better contrast the code highlight with the rest of the documentation
before:

highlights(rst): Reset highlights in doctest_block

---

lua/nvim-treesitter/parsers.lua
queries/jsonc/folds.scm
queries/jsonc/highlights.scm
queries/jsonc/indents.scm
queries/jsonc/locals.scm

`jsonc` is basically JSON with inline comments. It's used a lot for configuring desktop apps, including `waybar`, `coc`, `vscode` and others.
I've written a parser which is about 95% based on the `json` parser, with comment support added on top. The parser itself has some tests, as well as some manual testing on file I have lying around.

Add support for JSONC

---

lua/nvim-treesitter/parsers.lua
queries/vue/folds.scm
queries/vue/highlights.scm
queries/vue/injections.scm

Due to limitations in tree-sitter-vue, TypeScript and JavaScript are indistinguishable. Since the former is a superset of the latter, always treating them as TypeScript should result in valid highlighting in all
cases.
Support for LESS and other formats requires support from the tree-sitter itself.
Closes #936

Initial support for Vue files

---

README.md
queries/java/highlights.scm

Currently, something would be highlighted as a constant even if it has starts with only two uppercase letters, e.g. IOException

Fix java constants

---

lua/nvim-treesitter/ts_utils.lua

This update allows setting a visual selection mode when calling `ts_utils.update_selection()`. Essentially, behavior is equivalent to the following steps: go to start position of the node, invoke certain visual selection mode, go to end position of the node.
Note for possible update: for blockwise mode select block not from start to end positions, but block containing the whole node. The drawback is that it will not be aligned with default Vim's behavior: after selecting region, user can change selection mode (by typing `v`, `V`, or `<C-v>`). So with current approach two actions are equivalent: `update_selection(..., "blockwise")` and `update_selection(..., "charwise")` followed by `<C-v>`.
Related PR: nvim-treesitter/nvim-treesitter-textobjects/pull/37

Add `selection_mode` argument to `ts_utils.update_selection()`

---

queries/ruby/highlights.scm

Currently nvim-treesitter is highlighting ruby constants and types differently, but in ruby they are basically the same thing
Based on [vim-ruby highlight](https://github.com/vim-ruby/vim-ruby/blob/master/syntax/ruby.vim#L502), highlight most ruby constants as types.
| before | after |
| --- | --- |
| <img width="396" alt="_private_tmp_a_rb" src="https://user-images.githubusercontent.com/120483/102622819-78c43d00-4139-11eb-9cff-0e2dd0ea94a6.png"> | <img width="406" alt="_private_tmp_a_rb" src="https://user-images.githubusercontent.com/120483/102622846-84afff00-4139-11eb-986c-40696ab27163.png"> |

Ruby constants highlighted as Type

---

queries/markdown/highlights.scm

This enables highlighting of inline html comments in markdown (see #976 )

Add inline html comments highlighting for markdown

---

lockfile.json
queries/ocaml/highlights.scm

Now quoted strings can contain other nodes. Also change the order of highlight captures to adapt to neovim's order and added a couple of captures more.

Update ocaml parser to latest master

---

lua/nvim-treesitter/parsers.lua
queries/glimmer/highlights.scm
queries/javascript/injections.scm

Idk if this is correct, but I know that gql usage is similar:
```js
const query = gql`
query stuff
`;
```
so I copy-pasted that for glimmer, which looks like
```js
cost template = hbs`
<glimmer-stuff />
<html-like />
`;  
```
Here is the WIP syntax support for glimmer: https://github.com/alexlafroscia/tree-sitter-glimmer

Support the glimmer parser when the `hbs` template literal tag is used

---

queries/c/indents.scm
queries/cpp/indents.scm
queries/css/indents.scm
queries/go/indents.scm
queries/html/indents.scm
queries/java/indents.scm
queries/javascript/indents.scm
queries/jsonc/indents.scm
queries/lua/indents.scm
queries/ruby/indents.scm
queries/rust/indents.scm
queries/svelte/indents.scm

It doesn't work 100% though, for example this jsdoc comment
```javascript
// Original
/**
* Some description
* @param {string} foo - bar
* @return foo
*/
const foo = (foo: string): string => foo
// Without this PR
/**
* Some description
* @param {string} foo - bar
* @return foo
*/
const foo = (foo: string): string => foo
// After this PR (incorrect)
/**
* Some description
* @param {string} foo - bar
* @return foo
*/
const foo = (foo: string): string => foo
// Shouldn't get affected by the indent rule (correct)
/**
* Some description
* @param {string} foo - bar
* @return foo
*/
const foo = (foo: string): string => foo
```

feat: use @ignore for comments and multiline strings

---

CONTRIBUTING.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/highlight.lua
plugin/nvim-treesitter.vim
queries/dart/highlights.scm
queries/julia/highlights.scm
queries/ruby/highlights.scm

Addresses issue #892
Ruby and Dart literal symbols will now be highlighted by the new
TSSymbol highlight group, which itself will, by default, link to the Vim
Identifier highlight group. Vim theme authors can then set their
TSSymbol colors.
Symbol highlighting can apply to a number of languages as noted in the
following Wikipedia page: https://en.wikipedia.org/wiki/Symbol_(programming)
Not just for Ruby and Dart.
Closes #892

[highlights] Add TSSymbol highlight group

---

.github/workflows/test.yml
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/shell_command_selectors.lua
scripts/ci-install-macos-latest.sh
scripts/ci-install-ubuntu-latest.sh
scripts/ci-install-windows-latest.sh

I tried #347 and changes were looking fine(`cd` does not like `;`), but since the branch was too old I decided to do it this way.
Changes are working tested on windows machine. Also to make this work `nvim` has to be started from `Developer Command Prompt` (`cl.exe` has some environmental needs)

Add CI and Windows support for cl.exe

---

queries/dart/indents.scm

The `case` block can't be indented because the query doesn't group them (same with Java). Also, there's this scenario because I couldn't define *how many* it should get indented using the query.
```dart
// correct
static Future<Nvim> spawn(
{String nvimBinary = 'nvim',
List<String> commandArgs = const ['--embed'],
NvimHandler onNotify,
NvimHandler onRequest}) async {
var nvim = Nvim._spawn(nvimBinary, commandArgs);
nvim._nvim = await nvim._nvimFut;
// ....
}
// after indenting
static Future<Nvim> spawn(
{String nvimBinary = 'nvim',
List<String> commandArgs = const ['--embed'],
NvimHandler onNotify,
NvimHandler onRequest}) async {
var nvim = Nvim._spawn(nvimBinary, commandArgs);
nvim._nvim = await nvim._nvimFut;
// ....
}
```
ps: the code was stolen from [smolck's …

feat(dart): add indents

---

lua/nvim-treesitter/health.lua

cc @vigoux @theHamsta   treesitter 0.19 has some problem with neovim,so add the version in checkhealth will be useful. it works like this

add treesitter version in checkhealth

---

queries/ecma/highlights.scm
queries/rust/highlights.scm

(File shown is Javascript (.js))
Before: Parameter in callback function highlighted as TSVariable (white)
After: Parameter highlighted as TSParameter
(TSParameter colour is pink italic, TSVariable is white)
Arrow functions taking a single parameter with brackets omitted were not having their function arguments highlighted when they were passed as an argument.

Ecma: Highlight single-argument callback parameter

---

lua/nvim-treesitter/health.lua

Without this newline there is no syntax highlighting after the legend.

Add newline before legend

---

.github/workflows/update-parsers-pr.yml

This is an attempt to attend to: https://github.com/nvim-treesitter/nvim-treesitter/pull/1037#discussion_r595484547
as tree-sitter-clojure's master branch now has changes for upgrading to 0.19.x on it.
@theHamsta How's this?

Remove SKIP_LOCKFILE_UPDATES_FOR_LANGS

---

lua/nvim-treesitter/health.lua

Replace the asterisk used for "Multiple parsers found" by a plus sign. It prevents the asterisk from messing up the formatting of the rest of the `:checkhealth` buffer.

fix formatting issues caused by asterisk

---

lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/highlight.lua

I thought this is a better solution than giving an option to `ts.highlighter` (the culprit that deactivates syntax) because it seems to handle also the case no syntax was loaded (though in a weird way by deactivating syntax and then checking whether it's deactivated).
Fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/959
@sperezconesa can you check whether this works?
You would add the option `additional_vim_regex_highlighting = true` to you setup call of nvim-treesitter in the highlight section.

Syntax plus treesitter

---

queries/go/highlights.scm

As same as https://github.com/nvim-treesitter/nvim-treesitter/pull/1034 which adds built-in functions, this PR adds built-in `types`.
ref: https://golang.org/pkg/builtin/

go: add builtin types

---

queries/rust/highlights.scm

Treat `,` as a punctuation delimiter for `Rust`.

rust: treat `,` as a punctuation delimiter

---

lua/nvim-treesitter/indent.lua

The current implementation can make indent_size zero if shiftwidth is zero which results in no indentation for any line. With normal vim auto-indent shiftwidth is always used for indent size, unless it's zero in which case tabstop is used instead. The `vim.fn.shiftwidth()` function returns shiftwidth if it's non-zero and tabstop otherwise.

Fix indent size

---

README.md
lua/nvim-treesitter/health.lua
lua/nvim-treesitter/query.lua
plugin/nvim-treesitter.vim

Recently we don't get the actual error message due to compact health check. At least when we have errors we should not be too compact. Also really do the health check and don't rely on previously cached query loads.

Health error

---

README.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/utils.lua

This allows a list of parsers to be ignored from install. This is useful when you want 'all' parsers except maybe one that may be having issues or that you just don't want. For example, my scenario, three parsers fail to compile on macos so I want to exclude them.

feat(install): ignore parser install option

---

lua/nvim-treesitter/install.lua

@richban could you try which path this function actually returns on your machine: https://github.com/theHamsta/nvim-treesitter/blob/b8c2128e7954fd7916c2004d92aa831b8f2d9c32/lua/nvim-treesitter/utils.lua#L40-L46 ?
This PR should at least allow you to use nvim-treesitter without lockfile when it does not exist.

Address #1067: check whether lockfile exists

---

queries/rust/highlights.scm

The closure parameters can be de-referenced and then they are no longer identifier but ref_patterns.
```rust
vec.iter().fold(0, |acc, &m| acc + m)
```
Before:
After:

highlights(rust): Highlight dereferenced closure parameters

---

queries/ecma/injections.scm
queries/jsdoc/highlights.scm

Using separate queries makes it work as expected.
Also, for the comment parser to be able to override the other tokens
we need to remove the comment from highlights (this shouldn't be a
problem since that section is already highlighted as a comment).
And, the order of the captures matter,
having jsdoc first will have more priority over `@param`.
Fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/1069

Fix jsdoc: play nice with the comment parser

---

lua/nvim-treesitter/indent.lua
queries/jsx/indents.scm

Fixes #1019
Fixes #1074
Fixes #802
One issue with this PR is that python is still not working as expected.
I'm not sure why but python behaves quite strangely:
typing `def a():` gives a node without errors (although it's an empty function) thus indenting like the function start row
typing
```python
def a():
print(1)
|
|
```
it will indent on every new line (not sure if this is expected behavior.
I'm pretty sure the singularity of the python language makes it hard to make it work with other languages. (EDIT: maybe this could be solved with more advanced indent queries)
If someone has an idea on how to fix that, i'd be happy to hear them.
@jedrzejboczar i'd like your input on this. Newline indent is working super well with this PR, but for python i did not manage to make it work properly. …

fix: indent on new line

---

lockfile.json
lua/nvim-treesitter/health.lua
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/parsers.lua

- Error when `node` is not available on `:TSInstallFromGrammar`
- exclude `requires_install_from_grammar` parsers from `all`/`maintained` when user has no tree-sitter CLI
Will the parsers be updated to 0.19.X at some point? @cbarrete @undu  @ostera @madskjeldgaard @leo60228

Add node requirement

---

lockfile.json
queries/comment/highlights.scm

As requested in https://github.com/nvim-treesitter/nvim-treesitter/issues/236#issuecomment-797878646. No colons needed.

Comment: highlight text nodes

---

lua/nvim-treesitter/info.lua

Just a few small changes to make it more pleasant to read (IMHO):
- 2 spaces between modules in the header
- always same module order in the header (random order is super confusing)
- marks are exactly below the start of the module name in the header
- most importantly.. sort the languges by name. :P
Before:
After:

Improve :TSModuloInfo output

---

doc/nvim-treesitter.txt
lua/nvim-treesitter/info.lua

The new version uses its own buffer for listing the modules state for the current session.
Since there can be many modules and many using submodules, the code sorts them into namespaces. A list with the following modules..
{'indent', 'highlight', 'refactor.smart_rename', 'refactor.navigation'}
..will be changed to..
{ default = {'indent', 'highlight'}, refactor = {'smart_rename', 'navigation'} }
There is one table per namespace.
The colors are up for debate, but I added the highlight groups to the doc, in case people don't like the defaults.

:TSModuleInfo rewrite

---

lua/nvim-treesitter/query.lua

From https://www.lua.org/pil/20.html
> The call string.sub(s,i,j) extracts a piece of the string s, from the i-th to the j-th character inclusive.
This was breaking textobjects movement.

Fix usage of string.sub

---

queries/yaml/locals.scm

The parser doesn't break the symbols in `*` `&` from the name of
anchors/aliases. So go to definition doesn't work, but highlight of
usage does :D
Test with
```yaml
Defaults: &defaults
Company: foo
Item: 123
Computer:
<<: *defaults
<<: *defaults
Price: 3000
```
Ref https://github.com/nvim-treesitter/nvim-treesitter-refactor/issues/18

Yaml: update locals

---

queries/go/locals.scm

This would define `foo`
```go
import (
foo "fmt"
)
```

locals(Go): add namespace definition for import_spec_list

---

lua/nvim-treesitter/tsrange.lua

@michaelb would this fix your problem?
Maybe we should remove :TSRange altogether and work on directives upstream (similar to `offset!`)?

Fix #1182: fix TSRange:parent

---

lua/nvim-treesitter/shell_command_selectors.lua

This PR is a rebase of https://github.com/AdnoC/nvim-treesitter/tree/windows-tar-workaround as requested in #813.
This is a quick rebase, I've tried to keep the intended logic in place but I'm not exactly a git guru. 😃
There was one change introduced in 60e67de18c69d57691b09738585d58515458a281 which introduces the use of  `'-c', 'core.symlinks=true'` which caused the clone to fail again so I deleted that line.
I hope, that's okay. 😃 
At least I could now run `:TSUpdate`  and successfully update tree-sitter-typescript.

rebased AdnoC/windows-tar-workaround on master

---

lua/nvim-treesitter/configs.lua

- Choice already starts with 1, there isn't need to increment 1
- The first item is the prompt as recommended in `:h inputlist()`
(this way the choice matches when using the mouse)

Fix TSEditQuery with several files

---

queries/ruby/indents.scm

Hi all!
I have been using *nvim-treesitter*  for a few days (thanks!) and I found out that Ruby singleton classes are not indented. This is the result:
```ruby
class Sample
class << self
def say_hello
"hello!"
end
end
end
```
Adding the `singleton_class` element to the `indents.scm` list makes indentation look good:
```ruby
class Sample
class << self
def say_hello
"hello!"
end
end
end
```
Thanks!

Indent Ruby singleton classes

---

lua/nvim-treesitter/parsers.lua
queries/gdscript/highlights.scm

Everything is now highlighted correctly, similar to Python:
Also sent a PR to fix `:=` parsing in [grammar.js](https://github.com/PrestonKnopp/tree-sitter-gdscript/pull/5).
Many thanks to @theHamsta and @vigoux for guiding me!
Fixes #1181.

Fix GDScript highlighting

---

lockfile.json

Otherwise the Haskell parser would eat up all your RAM within seconds.

Fix #1207: update Haskell

---

lua/nvim-treesitter/fold.lua
queries/c/folds.scm

Do actually two things :
- fix(c): fold switch statements
- fix(folds): always fold more than one line

Some fixes with folds

---

queries/ecma/highlights.scm
queries/julia/highlights.scm

Closes #470.
As a note:
- Rust can't be done because the ternary is actually and `if {} else {}` statement
- I can't find anything in Dart

fix(highlights): always highlight ternary operator as operator

---

queries/lua/highlights.scm

This correctly handles field names in lua.
The query is a bit bizarre then, but that's because the parser does
not handle fields so well...
Fixes #1180

fix(lua): correctly highlight field names

---

lockfile.json
lua/nvim-treesitter/parsers.lua

Not required after https://github.com/cstrahan/tree-sitter-nix/pull/11

parsers: nix no longer requires_generate_from_grammar

---

queries/c_sharp/highlights.scm

Last update mentioned operator "with". We didn't have it in the queries.

highlights(csharp): add "with" as `@keyword.operator`

---

.github/workflows/check-query-files-and-compilation.yml
scripts/check-queries.lua

@vigoux  I don't know how to handle this best. I guess @elianiva needs some more time with the Haskell parser and it was expected to fail for a long time. We could have this to actually check whether CI is not failing for parsers we would not expect that it would. We could also just wait until Haskell can be installed properly-
A PR adding queries for Haskell should find a proper solution.

Allow failures for defined parsers

---

queries/vue/injections.scm

Before:
After:
This also works for v-bind (but not for regular arguments). Is this PR too naive? Perhaps there's some cases that I missed

Highlight v-bind and v-on using javascript

---

lua/nvim-treesitter/fold.lua

Fixes a bug introduced in 41ed83ffc762b611644a311e344b33d5efc01944
Closes #1226

fix(folds): use the correct rational operator

---

queries/cpp/highlights.scm

Highlight `using namespace foo; using namespace foo::bar;`

C++ highlights: Using namespace

---

README.md
lua/nvim-treesitter/parsers.lua
queries/gomod/highlights.scm

Adds a tree-sitter config for go.mod files as well as highlighting
queries.
A couple of notes:
- This only adds highlighting queries (not indentation, folds, etc.). I couldn't find any documentation on how those are interpreted. Happy to add those as well with some help. 
- This requires a `ftdetect` rule for go.mod files that sets `filetype=gomod`. It seems that graphql also doesn't set its filetype, so I wasn't sure if this is something that should be handled in this plugin. 
Example of it in action:

Add go-mod tree-sitter config

---

README.md
lua/nvim-treesitter/parsers.lua
queries/c/highlights.scm
queries/fish/folds.scm
queries/fish/highlights.scm
queries/fish/indents.scm
queries/fish/injections.scm
queries/fish/locals.scm

Closes #1268.
One small issue I have which I have not been able to figure out is how to highlight all command options like `--description`. As you can see from the highlight snippet below, only the first command option is highlighted (`--argument-names`) and following option on the same line (`--description`) is ignored. The following syntax highlight rule is from line 93:
```
(command
argument: [
(word) @parameter (#vim-match? @parameter "^-")
]
)
```
> Highlight
> Indent
Works well for every statement listed in `indents.scm` apart from `if_statement`. When adding `else` or `else if` clauses the indenation doesn't work and the `end` keyword indents on enter. See gif below.
> Folds

Add fish queries

---

README.md
lua/nvim-treesitter/parsers.lua

chore(erlang): don't generate parser from grammar

---

ftdetect/gdscript.vim
ftdetect/query.vim

I used `BufNewFile,BufRead` as suggested in `:h ftdetect`. I also noticed that we have `query.vim` that use `BufEnter,BufNewFile`. Probably we should change it to `BufNewFile,BufRead` too.

Add GDScript filetype and use BufNewFile,BufRead

---

README.md
lua/nvim-treesitter/parsers.lua
queries/dockerfile/highlights.scm
queries/dockerfile/injections.scm

This adds a config, highlights, and injections for Dockerfile parsing. 
Example:

Add config for Dockerfile parser

---

lockfile.json
queries/ocaml/highlights.scm

The updates removes a couple of aliases to avoid circular dependency. This causes a couple of more nodes to appear and needs a change in the highlights.
obsoletes #1282

Update ocaml parser

---

queries/latex/highlights.scm

https://github.com/neovim/neovim/pull/14382 requires to escape `\` in regexes if they are verbatim `\` (behavior of tree-sitter web or tree-sitter rust lib)
The change in Neovim was incompatible so people that are still behind that revision will have this regex not matching (but it should at least not error)

highlights(latex): fix regexes with backslashes

---

ftdetect/gomod.vim

A parser for go.mod files was added in #1259, but neovim does not set the correct filetype for go.mod files by default. This adds a ftdetect rule to set `ft=gomod`.

Add filetype detection for go.mod files

---

queries/fish/injections.scm

I used the bash injections.scm file as reference before #1266 was merged, so I am removing `@combined` since its clearly problematic.

Fish queries remove `@combined` from injections

---

queries/ecma/highlights.scm

Hi and thank you for your work!
This PR attempts to utilise more documented highlight treesitter groups. In the documentation it is mentioned that there is TSKeywordFunction which is not being used for ecma languages. This PR fixes it. Now theme developers should be able to distinguish function keyword from other language keywords.

highlights(ecma): use KeywordFunction as a highlight group for function

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/fortran/highlights.scm

Supercollider no longer requires generate from source

parsers: Fortran/Supercollider no longer requires_generate_from_grammar

---

queries/fish/highlights.scm

https://github.com/krnik/tree-sitter-fish/commit/1c25205cd7a68434bd1e576972193b3994404307 moved `test` under `test_command`, so the `command` highlighting no longer applies.

Fish highlights move `test` to `test_command`

---

queries/html/highlights.scm
queries/html_tags/highlights.scm
queries/html_tags/injections.scm
queries/svelte/highlights.scm
queries/svelte/injections.scm
queries/vue/highlights.scm
queries/vue/injections.scm

This should avoid duplication and easier maintenance for html, vue, and svelte. 
While doing this, I noticed `<script>` tag injection with `lang="ts"` injects both Javascript and Typescript -- which causes the type for a line like `export let asdf: string` gets highlighted as Javascript indetifier instead of Typescript type.
This is similar to #1209 which hopefully will be fixed by #1238.

refactor: make html-like languages inherit from single query

---

lua/nvim-treesitter/parsers.lua

The Common Lisp parsers depends on the Clojure parser when installed from grammar.js

parsers: generate_requires_npm for commonlisp

---

queries/dart/highlights.scm

Relates to https://github.com/UserNobody14/tree-sitter-dart/issues/18
Not sure what the outcome of that issue will be but this attempts to update/fix some highlights in the interim.

feat(dart): add async/sync* to highlights

---

queries/c/indents.scm
queries/cpp/indents.scm

Fixes #1320
I don't know very well how indents works so better rely on C indents. Also add class_specifier.

indents(c/cpp): let C++ use the C indents and add class_specifier

---

queries/rust/highlights.scm

highlights(rust): highlight fields with shorthand_field_initializer

---

README.md
lua/nvim-treesitter/parsers.lua

The original repo has been updated [4 days ago](https://github.com/serenadeai/tree-sitter-scss/commit/9da7c979c010c350c28ad2235893103db4622c10), better to use that instead.

feat: use serenadeai scss

---

queries/elixir/highlights.scm

`with` is also considered a conditional in Elixir. Highlight it accordingly.

Elixir: Highlight `with` as conditional

---

queries/elixir/injections.scm

1. Add markdown placeholder injection for when Markdown is re-added. This is enabled in the screenshot
2. Add regex injection

Add injections for Elixir

---

lua/nvim-treesitter/query_predicates.lua
queries/ruby/injections.scm

This is a follow-up to https://github.com/neovim/neovim/pull/14152 which was superseded by https://github.com/neovim/neovim/pull/14046 which allows setting the injected parser language on the metadata field of directives.
I moved the implementation of the `#downcase!` directive I proposed in https://github.com/neovim/neovim/pull/14152 to this plugin as it seems to be a better home for it.
Often times the text matched by an `@language` node may not exactly resemble the name of the parser for that language. More often than not the parser name will be lowercase, i.e. `html` instead of `HTML`. In the below example ruby code a string constant is defined using ruby's heredoc syntax. The coding conventions for heredocs are to surround the string content with the name of the language in all …

#downcase! directive to use with ruby injections

---

queries/jsx/highlights.scm

PR links to [this issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/1028).
JSX queries for highlighting are updated so that components with capital first letter are highlighted as constructor instead of type which should be the correct behavior.

jsx query - Components as constructor instead of type

---

lua/nvim-treesitter/parsers.lua
queries/c_sharp/folds.scm
queries/c_sharp/highlights.scm

Improved highlights and folds. Addresses #1349.
Here's a before and after for the highlights:
<details>
<summary>before:</summary>
</details>
<details>
<summary>after:</summary>
</details>
<details>
<summary>folds in action:</summary>
</details>
Some notable changes:
- `var` is now highlighted as a keyword. This felt like a more logical highlight than type.
- The first identifier in a series of identifiers (like `Console.WriteLine()`) is no longer highlighted as a type. This change was reverted (from #1351). The reasoning behind this is that this identifier isn't necessarily a type, it could also be a namespace. Since we don't really have any idea of which it could be, I think it's better to leave it blank for now.
- Field declarations are no longer restricted to starting with `_` or …

More C# improvements

---

queries/fish/highlights.scm

- Changes `match?` to `any-of?` for builtin functions
- Simplifies boolean highlight

fish: make use of any_of predicate for builtin functions

---

README.md
queries/dart/highlights.scm

This PR removes the usage of assignable selector, it turns out it was not necessary so it was hidden upstream to reduce noise in the tree. The same result is achievable for highlighting just using `unassignable_selector`
@theHamsta this should fix the issue caused by the most recent commits in the dart parser. I've done this as a PR into the `update-lockfile-pr` since the changes need to go together tbh. Can change it if you'd prefer staggering them or something in which case it's better that this goes in before the update one.
Full rationale for the change upstream is: https://github.com/UserNobody14/tree-sitter-dart/issues/19#issuecomment-854820659

fix: assignable selector was removed

---

queries/zig/highlights.scm

* Highlight the built-in `@import` function with the TSInclude highlight group
* Highlight character literals using TSCharacter instead of TSNumber

Update zig highlights

---

queries/cpp/highlights.scm

Current highlighting queries capture all identifiers with uppercase initials as types, which may work very poorly on some codebases, e.g. LLVM. This PR removes these heuristics and let (I guess) the inherited c highlighting queries do their work. Below are a comparison before and after the changes:

c++ highlights: don't capture all identifiers with uppercase initials as types

---

queries/rust/highlights.scm

- The derive query was incorrect, it was only matching `#[derive(derive)]`
- Macros were being highlighted as keywords
- Procedural macros symbols weren't highlighted (`#`, `#!`)

Rust: fix macros highlights

---

README.md

Fixed typo for "alternatively".

Fixed typo in `README`

---

README.md
lua/nvim-treesitter/parsers.lua
queries/cuda/folds.scm
queries/cuda/highlights.scm
queries/cuda/indents.scm
queries/cuda/locals.scm

I working on a CUDA parser that is basically just an extension of the C++ parser with support for CUDA's kernel call syntax.

parsers: add tree-sitter-cuda

---

queries/scss/highlights.scm

Single line comments, or doc comments, are defined in the [SCSS syntax](https://sass-lang.com/documentation/syntax/comments) and are also included in the [tree-sitter-scss/grammar.json](https://github.com/serenadeai/tree-sitter-scss/blob/9da7c979c010c350c28ad2235893103db4622c10/grammar.js#L366) file, but they are missing from the highlight files.
This PR adds the missing highlight group.
Before:
After:

highlight: add SCSS single_line_comment

---

queries/lua/highlights.scm

I added `self` as a builtin keyword for highlighting Lua code

feat: added `self` as builtin keyword for Lua

---

queries/rust/injections.scm

> THANKSSSSSSSSSSSSSSSSSSSS @Conni2461 ❤️ ❤️ 
This PR adds html ot html! macro. Many packages define their own html! tag or use popular ones. Thus, it is an awesome addition for people expermenting with wasm and rust.

rust: inject html to html! macro

---

queries/bash/highlights.scm
queries/clojure/highlights.scm
queries/comment/highlights.scm
queries/glimmer/highlights.scm
queries/go/highlights.scm
queries/julia/highlights.scm
queries/ocaml/highlights.scm
queries/svelte/injections.scm
queries/vue/injections.scm

With this pr, uses of `#match?` of the form
```lisp
(#match? "^(opt1|opt2)$")
```
are translated to
```lisp
(#any-of? "opt1" "opt2")
```
to increase readability, except where the pattern includes a prefix before the choices

Use `#any-of?` instead of `#match?` where posible

---

queries/haskell/highlights.scm

Since Haskell parser is getting better, I guess it's time to add the highlight query. 
Bare in mind that I just started to learn Haskell recently so the highlight group used here might not be accurate, so please give me your suggestions :)
you *might* want to take a look at/try this @phaazon

feat: add haskell highlights

---

lua/nvim-treesitter/query.lua

Right now, `has_query_files` with `nvim_get_runtime_file` is being executed a lot, which slows down TreeSitter code quite a bit. Especially when folding is enabled,
This PR caches the result so subsequent calls are instant.
Fixes #1438 
Fixes #1267

perf: cache has_query_files: fixes TS slowness

---

queries/php/highlights.scm

I added `fn` as a arrow funciton keyword for highlighting PHP code

Adds support for PHP's arrow funcion

---

lua/nvim-treesitter/query.lua

Check for `nil` is needed
Fixes #1444

fix: check if invalidate_query_cache[lang] is set before invalidating

---

queries/haskell/highlights.scm
queries/haskell/injections.scm

This PR adds highlights and injections for some common quasiquotes in Haskell.
I've been recently playing around with [IHP](https://github.com/digitallyinduced/ihp) which uses HSX quasiquotes. The screenshots below show the difference:
**Before:**
**After:**
As well as HSX, the PR also adds injections for the [shakespeare library](https://hackage.haskell.org/package/shakespeare), though at the moment it doesn't have special highlighting for templates.

Add common quasiquote highlights/injections for Haskell

---

queries/latex/injections.scm

Add comment highlighting in LaTeX for `TODO`, `FIXME`, etc.

---

queries/dart/highlights.scm

This PR adds in some more missing highlights for dart namely
* conditional_assignable_selector `field?.property`
* multiplicative operator e.g. `/,*`
I'm also trying to gerryrig a function call highlight, since there isn't really a node that identifies a function call.
From the grammar I see that the structure of a function call is
```dart
function_call(args)
// Identifier - selectors (argument_part)
```
So I tried using
```scheme
(((identifier) (selector . (argument_part)) @function)
```
However, using that query matches too many incorrect things, any advice would be much appreciated.

feat(dart): add multiplicative_operator

---

queries/query/highlights.scm

Only highlight the name of the predicate using TSFunction rather than
the entire predicate block.

query: Only highlight predicate name

---

queries/typescript/highlights.scm

highlights(typescript): fix indentifier for type imports

---

queries/python/highlights.scm

Apply fix suggested in https://github.com/nvim-treesitter/nvim-treesitter/issues/1441#issuecomment-870342791

python(highlights): don't use type for APP

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/hcl/folds.scm
queries/hcl/highlights.scm
queries/hcl/injections.scm

A parser for HCL (https://github.com/hashicorp/hcl). It could be useful for terraform, nomad, waypoint etc. It works fairly well for me right now.  
https://github.com/MichaHoffmann/tree-sitter-hcl
I'm using the highlight queries with the `onedark` colorscheme right now and they look ok, but are probably not canonical:

parsers: add HCL

---

queries/dart/highlights.scm

This is a work around since currently the upstream grammar does not support a `call_expression`. I hope to add this at some point in the future, but I'm not sure exactly when I'll have time to do it. In the short term, this allows function calls to be highlighted by using the fact that function calls are structured in a certain way, i.e. an identifier with a sibling node that has an argument part.

feat(dart): add function call expression highlight

---

queries/fish/highlights.scm

With this change, only the `test` keyword in test commands is highlighted as a function rather than the entire condition.
Before:
After:
Notice in the before picture that the parens and operator in the condition are highlighted.

fish: only highlight 'test' keyword instead of entire condition

---

lua/nvim-treesitter/parsers.lua

Fixes the missing `maintainer` field in the hcl parser config.

fix missing maintainer in hcl parser config

---

lockfile.json
queries/hcl/highlights.scm

* bumped the dependency of the hcl parser to make some tokens visible
* added a query for object element keys that are identifiers to highlight them as though they were block attributes
* dont highlight the whole `quoted_template` and `heredoc_template` as strings, but only the "stringy" parts

queries(hcl): improve highlighting

---

queries/hcl/folds.scm

Allows a fold on the `bar` object in 
```hcl
foo {
bar = {
man = mortal
socrates = man
}
}
```

fold HCL objects

---

CONTRIBUTING.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/highlight.lua
plugin/nvim-treesitter.vim
queries/c/highlights.scm
queries/c_sharp/highlights.scm
queries/dart/highlights.scm
queries/ecma/highlights.scm
queries/fish/highlights.scm
queries/fortran/highlights.scm
queries/gdscript/highlights.scm
queries/go/highlights.scm
queries/java/highlights.scm
queries/julia/highlights.scm
queries/kotlin/highlights.scm
queries/lua/highlights.scm
queries/php/highlights.scm
queries/python/highlights.scm
queries/ruby/highlights.scm
queries/rust/highlights.scm
queries/teal/highlights.scm
queries/verilog/highlights.scm
queries/zig/highlights.scm

Not too sure about [`teal`](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/teal/highlights.scm#L22) and [`fish`](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/fish/highlights.scm#L79-L81) since I wasn't able to find the meaning of `(WORD)` within a group of word.
I have tested this locally and it seems to work as expected.
closes #1485
@theHamsta

Add keyword.return & keyword.yield

---

lua/nvim-treesitter/parsers.lua

html_tags and ecma don't have a parser of they own,
but that's actually just to get around to inherit
common queries.
When editing these "base" queries,
the playground breaks. Having them in used_by would fix this https://github.com/nvim-treesitter/playground/pull/43

Update used_by for parent parsers

---

.github/workflows/lint.yml
.luacheckrc
scripts/pre-push
scripts/style-check.sh

The `--codes` flag can also be set from the config file

Luacheck: use config file to exclude files

---

queries/ecma/indents.scm

Fixes #1384
Before:
```js
var a = "b"
switch(a) {
case "a":
return "hmm";
case "b":
return "hmm2";
case "c":
return "hmm3";
case "d":
return "hmm4";
}
```
After:
```js
var a = "b"
switch(a) {
case "a":
return "hmm";
case "b":
return "hmm2";
case "c":
return "hmm3";
case "d":
return "hmm4";
}
```
---
This is my first functional PR here, please let me know if this isn't appropriate.

fix(ecma): add indent to switch and cases

---

lua/nvim-treesitter/fold.lua

The old logic to deduplicate folds was too lax: it only checked that both the start and the end existed, not that they were part of the same fold. This broke situations like
```
struct a {
};
struct b {
};
```
because the C fold file defines a `translation-unit` fold node, which combined with `struct a`, caused `struct b`'s fold to be ignored. The new logic works correctly as long as the nodes are given in preorder (which seems to currently be the case); let me know if that assumption is bad.
Also, revamp the start/stop logic to be more explicit, and make it handle `foldnestmax` slightly better.

Folds: fix fold deduplication and improve start/stop logic

---

queries/ecma/highlights.scm

I believe I have discovered a bug and a potential fix for it. I noticed that the braces for template string quasis are coloured inconsistently, I have set vivid colours for these 2 highlight groups
```vim
hi TSPunctBracket guifg=Yellow
hi TSPunctSpecial guifg=Red
```
`:TSHighlightCapturesUnderCursor` output for the closing brace
```
* @string -> javascriptTSString -> TSString
* @none -> javascriptTSNone -> TSNone
* @punctuation.special -> javascriptTSPunctSpecial -> TSPunctSpecial
* @punctuation.bracket -> javascriptTSPunctBracket -> TSPunctBracket
```
It seems that `TSPunctBracket` is overlaying(not sure if the word suits here) `TSPunctSpecial` which should be preferred here.
By placing the template string section after the section with braces  in `queries/ecma/highlights.scm` the …

Fix ecma template string braces highlight group

---

scripts/ci-install-macos-latest.sh

Out CI compiles the LLVM project at the moment. No wonder that Mac CI takes a long time.

CI: remove LLVM compilation from Mac CI

---

queries/julia/folds.scm
queries/julia/indents.scm

The julia.vim plugin has more indentation rules for collection literals, making matrices easier to read. I don't know how that would work with tree-sitter queries so I just ignored it. This only adds one indentation level, like the indent queries for other languages. I think it's fine for now, but I'd be interested in improving it in the future.

Add Julia indent queries and update fold queries

---

queries/lua/highlights.scm

In lua
```lua
function foo() end
```
is syntax sugar for
```lua
foo = function() end
```

Lua: highlight function definitions

---

queries/rust/highlights.scm

derive macros have to be defined after attribute macros for types to be highlighted properly.
EDIT: I wrote it the other way around in the commit :s
See #570

highlights(rust): Reorder macro queries

---

lua/nvim-treesitter/query_predicates.lua

get_node_text could be nil if the range is invalid.
Together with https://github.com/neovim/neovim/pull/15030/
this fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/1531

downcase predicate: nil protection

---

queries/elixir/folds.scm

This adds support for folding in elixir files.
This adds basic folding to any do blocks and anonymous functions. I think we can probably add folding to lists and maps, but I couldn't get immediately work, so I figured I could add the bare basic support for and figure out the rest later.
cc @nifoc

[elixir] basic folds

---

queries/jsx/highlights.scm

highlights(jsx): fix constant identifier

---

queries/python/highlights.scm

A class definition was being highlighted only if it has methods, we should just always highlight class definitions.
Closes https://github.com/nvim-treesitter/nvim-treesitter/issues/1546

Python: fix class highlights

---

doc/nvim-treesitter.txt
lua/nvim-treesitter/highlight.lua
plugin/nvim-treesitter.vim
queries/supercollider/highlights.scm

This was in our CONTRIBUTING.md file,
but wasn't defined.
Fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/1405

Highlights: define string.special

---

README.md
doc/nvim-treesitter.txt

It's a bit a of a duplication but at least the option is present where ever the other options of the module are documented.
Should the disclaimer of `docs/nvim-treesitter` also be added to the short-info in README?

doc: be more explicit about additional_vim_regex_highlighting

---

CONTRIBUTING.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/highlight.lua
queries/html_tags/highlights.scm
queries/jsx/highlights.scm

This PR adds distinct `@tag.attribute` for things like html/jsx, and to avoid mixing up the markup stuff with attributes/annotations from programming languages.
Sorry @theHamsta, I did a mess with the rebase in the other PR so I re-did it from current master. I hope it all looks ok now!

add @tag.attribute for html like attributes

---

plugin/nvim-treesitter.vim

Create the TSTagAttribute highlight group, links with TSProperty for backwards compatibility
https://github.com/nvim-treesitter/nvim-treesitter/pull/1572#issuecomment-879756651
references #1572

create TSTagAttribute highlight group

---

queries/c/folds.scm
queries/cpp/folds.scm

In C++, enums insides classes are parsed as type and default_value.

c(folds): fold on enums

---

queries/c/highlights.scm

A macro function such as
#define FOO(x) ...
should be highlighted with `@function.macro`, even though the name is in
all-caps (which would otherwise be treated as a constant). Similarly,
call sites of such functions, e.g.
int y = FOO(x);
should be highlighted with `@function` instead of `@constant`.
This is as simple as moving the query definition for functions
after the query definition for constants.

c: don't treat uppercase functions as constants

---

lua/nvim-treesitter/fold.lua

These cause vim to become more confused when there are multiple folds ending on the same line. For instance, consider:
```
int main() {         // >2
if (1) {         // >3
if (0) {     // >4
}}               // <4
}                    // <2
```
For some reason, including the ending mark on line 5 causes the level-3 fold to end on line 5 instead of line 4 (???). This should probably get fixed upstream, but this is a fine workaround for now.

Folds: remove ending marks for folds

---

ftdetect/hcl.vim

HCL parser was added in https://github.com/nvim-treesitter/nvim-treesitter/pull/1445, but neovim does not set the correct filetype for `*.hcl`, `*.tf` and `*.tfvars` by default:
This PR adds a `ftdetect` rule for those files:

feat: add HCL file type detection

---

README.md
ftdetect/yang.vim
lua/nvim-treesitter/parsers.lua
queries/yang/highlights.scm

I spent the last couple of weeks learning about Tree-sitter and implemented a parser for YANG, which I use extensively at work. It would be cool to add it to nvim-treesitter. I made a highlights query as well, it works really well:

Add YANG parser

---

queries/clojure/highlights.scm

I've been using these for the last week or so and they seem pretty good.
Some tweaks may be needed but they're definitely a better start (imo).
(using [moonlight.nvim](https://github.com/shaunsingh/moonlight.nvim))
<div float="left">
</div>
I think the Neovim default might be coming from conjure, but I still think the tree-sitter one is cool.

Improve clojure highlighting

---

lua/nvim-treesitter/shell_command_selectors.lua

Some versions of tar automatically infer `-z` if a `.gz` (or other compressed extension) file is passed -- but some, including OpenBSD's, don't do this and require an explicit `-z`. As far as I know, any version of tar which automatically unzips files supports `-z` so this should be a backwards compatible change for most versions of tar.

Add `-z` switch to tar.

---

README.md

When getting set up, the current instructions make me think I have to write `:TSInstall {'python'}`, when the correct command is `TSInstall python`
Let me know if this makes sense 😄

Updated TSInstall example command.

---

lua/nvim-treesitter/highlight.lua

I was debugging a telescope buffer previewer yesterday and stumped upon this "inconsistency".
The docs are talking that this could be a list of languages. https://github.com/nvim-treesitter/nvim-treesitter#modules
But you were treating it like a set.
One of both needs to be adjusted in my opinion, its your call which one :)

fix: make additional_vim_regex_highlighting actually accept a list

---

queries/gdscript/highlights.scm

The regex is broken and decided to remove it, it's better to parse it at the grammar side.
Before:
After:

Remove regex for field in GDScript

---

README.md
lua/nvim-treesitter/parsers.lua
queries/godotResource/folds.scm
queries/godotResource/highlights.scm
queries/godotResource/locals.scm

This aims at giving support to `*.tscn` and `*.tres` files for Godot Engine.
I am not sure about the filetype... I took the name given by the author of the parser, but `godotResource` as a filetype does not feel very conventional with vim. (I'd expect `gdresource`, similarly to `gdscript`)
Here's a preview:

feature: add godotResource queries

---

.github/workflows/check-query-files-and-compilation.yml

Try to install a recent npm version on Ubuntu. This will enable CI testing for Elixir and other `requires_generate_from_grammar` languages on Linux.

CI: install node on all OSes

---

queries/c/indents.scm
tests/indent/c/compound_lit.c
tests/indent/c_spec.lua

Before:
```c
return (struct foo) {
.x = x,
.y = y
};
```
After:
```c
return (struct foo) {
.x = x,
.y = y
};
```

Indent c compound literal expression

---

scripts/check-queries.lua

A faster fix for https://github.com/nvim-treesitter/nvim-treesitter/pull/1651

CI: don't require to have parsers installed to check for injections

---

ftdetect/elixir.vim
ftdetect/surface.vim
lua/nvim-treesitter/parsers.lua
queries/elixir/highlights.scm
queries/elixir/injections.scm
queries/surface/folds.scm
queries/surface/highlights.scm
queries/surface/indents.scm
queries/surface/injections.scm

[Surface](https://surface-ui.org/) is a template language and component library for Elixir and Phoenix LiveView. The syntax is like JSX, but for Elixir!
I created a new Surface [grammar](https://github.com/connorlay/tree-sitter-surface) and and I am happy with the results so far. This PR adds the necessary integration and queries to support using the grammar with NeoVim.
The grammar does not call any external scanners and it should be fairly stable at this point, save for any upstream changes to the language itself. I based the highlights and other queries on the existing work for Elixir, HTML, and JSX.
Additionally, I added ftdetect files for Elixir and Surface, and fixed a small bug with how Elixir highlights function call identifiers when the remote is a variable.
This is my first time …

Feature: Add Surface language and integrate with Elixir

---

queries/lua/highlights.scm

The usual `function_call` query would highlight the objects at the
beginning of a method call. The `method` query has to account for this,
and highlight the identifier as a variable again.

highlights(lua): Fix method calls

---

README.md
lua/nvim-treesitter/query_predicates.lua

`pred[3]` is string. So, `node:parent():named_child_count() > n` throws error.

fix: query_predicate - nth

---

queries/c_sharp/folds.scm
queries/c_sharp/highlights.scm
queries/c_sharp/locals.scm

3 main improvements in this one to further improve C# highlighting (as discussed in #1349):
1. Improved highlights:
Most notable improvements include missing keywords, support for [LINQ query syntax](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/query-syntax-and-method-syntax-in-linq), better local function support and better generics support.
2. Improved folds:
This was actually simplified. Instead of folding entire methods _including_ their attributes, this new way of folding will only fold their _blocks_. This makes it easier to look through code when you have methods with a lot of Attributes or a lot of arguments split into multiple lines.
3. Added locals:
This is a very simple implementation and is most likely not very good. It works, but not …

C#: Improve highlights + Improve folds + Add locals

---

README.md
lua/nvim-treesitter/install.lua

I want to write a plugin that provides tree-sitter queries for a custom `lua` parser.
And I want to leverages `nvim-treesitter`'s installation and update system for installing that custom parser.
Here's how the setup for that plugin would be:
```lua
local M = {
_initialized = false,
}
function M.setup()
if M._initialized then
return
end
local parser_config = require("nvim-treesitter.parsers").get_parser_configs()
parser_config.lua = {
install_info = {
url = "https://github.com/MunifTanjim/tree-sitter-lua",
files = { "src/parser.c", "src/scanner.cc" },
revision = "c910b4e77e9f4ff2408cec28f50eeeb572add33c",
}
}
end
return M
```
And after calling this function, user can simply do `:TSInstall lua` for installing the parser.
Without being able to set the `revision` key, that plugin won't be …

feat: allow 'revision' override in parser config

---

queries/rst/injections.scm

This isn't part of the rst spec,
but it's common enough on third party libs (sphinx specially).

RST: add code-block to injections

---

queries/ruby/locals.scm

Ruby singleton methods (`def x.y ... end`) weren't covered in the list
of locals. In addition, instance methods didn't support names that are
capitalised (`def Integer ... end`).
This commit ensures that both instance and singleton methods are
supported, and that both support identifiers and constants as their
names. This ensures that all following examples are covered:
def foo; end
def FOO; end
def self.bar; end
def self.BAR; end

Fix instance and singleton method locals for Ruby

---

queries/haskell/injections.scm

Keywords like "TODO" or "FIXME" that are in single line or multi-line comments are not currently highlighted like they are in other languages. 
Before:
After:

Add comment highlighting for keywords in Haskell

---

queries/vim/highlights.scm

fix(vim): highlight more punctuation

---

after/ftplugin/elixir.vim
after/ftplugin/heex.vim
after/ftplugin/surface.vim
ftdetect/elixir.vim
ftdetect/heex.vim
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/elixir/injections.scm
queries/heex/folds.scm
queries/heex/highlights.scm
queries/heex/indents.scm
queries/heex/injections.scm
queries/surface/folds.scm
queries/surface/highlights.scm
queries/surface/indents.scm

[HEEx](https://github.com/phoenixframework/phoenix_live_view/blob/master/CHANGELOG.md#new-html-engine) is a new template language for Elixir and Phoenix LiveView that extends EEx with HTML-aware validations.
I created a new HEEx [grammar](https://github.com/connorlay/tree-sitter-heex), based on my existing grammar for Surface. Similar to the Surface grammar, the new HEEx grammar does not use any external scanners. See my previous PR for more information on the Surface grammar: https://github.com/nvim-treesitter/nvim-treesitter/pull/1645
In addition to adding HEEx, this PR updates the version of the Surface grammar to support the addition of a new node type, bringing the HEEx and Surface grammars closer together.
Finally, this PR adds the missing `commentstring` definitions for Elixir, …

Feature: Add HEEx language and integrate with Elixir

---

queries/c_sharp/highlights.scm

Syntax highlighting update for C# language.
Changelist:
1. Added C#9 keywords:
- `record`
- `init`
- `and`, `or`, `not` used in a pattern matching.
2. Added missing keywords from previous language versions:
- `implicit`, `explicit`;
- `internal`;
- `event`, `add`, `remove`;
- `checked`, `unchecked`, `fixed`.
3. Updated inline LINQ expressions with `let` and `equal`.
4. Highlighted `global` as a keyword when access to the global namespace.
5. Highlighted `value` as a keyword in filed accessors (`get`, `set`).
Used reference https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/

Update CSharp highlights.

---

lua/nvim-treesitter/parsers.lua

This is mainly so the playground doesn't error when opening the jsx
query files.

Add jsx to javascript

---

README.md
ftdetect/tlaplus.vim
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/tlaplus/folds.scm
queries/tlaplus/highlights.scm
queries/tlaplus/injections.scm

Using [this](https://github.com/tlaplus-community/tree-sitter-tlaplus/) TLA+ tree-sitter grammar, locked to tagged commit v0.1.2.
Adds filetype detection, highlighting, folds, and injections for comments.

Add TLA+ to supported languages

---

lockfile.json
queries/zig/folds.scm
queries/zig/highlights.scm
queries/zig/indents.scm

In this release:
- All parsing error were fixed https://github.com/maxxnino/tree-sitter-zig/commit/4f4f96b9dc53fee7cc6287712714a2a5c6f93c2a. 
- Performance improve from 120ms -> 6ms
> ![performance](https://user-images.githubusercontent.com/34153891/130397661-784249b5-86cd-4889-b5c6-1ba7701e1ee7.png)
- Add fold for InitList, ErrorSetDecl and multiline string
- More highlight for function, type
- Add highlight for escape and format sequence in string and character
> Check my [Gallery](https://github.com/maxxnino/tree-sitter-zig/wiki/Gallery) for more images

Update new parse and query for zig

---

queries/zig/highlights.scm

In some context, like translate c macro, which is use all CAPS for #define constant

highlight(zig) highlight all caps is a constant

---

lua/nvim-treesitter/shell_command_selectors.lua

Fix #1748 — as described there `--no-progress-meter` is quite recent and `--silent` might be a better choice.

Replaces curl argument: no-progress-meter -> silent

---

ftdetect/json5.vim
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/json5/highlights.scm
queries/json5/injections.scm

This PR adds support for json5 files. It's basically the same as normal JSON, but it adds some constructions from ECMAscript.
More info [here](https://json5.org/)
```json5
{
/* I can do comments as well */
"hello": "world",
look_ma: "no quotes!",
lead_dot: .01,
trail_dot: 1., // With trailing commas, too!
}
```

Add json5 parser

---

README.md
lua/nvim-treesitter/parsers.lua
queries/pioasm/highlights.scm
queries/pioasm/injections.scm

This adds syntax highlighting for the RP2040 PIO assembler, [pioasm](https://github.com/raspberrypi/pico-sdk/tree/master/tools/pioasm) (documented in section 3.3 of the [RP2040 datasheet](https://datasheets.raspberrypi.org/rp2040/rp2040-datasheet.pdf)). Some sample files are available in [pico-examples](https://github.com/raspberrypi/pico-examples/tree/master/pio).

Add tree-sitter-pioasm with highlights and injections

---

queries/json5/highlights.scm

I realized that the old order for the queries makes key strings be highlighted as `@string` instead of `@keyword`. This should fix that 😄

Reorder json5 queries

---

.editorconfig

This adds python to editorconfig, becouse current config incorrectly uses indent 2 and tab_size 8 for python files.

Add python to .editorconfig

---

queries/php/highlights.scm

With this change, methods that are accessed using `nullsafe` operator will be highlighted correctly.
before:
after:

highlights(php): fix method access using nullsafe operator

---

queries/c/highlights.scm
queries/lua/highlights.scm

- Add Lua 5.1 built-in functions
- Make `sizeof` a `keyword.operator`

Update highlights (C, Lua)

---

README.md
ftdetect/dot.vim
lua/nvim-treesitter/parsers.lua
queries/dot/highlights.scm
queries/dot/injections.scm

DOT is a graph description language used in software Graphviz. I have written [tree-sitter-dot](https://github.com/rydesun/tree-sitter-dot), and this PR adds support for DOT.

Add tree-sitter-dot

---

queries/ecma/highlights.scm

* before
- <img width="321" alt="スクリーンショット 0003-08-31 10 42 39" src="https://user-images.githubusercontent.com/1239245/131427997-f3460ffe-0e6f-4564-a471-fad7a3f13e16.png">
* after
- <img width="318" alt="スクリーンショット 0003-08-31 10 42 57" src="https://user-images.githubusercontent.com/1239245/131428009-cf9a91a6-7ea9-48f7-88a7-b7817c2be2ce.png">

Set variable color for destructuring assignment

---

doc/nvim-treesitter.txt

The highlight groups documentation had some typos and missing periods… and I ended up updating most of it. Most comments are still "the floor is made of floor" though.
~~I also added some highlight queries since they served as good examples for a couple of highlight groups.~~
~~The list of Lua built-in functions is [here](https://www.lua.org/manual/5.1/).~~

docs: Update highlight groups descriptions

---

queries/hcl/highlights.scm

I noticed the queries could be improved for better terraform highlighting.
Maybe this should be an inherited query for terraform instead?

Better differentiate 'keywords' for HCL

---

queries/hcl/indents.scm

I ran a few comparisons to `terraform fmt` on some random local files and did not see any differences.  This should be an improvement over the previous indents definition.

indents(hcl): add more indentation rules for HCL

---

lua/nvim-treesitter/parsers.lua
queries/glsl/folds.scm
queries/glsl/highlights.scm
queries/glsl/indents.scm
queries/glsl/injections.scm
queries/glsl/locals.scm

In my config, I have 
```
au! BufRead,BufNewFile *.glsl,*.vert,*.frag set filetype=glsl
```
I'm not sure if *.vert alone is sufficient to classify it as GL/Vulkan shader. Not sure if I should add ftdetect.

parsers: add glsl parser

---

queries/c/highlights.scm

Highlight GCC's/Clang's __attribute__ specifier.

highlights(c): add __attribute__

---

lua/nvim-treesitter/ts_utils.lua

From `:h setpos()`
> If "col" is smaller than 1 then 1 is used.
This can be tested with incremental selection on a vim file.
```vim
set title
```
Probably the vim parser shouldn't include `\n` in the nodes, but that's an improvement for the parser.

Fix incremental selection for nodes that include EOL

---

lockfile.json
queries/hcl/highlights.scm

This PR updates the tree-sitter-hcl parser to v0.6.0, supporting template-if and template-for directives.
Before: 
After:

update hcl parser, update queries

---

queries/rust/highlights.scm

- Highlight angle brackets in type parameters and bars in closures as `@punctuation.bracket` not as `@operator`.
The queries have to be added after the `@operator` queries because the are more specific.
- Don't highlight bang `!` in macro invocations as an operator.
- Highlight colon `:` as a punctuation delimiter.

highlights(rust): Fix punctuation.

---

queries/graphql/highlights.scm

graphql: highlight `description` as a comment

---

queries/beancount/folds.scm

treesitter-beancount added grammar rules around orgmode and markdown
headers so that they are recognized in beancount documents. This change
makes it so that they will be taken into consideration when folding
text.
Commit: https://github.com/polarmutex/tree-sitter-beancount/commit/79ae7c1f2654a2a6936b0f37bf754e5ff59c9186

Add headers as an option to fold on

---

queries/ecma/highlights.scm

This PR removes the `@none` override for the interpolation because it overrides every ecma based template literal, setting none with a higher priority than ecma groups which made every template string look `un`highlighted.
should fix https://github.com/nvim-treesitter/nvim-treesitter/issues/1848

fix(ecma): remove `@none` from interpolation

---

after/ftplugin/graphql.vim

By default, `graphql` filetype have `/* %s */` as the commentstring instead of `# %s`. This PR attempts to fix that. As the filetype detection is already in the treesitter, I thought adding `commenstring` here would be appropriate.
Please feel free to close it, if this doesn't belong here :)

graphql: add `commentstring`

---

lua/nvim-treesitter/health.lua

This should help us to debug compiler errors.

chore: print compiler version in healthcheck

---

queries/rust/highlights.scm

Closes https://github.com/nvim-treesitter/nvim-treesitter/issues/1928

Rust: highlight uppercase identifiers in match arms as constant

---

queries/d/highlights.scm

The previous query was highlighting everything inside that node,
but we only want to highlight the identifiers.
Ref https://github.com/nvim-treesitter/nvim-treesitter/pull/1930/files#r735105675

D: fix duplicate `@namespace` capture

---

queries/python/highlights.scm

This PR adds the python keyword `del` for syntax highlighting.

Add `del` keyword to python highlights

---

lua/nvim-treesitter/tsrange.lua

- TSRange:new() was missing to extract the line from nvim_buf_get_lines
- TSRange:parent() was only working when current buf == self.buf

Fix bugs in TSRange

---

ftdetect/glimmer.vim

Without this, `*.hbs` files are not highlighted (unless you have some other plugin that adds it for you).
Fixes https://github.com/alexlafroscia/tree-sitter-glimmer/issues/44

Add `ftdetect` setup for `glimmer` parser.

---

doc/nvim-treesitter.txt

This will make the description of nvim-treesitter show up in the LOCAL
ADDITIONS section of the help text. So this
|nvim-treesitter|
instead becomes
|nvim-treesitter|  Treesitter configurations and abstraction layer for Neovim.

docs: move description to the first line

---

queries/html/indents.scm
queries/html_tags/indents.scm
queries/vue/indents.scm

There's no indentation file for Vue. This implementation is based on the HTML indentation file with a minor support for the `template_element` tag. As JS is bind with the JS Tree-sitter, the indentation is already fine.

feat(vue): add indents.scm file

---

queries/ruby/highlights.scm

Many operators were missing from Ruby, so, I added them. There's a list on the ruby-docs site: https://ruby-doc.org/core-2.6.2/doc/syntax/precedence_rdoc.html
Additionally, with string interpolation (`"#{xxx}"`), the closing `}` was being matched to `punctuation.bracket` instead of `punctuation.special`, so I fixed that too.
I didn't see any further details about how to contribute, so if I've overlooked anything, I'll be happy to add it.

Add Operators for Ruby

---

lua/nvim-treesitter/parsers.lua

This PR does two things:
* Add support for a parser to have multipart filetype support (e.g. `glimmer` parser actually does support `html.handlebars` just fine) by changing the implementation from #1771 slightly, to allow an exact match to exist before falling back to the first segment of the multipart filetype.
* Add `html.handlebars` as `used_by` for the `glimmer` parser. This filetype is in common use due to https://github.com/mustache/vim-mustache-handlebars/blob/master/ftdetect/handlebars.vim#L2.

Add support for parsers to support multipart filetypes, and add `html.handlebars` as a valid type for the glimmer parser

---

queries/elixir/highlights.scm
queries/elixir/injections.scm

It also adds support for colouring documentation metadata attributes (ex. `@doc foo: :bar`).

Fix Elixir non-doc sigils

---

lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/info.lua

The function is called with the language and bufnr, if it returns false,
the module is disabled for that buffer.
This gives the user more fine-grained control over whether a module is
started.
This is an initial implementation to gather feedback. I chose to add an additional `cond` setting, but I could just as well change it to support function values for the `disabled` config. Let me know what you prefer or if you'd rather have a completely different approach.
My problem was that some modules (mainly `highlight` and [`rainbow`](https://github.com/p00f/nvim-ts-rainbow)) massively slowed down opening of large files and I wanted a way to disable some or all modules for large files. I first tried using autocmds to just disable them with `TSBufDisable` but the autocmd events fired either …

Add condition function to module config

---

lua/nvim-treesitter/ts_utils.lua

Currently, `ts_utils.get_node_at_cursor` does actually not work for any `winnr` other than `0`, even though the function signature suggests you can pass any valid `winnr`. This PR is a naive and minimum implementation to achieve that in a way that it should not interfere with any current other uses of `get_node_at_cursor` or `get_root_for_position`.
cc @danymat

feat: get node at cursor of other win

---

queries/r/highlights.scm

Hightlight library namespace with `@namespace`
`lockfile.json` is up to date

r add new highlights

---

README.md
queries/c/highlights.scm

We are matching too much, we only want to match the identifier
Fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/1999

C: fix macro param hl

---

README.md

`queries/` and `after/queries/` are the same now.
I kind of prefer the old method, but just updating our docs to reflect
the reality for now.
Closes https://github.com/nvim-treesitter/nvim-treesitter/issues/1710
Closes https://github.com/nvim-treesitter/nvim-treesitter/issues/1441

Docs: update docs on how to override a query

---

lockfile.json
queries/lua/injections.scm

Hi!
This PR implements injection in `vim.cmd` codeblocks to improve the readability of Neovim+Lua codebases.
Currently it works for the following scenarios:
```lua
vim.cmd [[echo "Hello World!"]]
```
And:
```lua
vim.cmd "echo 'Hello World!'"
```
Obviously you can substitute `vim.cmd` for any of the other 3 functions that we have. There is one issue that I simply cannot resolve however, and that is this:
```lua
vim.cmd [[
echo "Hello World!"
]]
```
Your `cdef` injection is plagued by the same problem, and that is that multiline strings that are `#match?`ed don't seem to have their respective parser injected. Any idea why this may even be? When I remove the `#match?` it works however then the `#offset!` of `2` messes with single-line strings that only use one char (`"`/`'`) instead of two …

Add basic vimscript injection in `vim.cmd`/`nvim_command`/`nvim_exec`

---

queries/bash/highlights.scm
queries/c/highlights.scm
queries/clojure/highlights.scm
queries/comment/highlights.scm
queries/cpp/highlights.scm
queries/dockerfile/highlights.scm
queries/ecma/highlights.scm
queries/gdscript/highlights.scm
queries/glimmer/highlights.scm
queries/java/highlights.scm
queries/jsx/highlights.scm
queries/lua/highlights.scm
queries/lua/injections.scm
queries/php/highlights.scm
queries/python/highlights.scm
queries/python/injections.scm
queries/rust/highlights.scm
queries/scala/highlights.scm
queries/teal/injections.scm
queries/vim/highlights.scm

as string.find is much quicker than vim.regex:match*
Benchmarks from @muniter on [matrix](https://app.element.io/#/room/#nvim-dev:matrix.org) :
> So I was curious about Lua vs Vim regex/patterns and did some benchmark, non scientific but seems like Lua patterns are well as expected super fast.
>
> 123456NVIM v0.6.0-dev+631-ga6788a979
Build type: Debug
LuaJIT 2.1.0-beta3
>
> Ryzen 7 2700X
> Linux Kernel 5.14.16
>
> Benchmark Simple substring `iz` in `this is amazing` n: 10000000
>
> ```
> Vim regex      : 1.217601
> Lua string.find: 0.002445
> ```
>
> Benchmark Simple pattern l:`%d%d%d%l` v:`\d\d\d\l` `this is ama(231c)zing` n: 1000000
>
> ```
> Vim regex      : 1.275099
> Lua string.find: 0.158496
> ```
>
> Benchmark Greedy star `2.*` `this is ama(231c)zing` n: 1000000
>
> ```
> Vim regex …
```

Prefer lua-match over match

---

ftdetect/glsl.vim

Without this all GLSL filetypes do not have syntax highlighting

Add glsl ftdetect

---

lua/nvim-treesitter/parsers.lua

Zsh and Bash are not interchangeable, so using the Bash parser for Zsh causes a lot of issues. See <https://github.com/nvim-treesitter/nvim-treesitter/issues/655#issuecomment-978036615>.

Don't use the Bash grammar for Zsh files

---

queries/rust/highlights.scm

A bunch of small changes:
- Sort operators
- Remove duplicated `*`
- Add missing `<<=`
- Highlight `as` correctly (depending on whether it's for casting or path aliasing)
- Highlight leading quotes `'` as part of a label (not an operator)
- Highlight never type (`!`) as a type
- Sort keywords
- Highlight `super` as a namespace
- Highlight `break` and `continue` as `repeat` keywords
- Don't highlight `macro_rules!` as a keyword
- Place all queries for literals together
- Place function definition queries alongside function call queries

highlights(rust): update operators, keywords and literals

---

queries/zig/highlights.scm

Because two query below cause hanging neovim. I don't know what's cause the problem yet. It had been worked really well until now.
```
(PtrTypeStart "c" @variable.builtin)
(
(ContainerDeclType
[
(ErrorUnionExpr)
"enum"
]
)
(ContainerField (IDENTIFIER) @constant)
)
```

zig: work around for hang neovim

---

lua/nvim-treesitter/indent.lua
tests/indent/python_spec.lua

Fix #1987
Python tests have covered this, especially https://github.com/nvim-treesitter/nvim-treesitter/blob/63a88c873f3643aad9208488765dc53618edd40e/tests/indent/python/strings.py#L13-L17

fix: off-by-one errors in indent calculation

---

queries/yaml/injections.scm

Yaml is often used for CI. This applies an heuristic that strings after a "run" key are bash scripts. Note that `((` from bash were missing (separate PR).
before:

injections(yaml): inject bash on key "run"

---

.github/workflows/check-query-files-and-compilation.yml

Was removed because not always available. Add one nightly config to not have surprises.

ci: add nightly again to CI

---

README.md
ftdetect/pug.vim
lua/nvim-treesitter/parsers.lua
queries/pug/highlights.scm
queries/pug/injections.scm
queries/vue/injections.scm

I discussed my progress in #1520 
This is a WIP with the Pug tree-parser. If worked OK for my type of files. I am sure it does not support all of the syntax, yet, but it would be much better than a white screen.
As you can see, the highlighting is quite ok for raw "example.pug" files.
Unfortunately, if does not work with Vue template files, yet. I've added the ``ftdetect`` rule, but it is unable to map the ``@pug`` with the pug file
```
<template lang="pug">
body: div 
| this is unhighlighted
</template>
```
Is unhighlighted.... For test, I've changed the ``vue/injections.scm`` template rule from ``@pug`` to @typescript or @scss, and the highlighting works.... What am I missing? Where can I tell nvim how to handle the ``@pug`` marked parts as a pug file.
I've also tried using the @content …

Feat: Added Pug parser with inital queries

---

queries/ocaml/highlights.scm

That's what most other languages do.

OCaml use @constant.builtin for built in constants

---

queries/ocaml/highlights.scm

For string format specifiers use @string.special instead of @punctuation.special.

OCaml string format specifiers

---

README.md

0.5-compat branch was not actively maintained and nvim-treesitter
also runs with stable versions. We should be able to maintain
compatibility with latest stable by fall-back implementations in case
there should be a breaking change.
A lot of people were confused about what branch to use and that there
were only in frequent updates to the 0.5-branch. We can do a 0.6.0 tag
now for everyone not wanting this plugin move too fast.

docs: remove advice to use 0.5-compat

---

queries/rust/highlights.scm

Was `@string` instead of `@character`

rust(highlights): fix highlighting of char_literal

---

lockfile.json
queries/fusion/highlights.scm
tests/query/highlights/fusion/basic.fusion

Hey,
sorry for the inconvenience. I did not expect you update the lockfile regularly. Hope this will not happen often.
I updated some parts of the grammar and this broke compatibility to nvim-treesitter queries.
Is there a way we can link the queries in the grammar repo as default?
relates to #2088

feat(fusion): update highlight queries and some tests

---

queries/lua/highlights.scm
tests/query/highlights/lua/test.lua

This PR fixes the `next` built-in highlight. The current `function_call > identifier` query doesn't work as the `next` has its own node, I guess.

highlights(lua): `next` as builtin function

---

lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/parsers.lua
queries/markdown/highlights.scm
queries/markdown/injections.scm

parsers: Add MDeiml/tree-sitter-markdown as markdown parser

---

lua/nvim-treesitter/install.lua

Addresses #2108 
This creates a nice welcome experience and can be a first step to https://github.com/nvim-treesitter/nvim-treesitter/issues/2108#issuecomment-993642212. You will get nice highlighting in the second when it says "parser for XXX installed"
@wimstefan @HaleTom This will enable the parsers as soon as they are installed without reloading the buffer. So you can use the async installation. We can add an option for auto-install in a  separate PR

feat: enable parsers after installation immediately without reload

---

queries/markdown/highlights.scm

Allow targeting the text part of a link:
```markdown
[this part](https://a.a)
```
Ref: https://github.com/mcchrish/zenbones.nvim/pull/64#issuecomment-996518952

highlights(markdown): highlight link_text as @text.reference

---

README.md
doc/nvim-treesitter.txt

Put the comment above the line instead of at the side, that gives more space.
Ref https://github.com/nvim-treesitter/nvim-treesitter/issues/2095#issuecomment-992759818
also took this as an opportunity to update the example from the vim-doc file :D

Make example config more easy to read

---

README.md
ftdetect/gowork.vim
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/gomod/injections.scm
queries/gowork/highlights.scm
queries/gowork/injections.scm

The new golang 1.18 version (currently in beta) [introduced](https://github.com/golang/go/issues/45713) a new file type
called `go.work`.
This commit adds support for the syntax of that file using the https://github.com/omertuc/tree-sitter-go-work repository
That repository is heavily based on previous work in the https://github.com/camdencheek/tree-sitter-go-mod repository, with a few
minor changes to make it work on the very similar `go.work` files.

Add support for new golang `go.work` files

---

queries/python/highlights.scm

1. This function simplifies an unnecessary lua-match usage.
2. Fixes an accidental change, where "cls" was changed to "class" (fe4f320b66)
3. ~~Match functions, which have have a decorator.~~
4. ~~But exclude @staticmethod~~
5. Only highlight "cls" as @variable.builtin when the decorator is @classmethod
This might be a bit to complicated and some of this not to useful,
as this existing rule:
```scm
((identifier) @variable.builtin
(#eq? @variable.builtin "self"))
```
overwrites the queries anyway.
**EDIT**: Remove queries, which duplicate highlights of the above query.

highlights(python): Improve self and cls highlight

---

lua/nvim-treesitter/parsers.lua
queries/pascal/folds.scm
queries/pascal/highlights.scm
queries/pascal/indents.scm
queries/pascal/injections.scm
queries/pascal/locals.scm

What it says in the title. This grammar works for Delphi and Freepascal. Since I wrote it from scratch, it's probably not 100% complete, but 99%. At least it's a lot better than the default regex highlighter. You can find some screenshots [here](https://github.com/Isopod/tree-sitter-pascal#screenshots).
Supported queries:
- highlights
- scope
- injections
- indents
- folds

Add support for Pascal

---

queries/pascal/highlights.scm

Assume that any identifiers that aren't function calls, types, fields or constants are variables. This is consistent with the highlighting definitions for other languages (tested with C and Python). Some themes (e.g. zenbones) make use of this information and they don't look quite right unless we set those groups.
Before:
After:

highlights(pascal): Highlight variables

---

lua/nvim-treesitter/ts_utils.lua

This PR fixes `get_node_at_cursor` to consistently default `winnr` to 0 if it is `nil` (previously, this was only handled in one location).

Fix: Account for winnr being nil in calls to get_node_at_cursor

---

queries/python/injections.scm

These injections lead to inconsistent highlighting since some edge cases aren't handled (as mentioned in the [PR description that introduced the injections][0]). Besides, not all Python projects use reStructuredText syntax in docstrings.
If someone still wants to use them, they can extend the base injection queries through [`after/queries/`][1] or enable them with `vim.treesitter.set_query`.
See also: https://github.com/nvim-treesitter/nvim-treesitter/pull/1204
[0]: https://github.com/nvim-treesitter/nvim-treesitter/pull/917
[1]: https://github.com/nvim-treesitter/nvim-treesitter/tree/ad69e2528ac382b7cbf28f1ac7ee450981734ab0#adding-queries

Remove Python docstring injections

---

queries/supercollider/highlights.scm

This removes the pi_statement from the highlights query to reflect the same change upstream in the grammar. And some whitespace was removed.

fix: SuperCollider. Remove pi_statement from highlight to sync up with upstream change

---

queries/pascal/highlights.scm
tests/query/highlights/pascal/test.pas

#2176 inadvertently broke highlighting of types consisting of more than one identifier (such as `Foo.Bar` or `TFoo<T>`). I fixed it in this PR. I also added a test so it doesn't happen again.

highlights(Pascal): Fix highlighting of types

---

queries/markdown/injections.scm

Related to https://github.com/MDeiml/tree-sitter-markdown/issues/14. I introduced a new node in my grammar which is only the language part of the info string. We need to change the injection query to use this new node.
I'm not familiar with how nvim-treesitter chooses the commit from which to install a language. I think the node is not part of the commit that is currently used. Is it safe to reference it in the query files like this? Or do I need to trigger some other process first, so the newest commit of the parser gets used?

Fix language injection for markdown code blocks

---

queries/markdown/highlights.scm
queries/markdown/injections.scm

This PR improves the markdown highlighting by assigning TSPunctDelimiter group to the brackets used in links and fenced blocks. It also add support for yaml frontmatter

improve markdown highlighting

---

queries/haskell/highlights.scm

Improve highlighting for function declarations, function applications, type signatures, modules, and fixity keywords.
| Before                                                                                                         | After                                                                                                          |
| -------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------- |
| ![image](https://user-images.githubusercontent.com/4299733/148631093-766d3e62-2910-49a5-af49-a9876348d794.png) | ![image](https://user-images.githubusercontent.com/4299733/148631077-4eb259a2-2e24-4984-aad5-0f2b037565e9.png) …

Improve Haskell highlighting

---

README.md
after/ftdetect/foam.vim
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/foam/folds.scm
queries/foam/highlights.scm
queries/foam/indents.scm
queries/foam/injections.scm
queries/foam/locals.scm
queries/foam/textobjects.scm

Adding support for the [OpenFOAM](https://openfoam.org/) file format using [this grammar](https://github.com/FoamScience/tree-sitter-foam) which supports:
- highlights
- indents (* basic)
- locals, injections
- folds
- text-objects

Add OpenFOAM parser

---

lua/nvim-treesitter/ts_utils.lua

I noticed a small error with `get_ndoe_text` in `ts_utils.lua`. Whenever the range of the node is until the end of the file, the last line will be completely truncated.
This is because the last line returned by `nvim_buf_get_lines` is not actually the line with index `end_row` since the biggest line index is `end_row - 1`.

Fix get_node_text

---

lockfile.json
queries/markdown/highlights.scm

Implement highlight for block quote markers as discussed in https://github.com/MDeiml/tree-sitter-markdown/issues/20.

Add highlight for quote marker

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/kotlin/folds.scm
queries/kotlin/highlights.scm
queries/kotlin/injections.scm
queries/kotlin/locals.scm

Change the Kotlin parser used by nvim-treesitter from [Joakker/tree-sitter-kotlin](https://github.com/Joakker/tree-sitter-kotlin) to [fwcd/tree-sitter-kotlin](https://github.com/fwcd/tree-sitter-kotlin), since the latter parser appears to be more comprehensive and still in-development. Furthermore,  the parser lacked a locals and folds query so these have been added.
Comparison between the two parsers:

Change Kotlin parser

---

queries/markdown/highlights.scm

As discussed in #2206 this is only a temporary fix. The problem seems to resolve itself with newer versions of treesitter.

Fix slow startup times for markdown grammar

---

lockfile.json
queries/markdown/highlights.scm

Add highlight to markdown for delimiters for
* fenced code blocks
* code spans
* emphasis
as discussed in https://github.com/MDeiml/tree-sitter-markdown/issues/20

Add highlight for markdown delimiters

---

lockfile.json
queries/latex/highlights.scm

Add highlight for the LaTeX sectioning commands `\addpart`, `\addchap`, `\addsec` and their starred variants. Fixes #2236.
This requires the revision of `latex` in `lockfile.json` to be updated to https://github.com/latex-lsp/tree-sitter-latex/commit/6f796b700c69a8af28132e84ed6d0c8f0c17a5e2. But I wasn’t sure if this update should be part of this pull request, and therefore left it out for now.

Add LaTeX highlights: addpart, addchap, addsec.

---

queries/html_tags/highlights.scm
queries/vue/highlights.scm

Closes #1646 
For colorschemes that heavily makes use of bold and italics, the inheriting factor makes the highlights unpleasant. Solution is to make the targets more specific rather than the whole `template_element` or `element`.

Improve vue

---

queries/latex/highlights.scm

Add `\eqref` to the list of referencing commands. Fixes #2242.

Add a missing LaTeX hightlight.

---

queries/julia/highlights.scm
queries/julia/injections.scm

Currently, block comments are not highlighted in julia. 
This pull requests aims at adding highlight for block comments.

Add highlight for block comments

---

queries/haskell/highlights.scm

These are the queries for bindings that have no parameters but have type signatures of a function.
| Before                                                                                                         | After                                                                                                          |
| -------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------- |
| ![image](https://user-images.githubusercontent.com/4299733/149404206-ead4c59e-eaaa-4d06-a79a-ea4bf683a246.png) | ![image](https://user-images.githubusercontent.com/4299733/149404307-db8338c4-437d-44d4-ab54-e2a35ccf1d23.png) |

highlights(haskell): function with type signature

---

queries/php/highlights.scm

@theHamsta As mentioned in #2207 here are a couple of additions for PHP
* **@type**: added class and interface names in declarations, `use` statements and static method calls
* **@parameter** parameters in method and function declarations
* **@const** constant declarations and accesses
* **@namespace** namespace names
* **@conditional** added ternary operator `? :`
* **@string** added backtick expressions
* **@string.escape** escape expressions like `\n` in strings
* **@label** goto labels
Also added some keywords and operators and moved some things e.g. the `.` operator to **@operators**

highlights(php): fix and add missing highlights

---

lua/nvim-treesitter/ts_utils.lua

Offset encoding is a mandatory argument to `vim.lsp.util.apply_text_edits` since https://github.com/neovim/neovim/commit/bc722c8a74766e14aff3a8e2fc46db72ed864053; this function is used for `swap_nodes`. Since we are always within a Neovim context, we can just pass `"utf-8"`.
Fixes #2248

fix(util): pass offset_encoding to apply_text_edits

---

queries/php/highlights.scm

If I understand correctly, the @constructor group should match definition of constructor method.
That way it will highlight name of the method.

fix(php): change query for @constructor group

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/swift/highlights.scm
queries/swift/locals.scm

The upstream parser https://github.com/tree-sitter/tree-sitter-swift is marked as abandoned in favor of https://github.com/alex-pinkus/tree-sitter-swift/, so use this.
Caution: This parser requires generating the grammar via `npm install`, which takes quite a while, pulls in ~100 Mb of dependencies, and results in a 3.1 Mb parser. 
I also mostly copied the queries from that repo verbatim; they likely need adapting, and I'd appreciate help on this from someone who is familiar with Swift (and Scheme). Changes I've made:
* `@function.method` -> `@method`
@theHamsta 
closes #271

Fix: use maintained parser for Swift

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/highlighting_issue.yml

It would be a lot easier when highlighting issue wouldn't be reported as bugs but people would actually provide a triple of example file, parsing result and screenshot of how it currently looks like.
Also instruct reporters that examples with `ERROR`s should be reported to upstream parsers.
Open an issue at my fork to see the rendered result: https://github.com/theHamsta/nvim-treesitter/issues/new/choose

docs: add issue template for highlighting issues

---

queries/rust/highlights.scm

~~Port the lastest update parser PR (without llvm).~~
An interesting feature in this change-set is that Rust adds the keyword `yield` (https://github.com/tree-sitter/tree-sitter-rust/pull/110)

Add support for Rust's `"yield"`

---

tests/query/highlights/markdown/test.md
tests/query/highlights_spec.lua

Make tests with markdown (no actual comment nodes) working after merging #2209. Not a nice solution, though.

fix(ci): make highlight test working with markdown

---

queries/php/highlights.scm

Required to add a highlighting for
```php
<?php
$x = new MyClass();  // (name)
$x = new app\MyClass();  // (qualified_name)
```
Also moved `@constructor` quries into the Functions section to keep things well organized.

highlights(php): detect constructor calls on instantiation

---

queries/java/highlights.scm

Fix:  https://github.com/tree-sitter/tree-sitter-java/issues/94
PR: https://github.com/tree-sitter/tree-sitter-java/pull/95

feat(java)(highlights): add missing highlights for `@type`

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/lua/folds.scm
queries/lua/highlights.scm
queries/lua/indents.scm
queries/lua/injections.scm
queries/lua/locals.scm
tests/indent/lua_spec.lua

also take queries from https://github.com/MunifTanjim/nvim-treesitter-lua/tree/main/queries/lua
@MunifTanjim (it would help if you could summarize the advantages of your parser over the old one in a comment).
BREAKING CHANGE: queries are not compatible; modules will have to update

feat(lua)!: switch from our fork to MunifTanjim's

---

queries/php/highlights.scm

Matches [magic constants](https://www.php.net/manual/en/language.constants.magic.php) like `__LINE__`, `__METHOD__` and constants with only a single letter.

fix(php) match magic and single letter constants

---

queries/c/highlights.scm

@theHamsta This just takes out highlighting of `type_qualifier` as a `@type` as part of a declaration. Qualifiers themselves aren't really types. The one for the cast expression was unnecessary since all `type_descriptors` are already highlighted as types.

highlights(c): don't highlight type qualifiers in declarations as types

---

.github/workflows/check-query-files-and-compilation.yml
.github/workflows/tests.yml
.github/workflows/update-readme.yml

possibly want to wait to update to tree-sitter 0.21.0 (or whatever the upcoming version is)
also simplify tests:
* only run on push to master _or_ PR opened/synchronized
* cancel in-progress workflows for updated PRs
* only run ubuntu-latest+gcc+nightly on draft PRs
* only run ubuntu+gcc and macos+clang (plus windows x 3)

ci: bump neovim and tree-sitter cli to latest version

---

.github/workflows/check-query-files-and-compilation.yml
.github/workflows/tests.yml
.github/workflows/update-parsers-pr.yml
.github/workflows/update-readme.yml

so we only need to rebase all old PRs once
@theHamsta

ci: use stable tag for latest nvim release

---

doc/nvim-treesitter.txt

Improves clarity for a user that is not familiar with lua api.

docs: add missing vim table in the example

---

lua/nvim-treesitter/parsers.lua

The upstream repo has pre-generated bindings at:
https://github.com/PrestonKnopp/tree-sitter-gdscript/tree/master/src

fix: Don't require node for gdscript.

---

.github/workflows/check-query-files-and-compilation.yml

takes significantly longer than other combinations
probably easier now to just list the allowed combinations?

ci: drop windows+clang

---

.github/workflows/tests.yml

Decreases the time for Test Dependencies to half. 
**Before**:
**After**:

ci: fix cache path for rust cargo

---

lua/nvim-treesitter/health.lua
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/utils.lua

Check tree-sitter CLI version and if > 0.20.3 and generating a parser from grammar, use `--abi=vim.treesitter.language_version`.
Besides being able to opt-in to newer ABI benefits, this is a necessary workaround for an upstream bug with 0.20.3, where `parser.h` is not generated if the (optional) `--abi` flag is omitted.

feat: specify ABI version for generate on newer tree-sitter CLI

---

lockfile.json

closes #2323 
(lockfile PR is still stalled by viml parser...)

fix: bump phpdoc parser to 0.0.6

---

README.md
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/parsers.lua
lua/nvim-treesitter/shell_command_selectors.lua
scripts/compile_parsers.makefile

I don't know yet whether this is a good idea or whether the parser themselves should just have their own `Makefile` or `npm` task but we could at least increase the required C++ standard by having there compile commands.
A better solution would of course be to have a unified compilation, release and installation mechanism in upstream tree-sitter
https://github.com/nvim-treesitter/nvim-treesitter/pull/1766 @JoeyGrajciar

Haskell/norg c++14 compilation

---

.github/workflows/check-query-files-and-compilation.yml
.github/workflows/tests.yml

fixes issues with `parser.h` not being generated

ci: bump tree-sitter to 0.20.4

---

queries/elixir/highlights.scm
queries/elixir/injections.scm

Hello! This PR makes the following adjustments to the highlighting and language injection queries for Elixir:
* Injects markdown into [Elixir documentation](https://hexdocs.pm/elixir/writing-documentation.html#markdown)
* Injects JSON into [Jason sigils](https://hexdocs.pm/jason/1.3.0/Jason.Sigil.html)
* Adds the missing lower-case `z` sigil for Zigler injections
* Fixes a bug where module attributes are not highlighted properly outside of their initial definition (see images below)
* Fixes a bug where the string sigil is not highlighted as documentation
Module attribute highlights on master
Module attribute highlights on this branch

Elixir highlights and injection updates

---

queries/heex/highlights.scm
queries/heex/indents.scm
queries/heex/injections.scm
queries/heex/locals.scm

This PR makes the following changes to support version [0.3.x](https://github.com/connorlay/tree-sitter-heex/blob/main/CHANGELOG.md#030) of tree-sitter-heex:
* Improved support for Elixir injections that span multiple lines of HEEx
* Adds a `locals.scm` query file for HEEx
* Adds more accurate highlighting of HEEx function components
* Adds support for multi-line HEEx comments `<%!-- --%>`
* Adds support for HTML comments ``

Add support for HEEx 0.3.x

---

queries/phpdoc/highlights.scm

* Only capture `$` as keyword if it's a variable name, not anywhere else in comment
* `|` only as separator in a type list
* `<` and `>` only for the email in `@author` tags

fix(phpdoc) Improve keyword query

---

queries/gdscript/indents.scm
tests/indent/gdscript/basic_blocks.gd
tests/indent/gdscript_spec.lua

Indent is not handled correctly when adding new lines.
It seems that functions/loops/etc. are not recognized until they have at
least one indented block.
For example, if you enter a newline after `func foo():`, the cursor will
not be indented. If you manually indent and add a line like `pass`,
e.g.:
```
func foo():
pass
```
now any insertions above or below `pass` will be indented correctly.
This might be an issue with the grammar, as it seems to apply to highlights
as well.
The following will not be highligted
```
func foo():
```
However, the following will be:
```
func foo():
pass
```

feat(indent): Implement basic indent for gdscript.

---

queries/c/folds.scm

Enables folding local blocks like so:
```c
void f() {
// this can now be folded
{
// ...
// ...
}
// this can now be folded too
{
// ...
// ...
}
}
```

folds(c): fold at compound_statement

---

scripts/compile_parsers.makefile

- support both scanner.cc and scanner.c
- allow complete override for (`$CFLAGS`,`$CXXFLAGS`,`$LDFLAGS`)
- add `clean` target
- add `install` target
- add windows support
Tested on:
- Arch Linux
```console
$ make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
- MSYS2/Windows11
```console
$ make --version
GNU Make 4.3
Built for x86_64-pc-msys
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and …
```

refactor(installer): more modular makefile

---

scripts/compile_parsers.makefile

- add missing $(MKDIR) variable
- create a simple function to allow running `make clean` without an error if a file doesn't exist

refactor(makefile): better powershell handling

---

ftdetect/eex.vim
lua/nvim-treesitter/parsers.lua
queries/eex/highlights.scm
queries/eex/injections.scm
queries/elixir/injections.scm

Related to https://github.com/nvim-treesitter/nvim-treesitter/issues/1352
This PR adds support for EEx and LEEx files with [tree-sitter-eex](https://github.com/connorlay/tree-sitter-eex). Unlike HEEx, EEx does not make any assumptions about what language it is injecting Elixir into. The addition of this parser to nvim-treesitter should improve the experience of using Neovim and Tree Sitter on older Phoenix applications that have not migrated to HEEx yet, as well as other usages of EEx that do not target HTML.

Add tree-sitter-eex parser for (L)EEx files

---

scripts/update-lockfile.sh

`jq` has the ability to generate arrays output that is script friendly, so there's no need for any additional handling regarding that.

refactor(lockfile): use better jq parsing

---

CONTRIBUTING.md
queries/tlaplus/highlights.scm
queries/tlaplus/injections.scm
queries/tlaplus/locals.scm

[PlusCal](https://learntla.com/pluscal/) is a language, written in block comments and translated into TLA+.
Recently, PlusCal support [landed](https://github.com/tlaplus-community/tree-sitter-tlaplus/releases/tag/v0.4.0) into the `tlaplus` grammar
This PR updates the `tlaplus` grammar revision and adds queries to `locals.scm` and `highlights.scm`
@ahelwer FYI

update TLA+ revision, add queries for PlusCal

---

.github/workflows/update-parsers-pr.yml

This runs the update-parsers workflow every day (at 6:30 UTC, for no particular reason except before local morning) in addition to after each push to master. This ensures that we'll see parser updates even when nothing gets merged for a while.

chore: run parser update at least daily

---

queries/go/highlights.scm

I guess `@namespace` didn't exist the last time I touched the go highlights.
@primalmotion I'm not a go user. Do you think this is appropriate?

highlights(go): highlight `package_identifier` as `@namespace`

---

queries/c/folds.scm

This will fold in particular around raw braces
as reported in #2359 while avoiding to have double folds
at functions+braces. E.g.
```cpp
void foo()
{
foo();
}
```
would only have one fold for the whole function. While we would still have folding at naked braces.
```cpp
void foo()
{
// Section 1: we need to keep foo section for bar section separated
{
foo();
}
// Section 2:  bar does the actual work
{
bar();
}
}
```
This is probably just a personal preference as some people might want to have double folds in such situation.

folds(c): fold raw `compound_statement`s

---

queries/supercollider/highlights.scm
queries/supercollider/indents.scm

replaces https://github.com/nvim-treesitter/nvim-treesitter/pull/2392 and https://github.com/nvim-treesitter/nvim-treesitter/pull/2393

Supercollider update: add support for const and fix indent bugs

---

queries/cpp/highlights.scm
tests/query/highlights/cpp/static-namespace-functions.cpp

Fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/2396
An instance of the classical nesting problem. It could be solved by `#has-ancestor?` but we're currently trying to remove it.

highlights(cpp): fix function highlighting of Foo::bar::baz()

---

queries/lua/highlights.scm

This is not done in any other language. Before it would highlight the first `a` in `foo(a, a + b)` as parameter while the second `a` has the normal `variable` highlight.

highlights(lua): don't highlight arguments as parameters

---

lockfile.json
queries/heex/folds.scm
queries/heex/highlights.scm
queries/heex/indents.scm
queries/heex/injections.scm
queries/heex/locals.scm

See https://github.com/connorlay/tree-sitter-heex/pull/10 for associated changes to tree-sitter-heex
This PR upgrades the lockfile to target tree-sitter-heex v0.4.0 and adds support for HEEx [Slots](https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#module-slots).

Upgrade to tree-sitter-heex v0.4.0 and support slots

---

.stylua.toml
tests/indent/javascript_spec.lua

also made some changes to the the config:
* change deprecated option `no_call_parentheses = true` -> `call_parentheses = "None"`
* fixed some (default) settings for reproducibility and clarity.

chore: format with stylua 0.12.0

---

scripts/check-queries.lua

This should prevent different output formats on windows and unix.

ci: prefer io.write instead of print to have full control of output

---

.github/workflows/check-query-files-and-compilation.yml
scripts/check-queries.lua

This is meant as a temporary workaround until neovim 0.7 is released.
More context: https://github.com/nvim-treesitter/nvim-treesitter/issues/2313#issuecomment-1025258357

ci: skip swift check on neovim stable

---

.github/workflows/lint.yml
.github/workflows/update-parsers-pr.yml
.github/workflows/update-readme.yml

The required checks can be initiated by marking the PR is ready for
review.

ci: mark automated PRs as draft

---

queries/verilog/highlights.scm

* Add a bunch of the OO keywords and some of the more unusual block
delimiter types
* Highlight macromodule like module is.
* Highlight new as seen in constructor declarations like
`class blah; function new(...); ... endfunction endclass`
* Make endfunction a @keyword.function. This matches how lua does it.
* Make tasks @keyword.function: tasks in SystemVerilog are more or less just
impure functions
* Highlight casex/casez like case is currently highlighted (previously
these were not highlighted at all)
* Highlight unique, unique0, priority for constructs like
`unique case (...) ... endcase` and `priority if (...) ...`

verilog highlight: add some keywords, tidy keywords

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/latex/folds.scm
queries/latex/highlights.scm
queries/latex/injections.scm

This is a significant refactor, but with the patient help of @pfoerster, I got the queries back in pretty much the same shape they were in before. Some now possible improvements are left on the table:
* the `\section` etc. commands are now part of the grammar and can (and should) be captured as such
* same for new commands, references, glossary entries etc.
* injections for `pycode`, `minted`, etc. environments (as a future PR).
(Although there might be difficulties with those since they are defined via anonymous nodes.)

chore(latex): update parser

---

scripts/check-queries.lua

Convert nil to an empty string, which mimicks the behavior of standard
print

ci: make io_print accept nil as input argument

---

scripts/compile_parsers.makefile

certain parsers like `tree-sitter-go` only contain parser.{c|cc}

fix(makefile): scanner.c isn't always available

---

queries/latex/highlights.scm
queries/latex/injections.scm

Followup to #2436: replace literal nodes in queries with parser nodes where possible. (Note that you want the `TSMath` highlight group defined, otherwise you'll be missing out.)
Timings increased from 100ms to 150ms, though -- not sure that's acceptable?
Also added C injection for `asy` environments, for good measure.

refactor(latex): improve queries

---

.github/workflows/update-parsers-pr.yml
.github/workflows/update-readme.yml

Shaves off 10 seconds per workflow.

ci: remove apt update if on workflows where it's not used

---

README.md
lua/nvim-treesitter/parsers.lua
lua/nvim-treesitter/utils.lua

TODO: should i create a public function to modify this list instead of providing the user with the table ?
- remove print_warning function from utils.lua (unused)
- cleanup some functions in parsers.lua (shadowing parameters and wrong
bufnr used).
- log a deprecation notice when using used_by in a parser definition
- default the filetype_to_parsername table to the list of filetypes
previously in the used_by keys
- update the README to indicate that change
fixes #2373

refacto: deprecate used_by in parsers.lua

---

lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/highlight.lua

Decompose highlighter module in small functions to allow exporting a
start and stop functions without the syntax change.
Also fix linter issues in configs.lua
Should fix #1944

chore: expose start and stop highlighter

---

queries/vim/highlights.scm

Support to tree-sitter-viml was added with https://github.com/vigoux/tree-sitter-viml/pull/57

feat(vim): highlight default parameters

---

queries/julia/highlights.scm

- Add highlights for:
+ command strings
+ abstract type definitions
+ module `end` delimiters
- Distinguish `:` in quotes and ranges (it's already highlighted
differently in ternary expressions).

feat(highlights/julia): Add missing highlights

---

lua/nvim-treesitter/shell_command_selectors.lua
scripts/compile_parsers.makefile

- also add `CXX_STANDARD` again as it's the only variable used from the Lua side
There might be more errors in the Makefile https://github.com/nvim-treesitter/nvim-treesitter/issues/2463#issue-1125016147 let's see what the problem was there. I would prefer to return back to the basic Makefile we had in the beginning (which already had mentioned error of using the optimization flag during linkage phase)
https://github.com/nvim-treesitter/nvim-treesitter/issues/2463#issue-1125016147  was related to a `LDFLAGS` which was set in the user's environment and not by our Lua code.

fix: -Os should be used during compilation phase in makefile

---

queries/markdown/injections.scm

Two consecutive thematic breaks can cause content to be interpreted as yaml at the moment. This change fixes this by only allowing yaml blocks at the start of markdown files, which is the most common use case anyways.

Only allow yaml block at start of markdown file

---

scripts/compile_parsers.makefile

Apparently, I forgot the `CXX_STANDARD` again after editing the makefile

fix(makefile): add forgotten CXX_STANDARD again

---

queries/cpp/highlights.scm

so that methods like these are correctly highlighted
```cpp
class A {
class B {
void foo();
};
};
void A::B::foo() {
//         ^^^
}
```
This only increases the nesting level by one.
AFAIK, arbitrary nesting is difficult to do with current queries.
But this nesting is a pretty common case

highlights(cpp): Highlight method with nested qualified_identifier

---

queries/elixir/indents.scm

This PR updates the `indents.scm` queries for Elixir to better match what is produced by `mix format`, the official Elixir code formatter. For example, the first argument to a pipeline now matches the indentation level of each pipeline step:
On `master` this is how pipelines are indented:
```elixir
a
|> b()
|> c()
```
In this PR they are now indented like this:
```elixir
a
|> b()
|> c()
```

Update Elixir indents to take advantage of new features

---

lua/nvim-treesitter/utils.lua

As a user of the nvim-treesitter I wanted to add a command through `nvim-treesitter.utils.setup_commands` that receives the ranges like below
```
command! -range MyFun :lua require'..'.myFun(<line1>, <line2>)
```
Current implementation limits the `myFun` arguments to be only `<f-args>`.
This PR adds an extra argument to `nvim-treesitter.utils.setup_commands` - `f_args`, so that the user can add their own required argument types to their functions

Adds extra args to utils.setup_commands to add custom func args

---

README.md
lua/nvim-treesitter/parsers.lua
queries/lalrpop/highlights.scm
queries/lalrpop/locals.scm

LALRPOP is a parser generator for Rust. This only parses the LALRPOP
side of the generator, not the nearly-rust code of the actions.
I made the grammar, it's my first grammar so if you see any glaring issues, feel free to comment.

Add an lalrpop parser

---

.github/workflows/test-queries.yml
.github/workflows/tests.yml
.github/workflows/update-lockfile.yml
.github/workflows/update-readme.yml

Feel free to give other suggestions. This isn't a clear improvement but after the fifth time of mixing together the different workflows I thought it might still be worth a shot.

ci: rename workflows and jobs to be more consistent

---

queries/latex/highlights.scm

* add \caption to @function
* only highlight contents of curly text groups in references

fix(latex): some highlight query fixes

---

.github/workflows/tests.yml

This avoids any Rust build dependencies.

ci(tests): download highlight-assertions for faster CI

---

queries/vim/highlights.scm

Allow pattern to not contain pattern_multi node to be highlighted

fix(vim): fix highlight for pattern

---

README.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/highlight.lua

BREAKING: remove custom_captures from highlight config.
This allows plugin authors to extend the map. It also avoids settings user configuration specific values during the highlighter initialization (SOC).
Not sure how much value this brings, and might potentially break a lot of people configurations. This is questionable.

refacto: expose a function to set custom capture for the higlighter

---

queries/perl/folds.scm
queries/perl/highlights.scm

* Recognise many more keywords
* Assign highlight groups to control keywords, not entire structures
* Add some folding rules
Verymuch a work-in-progress as many bigger fixes will require improvements in `tree-sitter-perl`, but this is a good start.

Various fixes to queries/perl/*

---

queries/java/indents.scm
tests/indent/java/issue_2571.java
tests/indent/java/method.java
tests/indent/java_spec.lua

Similar to #2555, I noticed that the `queries/java/indets.scm` file was missing an `@indent_end` definition. This PR adds one in.
Fixes #2571

Added fix for incorrect Java indentation after a closing "}" in a method declaration

---

lua/nvim-treesitter/parsers.lua
queries/todotxt/highlights.scm

Adds a parser for the todo.txt syntax along with highlighting. Syntax can be found here: https://github.com/todotxt/todo.txt#todotxt-format-rules
As this syntax doesn't necessary map well to highlight names that exist in colorschemes available I mapped them to highlight names that look good (e.g. makes sense that a done task is greyed out so `@comment` made sense to me).
With my coloscheme ([gruvbox.nvim](https://github.com/ellisonleao/gruvbox.nvim/)) it looks like this:

parsers: Add todotxt parser

---

queries/cpp/highlights.scm

See https://en.cppreference.com/w/cpp/language/cast_operator for reference.
Before 
After

highlights(cpp): Add operator cast highlight

---

lockfile.json
queries/vala/highlights.scm

Note: Some items are commented in `(namespaced_identifier)` due to issue described in #2600.

highlights(vala): Reflect upstream refactor

---

lua/nvim-treesitter/shell_command_selectors.lua

The problem with #2613 was that `if vim.fn.executable "gmake" then` should be `if vim.fn.executable "gmake" == 1 then` and probably `gmake` was missing on that CI environment.

fix: prefer gmake over make

---

lua/nvim-treesitter/parsers.lua
queries/solidity/highlights.scm
tests/query/highlights/solidity/test.sol

I noticed the [original issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/1168) has been inactive for quite some time, and thought I might take a stab at adding basic highlighting support for Solidity.
Here's a preview of the highlighting:
Also managed to add the test and got the `./scripts/run_tests.sh query` passing for Solidity:
Do let me know if this is alright :bowing_man:

Add highlights.scm query for Solidity

---

queries/lua/highlights.scm

closes #2606
do the same for `@constant.builtin` while I'm at it.

fix(lua): restore precedence for @variable.builtin

---

queries/fennel/locals.scm

The current `locals.scm` for fennel binds a function's name only inside of the function itself. Setting the scope to "parent" is consistent with fennel's scoping.

Fix fennel function scope

---

queries/markdown/highlights.scm

Auto links (e.g. `<https://github.com>`) should be highlighted as URIs

Highlight markdown `uri_autolink` as `@text.uri`

---

queries/prisma/highlights.scm

Highlight the `type` keyword used in the new [composite types](https://www.prisma.io/docs/concepts/components/prisma-client/composite-types) syntax and in the deprecated type aliases.

fix(prisma): highlight "type" keyword

---

.github/workflows/update-lockfile.yml

The current revision of https://github.com/cstrahan/tree-sitter-nix fails our CI Windows test, even after updating all the queries.
Lock it for now until somebody can unblock https://github.com/nvim-treesitter/nvim-treesitter/pull/2668 so the lockfile update PR can go through without manual intervention every time.
@leo60228

ci: lock nix parser

---

CONTRIBUTING.md
queries/json/highlights.scm

highlights: conceal `"` in JSON

---

queries/r/highlights.scm

Highlight only the `identifier` in the `name` field

r(highlights): fix default_parameter

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/help/highlights.scm

Using @bfredl's shiny new `conceal` support on master. The captures are open for bike shedding.
I've add injection support for Lua in codeblocks, which (of course) tries to highlight all code as Lua, even if it's Vimscript (or just plain text). I don't think it's possible to be any smarter about it; it's up for debate whether this is an improvement over no highlighting at all. (I think... maybe?) 
I'm marking this as experimental since there seem to be some issues with the scanner (things like `"*"` and `:lua` after a backtick). @vigoux

feat: add vimdoc parser and queries

---

CONTRIBUTING.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/highlight.lua
lua/nvim-treesitter/query.lua
plugin/nvim-treesitter.vim

Some builtin highlight groups (see `:h group-name`) do not yet have
associated capture groups, so add them.
Note that there is a related [PR in neovim][1] to add these groups to the
*default* `hl_map`, but this PR does not depend on that one in any way.
[1]: https://github.com/neovim/neovim/pull/17835

Add capture groups for remaining builtin highlight groups

---

.github/ISSUE_TEMPLATE/highlighting_issue.yml

Unless I'm reading that the wrong way, we want to _“inspect which [...] and that legacy syntax highlighting is **not** interfering`_.

github: Fix typo in template

---

queries/scss/highlights.scm

Add highlighting query for Scss `@for` loops
The Scss language only had highlighting queries for `@each` loops, this
commit adds support for `@for` loops as well.
Also moved all loop-related keywords (including newly added ones) to
`@repeat` rather than `@keyword`
Before:
After:

Add highlighting query for Scss `@for` loops

---

queries/java/indents.scm
tests/indent/java/method_chaining.java
tests/indent/java_spec.lua

Solves an issue where Java indent was dedented one too far while method chaining.
```java
public class Testo {
void foo() {
new StringBuilder()
.append("a") // add newline here
|<-- cursor ends up here
}
}
```
```java
public class Testo {
void foo() {
new StringBuilder()
.append("a") // add newline here
|<-- cursor should be here
}
}
```

Fix Java indentation for method chaining

---

queries/ecma/indents.scm
tests/indent/ecma/issue-2515.js
tests/indent/javascript_spec.lua

Fixes #2515
Probably, "auto" is a good strategy when we are within a syntax error.

indents(ecma): use auto indent on (ERROR)

---

queries/lua/injections.scm

Inspired by the existing injections for viml, this PR adds one for the tree-sitter query language when calling `vim.treesitter.query.set_query`. Note this only applies to the third string argument, which is the query string itself.

injections(lua): inject query into vim.treesitter.query.set_query lua calls

---

lua/nvim-treesitter/parsers.lua

There are several markdown filetypes that are common that all support the same syntax. This adds `md`, `rmd`, and `pandoc` to all be matched to the `markdown` treesitter parser.

Add more filetypes for treesitter-markdown

---

queries/astro/highlights.scm
queries/astro/injections.scm

I realised I forgot to add curly brace interpolation support in astro (e.g. `<p> {"Hi"} </p>`, JSX-style), so I added it. Here are the new queries to take advantage of this.

feat: add curly interpolation support for astro

---

README.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/configs.lua

When a module is disabled by default in the config, running TSBufEnable will not enable the module because the `is_enabled` function will always return false, thus the module not being enabled.
Also, disabling/enabling the buffers is flaky.
This commit adds per buffer check when the module is not disabled. It also makes the enable and disable more indempotent.
I've also renamed TS*All to TS*.
Fixes #2754

fix(modules): enabling disabling per buffer and globally

---

README.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/parsers.lua

With the increasing number of parsers added to `nvim-treesitter`, the label "maintained" has stopped being a useful distinction, as just having a maintainer listed at time of inclusion does not entail any stability guarantee implied by this label. Users should explicitly specify the list of parsers that they want to use according to their risk tolerance, or use `ensure_installed = 'all'` if they insist on drinking from the firehose (not recommended!)
Deprecation period is until April 30; hopefully that will leave enough time for the ecosystem to adapt.
The warning is emitted from `parsers.maintained_parsers()` in the hope that this will be most visible (and not break CI).
@theHamsta @vigoux @kyazdani42

chore!: deprecate ensure_installed=maintained

---

queries/go/injections.scm

Adds C highlighting for [cgo](https://pkg.go.dev/cmd/cgo) ([example of code](https://github.com/kraftwerk28/gost/blob/master/blocks/rxkbcommon/rxkbcommon.go#L3-L34)). Though it only works for multiline comment `/* */`, because single line comment doesn't "merge" into a single TS node.

Add c injection for cgo comments

---

queries/latex/highlights.scm

Capture `text` nodes in `math_environment` as `@text.math` as well.
closes #2786

latex: capture math env contents

---

.github/workflows/test-queries.yml

Unarchive directory was renamed to `nvim-win64`

ci: update windows workflow to 0.7

---

queries/markdown/highlights.scm

It's interesting that the following would only conceal `_conceal1`
```
(fenced_code_block
(fenced_code_block_delimiter) @_conceal1
(info_string) @_conceal2
(#set! conceal ""))
```

highlights(markdown): add conceal to fenced code blocks

---

lua/nvim-treesitter/shell_command_selectors.lua

In #2466 we found that if a revision/tag name is something like 'v0.3.0', the `select_download_commands` creates a `mv` command that doesn't work properly for github. The bug results from github using the suffix `-0.3.0` instead of `-v0.3.0` in the tag archive. I tested:
- v1
- ~~v.a~~
- ~~va~~
- ~~v.1~~
- v1.1
- v1.a
The crossed out names did not exhibit this behavior, so it looks like if there's anything matching `^v\d`, then the `v` is removed.
This patch applies that behavior to github only.

fix: properly select name in revision archive (#2466)

---

lua/nvim-treesitter/ts_utils.lua

I wasn't sure whether to open this up on Zulip or here, but decided here since the code change is so small. Let me know if you want me to take it over there instead 🙏 
**Context**
I was digging into romgrk/nvim-treesitter-context#62 and tracked down the bug to this function: 
```lua
function M.get_parent_matches()
if not parsers.has_parser() then return nil end
-- FIXME: use TS queries when possible
-- local matches = ts_query.get_capture_matches(0, '@scope.node', 'locals')
local current = ts_utils.get_node_at_cursor()
if not current then return end
local parent_matches = {}
local filetype = api.nvim_buf_get_option(0, 'filetype')
local lines = 0
local last_row = -1
local first_visible_line = api.nvim_call_function('line', { 'w0' })
while current ~= nil do
local position = …
```

feat(utils): add ignore_injected_langs parameter to get_node_at_cursor

---

README.md
lua/nvim-treesitter/health.lua

Checks minimal version in `:checkhealth nvim-treesitter`
Also recommend nightlies
First in a series of PRs to upgrade to Nvim 0.7.

chore: bump minimal Nvim version to 0.7 and check

---

queries/java/highlights.scm

Introduced by https://github.com/tree-sitter/tree-sitter-java/pull/109 via https://github.com/nvim-treesitter/nvim-treesitter/pull/2814

highlights(java): add support for `text_block`s

---

queries/go/indents.scm
tests/indent/go/issue-2369-newline.go
tests/indent/go_spec.lua

This PR relates to #2369 and hopefully fixes it.
This fix is basically a direct implementation of the comment that @theHamsta made in https://github.com/nvim-treesitter/nvim-treesitter/issues/2369#issuecomment-1034229102.
Locally this seems to mean that when indent after a `}` the indent is reset, so for example
```go
func example() {
} <CURSOR>
-><CURSOR>
```
becomes
```go
func example() {
}<CURSOR>
<CURSOR>
```
I added in the `}` as I was seeing this behaviour there as well as in the example above.

fix(go): reduce indent after },)

---

doc/nvim-treesitter.txt
lua/nvim-treesitter.lua
lua/nvim-treesitter/locals.lua
lua/nvim-treesitter/ts_utils.lua

Could also just silently do `M.get_node_text = vim.treesitter.query.get_node_text`. Then, downstream users don't have to switch for each function that gets moved from ts_utils to core

chore: deprecate ts_utils.get_node_text

---

lua/nvim-treesitter/ts_utils.lua

This reverts commit c3848e713a8272e524a7eabe9eb0897cf2d6932e.
The wrapper needs extra work, so revert to unbreak all the things.

Revert "chore: deprecate ts_utils.get_node_text"

---

lua/nvim-treesitter/locals.lua

vim.treesitter.query.get_node_text returns a string, not a table as the deprecated function.
without this, nvim-treesitter-refactor does not work

adapt to vim.treesitter.query.get_node_text

---

lua/nvim-treesitter.lua
lua/nvim-treesitter/ts_utils.lua

After some discussion, it looks like the easiest thing to do for now is
to keep a private copy of get_node_text (just to skip the deprecation
message) and invoke that, until core provides an equivalent function
that can return the node content in a table representing the node
"lines".
Also fixes the statusline.
Fix #2849.

fix(ts_utils): fix swap_nodes after get_node_text change

---

README.md
lua/nvim-treesitter/parsers.lua

This simply adds the [tree-sitter-org](https://github.com/milisims/tree-sitter-org) parser to the list of parsers. Highlights, folds, etc. are handled by the separate [orgmode](https://github.com/nvim-orgmode/orgmode) plugin for now it seems. Regardless, this fixes the issue of having to separately add the parser to `nvim-treesitter` for the purposes of simply accessing treesitter information.

Add org parser

---

queries/yang/indents.scm

Adds indent queries for YANG.
I tested this locally by running:
```lua
vim.treesitter.set_query("yang", "indents", [[
(block) @indent
(block "}" @branch)
(statement) @indent
(statement ";" @indent_end)
]])
```
And manually setting `indentexpr=nvim_treesitter#indent()`, and it works great.
---
Is there anything more I need to do to enable indent support for the language in nvim-treesitter, other than provide an indents.scm file?

Add indent queries for YANG

---

queries/ocaml/highlights.scm

Units were shadowed by the punctuation highlights in all situations.
Restrict the context where parentheses are highlighted as punctuation so
() can be highlighted as constants.
Before:
After
:

highlights(ocaml): highlight units as such

---

queries/cpp/highlights.scm
tests/query/highlights/cpp/test.cpp

Fixes #2902
There was someone who suggested that `@operator` would make more sense when this was originally submitted. But I think since this is not an actual C++ operator it makes sense to align with Rust.

highlights(cpp): make "::" `@punctuation.delimiter`

---

queries/php/highlights.scm

Improve PHP highlight for attributes.
Before:
After:
Colorscheme: [gruvbox](https://github.com/morhetz/gruvbox)
Sample code: [treesitter-php](https://github.com/tree-sitter/tree-sitter-php/blob/6be89d517d550a47b067b23d0f89a364091b41ca/test/corpus/declarations.txt#L321-L358)

highlights(php): improve highlight for attributes

---

queries/scheme/highlights.scm

This PR fix block comments in Scheme and highlights `λ` correctly.

highlights(scheme): some fix

---

queries/ecma/locals.scm

In Telescope, function declarations were being exposed in the selector,
but not method definitions which are also a form of function
declaration.

Add method to definitions in ECMA locals

---

queries/php/highlights.scm
queries/php/indents.scm
tests/indent/php_spec.lua

Currently with
```vim
setlocal autoindent
setlocal smartindent
```
in `after/indent/php.vim` it allows correct indentation
inside PHP docblocks.
Closes #2873

indents(php): @auto on comment and ERROR

---

queries/python/folds.scm

Fold queries of Python were an issue in this query https://github.com/nvim-treesitter/nvim-treesitter/issues/1441
I think we should streamline the Python fold queries with the other languages. I think this will be also beneficial for everyone liking the current behavior as then all languages could be folded with first-line visible. Right, know "omitting the first line from folding" would require a different logic for Python and for C++.

python(folds): fold whole functions not only body

---

queries/latex/highlights.scm

Previously, it would highlight the whole command including arguments which can be annoying since some commands include whole paragraphs.

highlights(latex): only highlight command name, not whole command

---

README.md

This modifies the automatically generated "parserinfo" section of the README to display the supported languages as a table with an additional "related plugins" column.
The result can be seen on the branch, where I've also added related plugins for "org".
https://github.com/TerseTears/nvim-treesitter/tree/readme#supported-languages
Let me know what you think and if any fixes are required or if I should add other related plugins.

Reformat "parserinfo" as table with related plugins column

---

README.md
lua/nvim-treesitter/parsers.lua
queries/v/folds.scm
queries/v/highlights.scm
queries/v/indents.scm
queries/v/injections.scm
queries/v/locals.scm

Add support for vlang filetypes.
where C act like extern and access c functions. The vlang parser differentiate between C function calls and normal function callas as well as c and vlang arguments but I believe  highlighting C as builtin variable is sufficient indicator for now. I  tried to use `offset!` but failed. Any suggestions?
[vls]: https://github.com/vlang/vls/tree/master/tree_sitter_v
cc @elianiva @theHamsta

feat(vlang): initial support

---

lockfile.json
queries/nix/folds.scm
queries/nix/highlights.scm
queries/nix/locals.scm

Updates the nix queries to the latest changes upstream.
Upstream added a `variable_expression` which allows us to to specify the references/variables more (changed in `highlights.scm` and `locals.scm`). I also changed the binary and unary operators to be less specific in `highlights.scm`, as is done upstream's queries (which removes some code).
Pinging @leo60228 as maintainer

fix(nix): update parser and queries

---

queries/c/highlights.scm

Highlight C (or C++20) style designated initializers as `@property`
In theory we have `@field` but this is not used in C yet (neither for all the other `field_...` nodes). Probably, we should just throw together `field/property` into one category. The default highlight for both is the same `@TSProperty` says same as `TSField`

highlights(c): highlight field_designator as `@property`

---

lua/nvim-treesitter/health.lua

The `health` module was moved to `vim.health` in https://github.com/neovim/neovim/pull/18720

fix(health): update to upstream changes

---

queries/ecma/injections.scm

Sometimes we want to highlight graphql strings without using a template literal like `gql`. In vscode, you can tell the editor to highlight the string as graphql by adding a comment like this:
```typescript
const query = /* GraphQL */ 
`
type Thing {
name: String!
}
`;
```
This injection adds that capability.
Credit goes to @lukas-reineke. He gave me this injection snippet on reddit, but I thought it may as well be added to the repo.

injections(ecma): add injection for commented graphql template strings

---

lockfile.json
queries/swift/highlights.scm

I see that our queries are almost-but-not-completely the same as the upstream ones. Is the divergence intentional, or should/can I just pull in the latest upstream version?
@alex-pinkus @theHamsta

feat(swift): update parser and queries to 0.3.0

---

queries/help/highlights.scm

- A hotlink on vimdoc is `|foo|`.
Which is a reference to part of a document,
not a URI.
- (argument) wasn't being highlighted,
wasn't sure about the best hl group for this,
but `@parameter` seems like the obvious one?

Help: update highlights

---

README.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/shell_command_selectors.lua
lua/nvim-treesitter/utils.lua
tests/query/injection_spec.lua

Moves get_parser_install_dir into configs out of utils and adds a config option to satisfy  [#2959 ](https://github.com/nvim-treesitter/nvim-treesitter/issues/2959)
Previously `get_parser_install_dir` and `get_parser_info_dir` were both in
utils. This is because they only took into the package dir and the site
dir.
Now there is a configuration option, `parser_install_dir` that takes
precedence over the package and site directories. This is parsed in with
``` lua
configs.setup(
{
parser_install_dir = "some/path",
})
```
As such the `get_parser_install_dir` needs to take this option in. One
was is to leave it in usils and parse it in:
```lua
utils.get_parser_install_dir("parser", configs.get_parser_install_dir_option())
```
But that will always require access to configs, or will work …

 Add support for custom parser install locations #2959 

---

queries/markdown/highlights.scm

Before:
After:
I'm still getting antiquated with the query/scheme syntax used by tree-sitter so if there is a better way to write these queries please let me know!

highlights(markdown): conceal links

---

README.md

Some parsers are built with ABI 14, which was introduced in tree-sitter 0.20.3.

docs: minimal supported tree-sitter version

---

queries/ruby/highlights.scm

Adds `undef` and `redo` keywords.
https://docs.ruby-lang.org/en/2.4.0/syntax/miscellaneous_rdoc.html#label-undef
https://docs.ruby-lang.org/en/2.4.0/syntax/control_expressions_rdoc.html#label-redo+Statement

Ruby: Add `undef` and `redo` keywords to highlights.scm

---

queries/lua/highlights.scm

Before, all identifiers containing the substring "self" were highlighted as the builtin `self`. Now, only the identifier `self` is highlighted as `self`.

highlights(lua): highlight only `self` as `self`

---

queries/haskell/highlights.scm

fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/3056, although i'm not very confident this is the right change

fix(haskell): highlight exp_name as function in infix operations

---

lua/nvim-treesitter/install.lua
lua/nvim-treesitter/parsers.lua

This was very confusing when using the location property as it
always had to start with "tree-sitter-<lang>" for no real reason (just
because our installer would rename the download to that name).

Chore: remove prefix from parser "location" property

---

lockfile.json
lua/nvim-treesitter/parsers.lua
lua/nvim-treesitter/query_predicates.lua
queries/markdown/highlights.scm
queries/markdown/injections.scm
queries/markdown_inline/highlights.scm
queries/markdown_inline/injections.scm

My new split markdown parser works quite well now (better than the non-split one). This PR changes the config to point at the new branch because I want to keep the old branch for now as other projects are using it.
It also adds some other changes that are needed for the two parsers to work:
1. An `exclude_children!` directive, that might also be very useful for something like #2212 
2. Splitting markdown queries into block and inline ones and add the injection for inline into block grammar
3. Add an `include_dir` option to parser configs (needed, because the two grammars don't live in the repos root directory)

Switch to split markdown parser

---

lockfile.json
lua/nvim-treesitter/parsers.lua

See discussion in #2826 and bug report in https://github.com/alex-pinkus/tree-sitter-swift/issues/197. The `with-generated-files` branch uses ABI 13 and therefore doesn't benefit from the ABI 14 speed improvements.

feat(swift): compile the grammar from the main branch

---

scripts/ci-install-macos-latest.sh

macOS release archive now uses `nvim-macos` as extracted directory.

ci(macos): update to upstream changes in release

---

lua/nvim-treesitter/install.lua

This fixes the following issue I came across when using `auto_install = true`.
To reproduce:
1. `:TSUninstall bash`
2. `:e ~/test.sh` (parser will be installed)
3. `:e ~/test.sh` (user will be prompted whether parser should be installed again which is unexpected)
Also this includes a small refactor, because specifying `ask_reinstall` is not necessary.

fix: avoid installing parsers multiple times when using auto_install

---

queries/go/folds.scm
queries/go/highlights.scm

* `method_spec` highlight should be the same as the `method_declaration`
before:
after: 
* `block` should be foldable because it is handy with long table-driven tests

add method spec highlight and block folds

---

queries/go/highlights.scm

Add `any` type introduced in go1.18.

add go1.18 any type

---

queries/qmljs/folds.scm
queries/qmljs/highlights.scm

fix the hightlight in the function of the object, before it will all be property
add keyword on
change  these following into namespace.

Fix and add some highlight

---

queries/sql/highlights.scm

Highlight sql comments

---

queries/markdown/injections.scm

the Elm parser segfaults when injected in markdown. Disable it for now.
See https://github.com/elm-tooling/tree-sitter-elm/issues/124
@theHamsta @clason i'm not sure how to debug this, i haven't managed to make the elm parser segfault when not injected.

fix: disable elm parser in markdown to avoid segfault

---

lua/nvim-treesitter/indent.lua

Seems like the configs module already setup the filetype autocmd to attach, so this autocmd is not needed at all.
fixes #3172

fix(indent): set only one autocmd for binding indentexpr

---

queries/c/highlights.scm

Lower the priority of @variable to prefer @parameter
highlight when identifier appears in parameter_declaration.
Fixes #3061

highlights(c): Lower the priority of @variable

---

queries/markdown/injections.scm

Hugo, Zola, and likely other static site generators use `+++` for TOML, not YAML.

Support TOML metadata in Markdown injections

---

queries/php/highlights.scm

`encapsed_string`s are double-quoted strings. Highlight their non-escaped portions like normal single-quoted `string`s.
`nowdoc`s are non-parsed `heredoc`s. Highlight them like normal single-quoted `string`s.
`escape_sequence`s can appear in `heredoc`s and `shell_command_expression`s, not just `encapsed_string`s. Highlight these too.
Before:
After:

highlights(php): highlight more string types and escapes

---

queries/c/highlights.scm
queries/cpp/highlights.scm

Let's hope that this time the C tests pass, also for the built-in C
parser.
This will also bring attributes to GLSL.

highlights(c/cpp): move attributes to C (again)

---

lua/nvim-treesitter/ts_utils.lua
tests/unit/ts_utils_spec.lua

Currently the visual selection cannot start after the final character of a line. This is because the start position is set before entering the visual selection in which case the cursor cannot be after the last character. If one instead first starts visual selection this is possible and one just needs to switch side with `o` and go to the last.

feat(ts_utils): allow starting selection after last character

---

lua/nvim-treesitter/highlight.lua
plugin/nvim-treesitter.lua

If the plugin is loaded after a colorscheme is set that defines any of
these highlight groups, the default won't be applied. Subsequent
"highlight clear" commands (common when switching colorschemes) will
then clear any of those highlights, but these defaults never have
another opportunity to be initialized.
Effectively, if you load neovim with a colorscheme that has definitions
for some of these highlight groups, then load treesitter, then switch
colorschemes, many of these default links will be absent resulting in
colors that do not appear the same as if that colorscheme had been
used at startup.
Hooking the ColorScheme event with an autocmd that just reapplies these
defaults gives every colorscheme switch the opportunity to get the
defaults for non-explicitly-defined groups.

feat(highlight): re-apply default highlights on colorscheme changes

---

lua/nvim-treesitter/incremental_selection.lua

Thought that after https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/233 we could annotate more keymappings. This are the only keymappings in nvim-treesitter.
TODO:
- playground
- refactor

docs: add descriptions to incremental_selection keymaps

---

lua/nvim-treesitter/info.lua

should we be more precise in `:TSInstallInfo` when parser is still active after uninstallation?

chore: show in TSInstallInfo when parser is still loaded

---

CONTRIBUTING.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/highlight.lua
queries/bash/highlights.scm
queries/c/highlights.scm
queries/cpp/highlights.scm
queries/elixir/highlights.scm
queries/erlang/highlights.scm
queries/go/highlights.scm
queries/java/highlights.scm
queries/julia/highlights.scm
queries/kotlin/highlights.scm
queries/lua/highlights.scm
queries/perl/highlights.scm
queries/php/highlights.scm
queries/python/highlights.scm
queries/ruby/highlights.scm
queries/rust/highlights.scm
queries/scala/highlights.scm
queries/sql/highlights.scm
queries/swift/highlights.scm
queries/v/highlights.scm
queries/vim/highlights.scm
queries/zig/highlights.scm
tests/query/highlights/cpp/static-namespace-functions.cpp

Following the discussion in #3210, this is a draft reintroducing both method and function calls with the `TSMethodCall` and `TSFunctionCall` groups. Note that they both fallback on their respective `TS<Function/Method>` hl-groups. So far these groups are available for the following languages:
- Python
- Julia
- C
- C++
- Go
- Kotlin
- Bash
- Elixir
- Erlang
- Java
- Lua
- Perl
- Php
- Ruby
- Rust
- Scala
- SQL
- Swift
- V
- Vim (vimscript)
- Zig

Reintroduce Function/Method Call HL Groups

---

queries/sql/highlights.scm

Fix for https://github.com/nvim-treesitter/nvim-treesitter/pull/3270
Fixes for tree-sitter-sql queries for changes due to the latest parser version.

SQL highlight queries rely on latest parser AST

---

queries/go/indents.scm
tests/indent/go/multiple-vars.go
tests/indent/go/switch.go

- Don't branch at `case`
- Let `import_spec_list`/`var_declaration` behave like
`const_declaration`
Fixes #2166
@geefuoco can you test please!

indents(go): improve `@branch` rules

---

queries/go/folds.scm

Fold to: (I used a modified version of fold.lua that keep last `}`

go folds.scm composit_literal

---

lua/nvim-treesitter/ts_utils.lua

This error only happened when the pulgin tried to get_node_text while the current buffer was being edited/changed by other plugins(e.g. Formatter).
I mapped CursorHoleI to Treesitter Status Line and have seen the lines being empty from time to time.

ts_utils nil check for get_node_text

---

queries/zig/indents.scm
tests/indent/zig/pr-3269.zig
tests/indent/zig_spec.lua

An additional indentaion on newline is appended.
This PR fixes a bug that an additional indentaion on newline is appended.
Current Behaviour is 
```
}<cursor>
to
}
<indent><cursor>
```
But expected behaviour should be below
```
}<cursor>
to
}
<cursor>
```

fix(zig): Do not indent on newline after block

---

README.md
lua/nvim-treesitter/parsers.lua

Hey, I've moved `tree-sitter-http` parser repository to an organization very recently.
This PR aims to update said parser url, nothing more.

chore: update `tree-sitter-http` parser URL

---

queries/markdown_inline/highlights.scm

This change conceals `full_reference_link`, `collapsed_reference_link`,
and `shortcut_link` similarly to how the `markdown_inline` query file
already conceals `inline_link` and `image`.
```markdown
Some text before the link [full reference link text][link label] and now some
text after the link onto a new line.
Some text before the link [collapsed reference link text][] and now some text
after the link onto a new line.
Some text before the link [shortcut link text] and now some text after the link
onto a new line.
```
Closes #3267

Conceal reference and shortcut links in markdown

---

queries/go/indents.scm
tests/indent/go/issue-3288.go

I don't feel to confident about this change. I don't use go and our test coverage is not exhaustive.

indents(go): don't indent on all composite_literal

---

lua/nvim-treesitter/parsers.lua
queries/gitignore/highlights.scm

Not feeling too confident about the captures yet. Any feedback welcome!
@andy2mrqz 
Addresses https://github.com/nvim-treesitter/nvim-treesitter/issues/2282#issuecomment-1215780654

parsers: add tree-sitter-gitignore

---

queries/ecma/highlights.scm

- Add queries for value properties:
- undefined
- NaN
- Infinity
- Highlight regex delimiters as brackets instead of punctuation
- Format queries for literals
These changes were suggested by [u/based5 on reddit](https://www.reddit.com/r/neovim/comments/ws23tm/why_no_treesitter_highlight_for_undefined_in/). I don't know their github username, but credit to them.

highlights(ecma): Update queries for literals

---

.github/workflows/update-lockfile.yml
.github/workflows/update-readme.yml

Allows more easily triggering these workflows manually (e.g., in case of an important upstream fix).

ci: add workflow_dispatch to update actions

---

lockfile.json
queries/vim/highlights.scm

Adds support for map_bar.
Correctly highlight unknown builtin commands.

chore(vim): update parser and highlights

---

queries/java/highlights.scm

After #3336, I saw that there is also `"non-sealed"`

highlights(java): add "non-sealed" keyword

---

lua/nvim-treesitter/highlight.lua

https://github.com/neovim/neovim/pull/19931 adds direct support for highlighting capture groups (with fallback), obviating the need for `vim.treesitter.highlighter.hl_map`. Instead of
`hl_map["@keyword"] = "TSKeyword"`
users can simply
`hi link TSKeyword @keyword`
Check for the existence of `hl_map` and either use the former or the latter.
@bfredl

fix(hl_map): adapt to upstream changes on master

---

queries/jsx/injections.scm
queries/tsx/injections.scm

~Although this is only valid for jsx/tsx, I am putting this in `ecma` so both can inherit the injections.~ https://github.com/nvim-treesitter/nvim-treesitter/pull/3358#issuecomment-1225340609
Created `jsx/injections.scm` with the injection query which is (and should be) then inherited by `javascript` and `tsx` injections.
For some reason, `javascript` was already importing the `jsx` injections, thus no changes required.
---
Before and After

injections(jsx): highlight `<style jsx>` as css

---

README.md
lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/install.lua

- don't allow to silently fallback to alternative install location
- remove argument of function that wasn't used anywhere (neither in function nor in call sites)
- display warning when parser is still installed after `:TSUninstall`. nvim-treesitter will only uninstall from configured install dir
- warn when uninstalling a parser in ensure_uninstalled
Fixes #2777
Please test before merging! Will also test a few days. I think this is not urgent but helpful for issues in future.

No fallback install location

---

queries/cmake/highlights.scm

add escape word like "\n", "\;" to highlight
Log: escape sequence highlight for cmake

feat(cmake): add escape to highlight

---

queries/haskell/injections.scm

Support for inline json using the quasiquoter `aesonQQ`: https://github.com/sol/aeson-qq#readme

Haskell injection: support inline json

---

queries/haskell/injections.scm

This PR adds a haskell injection for [postgresql-simple](https://hackage.haskell.org/package/postgresql-simple) quasiquotes.

Add postresql-simple sql to haskell injections

---

lua/nvim-treesitter/highlight.lua

This PR fixes an issue where, for users on nvim nightly, the links for the captures are not reset when a user reloads or changes their colorscheme. This was previously done for the default highlight groups, but this logic did not include creating the links now need on 0.8. Not sure if this code is all destined for a fire at some point, but it's useful for people who are doing this in the short term.

fix(highlight): ensure links are rebuilt on colorscheme change

---

lua/nvim-treesitter/parsers.lua
queries/sxhkdrc/folds.scm
queries/sxhkdrc/highlights.scm
queries/sxhkdrc/injections.scm

This adds my recently created [sxhkdrc grammar](https://github.com/RaafatTurki/tree-sitter-sxhkdrc) which is the configuration format for the [simple x hotkey daemon](https://github.com/baskerville/sxhkd)
I've also added highlighting queries to make it useful from the get go:
At 1st I've had my highlight queries within the grammar repo itself and `tree-sitter highlight` worked using it but nvim wouldn't use it (`checkhealth nvim-treesitter` says my grammar has no highlighting support), Only after moving my queries into this plugin did nvim start highlighting things. I'm relatively new to the nvim-treesitter scene, Is there a way to relocate my queries back into my repo and have nvim-treesitter use them (that way I can update the queries without PRing here) or is that a no no?
*before* …

feat: add tree-sitter-sxhkdrc

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/menhir/highlights.scm
queries/menhir/injections.scm

Hi!
This patch adds support for [menhir](http://gallium.inria.fr/~fpottier/menhir/) files (menhir is a parser generator for [OCaml](https://ocaml.org/)). The parser has been used a little outside of nvim already, and is reasonably tested. I hope it can be a nice addition to nvim-treesitter :slightly_smiling_face: 
Let me know if I did something wrong in the PR, I'll be happy to fix it
cheers!

Add support for menhir (OCaml parser generator)

---

lockfile.json
queries/sql/highlights.scm

The node name `table_expression` has been refactored and renamed into `table_reference` in [here](https://github.com/DerekStride/tree-sitter-sql/commit/b032eaa5122e70cd4b012e2272eb357e1971ddc7).
Therefore, the queries for highlighting do not work anymore. They break with the following message:
```
ERROR 2022-09-07T07:56:07.092 2000835 decor_provider_invoke:37: error in provider treesitter/highlighter:line: Error executing lua: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: error at position 257
stack traceback:
[C]: in function '_ts_parse_query'
/usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: in function 'get_query'
...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:122: in function 'new' …
```

highlights(sql): change table_expression to table_reference

---

queries/sql/highlights.scm

This PR builds on https://github.com/nvim-treesitter/nvim-treesitter/pull/3445 and adds the rest of the changes that were present in https://github.com/nvim-treesitter/nvim-treesitter/pull/3458.
* I've added a new highlights for the `marginalia` & `keyword_only` nodes.
* I've cleaned up the query for matching `table_alias`.
* The previous query matches `table_reference` nodes so there isn't a need to repeat it.

highlights(sql): missing keyword & marginalia

---

lua/nvim-treesitter/parsers.lua
queries/gitattributes/highlights.scm
queries/gitattributes/injections.scm

Vim doesn't have a `gitattributes` filetype so it will have to be added by the user.
```lua
-- for example:
vim.filetype.add {
filename = {
[".gitattributes"] = "gitattributes",
},
pattern = {
[".*/git/attributes"] = "gitattributes",
[".*/info/attributes"] = "gitattributes",
}
}
```
---
I hadn't written a parser before this one, so I marked it as experimental just in case.

feat: add tree-sitter-gitattributes

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/jsonnet/highlights.scm

Neovim does not have a built in Jsonnet file type detection, so it only works with google/vim-jsonnet extension or with ftdetect file added (https://github.com/google/vim-jsonnet/blob/master/ftdetect/jsonnet.vim). Is it fine, or maybe that ftdetect file should be added to Neovim first? I'm not sure if they would even accept a PR that would only add file type detection without other features.

feat: add jsonnet

---

contrib/nvim-treesitter-scm-1.rockspec

so that users can install the plugin via luarocks but even better: 
so that other plugins can reference this one and add it as a dependency.

build: add a rockspec

---

lua/nvim-treesitter/fold.lua
lua/nvim-treesitter/query.lua
lua/nvim-treesitter/query_predicates.lua
queries/make/folds.scm
queries/markdown/folds.scm

Some languages that are difficult to parse via Treesitter may
incorrectly include whitespace lines at the end of regions. This can
make the calculated folds sub-optimal.
To rectify, use a new `trim!` directive for languages with this issue and account
for it when calculating folds.
Also added folds for Make
---
Here's a demo with Neovim's Makefile:
(left: original, right: fixed with this PR)

fix(fold): don't include whitespace end regions

---

queries/ecma/injections.scm

From [Use JSDoc: Getting Started](https://jsdoc.app/about-getting-started.html):
> Each comment must start with a `/**` sequence in order to be recognized by the
> JSDoc parser. Comments beginning with `/*`, `/***`, or more than 3 stars will
> be ignored. This is a feature to allow you to suppress parsing of comment blocks.

fix(ecma injections): jsdoc match /** */ only

---

lua/nvim-treesitter/highlight.lua

From my understanding you need to enable `skip_ts_default_groups` in order to set [custom colorscheme](https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/groups/integrations/treesitter.lua)
Without it after `:colorscheme catppuccin` the highlight captures will link to the deprecated TS* highlights
I can simply merge the old TS* highlight groups but that's rather ugly

fix(highlight): respect g:skip_ts_default_groups on ColorScheme autocmd

---

queries/comment/highlights.scm

This is a common comment marker, and nvim-tree sitter would provide more
value to developers by highlighting this by default! Please see #3536
for further motivation and discussion.
Fixes #3536

Add query to highlight comment marker `NOTE`

---

queries/haskell/highlights.scm

Sample:
```haskell
-- | Smart constructor that deduplicates plugins
pattern IdePlugins :: [PluginDescriptor ideState] -> IdePlugins ideState pattern IdePlugins{ipMap} <- IdePlugins_ (sortOn (Down . pluginPriority) . HashMap.elems -> ipMap) _
where
IdePlugins ipMap = IdePlugins_{ipMap_ = HashMap.fromList $ (pluginId &&& id) <$> ipMap
, lookupCommandProvider = lookupPluginId ipMap
}
```

haskell/highlights: Match `pattern` as a keyword

---

README.md

I found out that `disable` can be a function be looking through the source code, but it may be helpful to include this in the readme. 
In the readme I added an example of what I actually used this for - disabling highlight on large files. This is a nice workaround for https://github.com/nvim-treesitter/nvim-treesitter/issues/2996,  https://github.com/nvim-treesitter/nvim-treesitter/issues/2860, https://github.com/nvim-treesitter/nvim-treesitter/issues/1292, etc. This solution is also quite performant as from my tests `fs_stat` takes <100 us.

docs: add example of how to use function to disable a module

---

lua/nvim-treesitter/highlight.lua
tests/query/highlights_spec.lua

`Tests / Run tests` now runs with Neovim 0.8, which 
1. removed `_get_hl_from_capture`
2. switched to "native" tree-sitter highlight groups
3. added non-highlighting captures `@conceal` and `@spell`.
This is something of a band-aid until the tests are rewritten to use the new upstream highlight groups.

fix(test): update tests to Nvim 0.8

---

queries/proto/highlights.scm

`optional` came back with protobuf 3.15 as a valid modifier so highlight it the same way as `repeated`.

highlights(proto): highlight optional

---

queries/swift/highlights.scm

Upstream highlight queries have added support for Swift regex literals. This change brings that support to nvim-treesitter.
Also includes some minor reordering of modifiers for logical consistency (no impact on highlighting behavior).

feat(swift): sync highlight queries with upstream
