nvim-treesitter/nvim-treesitter

lua/nvim-treesitter/install.lua

`'all'` isn't a table, and this caused problems for `:TSUninstall`.

fix(uninstall): support `ensure_installed = 'all'`

---

queries/cpp/highlights.scm

These keywords are now supported by the parser.
See: https://github.com/tree-sitter/tree-sitter-cpp/pull/179

highlights(cpp): add alternative operator names

---

queries/julia/highlights.scm

This patch removes the highlight query for constant identifiers based on capitalization. This led to inconsistent highlighting since e.g. `AA` would be a regular identifier, but `AAA` a constant. It is indeed true that some constants are uppercase only identifiers, but there are also constants which doesn't follow this pattern. Since there are no rules about this it seems better to not try to guess.

fix(julia): remove highlight query for constants

---

queries/agda/highlights.scm
queries/bash/highlights.scm
queries/c/highlights.scm
queries/cmake/highlights.scm
queries/dot/highlights.scm
queries/ecma/highlights.scm
queries/fish/highlights.scm
queries/kotlin/highlights.scm
queries/latex/highlights.scm
queries/lua/highlights.scm
queries/perl/highlights.scm
queries/python/highlights.scm
queries/query/highlights.scm
queries/r/highlights.scm
queries/yaml/highlights.scm

Use the `@preproc` capture to highlight certain preprocessor directives and shebangs.
It could also be used to highlight (some or all) at-rules in CSS if that's desirable. 
There are definitely more languages which could use it that I'm not familiar with.

highlights: use @preproc where appropriate

---

lua/nvim-treesitter/parsers.lua

The parser is now on latest treesitter version: 
https://github.com/claytonrcarter/tree-sitter-phpdoc/pull/23
So this should no longer be required. It was added as it still used TS 0.17.3 before (See https://github.com/nvim-treesitter/nvim-treesitter/pull/2280#discussion_r786279693)

feat(phpdoc): Remove requires_generate_from_grammar

---

queries/yaml/folds.scm

The current yaml folds are based on #887 and #928, but I don't think this is a good folding syntax.
Example and Tests
-----------------
Let's take a look at the example which is a slight extension of #887's one:
```
days:
Monday:
- test: example
day: 1
Tuesday:
- test: example
day: 2
Wednesday:
- test: example
day: 3
- test: example
day: 3
Thursday:
- test: example
day: 4
Friday:
- test: example
day: 5
```
(at foldlevel=0)
```
days:  ⋯    ( 17 lines)
```
(at foldlevel=1)
```
days:
Monday:  ⋯    ( 16 lines)
```
Oops! you can fold the "body" of the `days` node (`block_mapping_pair`). See [this comment from #887](https://github.com/nvim-treesitter/nvim-treesitter/issues/887#issuecomment-874207744) as well.
(at foldlevel=2)
```
days:
Monday:
- test: example  ⋯    ( 2 lines)
Tuesday:
- …
```

folds(yaml): Fold at the entire node, not at the body.

---

lua/nvim-treesitter/configs.lua

This change allows for languages not managed by nvim-treesitter to use
Nvim-treesitter modules like folding and indent.

fix(modules): allow non-registered langs to use modules

---

CONTRIBUTING.md
README.md
lua/nvim-treesitter/parsers.lua
queries/diff/highlights.scm

This commit introduce diff parser.
I'm not sure but I introduce new highlights (`@diff.add` and `@diff.delete`) as I can't find any highlight matching to this usage.
Parser comes from https://github.com/the-mikedavis/tree-sitter-diff
Thanks for your awesome work !

feat(diff): add diff parser

---

lockfile.json
queries/bash/highlights.scm

This patch renamed `ansii_c_string` to `ansi_c_string` to match the upstream change.
See https://github.com/tree-sitter/tree-sitter-bash/pull/121.

fix(bash): Rename ansii_c_string to ansi_c_string.

---

lockfile.json
queries/python/highlights.scm

Added in https://github.com/tree-sitter/tree-sitter-python/pull/176
About the feature https://realpython.com/python311-exception-groups/#exception-groups-and-except-in-python-311

highlights(python): add "except*"

---

queries/ocaml/highlights.scm

By moving the Variables query higher it gives the @variable capture group a lower precedence when highlighting.
This makes it possible to distinguish between @function and @variable.
Fixes tree-sitter/tree-sitter-ocaml#61.

fix(ocaml): change query order for Variables

---

queries/markdown/highlights.scm
queries/markdown/injections.scm

This PR adds extra markdown support:
The only thing I'm not sure of, is that the `markdown_inline` for table cells with `conceallevel=3` would now mess existing table formatting without conceal.

feat: markdown table highlights and inline

---

queries/markdown/highlights.scm

I wan't able to make this work. I think it's not possible right now, because of `\` in `markdown` and `backslash_escape` in `markdown_inline`.
@MDeiml you were right about my other PR though.
This fixes the `|` outside tables.

markdown: fixup for #3736

---

lua/nvim-treesitter/configs.lua

I always get a warning when editing my dotfiles, as I have `ensure_installed = "all"`.
Let's fix it 😊 
Thanks for all your work guys!

fix(configs): ensure_installed can be a string

---

README.md

As discussed per issue https://github.com/nvim-treesitter/nvim-treesitter/issues/3642 .
This PR adds a line to README.md for the configuration. It's now possible to enable folding via nvim-treesitter but disable folding everything at startup. 
Tested with vim -d to see if folding during diff editing still works.

Disable folding at startup.

---

queries/help/highlights.scm
queries/lua/highlights.scm
scripts/ci-install-macos-latest.sh
scripts/ci-install-ubuntu-latest.sh

Remove bundled parsers in CI to make sure we test queries against the parser version specified in the lockfile.
Also bump `help` and `lua` queries (which were blocked by this issue) while I'm at it.

test: remove bundled parsers in CI

---

README.md

Hello! - this is a minor fix for the language in which the example option to disable folding on startup is written :)

fix(readme): disable folding at startup

---

lockfile.json
queries/julia/highlights.scm
queries/julia/locals.scm

See https://github.com/tree-sitter/tree-sitter-julia/pull/54
Remove a bunch of patterns with `argument_list`. No longer necessary
with `short_function_definition`.
Other minor changes including:
- Add boolean literals See
https://github.com/tree-sitter/tree-sitter-julia/pull/44
- Add highlights for `for_binding` and `subtype_clause` operators

Refactor Julia highlights

---

queries/rust/highlights.scm

This is what rust.vim used to do with the rustPanic and rustAssert highlight groups. If I'm remembering right, this is slightly better as it also catches `debug_assert!()`.
Edit: for clarity `println!` still highlights as `@function.macro`.

highlights(rust): panic!() and assert!() as @exception

---

queries/rust/highlights.scm

```rust
trait Trait { type Assoc; }
fn thing<T: Trait>(arg: T::Assoc) {}
```
Previously, T in `T::Assoc` was highlighted as `@namespace`. Now it's `@type`.
Highlights the for as a keyword, and the angle brackets as brackets.
```rust
type T = &'static dyn for<'a> Fn(&'a str) -> i32;
```
Highlights the angle brackets as brackets.
```rust
type A = <B as Trait>::Assoc;
<B as Trait>::method(5);
```

highlights(rust): namespace/type confusion; highlight `for<'a>` and bracketed types better

---

lua/nvim-treesitter/parsers.lua
queries/arduino/folds.scm
queries/arduino/highlights.scm
queries/arduino/indents.scm
queries/arduino/injections.scm
queries/arduino/locals.scm

This handles the (few) extensions and (many) built-ins defined by Arduino.
Almost all extensions are already highlighted via the C queries.
The only exception is `PROGMEM` which depends on #3693 (839c89a).
See: https://www.arduino.cc/reference/en/

feat(arduino): separate from cpp

---

queries/ecma/highlights.scm

`switch` must be removed from `@keyword` because it's already highlighted as `@conditional`
---
> In your screen shot it looks like `switch` is not highlighted as `@conditional`. Maybe that could be adapted as well...
It's `@keyword` and `@conditional` at same time.
I can create another PR to remove it from keywords
_Originally posted by @Trard in https://github.com/nvim-treesitter/nvim-treesitter/issues/3778#issuecomment-1310383801_
---

highlights(ecma): remove `switch` from `@keyword`

---

queries/go/highlights.scm

Continuing the discussion started at https://github.com/nvim-treesitter/nvim-treesitter/pull/3152
regarding `@type.definition` highlight if we should it or not.

add golang type definition highlight

---

queries/nix/highlights.scm
queries/nix/injections.scm

- highlight parameters
- add injections for code blocks (phases, runCommand*, writers) based on https://github.com/cstrahan/tree-sitter-nix/pull/31 by @nrdxp
- add injections for `builtins.match` (regex)

improve highlights and injections for Nix

---

lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/install.lua

`is_installed` is picking up parsers shipped by neovim v0.8 and these parsers have unknown version
and compatability.
_Note: this applies to any parser found in the rtp_
https://github.com/nvim-treesitter/nvim-treesitter/blob/2072692aaa4b6da7c354e66c2caf4b0a8f736858/lua/nvim-treesitter/install.lua#L94-L98
only consider a parser installed if ~~its revision is available~~ it's available in the `parsers_install_dir`.
_Edit: the revision file can still remain after uninstalling a parser, so it's not reliable heuristic!_

fix(installer): ignore globally installed parsers

---

queries/astro/injections.scm

The Astro parser should use the typescript parser for the `<script>` element instead of the javascript parser as defined by `; inherits: html`. This overrides it.
Note: Is this the correct way to do things? Does this completely override the HTML `javascript` injection or will this break at some point?

fix(astro): make the script element use typescript instead of javascript

---

queries/fish/highlights.scm

I have made a mistake in this PR: https://github.com/nvim-treesitter/nvim-treesitter/pull/3752
(changes were merged in here: https://github.com/nvim-treesitter/nvim-treesitter/pull/3851)
Instead of `@function` the capture name should be `@function.builtin` as it was previously.
Sorry 🙏

fix(fish): "test" command capture name

---

lockfile.json
queries/typescript/highlights.scm

Support the new [satisfies operator](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#the-satisfies-operator) added in TypeScript 4.9

highlights(typescript): Add satisfies keyword

---

lua/nvim-treesitter/install.lua

When installing nvim-treesitter without any config and then
running `TSUpdate`, the global parsers will be installed.
This PR fixes that

fix(installer): don't update parsers that are not installed

---

queries/ecma/highlights.scm

`default` keyword is used in [switch statements](https://262.ecma-international.org/12.0/#prod-DefaultClause) and [export declarations](https://262.ecma-international.org/12.0/#prod-ExportDeclaration).
In switch statements it must be highlighted as `@conditional`.
In export declarations it must be highlighted as `@keyword`.

highlights(ecma): distinguish between "default" in export and switch

---

queries/ecma/highlights.scm
queries/typescript/highlights.scm
tests/query/highlights/typescript/as.ts

`as` is currently always highlighted as `include`:
https://github.com/nvim-treesitter/nvim-treesitter/blob/1b3f93dcb90e1c282fe9259e5a15f34d504fd5a1/queries/ecma/highlights.scm#L213-L217
Adds a query for highlighting as `keyword` in `as_expression` type assertions.

highlights(typescript): Fix as highlight

---

scripts/check-queries.lua

Arguments to vim.startswith where swapped. Prefix has to go second.
:man_facepalming: :man_facepalming:

ci: fix check for valid capture

---

queries/gitcommit/injections.scm

Since last update of the parser, syntax tree is modified.
From : 
```scheme
(diff)
(generated_comment (title))
```
To
```scheme
(diff
(generated_comment (title)))
```

feat(gitcommit): improve diff injection since last parser update

---

queries/php/highlights.scm

This pull request changes the way of highlighting "$" sign and variable name  in PHP. In PHP all variables starts from "$" and I see no good reason why they should have different color as they do for now.
Current highlight
After PR
Maybe I'm missing something and some reasons exist for having different color?

improve PHP variables and $this highlights

---

queries/javascript/locals.scm

The previous locals were lacking a few locals related to JS classes. This expands the locals to include properties defined on classes (e.g. `this.foo = "bar"` or `static #targets`) as both vars & references, as well as private methods on classes (e.g. `#bar(x) { x }` and `#bar(y)`).

Expand locals to include properties and methods

---

lua/nvim-treesitter/health.lua

Often we get issue report without knowing which version of Windows or Linux or MacOS they are running.
E.g.
```
nvim-treesitter: require("nvim-treesitter.health").check()
Installation ~
- OK `tree-sitter` found 0.20.7 (870fb8772f3e47b5aef4c7000a78d61f3aa2b005) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v17.9.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `/usr/lib/ccache/clang-16` executable found. Selected from { "/usr/lib/ccache/clang-16", "cc", "gcc", "clang", "cl", "zig" }
Version: Ubuntu clang version 16.0.0 (++20221123042319+910204cfbdf3-1~exp1~20221123042440.568)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.
OS Info:
{
machine = "x86_64", …
```

chore: print OS version on health report

---

queries/bash/injections.scm
queries/julia/injections.scm
queries/perl/highlights.scm
queries/perl/injections.scm
queries/ruby/injections.scm

I added a missing node to the `string.regex` highlights for Perl but didn't add the injections because the patterns might include expressions which should be interpolated and highlighted by the grammar (though they currently aren't).

injections: add more regex injections

---

lua/nvim-treesitter/install.lua

`is_installed` sometimes returns false for parsers that are already installed. This can happen when the detected install_dir is an absolute path and the runtime `.so` files are relative paths, or vice-versa.
I've changed the logic to always convert the paths to absolute paths before doing the prefix comparison. I've also added a guard for the case where the install_dir is nil.

fix: is_installed correctly detects installed parsers

---

queries/phpdoc/highlights.scm

`optional_type` is not considered as `@type` in phpdoc.
Before:
After:

fix(phpdoc): highlight optional type as @type

---

queries/markdown/highlights.scm

See example below. Before they did not have highlights.

feat: added highlights for markdown checkboxes

---

CONTRIBUTING.md
queries/awk/highlights.scm
queries/c/highlights.scm
queries/ecma/highlights.scm
queries/fusion/highlights.scm
queries/hack/highlights.scm
queries/java/highlights.scm
queries/julia/highlights.scm
queries/meson/highlights.scm
queries/perl/highlights.scm
queries/slint/highlights.scm
queries/vim/highlights.scm
tests/query/highlights/fusion/expressions.fusion

After https://github.com/nvim-treesitter/nvim-treesitter/issues/470, we decided to use `@conditional` for ternary operator instead of operator despite `@conditional` is documented for keywords only. A sub-scoping can make it easier for people to highlight this operator group differently while keeping the `@conditional` highlight. It also makes the documentation clearer for people adding new languages with ternary operator as they will find the categorization in CONTRIBUTING.md
Also unify the usage of `@conditional...` across languages.

highlights: create subscoping for ternary operator

---

queries/ecma/folds.scm
queries/ecma/indents.scm
tests/indent/ecma/switch.js

Add `@indent` and `@fold` for `switch_default`.

indents(ecma): Fix switch default indent

---

queries/php/indents.scm

Indent for `match` and `switch` are broken, this will allows to provide this default indents:
```php
<?php
match($e) {
true => "ok",
false => "ko",
}
switch($e) {
case true:
echo 'ok';
break;
case false:
echo 'ko';
break;
}
```

feat(php): improve indents for match and switch

---

scripts/run_tests.sh

Add the test name to summary output. Also clean up regex.
Before:
```
Success: 	1
Failed : 	0
Errors : 	0
Success: 	1
Failed : 	0
Errors : 	0
...
```
After:
```
Testing: 	/Users/shraymonks/Projects/nvim-treesitter/tests/indent/graphql_spec.lua
Success: 	1
Failed : 	0
Errors : 	0
Testing: 	/Users/shraymonks/Projects/nvim-treesitter/tests/indent/wgsl_spec.lua
Success: 	1
Failed : 	0
Errors : 	0
...
```

test: Add test name to summary output

---

queries/typescript/highlights.scm

Add highlights for the `module` keyword that is used inside declaration files (`.d.ts`).

highlights(typescript): add `module` keyword

---

lockfile.json
queries/julia/highlights.scm
queries/julia/indents.scm
queries/julia/injections.scm

See https://github.com/tree-sitter/tree-sitter-julia/pull/83
- Add global and local as keywords. See https://github.com/tree-sitter/tree-sitter-julia/pull/78
- Fix a small mistake with subtypes in type definitions
- Restrict markdown injections to docstrings

Update Julia highlights and injections

---

queries/java/highlights.scm

Java highlighting is currently missing highlighting for '!' operator. #3987

highlights(java): fixed '!'+param+global highlight

---

lua/nvim-treesitter/health.lua

Some parser names are too long for the given space, which shifts the
features so they aren't in line.

fix(health): align the list of parsers when doing checkhealth

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/ada/folds.scm
queries/ada/highlights.scm
queries/ada/locals.scm

The grammar was built from the official Ada grammar available in the ISO standard, and from an existing similar grammar used for the Emacs ada-mode.
The resulting grammar is able to parse all source files in the GNAT runtime (the kind of "official" compiler for Ada), as well as the 3 million+ lines of code at my company), without ERROR, though of course I could not check all resulting trees.
The testsuite is reasonably complete at this stage.

feat: add Ada

---

queries/vue/injections.scm

My attempt to fix #3980 
Changes:
- Will no longer inherits `html_tags`
- Will only injects javascript if `lang="js"` is specified, or if there is no `lang` attributes
- Remove `typescript` as a validate predicate for typescript injection as there is no mention of `lang="typescript"` being a valid attribute on [vuejs website](https://vuejs.org/)
| Before AST | After AST |
| -- | --|
| ![image](https://user-images.githubusercontent.com/29790821/208475726-651c0b15-6940-42b0-991d-526d4b9f4dec.png) | ![image](https://user-images.githubusercontent.com/29790821/208475585-3eececdb-4be4-4f15-8b8e-2d36f144a264.png) | 
Any helps would be appreciated

injections (vue): fix js/css injection conditions

---

lua/nvim-treesitter/parsers.lua

Old usage was still working because of backward compatibility of nvim code:
```lua
if type(kwargs) == 'boolean' then
-- Support old signature for backward compatibility
plain = kwargs
else
```
https://neovim.io/doc/user/lua.html#vim.split()

chore: update usage `vim.split` to new signature

---

queries/vue/injections.scm
tests/query/injections/vue/test-vue-injections.vue

Follow up of #3981 
Update Vue injection queries with more queries to properly capture cases where it has no `lang` attribute
https://user-images.githubusercontent.com/29790821/209374232-63c1fa60-10ea-4a6b-8246-9d17a3df8079.mp4
It will still correctly capture even if we insert multiple spaces and newlines
https://user-images.githubusercontent.com/29790821/209374644-e178b5c5-8b49-407c-b2ec-1b609eacd173.mp4

injections(vue): Update injection queries

---

queries/vue/injections.scm
tests/query/injections/vue/test-vue-injections.vue

Change L5 and L33 to denote start of node's text so that `match?` can work properly (the `<` and `>` was recognized as something else, unsure what)
So explicity escape it to guarantees it won't be read as something else
CC @theHamsta again today, sorry for the regression :bow:

Injections(vue): Fix vue injection regressions

---

lua/nvim-treesitter/highlight.lua

Fixes #4026
I don't know whether this is the right thing (probably not). I was not aware of `vim.treesitter.start()`. When it is invoked somewhere else we should probably just do  `vim.treesitter.start()` when the installation is finished in case the highlight module is enabled.
Probably, the highlight module can be removed entirely when the functionality is managed by Neovim.

fix: do `vim.treesitter.start()` on highlight module attach

---

lua/nvim-treesitter/install.lua

else `vim._ts_has_lang` will return false.
Fixes #4026

fix: require_language is needed after installation to update Vim's language table

---

lockfile.json
queries/julia/highlights.scm

- Update patterns for type definitions:
The grammar was updated to parse `abstract type` and `primitive type` as a single token.
- Update `@symbol` capture to highlight quoted operators as symbols.
- Add pattern to highlight adjoint operator.
- Update patterns and captures for:
- "keyword" operators (`in`, `isa`, and `where`)
- type operators (`<:`, `>:`)
- Parametrized types.
---
- See https://github.com/tree-sitter/tree-sitter-julia/pull/87
- There's also a few changes that I forgot to add to https://github.com/nvim-treesitter/nvim-treesitter/pull/4016

Update Julia highlights

---

queries/haskell/highlights.scm

Add highlights for lambda bindings (`lambdaOne` below) and prevents capturing bindings as functions if signatures have different names (the last three bindings in the example below).  
| Before                                                                                                         | After                                                                                                          |
| -------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------- |
| ![image](https://user-images.githubusercontent.com/4299733/210000298-25a8eacd-800b-40cc-bbec-e61d901b6691.png) | …

highlights(haskell): lambda and function with type signature

---

lua/nvim-treesitter/parsers.lua
queries/wgsl_bevy/folds.scm
queries/wgsl_bevy/highlights.scm
queries/wgsl_bevy/indents.scm

This adds an extension (https://github.com/theHamsta/tree-sitter-wgsl-bevy) of tree-sitter-wgsl that understands [Bevy's](https://bevyengine.org/) preprocessor directives.

parsers: add wgsl_bevy

---

.github/workflows/tests.yml
queries/rust/highlights.scm
tests/query/highlights/rust/super-crate-imports.rs
tests/query/highlights_spec.lua

Fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/3992
Add negative assertions to verify, that there is no dual-highlight as before.

highlights(rust): use `@namespace` for `[(crate) (self) (super)]`

---

queries/haskell/highlights.scm

__Highlighting partially applied infix functions (right and left sections) as operators.__
The expected highlight would be:
```haskell
vowels :: [Char] -> [Char]
vowels = filter (`elem` "aeiou")
divisors :: Int -> [Int]
divisors n = filter ((== 0) . (n `mod`)) [1..n]
```
But currently we get:
This change fixes that:

highlights(haskell): Fix highlighting of partially applied infix functions

---

queries/elm/highlights.scm

I missed this in my previous MR.
Found it by browsing through large Elm codebases.
| ![image](https://user-images.githubusercontent.com/4299733/210181608-b172d2e4-4ae5-4e83-a0dd-00d70fb2d63a.png) | ![image](https://user-images.githubusercontent.com/4299733/210181618-bc35411f-ebea-4bf5-b020-3fcd84890cc4.png) |

highlights(elm): zero args constructor pattern matching

---

.github/workflows/update-lockfile.yml

See https://github.com/nvim-treesitter/nvim-treesitter/pull/4066
The diff will look different when a whole parser gets added:
```
@ ["gleam","revision"]
- "cfcbca3f8f734773878e00d7bfcedea98eb10be2"
+ "3eb2e1783f3bf6f85c16cdd150e2f256b2f6844e"
@ ["nix","revision"]
- "6b71a810c0acd49b980c50fc79092561f7cee307"
+ "1b69cf1fa92366eefbe6863c184e5d2ece5f187d"
@ ["wgsl_bevy"]
+ {"revision":"c81dc770310795caea5e00996505deba024ec698"}
```

ci: trim final `"]` when parsers get added in update-lockfile.yml

---

queries/html/injections.scm
queries/html_tags/injections.scm
queries/svelte/injections.scm
queries/vue/injections.scm
tests/query/injections/html/test-html-injections.html
tests/query/injections/svelte/test-svelte-injections.svelte

- A partial implementation for #4034 
- Update html_tags injections file so that vue/svelte parsers can inherit it without having a script/style tag being captured twice
- Update vue, svelte injections
- Add test file for html, svelte
Preview:
| ![image](https://user-images.githubusercontent.com/29790821/210190509-cc89c707-b07c-4d03-be6e-d66f8c2f00db.png) | ![image](https://user-images.githubusercontent.com/29790821/210190565-c76fa11a-4e24-4af2-8755-446d3cd52582.png) |

injections(html, vue, svelte): Update injections

---

queries/html_tags/indents.scm
tests/indent/html/issue-3986.html
tests/indent/html/script_style.html
tests/indent/html/self_closing_tag.html
tests/indent/html/start_tag.html
tests/indent/html_spec.lua

- HTML was only indenting child elements of element captures, but dedents all end tags (including script/style elements)
Change it so it now only dedents end tag of non-script/style elements
- Indent for elements was specified, but no ending mark for indents means directly following text/element will be incorrectly indented
- It will still indent correctly if you add one space after the ending tag (not nice)
- So adding `indent_end` to properly mark end of an element
Before:
```html
<body>
<script>
</script>
<div>
</div>
| cursor will be here if you click enter on the line above
</body>
```
After: 
```html
<body>
<script>
</script>
<div>
</div>
| cursor will be here if you click enter on the live above
</body>
```

fix(html): fix incorrect indents for elements/texts after end tag

---

lua/nvim-treesitter/ts_utils.lua
tests/unit/ts_utils_spec.lua

The char_delta is not calculated correctly right now when there are two treesitter nodes being swapped, one directly following the other. This is rare but can happen for example when attempting to swap "print" and "(1)" in "print(1)". In this case an incorrect char_delta is calculated because of a bug in range comparison.

fix(utils): swap_nodes calculates correct char_delta

---

lua/nvim-treesitter/ts_utils.lua

With [4bcd3a3](https://github.com/nvim-treesitter/nvim-treesitter/commit/4bcd3a3cc31b9628a48ff126938262292b1ed988) some issues have come up since `feedkeys` is being used to pass `gv`. 
With the current implementation if gv is remapped, e.g. `map gv <NOP>` then `update_selection` wouldn't work properly. That's why I suggest passing instead `:normal! gv` , as it would limit side-effects.

Remove update_selection side-effects

---

.github/workflows/test-queries.yml
lua/nvim-treesitter/shell_command_selectors.lua

E.g. installing C [here](https://github.com/nvim-treesitter/nvim-treesitter/issues/4056) does not require libstdc++.

install: allow pure C parsers to be compiled without `-lstdc++`

---

queries/cpp/injections.scm

the delimiter describes the language to use for the injection content
```cpp
auto python_code = R"python(
import os
if __name__ == '__main__':
print(os.name)
)python";
```

injections(cpp): add injections for raw string literals

---

queries/ruby/indents.scm
tests/indent/ruby/indent-square-brackets.rb

I don't think the opening bracket should be included in `@branch`. I also moved `'end'` so it would be in the same order as in the previous group. That might be over the top.

Update to Ruby Indents for Square Brackets

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/wgsl/highlights.scm
queries/wgsl/indents.scm

https://github.com/szebniok/tree-sitter-wgsl/pull/7/files#diff-bbcf6c785b007d9655b443abc204cc3cc32aa03cea190cb865fe44252dc6f1df added support for block comments. This requires to add a parser and to replace `comment` in the queries.

Fix bevy: comment -> {line,block}_comment

---

lua/nvim-treesitter/parsers.lua

Someone like qml to mark qmljs, so let 'qml'
use qmljs

feat: let filetype qml use the highlight of qmljs

---

lockfile.json
queries/nickel/highlights.scm

Follow upstream change in https://github.com/nickel-lang/tree-sitter-nickel/pull/13/files#diff-d485a982e458ef8da2cc203585065b7542665cb80b78d230b1e8f77ea25825d4 that also modified highlights.scm

Fix nickel: switch -> match

---

queries/scss/highlights.scm

also removed `@media` as we are already inheriting it from [`css`](https://github.com/nvim-treesitter/nvim-treesitter/blob/9a257d989a526c413a28c252c4ec9113a7d35a28/queries/css/highlights.scm#L2)
Ref: https://sass-lang.com/documentation/at-rules

feat(scss): add known at-rules to keyword list

---

README.md

In the README.md, [it is suggested to add `vim.opt.runtimepath:append("/some/path/to/store/parsers")` **after** the call of `require'nvim-treesitter.configs'.setup`](https://github.com/nvim-treesitter/nvim-treesitter#changing-the-parser-install-directory).
However, it seems to me that it only works if it is placed before.
Related issue: https://github.com/nvim-treesitter/nvim-treesitter/issues/3605

readme: runtimepath before setup call

---

queries/c/indents.scm
tests/indent/c/if_else.c
tests/indent/c/issue-4079.c
tests/indent/c/issue-4117.c
tests/indent/c/no_braces.c
tests/indent/c_spec.lua

Resolves #4079
Resolves #4117
Behavior changes:
- Before:
- An if statement without code blocks, following by another if statement/ code blocks will be indented twice
- If the chain continues, then it is indented multiple times (equal to the amount of bare if statements that appears in the chain of if-else above it)
- Now:
- A bare if statement, followed by a bare if statement, then the second bare if statement will not be indented any extra
I have yet to cover for the situations below
- else immediately followed by a for/while/switch statement (indent twice)
- This case I don't know how to handle, as there may be two styles for this (for/while in the same/different line to else)
<details>
<summary>Supported if styles</summary>   
```   
if 
ret
else if
ret
else
ret
if
{
ret
}
else if
{ …
```

refactor(c): Refactor indent queries

---

.github/workflows/update-lockfile.yml

This is wasteful and noisy for unrelated commits, while the intended use
(making sure that new parsers have a lockfile entry) can be covered by
either making sure this is part of the initial PR (ideally) or running
the action manually.

ci: stop running update-lockfile after every commit

---

lockfile.json
queries/scala/highlights.scm

There has been a lot of changes recently to the Scala grammar and we've been merging in a handful of things before syncing the actual generated parser. We are currently at a stage where we're going to sync everything, but there are some breaking changes that are included in https://github.com/tree-sitter/tree-sitter-scala/pull/135, so when that commit gets synced here stuff will break. We've taken the queries that existed here and have been building off of them in the actual upstream repo. This will hopefully make the transition smooth and updates the queries to ensure that there is no breakage. It's recommended to wait until that pr is merged, synced here, and then merge this in around the same time.
Co-authored-by: eugene yokota <eed3si9n@gmail.com>
Co-authored-by: Anton Sviridov …

refactor(scala): update the Scala highlight queries

---

queries/haskell/highlights.scm

This PR adds highlights for several things:
1. Range operator (`..`)
2. Dot in qualified types and variables (`M.Map` & `M.lookup`)
3. Dot at the end of `forall` statements.
4. `*` in kind signatures (`* -> *`).
| ![image](https://user-images.githubusercontent.com/4299733/212496637-e60d053d-c1d1-4752-8505-198f8b7671f6.png) | ![image](https://user-images.githubusercontent.com/4299733/212496599-cc218f47-242c-4eca-84de-54e38e6e00fa.png) |

highlights(haskell): special sigils and operators

---

lua/nvim-treesitter/parsers.lua
queries/elm/highlights.scm

This fixes a query similar to #4130 with @ObserverOfTime's suggested query.
| ![image](https://user-images.githubusercontent.com/4299733/212498416-a304a2e8-1731-49eb-86b9-3426b3de4da8.png) | ![image](https://user-images.githubusercontent.com/4299733/212498365-99580767-c6d7-4da7-9a2d-68a9e7e95e37.png) |

highlights(elm): fix boolean literals

---

queries/haskell/highlights.scm

The regex was matching `True` / `False`, but also any constructor containing the value as substring, such as `AlwaysTrue`.
The regex was changed to ensure the matched `True` / `False` is the complete name.
Was:
Now:

highlights(haskell): xxx(True/False)yyyy is not a bool

---

CONTRIBUTING.md

This is just a tiny change that was in reference to
https://github.com/nvim-treesitter/nvim-treesitter/pull/4153#discussion_r1070276800.
The basis is that `@storageclass` should only be used unless it's
actually affecting storage in memory. There are further conversations
about this in the following places:
- https://github.com/nvim-treesitter/nvim-treesitter/pull/3648#issuecomment-1279923861
- https://github.com/nvim-treesitter/nvim-treesitter/pull/3648#issuecomment-1291624844

docs: clarify @storageclass in CONTRIBUTING docs

---

lua/nvim-treesitter/parsers.lua
queries/ini/folds.scm
queries/ini/highlights.scm

Works with classic one-line key-value pairs. Not with Python-style inis with multiline values (highlighting is still ok with used queries)
Addresses https://github.com/nvim-treesitter/nvim-treesitter/issues/2282#issuecomment-1398856301
@dsully

Add support for tree-sitter-ini

---

CONTRIBUTING.md

Also, `@conditional.ternary` should not be in the "keywords" section, while `@conditional` should.
Possible solutions:
- Make a new group for conditionals (not worth it)
- Replace `@conditional.ternary` with `@operator` or `@operator.ternary`
- Just don't mention `@conditional.ternary` in the docs (this has my vote)

docs: fix comment alignment

---

queries/scala/highlights.scm

This is a small change that comes from the discussion we had in
https://github.com/tree-sitter/tree-sitter-scala/discussions/168#discussioncomment-4718624.
The idea here is that we're sort of making an assumption on what an
uppercase identifier is in Scala and more times than not, it's actually
a `@type`. So this changes the `@constant` capture to a `@type` one. You
can find the full context in the linked discussion.

refactor(scala): update scala highlights for uppercase identifiers

---

queries/html_tags/injections.scm

Use built in anchor node instead of predicate for checking no attribute style/script tags

injections(html): update injection queries

---

queries/json/highlights.scm

This PR partially reverts da6dc21 as currently it breaks highlighting if the value of a pair is not a string (can also be boolean, number, array and object)
@ObserverOfTime is it ok to revert this?

Partially revert json highlight updates

---

queries/rst/highlights.scm

highlights(rst): don't spell check links

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/capnp/highlights.scm

This PR adds a capnp parser+queries
Parser: https://github.com/amaanq/tree-sitter-capnp
Reference: https://capnproto.org/language.html
cc: @marziply since they first brought it up in #2282 
There are some oddities with this language in general that I'd like some advice on as to how to define the queries for. Cap'n Proto fields have a numeric identifier as a type of "version" for that field, e.g. 
```capnp
struct Test {
voidField    @0  : Void;
boolField    @1  : Bool;
}
```
So voidField has a version of 0, boolField 1. you can also optionally add a ! to indicate that the number is an inline (immediate) value, as opposed to a reference to a value stored elsewhere in the data structure, for more efficient encoding and decoding of data. 
At first I thought of just using operator, but that …

feat: add capnp

---

lua/nvim-treesitter/parsers.lua

Adds the [quarto](https://quarto.org/) filetype to use the markdown parser. When the filetype was very new we had just changed the filetype from quarto to markdown, but now it is time to make use of it :)

map quarto ft to markdown parser

---

queries/c/highlights.scm

Using `@storageclass` so it's consistent with `extern` as `storage_class_specifier`.

highlights(c): extern in linkage specification

---

queries/php/highlights.scm

Is `@preproc` the right capture for this?
| ![image](https://user-images.githubusercontent.com/4299733/213964895-22a2d35b-a1d3-40df-ad08-5eecacfacd25.png) | ![image](https://user-images.githubusercontent.com/4299733/213964825-b77a45d7-c383-4832-89e6-7fd0e70beac9.png) |

highlights(php): declare directives and `:`

---

lua/nvim-treesitter/install.lua

If the user changes the parser_config by modifing the table returned by get_parser_configs(), then internally mark the config so when we install we 1) don't use the revision pointed to by the lockfile, and 2) always download the parser via git.

fix: better support for custom parsers

---

queries/jq/highlights.scm

`jq/highlights.scm` should highlight the `elif` keyword

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/ron/folds.scm
queries/ron/highlights.scm
queries/ron/indents.scm
queries/ron/injections.scm
queries/ron/locals.scm

This PR adds support for RON (Rusty Object Notation) https://github.com/ron-rs/ron
cc: @xrelkd as they first requested it in #2282
This is my first time adding queries that aren't highlights, so I'd really like a maintainer to have a look over folds, indents, and injections just for a sanity check.
I also noticed a lot of parsers have an injection for comments where it's just `@comment`, it'd be nice if someone could explain the reason/why behind that :)
Lastly, I removed redundant branch = "master" from my parsers, I also noticed quite a few parsers have this and have a redundant filetype field as well (which is meant for when the parser name doesn't equal the filetype name right?). If it's alright, I'll fix up other filetype/branch redundancies as well.

feat: add RON

---

lua/nvim-treesitter/ts_utils.lua
tests/unit/ts_utils_spec.lua

The `ts_utils.get_node_range()` and `ts_utils.is_in_node_range()` have identical copies in `vim.treesitter`.
This PR deprecates the two functions in favour of the `vim.treesitter.*` equivalents.

Deprecate ts_utils.get_node_range and is_in_node_range

---

queries/comment/highlights.scm

There are a couple cases where the comment highlights will match things that aren't really a tag.
For example, in Rust, when commenting a block that deals with generics (generics are declared as `T: Type`),
this may be distracting.
So, instead of highlighting all tags, we can restrict to highlighting the explicit keywords.
I'm also thinking that I could change the parser itself to match just a set of keywords, and if users want more keywords, add them to the parser or expose a compile-time option to provide a set of keywords.
Suggestions are welcome!
Ref https://github.com/stsewd/tree-sitter-comment/issues/14

RFC: Reducing false positives for comment highlights

---

queries/hcl/highlights.scm
queries/terraform/highlights.scm

cc @MichaHoffmann 
First off - appreciate all the work from everyone going into this plugin! I was recently messing around with LunarVim and liked the syntax-highlighting it was providing for terraform. Through the help of my colleague @pappasam - he helped me understand how syntax highlighting works. From there, I was able to determine that LunarVim was shipping an old version of the tree-sitter parsers.
I'm hoping we can bring back this particular change because it's visually much more pleasing. I'm still learning tree-sitter parser syntax so not sure if this is the best approach and also know this is subjective. Screenshots with before/after.

Update syntax highlighting for hcl

---

README.md

Also uses prettier formatting
I've seen many people, including myself, being confused about `highlight { enable = false }` disabling the whole extension. It means it will disable highlighting, but people get it wrong thinking that they can't use textobjects or any other treesitter related stuff.
Reference: https://github.com/nvim-treesitter/nvim-treesitter-textobjects/discussions/379

Remove confusing enable = false comment in Readme

---

lua/nvim-treesitter/ts_utils.lua

use `vim.treesitter.is_in_node_range()` directly

refactor(utils): clean up deprecated code

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/thrift/folds.scm
queries/thrift/highlights.scm
queries/thrift/indents.scm
queries/thrift/injections.scm
queries/thrift/locals.scm

This PR improves Thrift queries.
* Set branch to main (if it's not master you should do this right?)
* Added indents, injections, and locals, improved folds
One semi-issue I had was getting the indent to go to the function identifier level after parameters if there's an exception (in thrift, a comma signifies the end of a function definition in a service so this would happen in the absence of a comma, note the screenshot has the comma after the exception parameters signifying the function end)
Screenshot shows my cursor position after hitting enter after a parameters list. It should ideally be aligned where throws is (under the function name), but I could not figure that out. If anyone reviewing this has a solution for that, that'd be a great addition to the indents.
Thanks!

feat: improve Thrift queries

---

queries/go/folds.scm

Adds folds for type switches, switch cases and default cases, see this snippet:
```go
func test(hello any, world string) {
switch hello.(type) { // a new fold
case string: // a new fold
log.Println("a string")
default: // a new fold
log.Println("something else")
}
switch world[0:1] { // was already a fold
case "h": // a new fold
log.Println("starts with h")
}
}
```

feat(go): add folds for type switch and switch cases

---

queries/kotlin/highlights.scm

it would be nice, if the parser could distinguish arguments and giving arguments by specified name of the parameter. The first one is an argument, but the latter is just the name of the parameter and therefore it should be recognized as a parameter rather than a `value_argument->simple_identifier`

feat(kotlin): improve highlight queries

---

.github/workflows/lint.yml
.github/workflows/test-queries.yml
.github/workflows/tests.yml

It's only needed if a job is disabled for drafts. Otherwise it will just
run the same workflow twice.

ci: remove ready_for_review type

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/starlark/folds.scm
queries/starlark/highlights.scm
queries/starlark/indents.scm
queries/starlark/injections.scm
queries/starlark/locals.scm

cc: @folliehiyuki since he first requested it in #2282
This PR adds support for Starlark: https://github.com/bazelbuild/starlark
Grammar: https://github.com/amaanq/tree-sitter-starlark
It is mainly derived from Python with some minor differences. The two differences I'd like looked over by a maintainer are:
- Imports being replaced by a load() call, where individual strings are a module and as such I'd like to have `@conceal` work for the strings in there, but I could not get that to work and my testing would have the actual "load" keyword concealed.
- Classes being replaced by a struct call, e.g. `a = struct(x=123, y=False, z="string")`, so x/y/z are fields. Only issue is when matching I identified the struct in struct() as `@_func` to capture it later, but it seems like this capture is …

feat: add starlark

---

lockfile.json
queries/java/highlights.scm
queries/java/indents.scm
queries/java/injections.scm
queries/java/locals.scm

Closes #3942 
This PR distinguishes escape sequences (finally), moves a couple keywords to where they belong (continue, break to `@repeat`, some others to `@include`), and fixed a few local definitions where parameters were `@definition.var` and not `@definition.parameter`.
Thanks,
Amaan

feat: improve java queries

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/dhall/folds.scm
queries/dhall/highlights.scm
queries/dhall/injections.scm

cc: @FollieHiyuki since he first requested it in https://github.com/nvim-treesitter/nvim-treesitter/issues/2282
This PR adds support for Dhall: https://dhall-lang.org/
Grammar: https://github.com/jbellerb/tree-sitter-dhall
I mostly ported helix's queries, Dhall goes wayy over my head (One of the weirdest languages I've seen...). Only part I'm unsure about is the vim-match bit in highlights.scm, original version is [here](https://github.com/helix-editor/helix/blob/6494fc1daf2bb379e6a1f4ec94f3dafd99b3fb34/runtime/queries/dhall/highlights.scm#L32)
Thanks,
Amaan

feat: add dhall

---

queries/go/indents.scm
tests/indent/go/select.go

fix(go): apply indents in a communication case in a select statement

---

.github/workflows/release.yml

new version adds 'make' support and should fix the release job

ci: bump release workflow

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/solidity/highlights.scm
tests/query/highlights/solidity/test.sol

Closes #3421 (cc: @shuklaayush)
This PR uses the maintained parser (of which the current nvim-treesitter parser is a fork of, and now somewhat dead), and updates the highlights accordingly

feat(solidity): use maintained parser and update highlights accordingly

---

queries/elixir/highlights.scm

When viewing the previous rule in the `TSPlayground` the `@function` captures were not actually matching. This led all functions to get the `@function.call` group applied to them. This change makes it so that the capture now works and where functions are defined will get the `@function` group.

fix(elixir): properly apply `@function` captures

---

doc/nvim-treesitter.txt
lua/nvim-treesitter/statusline.lua
lua/nvim-treesitter/ts_utils.lua

In the spirit of full disclosure, this is mostly about supporting a single use case that I came up with, but I think it's fairly reasonable. And unless my understanding of lua is wrong, shouldn't affect anyone's existing code.
The first change is editing `ts_utils._get_line_for_node` to also pass the treesitter node as an argument to the `transform_fn` that `statusline` uses to format the components of its output.
The second is adding another option to `statusline` to allow duplicate items. Honestly I don't know why it's deduping at all, that seems wrong, but in the interest of backwards-compatibility I just added an option. 
---
If you're interested, my specific use case is configuring a statusline call that will give me a sort of "path" query in a `yaml` file. I'm sure it could be …

statusline: pass node to transform_fn and allow dupes

---

lua/nvim-treesitter/ts_utils.lua

When the `goto_node` is used in operator-pending mode, it will miss the last character. So the result of  
`v]Md` is different from `d]M`.
It's a similar issue to https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/381 and it's not only limited to the built-in movements. This PR fixes the node movements.
The solution is to enter visual mode just like in `update_selection`. It will make operator-pending mode consistent with visual mode behaviour, including the last character.
I will add tests in the `nvim-treesitter-textobjects`.

goto_node select last character when in operator-pending mode

---

queries/ecma/injections.scm

injects HTML into `el.innerHTML = '<html>'` etc

feat(ecma): add innerHTML/outerHTML injection

---

lua/nvim-treesitter/parsers.lua

The filetype for the `eex` is actually called `eelixir`.

fix(eex): map eelixir filetype to the eex parser

---

queries/comment/highlights.scm

Using a non-english spellings language spell checks TODO, WARNING, XXX, and others. This removes the spellcheck for those 'tags'. It also seems irrelevant to spellcheck usernames.

comment(highlights): add @nospell to tags and user mentions

---

lockfile.json
queries/prql/highlights.scm

`literal_string` is now a public node, thus `@string` matches now directly instead on `literal`
* added multiple builtin functions

feat(prql): update queries

---

queries/python/highlights.scm

Added new keywords "is not" and "not in" to support common python coding conventions.
Before change:
"not in" and "is not" are not recognized by Treesitter 
After change:

Update highlights.scm for Python

---

queries/v/highlights.scm
queries/v/injections.scm

Inject regex for the methods in the vlib module re:
- [re.regex_base](https://modules.vlang.io/regex.html#regex_base)
- [re.regex_opt](https://modules.vlang.io/regex.html#regex_opt)
- [re.RE.compile_opt](https://modules.vlang.io/regex.html#RE.compile_opt)
Some notes:
- It only checks if the name (field of the call expression) is one of regex_base, regex_opt and compile_opt, which I think will be enough of a check, because these are fairly unusual names. But I could also check if the module name is re.
- Pattern has to be of node type raw_string_literal (thus an r'' string), but could also include 'normal' strings if wanted
- Noticed raw strings were not highlighted, so also added the highlight for them.
- Are there formatters available for the scheme files? I'm not sure how to format them …

v: inject regex for some methods in `re` module

---

queries/go/indents.scm
tests/indent/go/switch.go

The type switch construct emits a `type_case` node rather than an `expression_case`, so we need to explicitly ident on it.

fix(go): Indent on type switch case properly

---

queries/ecma/highlights.scm
tests/query/highlights/ecma/const.js

Fixes #4434
I also changed the const identifier to allow single letter const identifiers as well

fix(ecma): properly capture constants in const declarations

---

queries/sql/highlights.scm

* added missing keywords
* moved some instructional keywords to the group `@attribute` e.g.:
* `collate`, `concurrently` or `engine`
There are some statements, which can definitely improved for example:
```sql
alter table my_table
modify column if exists val6 int;
select
max(c) over (partition by a,b
order by a asc nulls first
rows between 3 preceding
and 3 following exclude current row)
from
tab;
```
Here, some lines are just `@keywords` with no distinction.
@DerekStride can you take a look?

highlights(sql): add missing keywords

---

queries/html_tags/injections.scm
tests/query/injections/html/test-html-injections.html
tests/query/injections/vue/test-vue-injections.vue

- This partially reverts the queries added in #4073 
- Add tests for expected behavior
The intention for the queries were: Only if `lang` and `type` is not an attribute, then inject css/js. At the time, I did not understand `any-of?` so they were faulty.
For the reasonings of not noticing this, it was that I didn't code in Vue for the past 2 months (lol)
Revert back to regex-based matching to ensure correct behavior

fix(html): fix faulty css/js injections

---

queries/java/indents.scm
tests/indent/java/constructor_with_arguments_on_multiple_lines.java
tests/indent/java/method_with_arguments_on_multiple_lines.java
tests/indent/java_spec.lua

Fixes #4448 
Both `(constructor_declaration)` and `(constructor_body)` are marked for indent, but it looks like we only need to indent one of them.
NOTE: Java indent tests are not passing for this PR. When I run `./scripts/run_tests.sh indent/java_spec.lua`, I get a failure for the "whole file" test.
```
Fail	||	indent Java: whole file: ./constructor_with_arguments_on_multiple_lines.java
./tests/indent/common.lua:80: Incorrect indentation
Found:                                       Expected:
|public class Testo {                        |public class Testo {
|  public Testo(                             |  public Testo(
|    String a                                |    String a
|  ) {                                       |  ) {
2 vs 0 => |  }                                         |} …
```

fix: Java indent for multiple line arguments

---

queries/vue/indents.scm

"</" was previously used as a workaround to pass tests, but doesn't really work well in actual usage
"</" usage was also replicating usage for JSX template fragment, but in actuality it should be similar to normal HTML elements instead of that
Changing dedent logic to `(end_tag)` instead of relying on anchors
@amaanq have a look

indents(vue): Update dedent logic for <template>

---

queries/ecma/highlights.scm

This partially reverts commit c553e6c5608ba54e210e9131bf9ba5e36ef18e57.
Closes #4466
I was a bit naive in understanding how js consts work (I only use it for writing tree-sitter grammars..oops)

Partially Revert "fix(ecma): properly capture constants in const declarations"

---

queries/cmake/highlights.scm

highlights(cmake): match digits in unquoted arguments

---

queries/ecma/injections.scm

Also add a comment what the query does.
Before:
After:

Fix injection based on "call_expression" for "ecma"

---

README.md

I noticed that the `README` generally uses the short `:h` command, but one line uses the expanded `:help` command. This pull request makes the shorter style consistent throughout.

docs: consistent `:h` in README

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/mlir/highlights.scm
queries/mlir/locals.scm

The parser is currently in development, and 60-80% of MLIR files in the test suite of MLIR, within the Arith, SCF, Tensor, and Linalg dialects parse successfully.

parsers: add tree-sitter-mlir parser

---

lua/nvim-treesitter/shell_command_selectors.lua

Fixes nvim installation on vim configuration that use powershell.
Fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/3316 
Maybe fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/1965
There's a similar pull request here https://github.com/nvim-treesitter/nvim-treesitter/pull/4365 but [has potential problems](https://github.com/nvim-treesitter/nvim-treesitter/pull/4365#issuecomment-1445416964)

fix(windows): fix invalid powershell separator during install

---

queries/python/indents.scm
tests/indent/python/return_dedent.py
tests/indent/python_spec.lua

`return ...` is usually the last line of a
function/statement, so mark some possible patterns of `return` with
`@indent_end` to dedent the line after it
@amaanq should this be added?

feat(python): add "return" @indent_end

---

lockfile.json
lua/nvim-treesitter/parsers.lua

As of https://github.com/derekstride/tree-sitter-sql/pull/100 we're publishing the `parser.c` source code artifact on the `gh-pages` branch, which should make it easier to install.
I tried running `scripts/update-lockfile.sh sql` to bump the lockfile to use the revision on the new branch but that didn't seem to work. I'd commit the new revision manually but I'm concerned it's an issue with the script. I'll investigate.

Use pre-generated parser files for sql grammar

---

queries/cpp/highlights.scm

fix(cpp): nullptr should be `@constant.builtin`

---

queries/ecma/injections.scm

The change in https://github.com/nvim-treesitter/nvim-treesitter/commit/e3ebc8ec5d586162f3c408417621daa59ba8ea62 broke lit-html highlighting. 
Here is the new, broken injection:
Here it is with the parens, which causes a runtime error
I'd now need to wrap the template literal in parens, which is not the same kind of function call, as demonstrated in this screenshot:
This also assigns the HTML parser for SVG tagged literals, since svg uses the HTML parser
```js
svg`<svg>...</svg>`
```

fix(ecma): template literal injections

---

queries/html_tags/injections.scm

Injects regexp grammar into `<input pattern="...">`
Replaces regex part of #2577
Closes #2569

injections(html): input regex patterns

---

queries/lua/highlights.scm

Before:
After:
The label identifier should be `@label`, the double colons `@punctuation.delimiter`

fix(lua): properly highlight labels

---

queries/lua/highlights.scm

Up for debate, especially the metamethods. I'm thinking a new group like `@function.special` for those in Lua and Python

queries(lua): add more keywords related to variable/function builtins, debug, and coroutines

---

queries/comment/highlights.scm

This prevents it from overwriting luadoc (or other) highlights.

comment(highlights): reduce user mention priority

---

lua/nvim-treesitter/query_predicates.lua
queries/html_tags/injections.scm
tests/query/injections/ecma/ecma-test-injections.js
tests/query/injections/html/test-html-injections.html

Replaces the `<script type>` parts from #2577 
<details><summary>test file</summary>
```html
<script>
html`<p></p>`
html(`<p></p>`)
svg`<p></p>`
svg(`<p></p>`)
</script>
<script type="module">
html`<p></p>`
html(`<p></p>`)
svg`<p></p>`
svg(`<p></p>`)
</script>
<input pattern="[0-9]+">
<input pattern=[0-9]+ type="tel">
<script type="application/json">{ "true": false }</script>
<script type="importmap">{ "true": false }</script>
<script type="text/markdown">## Hello *World*!</script>
<script type="application/graphql">query OK { dokey }</script>
<script type="javascript">function foo () {}</script>
<script type="module">function foo() {}</script>
<script type="application/ecmascript">function foo() {}</script>
<script type="text/ecmascript">function foo() {}</script>
<script …
```

injections(html): various <script type>

---

queries/python/highlights.scm

Pretty self-explanatory from the title.
Before change: 
After change:

fix(python): add object as `@type.builtin`

---

lua/nvim-treesitter/parsers.lua

This PR extends highlighting for V files to file types set to `vlang`.
Currently, highlighting requires `ft=v`. However, until the recent merge to also include `ft=v` in nvim-lspconfig, `vls` required `ft=vlang`, which will disable tree-sitter highlighting for V. 
Since the recommendations to set the file type for V are just becoming more consistent and both are valid, this PR makes it work interchangeably.

fix(v): add `vlang` as filetype

---

queries/typescript/highlights.scm

The problem is methods in declarations, class fields, and interface fields were being higlighted as fields no matter what. For declarations and classes, this was a simple fix as seen in the changes to highlights.scm
For interfaces, this is a bit tricky as we can have a union type be a function or undefined, see the following example:
```ts
interface ScriptInvocationListenerCallbacks {
/**
* Called synchronously when a thread is about to enter the target function.
*/
onEnter?: ((this: InvocationContext, args: InvocationArguments) => void) | undefined;
/**
* Called synchronously when a thread is about to leave the target function.
*/
onLeave?: ((this: InvocationContext, retval: InvocationReturnValue) => void) | undefined;
}
```
onEnter is a maybe undefined/null type, with the non-null type …

feat(typescript): add various missing function/method captures

---

README.md
lua/nvim-treesitter/health.lua

Minimim required version has been bumped to 0.8.0+ since https://github.com/nvim-treesitter/nvim-treesitter/pull/3656

fix(health): check required neovim version

---

lua/nvim-treesitter/compat.lua
lua/nvim-treesitter/locals.lua
queries/lua/injections.scm

This PR adds more shims in the `nvim-treesitter.compat` module and reroutes every
occurrence of the old function calls to the new ones, to comply with the
breaking neovim/neovim@cbbf8bd.
I have made this pull request to quickly solve deprecation messages for those on
neovim nightly, such as in nvim-treesitter/playground#120.

fix: `get_range` shim for playground

---

lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/install.lua

The get_ensure_installed_parsers function return a table for the option "all" because uninstall accepts a table
This PR fix an error when trying to delete all parsers.
```
E5108: Error executing lua vim/shared.lua:0: t: expected table, got string
stack traceback:
[C]: in function 'error'
vim/shared.lua: in function 'validate'
vim/shared.lua: in function 'tbl_contains'
...cker/opt/nvim-treesitter/lua/nvim-treesitter/install.lua:492: in function 'uninstall'
...cker/opt/nvim-treesitter/lua/nvim-treesitter/install.lua:482: in function 'run'
[string ":lua"]:1: in main chunk
```

fix: uninstall function in the install.lua

---

nvim-treesitter-scm-1.rockspec

The `doc` folder should be copied, so documentation can be accessed when installing through luarocks.

fix(rockspec): add doc folder to rockspec

---

lockfile.json
queries/cpp/highlights.scm
queries/cpp/locals.scm

Most recent parser version [0b6d0eb9abdf7cea31961cd903eeed5bbd0aae74](https://github.com/tree-sitter/tree-sitter-cpp/commit/0b6d0eb9abdf7cea31961cd903eeed5bbd0aae74) improves the node tree related to namespaces. This deprecates the need for extra rules to try to get @namespace applied to the right nodes.
also, `namespace_identifier` can't name a constant since it only names things guaranteed to be namespaces, or type/enums when in a qualified identifier as part of scope resolution.

feat(cpp): simplify namespace query rules now that parser is a bit more consistent

---

queries/ruby/highlights.scm

These highlight queries caused some odd highlighting for me when I have nested modules inside of a conditional:
In the above screenshot I do not expect the `::` between constants to be red, but they're getting the `@conditional.ruby` highlight.
The `(then)` node in `(if (then))` is actually the entire block guarded by the conditional, not just the "then" keyword, which I think was the intended target of these queries.

fix(ruby): @conditional highlights

---

queries/scala/locals.scm

I noticed that some locals definitions were missing for scala language. This PR adds `block` scope and `class` level parameters.

fix(scala): Add missing locals definitions for scala

---

lua/nvim-treesitter/shell_command_selectors.lua

This will make the parsers align more closely to the ones bundled with
Neovim, because CMake uses the `-bundle` flag (instead of `-shared`) on
macOS when a library is compiled as a `MODULE`.
See, for example: https://github.com/neovim/neovim/blob/10baf89712724b4b95f7c641f2012f051737003c/cmake.deps/cmake/TreesitterParserCMakeLists.txt#L6-L9
Additional context available at https://github.com/neovim/neovim/issues/21749#issuecomment-1418427487.

feat: use `-bundle` to build parsers on macOS

---

CONTRIBUTING.md

This just adds a small note in the CONTRIBUTING section about local
queries and how they differ from those listed upstream.

docs: add a small note about local queries

---

lockfile.json
queries/kotlin/locals.scm

Update `queries/kotlin/locals.scm` to use the the newly exposed `function_value_parameters` node.

Update parser: kotlin

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua

The current vimscript parser has not been maintained for a while, which was a blocker for packaging the coming Neovim release. It was therefore forked to https://github.com/neovim/tree-sitter-vim/ and will be maintained there going forward.
Right now, only some already reviewed PRs were merged and a bit of general cleanup was performed, but we might consider replacing the parser implementation completely if a better one comes along. (The point is to have a stable and maintained URL for Neovim's bundled vimscript parser, just like for the vimdoc parser.)

vim: switch to parser maintained by Neovim

---

queries/html_tags/injections.scm

Use equivalent pattern to `match? (a|b)` using lua-match instead.

refactor(html_inject): Use lua-match instead of match

---

lua/nvim-treesitter/indent.lua
tests/indent/algorithm/trailing.py
tests/indent/algorithm/trailing_whitespace.html
tests/indent/algorithm_spec.lua

Before this change, the case below was very frequently happening 
- If a trailing whitespace exist, the whitespace will be the position to find the ending smallest range for a node, which means it goes over the node that should have been captured
- If a trailing comment exist, it will be captured, and next line indent will follow indent laws of that comment parser.
Indent algorithm was not ignoring trailing whitespaces and comments, hence we need to trim+ignore the node
With this PR, it makes sure that trailing whitespaces/comments will not be accounted in the indentation calculation of the next line
Examples:
- Notes: `<SP>` is whitespace, while `<CR>` is Enter, and `|` to denote the cursor position after pressing enter
```c
int main(){
for (x = 1; x <= 10; x++) {
}<SP><CR>
|
}
```
- The …

fix(indent): Make indent ignore trailing spaces/comment

---

queries/rust/highlights.scm

<details>
<summary>outdated</summary>
fix(rust): don't highlight scoped constant as @type
* This rule is redundant because the `@type` rule at line 8 already does the job and is not overriden by other rule.
* This rule falsely overrides the rule for `@constant`, which resulted in CONSTANT_ITEM in Self::CONSTANT_ITEM being highlighted as `@type`.
</details>

 fix(rust): highlight SNAKE_CASE scoped identifier name as @constant 

---

queries/dart/indents.scm
tests/indent/dart/try.dart
tests/indent/dart_spec.lua

```dart
void test() {
try {
| <--- cursor is here
} catch(e) {}
}
```
```dart
void test() {
try {
| <--- cursor is here
} catch(e) {}
}
```

fix(dart): try statement wouldn't indent

---

queries/html_tags/injections.scm

Cleanup and change `#match?` to `#lua-match?` for what was missed in #4625

refactor(html_inject): lua-match for <script>

---

queries/dart/indents.scm
tests/indent/dart/switch.dart
tests/indent/dart_spec.lua

~~Closes~~ Workaround for #4639 
This breaks `=` motion (it wasn't working before, or after this change, but this PR will make it look out of place)
@RobertBrunhage have a test

fix(dart_indent): Fix dart case/default indent

---

queries/php/injections.scm

Resolves #2565
PHP's HTML injection were missing `@combined`, as were specified from upstream queries at https://github.com/tree-sitter/tree-sitter-php/blob/master/queries/injections.scm

fix(php_inject): add missing @combined to text

---

queries/cpp/highlights.scm
tests/query/highlights/cpp/static-namespace-functions.cpp

Recent commit added support for distinguishing function.call but only supported up to 3 levels of nesting and each were hard coded.
This adds a query that uses `has-ancestor` to support any qualified function call if it detects a nesting level greater than 3 for namespace/type qualifiers.

feat(cpp): improve function.call to support any level of nesting for qualified identifiers

---

queries/ruby/highlights.scm

Right now symbol is placed in the same category as heredoc which is not quite right. I as a user expect to see array of symbols highlighted in the same color as `simple_symbol`
|before|after|
|------|-----|
|<img width="600" alt="Screenshot 2023-04-16 at 9 03 43 PM" src="https://user-images.githubusercontent.com/20648459/232332637-421ac1f6-bd6f-49bb-b60a-79172cad9aea.png">|<img width="600" alt="Screenshot 2023-04-16 at 9 06 25 PM" src="https://user-images.githubusercontent.com/20648459/232332737-252c1641-ec51-4525-bc99-10c530a7f22c.png">|
more examples
I don't see that Ruby has any tests right now but if I need to add smth let me know, appreciate any help on this
P.S.
here is an example from tree-sitter-ruby repo
https://github.com/tree-sitter/tree-sitter-ruby/blob/master/queries/highlight …

fix(ruby): bare_symbol should be `@symbol`

---

lua/nvim-treesitter/query_predicates.lua
queries/markdown/injections.scm

Closes #2131  
This PR, in the same vein as #4522, hard codes configuration for certain language aliases, namely `sh => bash`, `js => javascript` and `ts => typescript`
before:
after:

feat(markdown): configured aliases for fenced code block languages

---

README.md
lua/nvim-treesitter/parsers.lua

the parser is installed (via ":TSInstall") using the name "git_config" so this might save someone 5 seconds

Update README.md to reflect name of git_config parser

---

queries/c/highlights.scm

Motivation - function pointers in struct fields
Before:
After:

feat(c): highlight parenthesized function pointer decl identifiers as `@function`

---

lua/nvim-treesitter/shell_command_selectors.lua

Hi, I found there is an error when I update nvim-treesitter from lazy.nvim, after updated and re-open nvim, I get the following error.
[![asciicast](https://asciinema.org/a/D5eyrVYvfrlNlrOtFu9uSWbQx.svg)](https://asciinema.org/a/D5eyrVYvfrlNlrOtFu9uSWbQx)
It seems that the new compiled `parser.so` can't be move to target directory because it exists, to avoid the error, I have to remove target directory manually, and re-open nvim again..
So I'd like to propose a `-f` argument to "mv" command to avoid such issue.  I've confirmed that `-f` flag exists on Linux, MacOS, and Nushell

add `-f` argument to "mv" command to avoid updating error

---

queries/scala/locals.scm

`@scope` included `function_declaration` while is should have included `function_definition` instead. The former one is used to declare abstract functions while the latter one is used to define functions together with their bodies.

fix: Correct scope definition for scala

---

queries/python/highlights.scm

fix(python): fields should not match uppercase-beginning names

---

queries/query/indents.scm

```scheme
[
...
]
```
now should become
```scheme
[
...
]
```

fix: query missing dedent for "]"

---

queries/html/injections.scm

Too niche, maybe?
I put this in html instead of `html_tags` as there can definitely be some cases where people name their components `py-script`, but this can't happen in html.
Infos are from
- https://docs.pyscript.net/latest/tutorials/index.html
- https://github.com/pyscript/pyscript/

feat: add py-script injections for html

---

queries/go/highlights.scm

Priority is to beat the lsp, removed _ as that's not a constant but more a discard, could be `@comment` like Gleam but `@constant` is just wrong

feat(go): highlight constructors

---

queries/c_sharp/highlights.scm

The `?` is highlighted `@operator` and the `:` is highlighted as `@punctuation.delimiter`. The `@conditional.ternary` group exists for this purpose, so it seems right.
Let me know if anything needs to be changed, or feel free to close if it isn't appropriate

ref(c_sharp): highlight ternary operators as `@conditional.ternary`

---

queries/c_sharp/highlights.scm

This allows `x > 4` to show `>` as `@operator`, whereas it is currently `@punctuation.bracket`
Let me know if anything needs to be changed, or feel free to close if it isn't appropriate

ref(c_sharp): highlight `<`, `>` as bracket only in type param list

---

queries/rust/highlights.scm

E.g. `dbg!` and `debug_assert!`
They are currently just highlighted as `@macro`, which is accurate, but there is a dedicated capture for debug keywords so it seems right.
The order of `assert` and `debug` can be swapped if it's desired to let `debug_assert` show as `@exception`
Let me know if anything needs to be changed, or feel free to close if it isn't appropriate

ref(rust): highlight debug macros as `@debug`

---

queries/java/highlights.scm

It is currently highlighted as `@operator`
Let me know if anything needs to be changed, or feel free to close if it isn't appropriate

ref(java): highlight `Foo<Bar>` as `@punctuation.delimiter`

---

tests/indent/dart/try.dart
tests/indent/dart_spec.lua

Addresses #4632
Closing brace of incomplete `try` will be correctly indented. Content of incomplete `try` block will still not be indented correctly.

indents(dart): add test for #4632

---

lockfile.json
queries/sql/highlights.scm

Upstream, we have refactored the `count` node. Since this is also just a normal invocation, we removed this node. Here, we just update the hightlighting of `count`

highlights(sql): refactor `count` to generic `invocation`

---

queries/query/highlights.scm

`:h treesitter-query-modeline` reads:
```vimdoc
Note: These modeline comments must be at the top of the query, but can be
repeated, for example, the following two modeline blocks are both valid:
>query
;; inherits: foo,bar
;; extends
;; extends
;;
;; inherits: baz
<
```
This PR just allows multiple comments to start the block.

fix(query): allow multiline modeline (inherits/extends)

---

queries/cpp/highlights.scm

Template argument lists were already matched this way but not template
parameter lists.  Some people have custom highlighting for @operator and
the current bracket matching for templates is inconsistent.  This diff
below attempts to fix this.

Add bracket matching for template parameter list

---

queries/go/highlights.scm

- added missing [operators](https://go.dev/ref/spec#Operators_and_punctuation)
- added [iota](https://go.dev/ref/spec#Predeclared_identifiers) constant
- added comparable
- edited go keyword type

highlights(go): add some highlights

---

queries/sql/indents.scm
tests/indent/sql/case.sql
tests/indent/sql/compound.sql
tests/indent/sql/create.sql
tests/indent/sql/cte.sql
tests/indent/sql/insert.sql
tests/indent/sql/select.sql
tests/indent/sql/subquery.sql
tests/indent/sql_spec.lua

As mentioned in #4852 I want to add indentation rules for SQL. 
Some of them are not working as intended and I don't know why. I have added test cases, but I also don't know how to run the tests locally and how the spec file should be written. Here is the indented SQL file for all the test cases with comments what is currently working/not working:
```SQL
-- first term in select_expression is not indented
select
a,
b
from tab;
-- closing bracket of cte is not dedented
with data as (
select
a,
b
from tab
)
select * from data;
-- this works!
create table my_table (
id bigint,
date date
);
-- case when then end works
-- issue is again the first term
-- of the select_expression
select
case
when a = 1 then '1'
when a = 2 then '2'
when a = 3 then '3'
else '0'
end as stmt1
from tab;
-- this may …
```

indents(sql): initial support

---

queries/markdown/indents.scm

Should resolve #2178
`indents.scm` only works if there's an `indents.scm` file, and because the root node doesn't have it, there was no root tree, leading to treesitter indents not working, which is the cause of the issue

feat: markdown indents

---

queries/go/highlights.scm

The next Version of Go (1.21) introduces a new built-in function `clear`: https://github.com/golang/go/blob/8c445b7c9fe6738cbef2040a1011bd11489b0806/src/builtin/builtin.go#L230-L237. 
So, this PR just registers `clear` as a new built-in function.

go: register `clear` as a new builtin function

---

queries/clojure/highlights.scm

Instead of relying on regex for matching (which matches custom symbols), explicitly list each of the variations in `@variable.builtin, `@conditional`, `@function.macro`.
Add `@variable.builtin` for the builtin repl variables `*1`, `*2`, `*3`, and `*e`, which are occasionally used in tests and comments.
Move `ex-info`, `ex-cause`, `ex-data`, and `ex-message` to `@functions.builtin`.
Add missing `clojure.core` functions to `@functions.builtin` at the bottom to minimize diff. Includes functions from 1.12-alpha2 release as well.

Update Clojure queries

---

queries/bash/highlights.scm

"select" is an opening keyword for select statements which are characterized as "for_statement" nodes per the bash language grammar. This adds the corresponding highlight for it under the @repeat group

Bash: add "select" highlighting

---

runtime/queries/latex/injections.scm

Following a recent [pull request](https://github.com/latex-lsp/tree-sitter-latex/pull/89) to [the latex parser](https://github.com/latex-lsp/tree-sitter-latex/) treating environments defined by the `sagetex` latex package as "special". This pull request to `nvim-treesitter` is to enable Python language injections in these environments as they contain SageMath code (very similar to python, but there is no SageMath tree-sitter grammar available).
```latex
\documentclass{article}
\usepackage{sagetex}
\begin{document}
\begin{sagesilent}
print("Hello, SageTeX!")
\end{sagesilent}
\begin{sageblock}
print("Hello, SageTeX!")
\end{sageblock}
\end{document}
```

Add extra language injections for latex

---

queries/scala/highlights.scm

This accounts for the updates in https://github.com/tree-sitter/tree-sitter-scala/pull/273.

highlights(scala): add support for using directives

---

runtime/queries/query/injections.scm

injections(query): add `#gsub!` pattern

---

queries/typescript/highlights.scm

| ![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/4299733/e8a4ae15-9d21-448a-871a-dbe79fa4c6f6) | ![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/4299733/ebd30e78-b13d-4b38-8322-1bcdc6902add) |

highlights(typescript): `is` and `:` in type predicate

---

queries/ecma/highlights.scm
queries/typescript/highlights.scm
tests/query/highlights/typescript/as.ts

This is a follow-up for #4835.

highlights(ecma): convert eligible `@keyword.operator`s

---

queries/t32/indents.scm
queries/tiger/indents.scm
scripts/minimal_init.lua
tests/indent/t32_spec.lua
tests/indent/tiger_spec.lua
tests/indent/wgsl_spec.lua

Similar to #4900 but for master, testing to see why something works/not work
These filetypes were not recognized, so the tests were always marked with `XFAIL`, because they never run.
Therefore, Removing XFAIL for most of the tests, alongside adding ft to these unrecognized extensions

tests: fix failed tests

---

queries/bash/highlights.scm

Adds "until" highlighting as it is a keyword for while loops per the bash grammar https://github.com/tree-sitter/tree-sitter-bash/pull/168

bash: add "until" highlighting

---

queries/lua/highlights.scm

Make functions higlight a bit nicer. These will now be highlighted as function:
```lua
local func_one = function() end
--    ^
local tbl = {
func_one = function() end,
--  ^
}
```
---
On related note:
I just realized I can't test highlights in https://github.com/MunifTanjim/tree-sitter-lua using `tree-sitter test`, because upstream `tree-sitter` treats highlight queries differently than Neovim. Is there any plan to unify that?

feat(lua): update highlights query for functions

---

queries/scala/highlights.scm

This accounts for a correction in interpolations and also adding support for `self_type`.
This is a follow-up to #4920.

feat(scala): sync highlights with latest upstream

---

queries/commonlisp/highlights.scm

Before, those symbols were available via https://github.com/theHamsta/nvim-treesitter-commonlisp. Since then `#any-of?` has become more efficient via tables and clojure also added all builtin functions (https://github.com/theHamsta/nvim-treesitter/blob/72cbda75a901bf14a2eb98a47584fe5fc32689ab/queries/clojure/highlights.scm#L169-L278).
The list I'm adding is defined by the 1994 ANSI standard that has not changed since. This is why I don't expect any changes or maintenance burden due to adding that list.
Fixes https://github.com/theHamsta/tree-sitter-commonlisp/issues/18

highlights(commonlisp): include all symbols defined by the ANSI standard

---

queries/bash/highlights.scm

I noticed that many shell builtins were missing in the highlights, so I added them.
Moreover:
* added `break` and `continue` as conditionals because it just makes sense
* added `let` and moved `set` and `return` to keywords since they are more akin to things like `declare`, `local` and `unset` which were already there

feat(bash): add various shell builtins

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/matlab/folds.scm
queries/matlab/highlights.scm
queries/matlab/indents.scm
queries/matlab/locals.scm

I wrote a MATLAB parser which has more features than the current one:
- It detects commands. The code
```matlab
variable P(1, 2, 3) semidefinte
```
returns a `function_call` token with 2 `argument` tokens, which is how matlab sees it. I use a scanner to correctly detect the line, so it won't mix it with a function call followed by a identifier.
- It detects string escapes and formatting. This returns a string with two tokens inside, differentiating escape sequences from formatting options. Unfortunately there is an issue with tree-sitter that prevents me from doing it with single-quoted string at the moment, but it works fine with double-quoted ones.
```matlab
"Format: \t %2.3f"
```
- It detects line continuations, lambdas, parfor statement, arguments statements (a kind of MATLAB block), …

feat(matlab)!: replace parser

---

queries/sql/highlights.scm

Fixes the query order in SQL highlighting introduced due to changes in #4979

fix(sql): fix highlights order for `invocation`

---

lockfile.json
queries/sql/highlights.scm

Refactored `group_concat` upstream in https://github.com/DerekStride/tree-sitter-sql/pull/163

highlights(sql): remove `keyword_group_concat` after refactor

---

lockfile.json

e9984bb appears to have forgotten to update `lockfile.json`, causing `:TSUpdate haskell_persistent` to always update.

fix(haskell_persistent): add to lockfile.json

---

queries/awk/highlights.scm

Using `@constant.builtin` to differentiate [auto-set](https://www.gnu.org/software/gawk/manual/html_node/Auto_002dset.html) from [user-modified](https://www.gnu.org/software/gawk/manual/html_node/User_002dmodified.html) variables even though they're not (all) constants.

feat(awk): highlight builtin variables & shebang

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/pem/folds.scm
queries/pem/highlights.scm
queries/pem/injections.scm

Should we highlight labels recognised by [OpenSSL](https://github.com/openssl/openssl/blob/master/include/openssl/pem.h#L35-L60) as `@label.builtin` or nah?

feat(pem): add parser

---

queries/fish/indents.scm

Previously, "end" and "case" were not captured, leading to ending a line with such keyword makes the next line to continue the indentation.
Closes #5026.
@lewisacidic Can you have a test to see if this is the desired behavior

indents(fish): Add "end" and "case"

---

lua/nvim-treesitter/query_predicates.lua

`trim!` was upstreamed. Adding `force = true` to skim error

fix: Add `force` to all custom predicates/directives

---

queries/html_tags/highlights.scm

Removes expensive regex `#match?`; make similar distinction as for Markdown

fix(html): distinguish <hX> levels

---

lockfile.json
queries/sql/highlights.scm

Companion update to https://github.com/DerekStride/tree-sitter-sql/pull/179
We now enforce that all `keyword_` named nodes are referenced in the `highlights.scm` file. This PR updates the list for nvim-treesitter to include the nodes that were missing. There are also a few duplicates that got removed / updated.

Update parsers: sql (incl highlights)

---

queries/nix/highlights.scm

A Nix expression like
```nix
builtins.readFile ~/testing
```
parses to
```text
expression: apply_expression [0, 0] - [0, 27]
function: select_expression [0, 0] - [0, 17]
expression: variable_expression [0, 0] - [0, 8]
name: identifier [0, 0] - [0, 8]
attrpath: attrpath [0, 9] - [0, 17]
attr: identifier [0, 9] - [0, 17]
argument: hpath_expression [0, 18] - [0, 27]
path_fragment [0, 18] - [0, 27]
```
The relative path `~/testing` is captured by [`hpath_expression`](https://github.com/nix-community/tree-sitter-nix/blob/02878b40ac77d2889833519c6b6e9e63cfc690e6/src/grammar.json#L84-L122) which is currently not highlighted properly (it should be highlighted the same as `path_expression` or `spath_expression`).

highlights(nix): add hpath_expression

---

lockfile.json
queries/groovy/highlights.scm

Multiline comment support for Groovy. See https://github.com/Decodetalkers/tree-sitter-groovy/pull/2 for details.

feat(groovy): Update highlights from upstream. Groovydoc multiline comment support.

---

queries/ecma/highlights.scm
queries/pug/highlights.scm

The parser is still missing a couple of constructs and breaks often so it will remain experimental.
---
Also added "self" highlighting to ecma both for [pug](https://pugjs.org/api/reference.html#options) and [service workers](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/self).

feat(pug): improve syntax highlighting

---

queries/ecma/highlights.scm

I don't know if the flag should be highlighted the same as the regex, but it does look weird without any highlight at all.

fix(ecma): Highlight regex flags

---

.github/workflows/lint.yml
.github/workflows/update-lockfile.yml
.github/workflows/update-readme.yml

`create-pull-request@v4` has deprecation warnings

ci: bump actions to latest

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/hurl/folds.scm
queries/hurl/highlights.scm
queries/hurl/indents.scm
queries/hurl/injections.scm
scripts/minimal_init.lua

Adds support for the hurl file extension. Hurl is a command-line rest api runner/testing engine. 
Note: .hurl files are not currently detected by vim/neovim. I have opened a PR to vim for hurl file type detection https://github.com/vim/vim/pull/12631
Grammar: https://github.com/pfeiferj/tree-sitter-hurl/
Hurl file format: https://hurl.dev/docs/hurl-file.html

feat(hurl): add hurl support

---

queries/julia/highlights.scm
queries/julia/injections.scm

`string_literal` before a short function definition should be docstring:
```
In [1]: begin
"""
foo()
This is a docstring before short function definition.
"""
foo() = nothing
end
Out[1]: foo
help?> foo
search: foo ...
foo()
This is a docstring before short function definition.
```

feat(julia): highlight docstrings before short function definitions

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/robot/highlights.scm

Added a parser and syntax highlighting for Robot Framework files.
The parser seems to be very basic, but sufficient, as it was added to Helix not so long ago [here](https://github.com/helix-editor/helix/pull/6611).
Let me know if anything else is needed.

feat: Add Robot Framework parser and highlights

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/promql/highlights.scm
queries/promql/injections.scm
queries/yaml/injections.scm
tests/query/injections/yaml/promql-on-prometheus-rules.yaml

This is an effort so we can get promql highlighted in prometheus rule manifests:

feat(promql,yaml): add parser and yaml injections

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/systemtap/folds.scm
queries/systemtap/highlights.scm
queries/systemtap/injections.scm
queries/systemtap/locals.scm

[SystemTap] is a Red Hat-driven Linux instrumentation framework that’s been around since 2005. It exposes a scripting language inspired by C and awk. I’ve written a complete [grammar] and have shown up to contribute nvim-treesitter queries.
Here’s the highlights query in action on some of my code:
There’s very little SystemTap in the wild, so I would consider this PR to be a relatively low priority.
Your feedback is greatly appreciated, even if this PR doesn’t succeed. Thank you for your work on nvim-treesitter!
[grammar]: https://github.com/ok-ryoko/tree-sitter-systemtap
[SystemTap]: https://sourceware.org/systemtap/

feat: add SystemTap

---

queries/yaml/injections.scm

This PR adds a missing `?` to `#eq` predicate in `promql` injection into `yaml`.
Appeared after b64ea2ec444c27efd8d3bd2377a8b24589954363

fix(yaml): typo in promql injection

---

queries/julia/highlights.scm

Update the `@symbol` capture to enable highlighting symbols and variables differently.
See https://github.com/tree-sitter/tree-sitter-julia/issues/110

fix(julia): symbol highlighting

---

queries/comment/highlights.scm

`PERF` and `TEST` can be found as defaults for example in https://github.com/folke/todo-comments.nvim
all new tags are also common, for example as conventional commit keywords

feat: add some common comment tags

---

lockfile.json
queries/wgsl_bevy/highlights.scm

Bevy has switched to https://github.com/bevyengine/naga_oil which allows new syntax constructs.

highlights(wgsl_bevy): add support for naga_oil features

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/scfg/highlights.scm
queries/scfg/injections.scm

This introduces a new parser for scfg. The highlights.scm file was copied from the repository for tree-sitter-scfg (and I have retained the license accordingly).
I don't think that there is a mechanism to copy the scm files from the parser repository itself, but that would be ideal in this case, especially since upstream targets neovim in this particular case.
Cc: @rockorager

scfg: new parser

---

lockfile.json
queries/promql/highlights.scm

The removed tokens are now case insensitive via an ugly regular expression; we cannot use them in captures here anymore.

fix(promql): bump parser, fix queries

---

queries/c/injections.scm

`#define FOO BAR` does not need an injection

fix(c): only inject in preproc function calls/definitions

---

lua/nvim-treesitter/health.lua

**Before:**
```
The following errors have been detected in query files: ~
- ERROR cpp(queries): 
```
**After:**
```
The following errors have been detected in query files: ~
- ERROR cpp(queries): dependency c missing
```

fix(health): show error information

---

lua/nvim-treesitter/parsers.lua
queries/t32/highlights.scm
queries/t32/locals.scm
scripts/check-queries.lua
tests/indent/t32/if_block.cmm
tests/indent/t32/repeat_block.cmm
tests/indent/t32/subroutine_block.cmm
tests/indent/t32/while_block.cmm
tests/indent/t32_spec.lua
tests/query/highlights/t32/comments.cmm
tests/query/highlights/t32/keywords.cmm
tests/query/highlights/t32/literals.cmm
tests/query/highlights/t32/var.cmm

Version 2.1 of the grammar has improved support for commands with HLL (high-level language, think C or C++) expressions. This change should update the existing queries accordingly.
Even though the syntax for HLL expressions is very close to C, it is, from my point of view, not really possible to add the support via language injection. The two main problems are that in contrast to C
- whitespaces or the lack thereof matters in weird ways, and that
- there are syntax extensions on top, like a slice operator for arrays (e.g. `Var.DRAW flags[0..16]`) or HLL variables that can be defined on the fly (e.g. `Var.set \x=func3(5,3)`).
That's why I tried to extract the relevant parts from tree-sitter-c, but keep most of the node definitions consistent.

feat(t32): Add query support for extended HLL expression support

---

lua/nvim-treesitter/parsers.lua

The grammar is approaching feature completeness, so I expect to have fewer breaking changes in the future. `nvim-treesitter` could follow the latest version of the grammar.

refactor(t32): remove revision pinning

---

CONTRIBUTING.md
queries/bash/highlights.scm

- Document that only certain kinds of strings are spell checked, and
reasons why they may not.
- Remove spell checking for bash strings.

fix(spell): do not spell check certain types of strings

---

.luarc.json

See https://github.com/neovim/neovim/pull/24592

feat: add .luarcjson

---

queries/go/highlights.scm

The next version of Go (1.21) introduces new builtin functions: `max` and `min`:
https://github.com/golang/go/blob/a031f4ef83/src/builtin/builtin.go#L211-L221

go: register `max` and `min` as new builtin functions

---

lua/nvim-treesitter/parsers.lua

This is a follow-up for https://github.com/nvim-treesitter/nvim-treesitter/pull/4990 that I opened at about the same time as [PR for Vim](https://github.com/vim/vim/pull/12573) to recognize the filetype for the persistent library.
The recognition is now merged, but with another filetype name. I am grateful to Bram for taking time to explain why the filetype should not have a dot.

fix: rename filetype for haskell persistent to match vim name

---

tests/indent/cpp_spec.lua
tests/indent/javascript_spec.lua
tests/indent/jsx_spec.lua

It is not a recognized filetype in Neovim, so adding/fixing the test case to the original author's desired intention

tests: fix tests on main

---

.github/workflows/release.yml

sry for that but picking up the old PR, I forgot to remove some cruft as mentioned by @mrcjkb see https://github.com/nvim-treesitter/nvim-treesitter/pull/4403#pullrequestreview-1575769713 .
Seems like I've lost the ability to set LUAROCKS_API_KEY (but I should have already added one) and tag a release so once this is merged, it would be nice if an admin could tag a release to make sure this works and the rockspec is properly uploaded to luarocks.org

ci: dont hardcode the rockspec version

---

lockfile.json
queries/arduino/injections.scm
queries/c/highlights.scm
queries/c/injections.scm
queries/cpp/injections.scm
queries/cuda/injections.scm
queries/glsl/injections.scm
queries/hlsl/injections.scm

```c
int foo(bar, baz, qux)
int bar, baz;
char *qux;
{
}
```
Is now supported
Well an issue might be that C++ just doesn't support this at all..

feat(c): update parser, add K&R-style function parameter support

---

lockfile.json
queries/python/highlights.scm
queries/starlark/highlights.scm

Never noticed this was bugged until Starlark failed, both are fixed upstream

fix(python,starlark): update parsers & add escape_interpolation

---

queries/c_sharp/highlights.scm

I noticed Null Coalescing operator (`??`) is not highlighted, so I searched the c# tree-sitter grammar and found out that their [highlights file](https://github.com/tree-sitter/tree-sitter-c-sharp/blob/master/queries/highlights.scm) already had the `??` and `??=` operator, `alias` and `when` keyword.
Added:
* `??` and `??=` as operators
* `alias` as keyword
* `when` as conditional
I don't know if this was the correct move. Please let me know if I made some kind of mistake, or if I missed something.
<details>
<summary>
Before/After
</summary>
**Before**
**After**
</details>

feat(c_sharp): Add missing highlights

---

README.md
lockfile.json
queries/robot/folds.scm
queries/robot/highlights.scm
queries/robot/indents.scm

I have completed and polished the tree-sitter parser for Robot files. This PR:
- Updates tree-sitter-robot to the latest ref
- Removes "experimental" and sets me as maintainer
- Improves syntax highlighting
- Adds queries for indents and folds

Update tree-sitter-robot version and maintainer

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/gpg/highlights.scm
queries/gpg/injections.scm

Currently only supports `gpg.conf`, but so does Vim.
I might eventually extend it for the other gpg config files (e.g. `gpg-agent.conf`).

feat: add gpg config parser

---

queries/lua/injections.scm
tests/query/highlights/lua/test.lua

This fixes a problem similar to #5244, but for lua.
In the following code, the injection of `luap` causes errors outside of the string because the string content node has children that are not being parsed in the injection (in this case, the `escape_sequence` node).
```lua
--- this isn't a lua pattern
string.match("123", "\0%d+")
```
To solve this, `(#set! injection.include-children)` was added to the captures.
Also, I made the captrues slightly more specific. If something is wrong with this logic, it can be reverted.

fix(lua): luap injection

---

queries/java/highlights.scm

Introduced in tree-sitter/tree-sitter-java#157
`@punctuation.bracket` might not be the most fitting for this

feat(java): add highlights to string interpolation

---

queries/swift/highlights.scm

- Add hl to “mutating” modifier
- Add hl to property access
- Add hl to argument name
- Add hl to context aware method call
I noticed that the bang operator (`!`) is not being highlighted but if I add `(bang) @operator` it works, I guess this is a parser thing (?). Should I add this highlight?
<details>
<summary>Before/After</summary>
**Before:**
**After:**
</details>

feat(swift): improve highlights

---

queries/lua/injections.scm

Fixes #5294, #5291.
This partially reverts #5263.
The root issue is fixed with neovim 0.9.2 (neovim/neovim#24595). But the current stable version is neovim 0.9.1, so partially reverts the commit to make it compatible with the current stable version.
Todo: Reapply #5263 once 0.9.2 becomes the stable version

fix(lua): use include-children instead

---

queries/clojure/highlights.scm
queries/dhall/highlights.scm
queries/glsl/highlights.scm
queries/latex/highlights.scm
queries/query/injections.scm
queries/ruby/highlights.scm
queries/tlaplus/locals.scm

Also, Ruby currently highlights all `(constant)` nodes as `@type`.
I made it default to `@constant` and have `@type` *not* match `^[A-Z0-9_]+$`.

refactor: replace some match & vim-match usages

---

lockfile.json
queries/doxygen/highlights.scm
queries/doxygen/injections.scm

I added codeblocks, mind trying it out for any suspicious crashes @ObserverOfTime 
I think C's identifiers having a priority of 95 is a slight nuisance though

feat(doxygen): update parser and queries

---

lua/nvim-treesitter/indent.lua
tests/query/highlights_spec.lua
tests/query/injection_spec.lua

- I've been using it for the past week and have yet to see downsides of it, under the scenario that treesitter highlights will carry the parsing the rest of the tree

fix!: use win line range to re parse indents

---

queries/julia/highlights.scm

At present, the `end` is defined as `@keyword` globally, causing every instance of `end` to be recognized as a keyword, even in cases where it should not serve as one, as in `if foo; end`. In such cases, `end` should be categorized as `@conditional`.
Upon reviewing the `grammar.js` file of `tree-sitter-julia`, I noticed that the `end` keyword is never used in isolation, except within the keyword list. Furthermore, this keyword list is solely employed in the definition of the `quote_expression`, where keywords should be treated as regular identifiers. Based on this analysis, I have removed `macro`, `struct`, and `end` from the global `@keyword` and now match them within their specific scopes.
Here is a comparison between the highlight before this change (left) and after this change …

fix(julia): highlight for `end` keyword

---

lua/nvim-treesitter/install.lua
lua/nvim-treesitter/parsers.lua

Haven't put much thought into the API for this, but I need this so I can do:
```lua
local c_info = require "nvim-treesitter.parsers".configs.c.install_info
c_info.url = 'https://github.com/neovim/tree-sitter-c'
c_info.revision = 'nvimc'
```

feat: allow a custom revision in install_info

---

queries/html/injections.scm
queries/html_tags/injections.scm
queries/lua/injections.scm
queries/markdown_inline/injections.scm
queries/svelte/injections.scm
queries/vue/injections.scm

As the injection range issue has been resolved, there isn't any reason to keep the workarounds anymore
I will do some extra experiment with markdown later, as that's the final `include-children` that we still have

refactor: remove `include-children` from queries

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/snakemake/folds.scm
queries/snakemake/highlights.scm
queries/snakemake/injections.scm
queries/snakemake/locals.scm

Hi!
Snakemake is a workflow management system based on Python: https://snakemake.readthedocs.io/en/stable/
The grammar can be found here, but it is not complete: https://snakemake.readthedocs.io/en/stable/snakefiles/writing_snakefiles.html#grammar
I took a stab at implementing a parser for it based on the Python parser because I wanted consistent highlighting between Python and snakemake: https://github.com/osthomas/tree-sitter-snakemake
I've been using it for a bit and would be happy to see it included in nvim-treesitter.

feat: add snakemake

---

queries/t32/indents.scm
tests/indent/t32/if_block.cmm
tests/indent/t32_spec.lua

In the latest version of the grammar, handling of consecutive line breaks has changed. Tests inserting single lines will now fail (after next parser update). I am not quite sure why this is happening.
The updated queries are a bit simpler than before and seem to do the job.

fix(t32): update indent queries & test

---

queries/markdown/highlights.scm
queries/markdown_inline/highlights.scm

Porting the queries that will be included in https://github.com/neovim/neovim/pull/25073.

feat(markdown): conceal triple backticks and HTML entities

---

lua/nvim-treesitter/parsers.lua

Scala parser is now capable of parsing sbt files. The sbt filetype is also added in the `package.json` - https://github.com/tree-sitter/tree-sitter-scala/blob/master/package.json#L29

Use scala parser for sbt filetype

---

queries/nix/injections.scm

continuation of #3902 since https://github.com/neovim/neovim/pull/21548 is in stable
requires https://github.com/neovim/neovim/pull/23015 to work correctly since `#gsub!` is bugged in neovim 0.9.0
this allows doing things like this to highlight code blocks of arbitrary languages with comments
```nix
/* lua */ ''
print("Hello, world")
''
```

injections(nix): dynamic language injection via comments

---

queries/haskell/highlights.scm
tests/query/highlights/haskell/test.hs

This is a follow-up to #5466.
Things done:
- Move `(variable) @variable` and `(pat_wildcard) @variable` to the top so they don't override `@parameter`.
- Refine infix-based `@function.call` queries.
- Remove queries for higher order function parameters (they don't scale well - this would be better left up to haskell-language-server when/if semantic highlighting is implemented).
- Merge separate queries for `(variable)` and `(qualified_variable (variable))` -> `[(variable) (qualified_variable (variable))]`
- Add more `@parameter` cases
- Add more `@field` queries
I'll leave this as draft while I dogfeed it.

fix(haskell): highlight fixes

---

queries/java/highlights.scm

The pattern before does not occur if it's in import, leading to incorrect coloring
| - | - |
| ![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/29790821/fe2059e4-7e10-4907-9240-5f54d066fa39)| ![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/29790821/4a504ea2-9ac7-47c4-be6c-5d8c9f717e40)|

java(highlights): add missing import highlights

---

queries/hurl/injections.scm

hurl injection currently throws an error of `No handler for inject-language` this fixes the injection to match new injection syntax. I pulled from the markdown injection as my example

fix(injections): fix injection for hurl for new injection syntax

---

queries/java/highlights.scm

Nothing much to say about this rather than 'var' ~~is a keyword~~ is highlighted as keyword in Intellij and should be treated as such for highlighting.

feat: (java) Add "var" as part of keyword

---

queries/php/highlights.scm

[`never` type](https://www.php.net/manual/en/language.types.never.php) is not highlighted. The parser, [tree-sitter-php](https://github.com/tree-sitter/tree-sitter-php), can parse it as `bottom_type` node, but there is no highlight for it.
Highlight `bottom_type` node as `@type.builtin`.

fix(php): highlight `never` as `@type.builtin`

---

queries/typescript/highlights.scm

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined

fix(typescript): do not highlight undefined as variable

---

queries/haskell/highlights.scm
tests/query/highlights/haskell/test.hs

- Consider functions with only one value on the rhs as variables
- Applied composition: `(f . g) <param>` -> `@function.call`
- View patterns
- `@field` in record update expression
- type_tuple and type_list as variables
- quantifier for `exp_apply (<rhs>)+ (variable)`
- type_tuple and type_list as variables
- Treat signatures with only one value on the rhs as variables (except for `IO a`) -> Fixes #5505.
- Remove redundant anchors from signature function queries.
- Move signature function queries to give them higher priority
- Scoped function types
- Add signature query to function with parameters query

feat(haskell): highlights improvements

---

queries/scala/locals.scm

When you have a lambda expression like:
```scala
val fruits = List("apple", "banana", "avocado", "papaya")
val countsToFruits = fruits.groupBy(fruit => fruit.count(_ == 'a'))
for ((count, fruits) <- countsToFruits) {
println(s"with (fruits) 'a' × $count = $fruits")
}
```
The `fruit => fruit.count(_ == 'a')` lambda expression (note: without wrapping parenthesis) does not create a `(binding)` node. Its syntax tree is:
```
(lambda_expression) ; [5:18 - 47]
parameters: (identifier) ; [5:18 - 22]
(call_expression) ; [5:27 - 47]
function: (field_expression) ; [5:27 - 37]
value: (identifier) ; [5:27 - 31]
field: (identifier) ; [5:33 - 37]
arguments: (arguments) ; [5:38 - 47]
(infix_expression) ; [5:39 - 46]
left: (wildcard) ; [5:39 - 39]
operator: (operator_identifier) ; [5:41 - 42]
right: …
```

fix(scala): Mark `(lambda_expression)` without bindings as `@defintition.parameters`

---

queries/markdown/highlights.scm

fix(markdown): give code blocks higher priority than block quotes

---

queries/php/indents.scm
tests/indent/php/issue-3591.php
tests/indent/php_spec.lua

This is an improvement fix on top of the #3591 so indentation also works properly in cases like:
```php
<?php
function test() {
$array = [|] // insert new line in between braces
}
```

fix(php): fix indentation for in between braces

---

queries/elixir/highlights.scm

Elixir does not require parenthesis after the function name for a valid function definition.

fix(elixir): highlight functions without parenthesis

---

queries/scala/locals.scm

Prior to this change, a defined function was not seen as being in scope for the parent scope. This mirrors a similar change done to a number of other languages (python, javascript, etc).

fix(scala): Ensure (function_definition) is in parent scope

---

queries/scala/locals.scm

This change does two main things:
1. Indicate that `(for_expression)`'s introduce a `@scope` (this is the scope for the enumerators to be used within the loop).
2. Indicate that the `(identifiers)` within the `(enumerators)` are `@definition.var`s.
---
For the following example snippet:
```scala
val fruits = List("apple", "banana", "avocado", "papaya")
val countsToFruits = fruits.groupBy(fruit => fruit.count(_ == 'a'))
for ((count, fruits) <- countsToFruits) {
println(s"with (fruits) 'a' × $count = $fruits")
}
```
The `count` and `fruits` identifiers are new definitions introduced by the `for` expressions scope.

fix(scala): Add (for_expression) locals

---

lua/nvim-treesitter/parsers.lua

APKBUILDs are technically shell scripts, so this highlighting fits perfectly. `filetype=apkbuild` is commonly used because bash-related tools (e.g.: language servers) provide bogus results for it, and dedicated linting tools (e.g.: ale+apkbuild_lint) expect this filetype.

Highlight APKBUILD files as bash scripts

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/perl/folds.scm
queries/perl/highlights.scm
queries/perl/injections.scm
queries/pod/highlights.scm

This replaces the perl parser from ganezdragon with an actively maintained + considerably
more correct version. There are some features that we're still working on, but by and
large this has already proven very useful for me in my day to day.
One of the things that we support is coloring scalars, arrays and hashes differently. Is
there a way to expose that in a simple way to users? We're doing it by making a
`@variable.scalar`, `@variable.array` and `@variable.hash`.

feat(perl)!: replace parser

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/objdump/highlights.scm
queries/objdump/injections.scm

[tree-sitter-objdump](https://github.com/ColinKennedy/tree-sitter-objdump) parses [objdump](https://man7.org/linux/man-pages/man1/objdump.1.html) disassembly so users can quickly and easily parse / highlight / query the objdump text separately from the raw, generated Assembly code.
I've got some unittests / highlight tests which I can copy over to here if the maintainers are interested. The setup for running tests in nvim-treesitter changed I think since the last time I contributed a language though so if I could be directed to any documentation on how to run it now, that'd be helpful.
In a future PR, hopefully to github.com/vim/vim, I'd like to recognize .objdump / .cppobjdump etc files but I'll omit that from this PR since I hear maintainers prefer to receive those changes as …

Added objdump to the supported languages

---

lockfile.json
queries/leo/highlights.scm

- make sure affine_group has priority, so parens and comma will not be miscolored; added `annotation` as `@attribute`
- `then` is not used as conditional, so moved to keywords
- finalize function highlight added
- differentiate between constant and variable variable identifiers

fix(leo): minor coloring fixes constant highlight, finalize function highlights, affine_group highlights

---

queries/lua/highlights.scm

Highlights the `...` parameter in Lua as a builtin parameter, similar to [other languages](https://github.com/search?q=repo%3Anvim-treesitter%2Fnvim-treesitter%20parameter.builtin&type=code).
Example:
```lua
local function test(...)
print(...)
end
```
In this case both instances of `...` would be highlighted.

feat(lua): highlight variadic expressions as builtin parameters

---

queries/julia/indents.scm

Hi!
This second PR fixes two remaining problems with the Julia indentation (sorry, I decided to break up into two PR instead of making every change in one).
The first is the indentation of the curly expressions. Currently, the code:
```julia
function teste(
a::Union{
Number,
String
},
)
return a
end
```
is indent to:
```julia
function teste(
a::Union{
Number,
String
},
)
return a
end
```
After the PR, the original version is not changed after the indentation.
The second problem was related to the cursor position when we have `)`, `]`, `}` as the only character in a line. When a new line is entered, the indentation is wrongly increased. For example, if the cursor is here:
```julia
function teste()
a = [
1,
2,
]|
end
```
it goes to this scenario after a new line:
```julia
function teste()
a …
```

Fix indent. of curly expressions and of ],} in BOL

---

queries/query/highlights.scm

Without this any word starting with "extends" was highlighted as `@preproc`.

fix(query): stricter match for `extends` directive

---

queries/rnoweb/highlights.scm

Add an empty highlights query to rnoweb. Without the empty query, the highlighting for injected languages is disabled.

rnoweb: add highlights query

---

queries/vue/injections.scm
tests/query/injections/vue/test-vue-injections.vue

Interpolations (`{{valid js code}}`) and directive attributes (`<element :directive="valid js code"`) can also be typescript code, hence we can inject typescript instead of javascript here and still ok with highlights (bar some changes between ts and js)

injections(vue): inject typescript instead of js

---

queries/kotlin/highlights.scm

Built-in variables, jumps, and type arguments.
Replaces #5527 (CC @anthony-S93)

fix(kotlin): improve highlights

---

queries/html_tags/highlights.scm
queries/htmldjango/highlights.scm

Instead of increasing all the priorities, I opted for reducing the string priority in html_tags instead.
This shouldn't cause an issue in html and it might even help other template languages as well.

fix(htmldjango): improve highlights

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/wing/folds.scm
queries/wing/highlights.scm
tests/query/highlights/wing/class.w

- Fixing the grammar/queries in response to https://github.com/nvim-treesitter/nvim-treesitter/pull/5663#issuecomment-1807149869
- See error https://github.com/nvim-treesitter/nvim-treesitter/actions/runs/6846542305/job/18613312866#step:10:1227
- Additional fresh breaking change addressed here in tests/query/highlights/wing/class.w where the `init` keyword was changed to `new`
- Adds @MarkMcCulloh (me) as a maintainer, I am also a maintainer of https://github.com/winglang/wing

fix(wing): update parser and update test/queries for breaking changes, add maintainer

---

queries/markdown/highlights.scm

Adds conceals for Markdown bullets and block quotes. Preview:
**KNOWN LIMITATION:** When using a bullet with an immediate indented code block, e.g.:
```md
-     print('code here')
```
the conceals will display this as:
```md
- print('code here')
```
As far as I know there is no (easy?) way to fix this, as (unlike with the block quote markers) the bullet point capture fills whitespace until the first non-whitespace content is reached. However I think little to no users will be affected by this, and even so, indented blocks still display all preceding whitespace on a new line in a bullet. E.g.:
```md
- This works
print('code here')
```

feat(markdown): conceals for bullets, block quotes

---

queries/lua/folds.scm

Allows folding of the following
```lua
function(
lots_of_parameters,
lots_of_parameters,
lots_of_parameters,
lots_of_parameters
)
print('function')
end
print(
'lots of arguments',
'lots of arguments',
'lots of arguments',
'lots of arguments',
'lots of arguments'
)
```

feat(lua): folds for parameter, argument lists

---

queries/python/highlights.scm
queries/python/injections.scm

This PR removes the requirement that injected regex for Python must be a raw (`r'.*'`) string. For example, the following code is still valid, even though the first string is a regular Python string and not a raw one:
```python
txt = 'The rain in Spain'
x = re.search('^The.*Spain$', txt)
```
It also highlights this string as `@string.regex` for canonical purposes.

feat(python): `@string.regex` capture, injection improvements

---

queries/css/highlights.scm

Moves `and`, `or`, `not`, and `only` from `@operator` to `@keyword.operator`

fix(css): tweak operator keyword highlights

---

queries/twig/injections.scm

As it is in https://github.com/gbprod/tree-sitter-twig/blob/main/queries/injections.scm
What changes for the user?
instead of
I didn't realise this was fixed after reading some issues in gbprod/tree-sitter-twig. Until I compared the injections.scm in both repositories and seeing a similar update was made for PHP which had the same issue.

twig queries: add combined injections by default

---

queries/astro/highlights.scm

Adds custom `@type` captures for custom components ala JSX to Astro's highlights.
Closes https://github.com/virchau13/tree-sitter-astro/issues/17.

astro: add custom component highlighting

---

queries/cpp/highlights.scm

This PR fixes #5731 by removing the `@field` highlight group for identifiers that start with `_`. Identifiers that start with `m_` will still be given the `@field` highlight.

fix(cpp): remove `@field` for identifiers with `_` prefix (#5731)

---

Makefile
contrib/nvim-treesitter-luarocks.template

CC @teto @vhyrro 
This fixes two issues with the rockspec and rockspec template (for luarocks packaging).
The current makefile installs *all runtime directories* - the `lua/` directory to the `share/lua/<lua-version>/` directory.
This PR corrects it, so that only the `lua` directory contents are installed to `share/lua/<lua-version>/` (by the `Makefile`) , and the runtime paths are installed to the appropriate place in `lib/luarocks/rocks-<lua-version>/<package-name>/<package-version>/` (specified by the `copy_directories` table in the rockspec).
This is in line with how luarocks would package a plugin with the `builtin` build type (which we don't use here because of test files containing deliberate syntax errors).
I have modified to rockspec template (used by the `luarocks-tag-release` …

fix(luarocks): proper library and runtime path packaging

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/rbs/folds.scm
queries/rbs/highlights.scm
queries/rbs/indents.scm
queries/rbs/injections.scm

I would like to add rbs (Ruby type signature) parser support.
I see that there was a pull request in the past to support rbs, but it wasn't merged.
Sorry, this pull request is for a different implementation by myself.

feat: add rbs parser support

---

queries/java/highlights.scm

Otherwise, attributes like `@GET` get highlighted as constants.

fix(java): move attributes after constants

---

queries/gitcommit/highlights.scm

After introducing a new token in gitcommit tree-sitter grammar, I think we should add a highlight group.
Ref: https://github.com/gbprod/tree-sitter-gitcommit/pull/48

feat(gitcommit): add highlight group for subject_prefix

---

queries/vim/highlights.scm

Should also be upstreamed to neovim & tree-sitter-vim.

fix(vim): highlight 'scriptencoding' command

---

queries/python/highlights.scm

The `args` / `**kwargs` in `lambda *args, **kwargs: ...`

fix(python): highlight variadic lambda parameters

---

queries/rust/highlights.scm

Matches inline attribute highlights (e.g. `#![crate_name = "rust"]`) to the regular attribute highlights. Preview (with semantic highlights disabled):
Before:
After:

fix(rust): highlight inline attributes properly

---

lua/nvim-treesitter/indent.lua

fix: remove 0-length range usage in indent.lua

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/ecma/injections.scm
queries/styled/folds.scm
queries/styled/highlights.scm
queries/styled/indents.scm
queries/styled/injections.scm

I created a parser for styled-components or other CSS-in-JS languages to highlight CSS within `styled.div` type expressions.

feat: add tree-sitter-styled

---

queries/haskell/highlights.scm

See [`Control.Monad.Fail`](https://hackage.haskell.org/package/base-4.19.0.0/docs/Control-Monad-Fail.html).

highlights(haskell): add `fail` to exception highlights

---

queries/latex/highlights.scm

In TeX files, enabling the spell checker results in label definitions and references being flagged as spelling errors. These labels often contain things like abbreviations and should not be flagged as spelling errors. See the screenshot below. This pull request fixes this phenomenon by adding @nospell annotations to the highlights.scm file corresponding to LaTeX.

fix(latex): add `@nospell` to labels

---

queries/cpp/indents.scm
tests/indent/cpp/class_newline.cpp

Removed `@indent.begin` from `(class_specifier)`, otherwise it indents as:
```cpp
class Foo
{
int x;
class Bar {
int y;
};
Bar z;
};
```
Added a test for this.
I also removed  `@indent.begin`  from `(condition_clause)` as I couldn't find why this is there. No tests fail due to removing it and I tried some variants of `if (x) ...` and indenting still seems to work correctly, so maybe this was some legacy code that is no longer needed due to changes in `c/indents.scm`?

fix(cpp): incorrect indent of class with opening { on new line

---

queries/julia/highlights.scm

In Julia when piping into a function the function should be highlighted as a function call, and not a variable.
This change adds `@function.call` to any identifier that are piped into by matching the operator in a binary_expression against the string "|>". It also annotates the operator with `@pipe`, as a side-effect.

fix(julia): pipe function highlight

---

queries/luap/highlights.scm
queries/regex/highlights.scm

This PR adds some highlights similar to #5698 to be a bit more consistent. It also adds logic to make sure that any instances of `.` that are to be matched as a literal full stop will be highlighted as `@constant`, as other characters in a set should be.
Before:
After:

feat(luap): highlights more consistent with regex

---

queries/lua/highlights.scm
queries/lua/injections.scm
queries/luau/highlights.scm
queries/luau/injections.scm
queries/query/highlights.scm

Applies `@string.regex` highlights to places where `luap` is injected. Also applies it where `regex` is injected in `query` files.
**NOTE:** For the query used in the `query` files, I didn't have any success using the `#offset!` directive for some reason (maybe due to https://github.com/neovim/neovim/issues/23664? I really have no clue), even though it seemed to be working in the `injections` file... hence the hacky workaround by highlighting the actual `"` nodes

feat: more `@string.regex` highlights

---

runtime/queries/rust/indents.scm

@clason 
Not really a regression, but an oversight that was not caught

fix(rust): Add back 1 indent for macro rules

---

queries/julia/highlights.scm

If writing a selected import, e.g. `using BSON: @load`, the colon isn't currently captured. This change captures it as `@punctuation.delimiter`.

fix(julia): add missing capture of ":" in selected import

---

queries/latex/highlights.scm

Right now, basically every function of the form, e.g., `\funcname`, is highlighted as `@function`, except for `\text`, because it is not technically parsed as a `(command_name)`. This PR makes it so that `\text`, too, is highlighted as a `@function`.

fix(latex): highlight text functions

---

queries/markdown_inline/injections.scm

Fix https://github.com/nvim-treesitter/nvim-treesitter/issues/5397 
The `injection.include-children` is needed in markdown_inline parser.
See https://github.com/MDeiml/tree-sitter-markdown/issues/117#issuecomment-1793717965 , it is neccessary to pass the `$` delimiter to latex parser to let the latex parser know the content is a math content.

fix(markdown_inline): latex highlight injection (#5397)

---

queries/html/highlights.scm

HTML entities, e.g. `&nbsp;`, are detected by the HTML parser, but not currently highlighted. It's not totally clear to me what highlight group they should get – I can see an argument for `@string.escape`, `@escape`, `@character.special`, `@constant`, the list goes on – and I'm open to input on that, but they should get _something_.

Highlight HTML character references (a.k.a. entities)

---

queries/c_sharp/highlights.scm

fix(c_sharp): link type in pattern matching correctly

---

lua/nvim-treesitter/configs.lua

Problem: Nvim-treesitter ships with queries that may be incompatible with parsers bundled by Neovim and used by default (in particular `vimdoc`, whence the recent flood of issues).
Solution: Force installation of bundled parsers that may be used by Neovim.
This is a bandaid fix to tide us over until 1.0, which addresses this issue more cleanly.

fix(config)!: always install parsers bundled with nvim

---

queries/html_tags/injections.scm

Allows TODO comments and comment URIs, etc. to be recognized by comments in html, markdown, etc.

feat(html): inject comment

---

queries/markdown/highlights.scm

With #5895, `@none` is the new `@text`. This is great but if none is to be highlighted as text was, probably as a generic foreground color, then it will remove highlighting from code fence blocks which have a none capture for some reason. This PR removes it.

fix(markdown): remove @none from code fences

---

queries/rust/folds.scm
queries/rust/indents.scm

The rust indents commit from `main` duplicated the `indent.end` queries as well. This also remove that

Backport rust changes from `main`

---

queries/markdown_inline/highlights.scm

Right now the conceal code is overriding the `@markup.link.url` highlight for link URIs with `@markup.link`. This PR applies the more specific, non-conceal queries _after_ the conceal ones so they are given higher precedence.
**NOTE:** This is not necessary right now for the link label query, but I moved them both so they are near each other still.

fix(markdown_inline): prioritize link URI

---

queries/git_config/folds.scm

Defines folds for sections of `.gitconfig` files, like the following:
```.gitconfig
[core]
editor = nvim
pager = delta
[credential]
helper = libsecret
[delta]
navigate = true
syntax-theme = Dracula
side-by-side = false
line-numbers = true
```

feat: folds for git config files

---

CONTRIBUTING.md
queries/comment/highlights.scm
queries/gitcommit/highlights.scm
queries/vimdoc/highlights.scm

Distinguishing `hint` and `info` is too confusing; it's enough to have `error`, `warning`, `todo`, and `note`.
Alternative to #5929 
(@ribru17 thanks for pointing this out!)

fix(comments)!: consolidate note captures

---

CONTRIBUTING.md

I would like to take this opportunity for improving the capture documentation (which will be upstreamed). Suggestions welcome.

docs(contributing): typos and examples

---

queries/wgsl_bevy/highlights.scm

Old version of `format-queries` incorrectly took away a space, creating a wrong capture.
This is a fixup for that.

fix(wgsl_bevy): Correct formatter mistake

---

lua/nvim-treesitter/locals.lua

Bad indexing is leading to no results using the `get_definitions`, `get_scopes` and `get_references` API.
related commit: https://github.com/nvim-treesitter/nvim-treesitter/pull/5895/commits/d1b59d4e28406bcc77c04d4dbaced4447227fc1e
related downstream issue: https://github.com/nvim-telescope/telescope.nvim/issues/2883

fix(locals): index matches with split capture names

---

queries/rust/injections.scm

tree-sitter-rust and helix both have `injection.include-children` for the pattern in this PR. So it's best to changed to match the intended results
Fix #5958. 
Tested with the source code:
```rust
fn main() {
println!("ok");
println!("{}", returns_string_hello());
}
```
| Before:
```
(function_item ; [1:1 - 4:1]
name: (identifier) ; [1:4 - 7]
parameters: (parameters) ; [1:8 - 9]
body: (block ; [1:11 - 4:1]
(expression_statement ; [2:3 - 17]
(macro_invocation ; [2:3 - 16]
macro: (identifier) ; [2:3 - 9]
(token_tree ; [2:11 - 16]
(ERROR ; [2:11 - 16]
(unit_expression)) ; [2:11 - 16]
(string_literal)))) ; [2:12 - 15]
(expression_statement ; [3:3 - 41]
(macro_invocation ; [3:3 - 40]
macro: (identifier) ; [3:3 - 9]
(token_tree ; [3:11 - 40]
(expression_statement ; [3:11 - 40]
(unit_expression …
```

fix(rust): Follow upstream injections

---

lockfile.json
queries/devicetree/highlights.scm

Bumps devicetree parser to 0.9. Related to https://github.com/nvim-treesitter/nvim-treesitter/pull/5959#issuecomment-1905410470.
@lucario387 is this what you meant or something else breaks?

Update parsers: devicetree

---

queries/python/highlights.scm

fixes this case:
```python
class Foo:
_bar: int
```

chore(python): update member lua pattern

---

queries/latex/highlights.scm

Better precedence for highlighting environments (supporting different nesting levels), and operator highlights for super- and subscripts. Some examples below.
Before:
After:
A lot of the changes are simply from query reordering which applies highlights with different precedence. Other than that, this PR makes it so all nodes (not just `text`) in a math environment are highlighted as such, and the aforementioned operator highlights.

feat(latex): more comprehensive highlights

---

queries/vim/highlights.scm

Incidentally, I found an issue in the parser. :thinking: 
The `<CR>` in `<Cmd>...<CR>` is parsed as `(command_argument)`, leaving a `MISSING` `(keycode)` node in the tree.
```vim
nnoremap <C-q> <Cmd>quit<CR>
```
```clojure
(script_file [0, 0] - [1, 0]
(map_statement [0, 0] - [0, 28]
lhs: (map_side [0, 9] - [0, 14]
(keycode [0, 9] - [0, 14]))
rhs: (map_side [0, 15] - [0, 28]
(keycode [0, 15] - [0, 20])
(unknown_builtin_statement [0, 20] - [0, 28]
(unknown_command_name [0, 20] - [0, 24])
(arguments [0, 24] - [0, 28]
(command_argument [0, 24] - [0, 28])))
(keycode [0, 28] - [0, 28]))))
test.vim        0 ms    (MISSING keycode [0, 28] - [0, 28])
```

feat(vim): highlight keycodes

---

queries/bash/highlights.scm

In this shell snippet, it would be helpful for the `.y` parts to be a different color than the `foo` variable to clarify that the variable name is not `foo.y`. Only the second line `$foo.y` was originally misleading, but I edited the third line too for consistency. I think it's most correct to highlight as `@string`. The 5th line is a bit of an outlier because it's still highlighted as `@parameter`, which seems fine.
Before:
After:
With `nvim --clean foo.sh` (no treesitter, for reference):

feat(bash) Highlight concatenated words as strings

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/disassembly/highlights.scm
queries/disassembly/injections.scm

A couple months ago I made added tree-sitter-objdump (https://github.com/nvim-treesitter/nvim-treesitter/pull/5548). One oversight of that repository is that you cannot parse just disassembly on its own, nor memory dumps. So I pulled that portion out and made a separate parser for it.Thanks @amaanq for bringing that to my attention.
Since then, I've started adding a disassembly view to nvim-dap-ui which is working really well. You can see a demo of the parser in action, here. 
https://github.com/nvim-treesitter/nvim-treesitter/assets/10103049/52a66458-ae0c-4f68-81d0-f1fbed43252b
And adding this parser should pave the way for viewing raw memory with nvim-dap-ui, too. I also took a different approach for parsing disassembly in tree-sitter-disassembly than I had in tree-sitter-objdump so it …

Add tree-sitter-disassembly

---

queries/jsx/highlights.scm

This PR changes the uppercase JSX tag highlights from `@constructor` to `@tag`. There was discussion about this before and it was decided to keep it this way so that they were differentiated from builtin tags, but now we have `@tag.builtin` so I figured this would be OK. This PR changes existing highlights of `@tag` to the builtin variant, so users and colorscheme authors can still have proper differentiation. Using constructor is especially annoying for colorschemes like [onedark](https://github.com/navarasu/onedark.nvim) that use bolded constructors or other styles that cascade through just color highlights.

fix(jsx): proper tag and builtin tag distinction

---

queries/dart/indents.scm

Pattern for dedenting else blocks is painfully slow (~20% of total test
time), so replace with `@indent.auto` for the whole `if_statement` for
now.

fix(dart): replace slow indent with simpler strategy

---

lua/nvim-treesitter/locals.lua

Mostly I explained everything in my issue - https://github.com/nvim-treesitter/nvim-treesitter/issues/5980. 
Should close https://github.com/nvim-treesitter/nvim-treesitter/issues/5980 if merged.
Although, I haven't put `if` for checking whether that “local” exists, I don't think we should as per other lines: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/locals.lua#L44

Fix find_usages

---

queries/python/highlights.scm

Example:
```python
#!/usr/bin/env/python
"""module docstring."""
```
Python indeed recognizes it:
```
$ python -c 'import testfile; print(testfile.__doc__)'
module docstring.
```

feat(python): allow comments before module docstring

---

queries/git_config/highlights.scm

Highlights values starting with `../` (relative to parent directory) as file paths as well

fix(git_config): highlight parent relative path

---

queries/lua/injections.scm

context - https://github.com/amaanq/tree-sitter-luadoc/issues/8#issuecomment-1911045824
I can understand this being rejected for false positives with normal comments just happening to start w/ a `|`, but I'd assume that'd be rare

fix(lua): inject luadoc into comments immediately beginning with a `|`

---

scripts/check-queries.lua

This allows contributors to run the tests on some languages only via
`./scripts/check-queries.lua foo bar baz`
Makes it more feasible to ask them for before/after timings on PRs that might have a performance impact.

feat(tests): allow check-queries to take list of parsers

---

queries/make/highlights.scm

Highlights order-only prerequisite separator pipe as `@operator`. Specified in [the manual](https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html)

fix(make): highlight order-only prerequisite pipe

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/angular/folds.scm
queries/angular/highlights.scm
queries/angular/indents.scm
queries/angular/injections.scm
queries/angular/locals.scm
queries/ecma/injections.scm
queries/html_tags/injections.scm

This PR adds a new Angular parser, which is built from scratch, extending the HTML parser so it works better with the new Angular syntax. No injections in HTML are required (only in ecma for inline templates/styles).
This PR replaces #5734
EDIT: FYI I have added in the README of [tree-sitter-angular](https://github.com/dlvandenberg/tree-sitter-angular) that filetype must be set (manually or via autocmd) in order for this parser to work.

feat(angular)!: switch to parser supporting v17

---

.github/workflows/lint.yml
.github/workflows/update-lockfile.yml
.github/workflows/update-readme.yml

This should allow automated `update-lockfile` and  `update-readme` PRs to run CI automatically (following https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens, but using the new official Github token action). 
It's possible to exempt the bot from the branch protection rule; this would allow fully automated (non-breaking) lockfile updates. In this case, the update-readme workflow could also push straight to master so we don't have to deal with the noise of a PR.

ci: use token for automated PRs

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/groovy/folds.scm
queries/groovy/highlights.scm
queries/groovy/indents.scm
queries/groovy/injections.scm
queries/groovy/locals.scm

I've been actively building a new parser for groovy because I was dissatisfied with the included one. The [README of my project](https://github.com/murtaza64/tree-sitter-groovy/blob/main/README.md) includes a screenshot showing some of the superficial improvements, but this new parser much more accurately and richly parses groovy code based on the groovy language spec, and supports features including annotations, closures, the various string types in groovy and more. It also includes a pretty extensive test suite to aid in future improvement.
I've been daily driving it for a few months now, and I work on Jenkins pipelines a lot and have been pretty happy with it.
Willing to change or add stuff if other people find issues with it. Also willing to go into more detail about the improvements, …

feat(groovy)!: switch to more complete parser

---

queries/gdscript/highlights.scm
queries/gnuplot/highlights.scm
queries/make/highlights.scm
queries/matlab/highlights.scm
scripts/format-queries.lua

Cut down on the amount of captures required for a file to support this case.
Related: https://github.com/nvim-treesitter/nvim-treesitter/pull/5594#discussion_r1467326738

fix(format): handle list with 300 nodes

---

queries/jsx/highlights.scm

Followup to tree-sitter/tree-sitter-javascript#284 now that it's merged – add highlight groups for HTML character references (entities) in JSX & TSX:

highlight(jsx,tsx): character references (a.k.a. entities)

---

queries/latex/highlights.scm
tests/query/highlights/latex/test.tex

This commit also moves things around to give text better precedence in the case of `textit` and `textbf`.
Fixes #6047 
I created a comprehensive example file to show some differences. Before:
After:
Note that this was tested in Markdown only but I did a few tests in a `.tex` file and the same results were noticed. Hopefully this fixes the last of this weirdness, but I am not certain that every edge case is caught.

fix(latex): give comments higher precedence

---

lockfile.json
queries/angular/highlights.scm

This PR updates the angular parser to the latest version and adds a highlight capture to mark the _nullish coalescing operator_ `??` as an operator.

fix(angular): nullish coalescing operator in Angular templates

---

queries/kotlin/highlights.scm
queries/kotlin/locals.scm

Fixes #5810 
The following query inside `query/kotlin/highlights.scm` leads to noticeable delay in the opening of kotlin files.
```
(class_body
(property_declaration
(variable_declaration
(simple_identifier) @property)))
```

fix(kotlin): temporary fix for treesitter bug that causes delay in file opening

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/tcl/folds.scm
queries/tcl/highlights.scm
queries/tcl/indents.scm

Taken from https://github.com/tree-sitter-grammars/tree-sitter-tcl/tree/main/queries/tcl so people _can_ install it with nvim-treesitter (if they want).
Upstream for the queries remains them, so improvements should always go there first. (I did run the formatter on them, though.)
@lewis6991

feat(tcl): add parser and queries

---

queries/readline/highlights.scm
queries/readline/indents.scm

Improves indents to if statements before the full block can be parsed (basically while typing them on the fly), also changes the version number highlight after a parser update, see [this discussion about it](https://github.com/nvim-treesitter/nvim-treesitter/pull/6058#discussion_r1483418958)

Readline fixups

---

.github/workflows/test-queries.yml
.github/workflows/tests.yml

It's convenient to not need to manually update the runner version.

ci: use `windows-latest` over `windows-2022`

---

.github/workflows/test-queries.yml
.github/workflows/tests.yml
.github/workflows/update-lockfile.yml
.github/workflows/update-readme.yml
scripts/ci-install-macos-14.sh
scripts/ci-install-ubuntu-latest.sh
scripts/ci-install-windows-2022.sh
scripts/ci-install.sh

Context variables aren't always available, so we can't rely on them for
e.g. environment variables.
Also merge all install scripts into `script/ci-install.sh`, that way it
can be called the same way regardless of system.

ci: fix invalid workflow

---

lua/nvim-treesitter/install.lua

Problem: The FileType autocmd to automatically install parsers on a new
filetype (introduced in #3130) did not have augroup. As a result, when
`ts_configs.setup{ }` is called multiple times (for some reason),
duplicated installation requests will be made.
Solution: Use augroup with `clear = true`.

fix: use augroup for auto_install autocmds

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua

The development source for `v-analyzer` has moved, therefore the PR updates it's URL.

chore(v): update repository url

---

queries/cpp/injections.scm

accidentally removed in https://github.com/nvim-treesitter/nvim-treesitter/commit/57a8acf0c4ed5e7f6dda83c3f9b073f8a99a70f9#diff-7e47e0991335c05bf503d5603c5c047b7648299bb0f6fe6d2f08230827cece77

fix(cpp): add back comment injection

---

queries/lalrpop/highlights.scm

Lalrpop support putting annotation like `#[precedence(level = "1")]`. This commit aims to highlight `precedence` with the `function.macro` highlight group, like rust does with its proc macros.

feat(lalrpop): highlight annotation macros

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/hlsplaylist/highlights.scm
queries/hlsplaylist/injections.scm

m3u or m3u8 is the format used by Apple's [HLS](https://developer.apple.com/streaming/) (HTTP live streaming).
Its document is [RFC8216](https://datatracker.ietf.org/doc/html/rfc8216#page-10).
<https://github.com/iptv-org/iptv> provide m3u source in <https://iptv-org.github.io/>.
For example, <https://iptv-org.github.io/iptv/languages/zho.m3u> is the source for Chinese IPTV's m3u.
In Apple's website, [more examples](https://developer.apple.com/documentation/http-live-streaming/creating-a-multivariant-playlist) can be found.

feat: add the hlsplaylist parser

---

lockfile.json
queries/latex/highlights.scm

Match grammar.js from commit 0d598bb95ffe3ba63403979d0d32158210974ca5 in latex-lsp/tree-sitter-latex

fix(latex): update bibstyle queries

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/muttrc/highlights.scm
queries/muttrc/injections.scm

The above is tree-sitter, the below is vim syn.

feat: add the muttrc parser

---

lua/nvim-treesitter/parsers.lua

ebuild comes from https://github.com/gentoo/gentoo-syntax which is installed by Gentoo/Linux
tutor comes from $VIMRUNTIME/syntax/tutor.vim
mysql comes from $VIMRUNTIME/syntax/mysql.vim
text comes from $VIMRUNTIME/ftplugin/text.vim
expect comes from $VIMRUNTIME/syntax/expect.vim
I am not sure should we add
brewfile => ruby, comes from https://github.com/bfontaine/Brewfile.vim
altera => tcl, comes from https://github.com/vim-scripts/altera.vim
xdc => tcl, comes from https://github.com/amal-khailtash/vim-xdc-syntax
Because they don't come from $VIMRUNTIME
or preinstalled by any GNU/Linux distributions.

feat: add some ft, lang pairs

---

plugin/query_predicates.lua

Update custom predicates and directives to handle multiple nodes per capture ID per changes upstream.
Ref: https://github.com/neovim/neovim/pull/24738

fix: update add_predicate and add_directive calls for upstream

---

queries/ecma/highlights.scm

Highlights [Javascript labels](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label), e.g. `loop1` in
```js
loop1: for (let i = 0; i < 5; i++) {
if (i === 1) {
continue loop1;
}
str = str + i;
}
```

feat(ecma): highlight label identifiers

---

queries/latex/highlights.scm

Highlights all possible functions that invoke `text_mode`, following a parser update.

feat(latex): more text func highlights

---

queries/ecma/highlights.scm

Highlights the colon following a loop label indentifier (when present). Sorry, this should've been added in #6112... lol

fix(ecma): label delimiter highlight

---

queries/bash/highlights.scm

Right now for something like `CDPATH=$HOME:.`, the `:.` will be highlighted as a string. But if the order is switched, in `CDPATH=.:$HOME`, `.:` will not be given a highlight. This PR makes it so any words in a concatenation are treated as strings. 
I'm not sure if this was done intentionally because only words next to an expansion should be considered strings, if so feel free to shoot this down.

fix(bash): unordered concatenation highlights

---

scripts/format-queries.lua

No need for assert as the use is contained within the script only.

fix(format): update scripts to support nightly

---

scripts/format-queries.lua

Once again, related: https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/523

fix(scripts): add missing \n for nested grouping

---

queries/ecma/folds.scm

Adds folds for arguments passed to functions, when there are many on multiple lines. Like:
```js
let total = sum(
123,
99,
36,
346,
100,
22,
);
```

feat(ecma): folding for function arguments

---

queries/muttrc/highlights.scm

I found almost colorscheme doesn't distinguish `@variable` and `@variable.builtin` .
So I am not sure is this PR useful.

feat: improve queries/muttrc/highlights.scm

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/fennel/folds.scm
queries/fennel/highlights.scm
queries/fennel/injections.scm
queries/fennel/locals.scm

This PR changes the [original](https://github.com/TravonteD/tree-sitter-fennel) Fennel parser to my own fork.
I simplified the grammar in order to focus on ease of querying rather than hardcoding all the forms/macros into the grammar, making it easier to add support for new Fennel versions. For a full description of the parser see [README](https://github.com/alexmozaidze/tree-sitter-fennel/blob/main/README.md).
On queries side, I made sure `highlights.scm` and `injections.scm` are working correctly; I also replicated Lua's `injections.scm` to have full parity.
However, I didn't test `locals.scm` and `folds.scm`, I tried to adapt them from their old definitions. I don't really use folds, nor do I use any plugin which uses locals, so I am unable to test them (maybe I should remove those 2 …

feat(fennel)! change parser and update queries

---

queries/phpdoc/highlights.scm

Currently, phpdoc types that are not union type are not highlighted, this change allows to apply `@type` group to all types.
Eg:
Without this change
With this change

fix(highlights): highlight @type in phpdoc

---

queries/c_sharp/highlights.scm

Highlight enum member declaration in C#:
before:
after:

feat(c-sharp): add enum member declaration highlight query

---

lockfile.json
lua/nvim-treesitter/parsers.lua

parser new version does not `requires_generate_from_grammar`

fix(fidl): remove requires_generate_from_grammar

---

queries/c/highlights.scm

Highlights for local label declarations.
Before:
After:

feat(c): local label highlights

---

CONTRIBUTING.md

- Treesitter now is neovim land :smiling_imp: so we can remove the last/first-win notes
- Add a short note on how injection queries should be written

doc: better clarification of highlights/injections

---

queries/gitcommit/highlights.scm

Highlights overflow differently per [this suggestion](https://github.com/gbprod/tree-sitter-gitcommit/pull/58#issuecomment-1970650563). This PR is in response to overflow being parsed for the git commit message body as well as the title. Here `@none` doesn't help because the commit message body already has no highlight.

feat(gitcommit): highlight overflow in commit body

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/vue/highlights.scm

The new branch is renamed to `main`; the old to `fork` but still default so previous commits of this plugin remain working. We'll switch the default (and delete the old branch) after a grace period.
@amaanq queries may need adaptation; feel free to push to this PR (and mark as breaking).

feat(vue): switch to new parser

---

CONTRIBUTING.md
queries/cpp/highlights.scm
queries/cue/locals.scm
queries/ebnf/highlights.scm
queries/firrtl/highlights.scm
queries/fsh/highlights.scm
queries/hare/locals.scm
queries/hoon/highlights.scm
queries/jsonnet/highlights.scm
queries/latex/highlights.scm
queries/linkerscript/highlights.scm
queries/markdown/highlights.scm
queries/markdown_inline/highlights.scm
queries/objc/highlights.scm
queries/perl/highlights.scm
queries/rbs/highlights.scm
queries/rst/injections.scm
queries/ruby/highlights.scm
queries/rust/highlights.scm
queries/slint/locals.scm
queries/soql/highlights.scm
queries/squirrel/highlights.scm
queries/squirrel/locals.scm
queries/strace/highlights.scm
queries/ungrammar/locals.scm
queries/vimdoc/highlights.scm
queries/xml/highlights.scm
scripts/check-queries.lua
tests/query/highlights/markdown/test.md

Problem: Allowing undocumented "secret" (sub)captures makes it harder to write comprehensive colorschemes and catch inconsistent captures.
Solution: Only allow captures listed in CONTRIBUTING.md. Add useful (cross-language) subcaptures and drop language-specific or too niche ones.
Language-specific subcaptures should instead be added in user config or a custom language plugin.
**NOTE:**
* `@markup.environment.name` ~~very LaTeX specific, but without it, environments don't make sense. So I used that for language annotations as well (did I miss one); I'll upstream that and link to `Label` by default.~~ changed to `@label`
* `@markup.environment` is correspondingly changed to `@module` (as originally suggested in the Great Renamening)
* `@keyword.type` added; see #6205 (and already used in …

feat(highlights): enforce documented captures

---

lockfile.json
queries/angular/highlights.scm

- Fixes typo in `concatination_expression` -> `concatenation_expression`

fix(angular): Fix capture name

---

queries/markdown/highlights.scm

Highlights the colon following a link label:
```md
[1]: website.com
^ here
```

feat(markdown): highlight link label delimiter

---

queries/c/injections.scm
queries/cpp/injections.scm

Add support for `///` and `//!` comments.
Closes #6276

fix(c): improve doxygen comment matching

---

queries/php_only/highlights.scm

With this change, properties that are accessed using nullsafe operator will be highlighted correctly.
After | Before

highlights(php): fix property access using nullsafe operator

---

queries/ecma/injections.scm

This adds support for `css` and `keyframes` tagged templates to support additional CSS-in-JS frameworks like Emotion.
```js
const style = css`
border: 1px solid red;
`
const animation = keyframes`
from { opacity: 0; }
to { opacity: 1; }
`
```
https://emotion.sh/docs/introduction

Add ECMA injections for additional CSS-in-JS frameworks

---

queries/markdown_inline/highlights.scm
queries/vimdoc/highlights.scm

Problem:
https://github.com/neovim/neovim/commit/cb46f6e467268edf917cc3617b4c024a66b256de#diff-edf997b0c2d42d31828800641ac1f5a46487fe24a0d46ccf70bcd58a14f3868f
introduced a regression on how `#set!` behaves with several matches in a
single pattern, breaking conceals in, e.g., taglinks.
Solution: Separate taglink etc. patterns into concealed marker and
contents. Also add URL support for concealed markdown links.

fix(vimdoc): adapt to breaking Neovim change

---

queries/rust/highlights.scm

Trying to match this to e.g. C++ `public` keyword. Also consolidates most of the captures into one set

feat(rust): move pub to `@keyword.modifier`

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/http/highlights.scm
queries/http/injections.scm

Hey, I recently updated the HTTP parser with a lot of breaking changes. This PR is intended to update the parser here so that it works correctly.
Some of the changes:
- Update `http` revision in the lockfile
- Update queries
- Remove `generate_requires_npm` field in the `install_info` table, not required anymore
I have also added myself again as one of the maintainers, I now have free time again to help with that work. I hope there is no problem with that :)
---
Supersede #6315

feat(http): switch to new parser version

---

queries/latex/folds.scm

Folds comments between `\iffalse` and `\fi`.

fix(latex): Fold \iffalse..\fi comments

---

queries/clojure/highlights.scm
tests/query/highlights/clojure/test.clj

Clojure has the concept of metadata, where a symbol can hold "hidden" data. This is done with a ^ and data in front: `^java.util.Long some-foo`. The current clojure treesitter parser produces a tree that stores the metadata node on the `sym_lit` node. When a query matches on `sym_lit`, it's looking at the metadata too, which means that any queries that match the metadata will in fact leak across to the following symbol.
For example:
```
((sym_lit) @type
(#lua-match? @type "^[%u][^/]*$"))
```
We can fix this by being more specific about what we're matching against, selecting the `name` or `namespace` field:
```
(sym_lit
name: (sym_name) @_name
(#lua-match? @_name "^[%u][^/%s]*$")) @type
```

Update Clojure highlights to be metadata aware

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/just/folds.scm
queries/just/highlights.scm
queries/just/indents.scm
queries/just/injections.scm
queries/just/locals.scm

Following up on: https://github.com/nvim-treesitter/nvim-treesitter/pull/5696
The parser has gotten some attention since last time. Most importantly, it no longer uses c++ for the scanner, so it should now be possible to add it to nvim-treesitter.

feat: add just parser

---

lua/nvim-treesitter/parsers.lua
queries/djot/highlights.scm
queries/djot/injections.scm

Closes #6326 
I copied the applicable `queries` files from [the djot ts repo](https://github.com/treeman/tree-sitter-djot), updating `highlights.scm` to match nvim-treesitter's acceptable captures.

feat: add djot support

---

queries/bash/highlights.scm

Hi, I think that command and process substitutions [ie. $(), >(), and <() ] should be highlighted the same as other expansions, which use `@punctuation.special`. This PR sets that up.
In defense of this approach, the [bash manual](https://www.gnu.org/software/bash/manual/html_node/Shell-Expansions.html) considers command and process substitutions to be forms of expansions, so they should be highlighted as such. This is traditionally how they have been highlighted in the past too.
The default colorscheme links both `@punctuation.special` and `@punctuation.default` to `Special` so they DO happen to look the same in that particular colorscheme, but this might not be the case for others. I ran this command to make the difference more apparent:
```colorscheme default | hi link …
```

feat(bash): align substitutions with expansions

---

lua/nvim-treesitter/shell_command_selectors.lua

Probably very few people affected by this, but... I'm using the shell [xonsh](https://xon.sh/), and because of its syntax expectations (allows both python and bash in an interesting mix) whitespace is sometimes meaningful. Therefore, the newline + space combo after the semicolon in this shell command fails for me.
This might be better considered to be a bug in xonsh (although, I'm not actually sure if this is solvable, given the syntax it's trying to support; it might not be fixable; but I've [opened an issue over there](https://github.com/xonsh/xonsh/issues/5312) as well) but since this would be a 1 character fix in this repo, thought I'd open the PR in case this is amenable.
Before this PR, parser installation (e.g. `ensure_installed = {'python'}`) fails for me with the following:
``` …
```

bug: remove extra space during cd

---

queries/lua/injections.scm

I have it working for the uses I have in my dotfiles and for the examples in the documentation:

feat(lua): add injections for `vim.filetype.add`

---

queries/markdown/highlights.scm

Highlights metadata blocks such as the following:
```md
---
title: A title
author: An author
---
```
The highlight is given a lower priority because everything except the delimiting dashes/pluses will be injected with the appropriate metadata language.

feat(markdown): yaml, toml metadata highlights

---

queries/rust/indents.scm

fix(rust): indentation in tuple struct patterns

---

queries/julia/highlights.scm

Add support for capturing function call after a broadcasted pipe. Currently works for unbroadcasted pipe.
There might be a better more complicated way to do this, since this will capture the broadcasting dot as part of the `@_pipe` capture.

feat(julia): broadcast pipe

---

queries/python/highlights.scm

Add "staticmethod" to built in decorators

fix(python): add staticmethod to builtin decorators

---

lua/nvim-treesitter/install.lua

fix(uninstall): use correct path separator on windows

---

queries/nix/highlights.scm

Adds some punctuation highlights that seem to be missing, and also changes the ellipsis parameter to parameter.builtin to match other languages that do this to their ellipsis params, like lua e.g.

Misc nix fixes

---

queries/rust/indents.scm

Fix indentation when tuple are on multiple lines.
Example:
previous:
```rust
fn do_stuff(
mut thing_query: Query<(
&Transform,
&Sprite,
)>
) {
// ...
}
```
new:
```rust
fn do_stuff(
mut thing_query: Query<(
&Transform,
&Sprite,
)>
) {
// ...
}
```

fix(rust): indentation in tuple type patterns

---

queries/rust/indents.scm
tests/indent/rust/tuple.rs

previous:
```rust
for (
abc,
def
) in thing.iter() {
// ...
}
```
new:
```rust
for (
abc,
def
) in thing.iter() {
// ...
}
```

fix(rust): indentation in multi-line tuple pattern

---

queries/bash/injections.scm

The `(string)` node has a `(string_content)` child which breaks the injection of `printf`. The solution was to use `(#set! injection.include-children)`.
I also added support for `(concatenation)` nodes.

fix(bash): fix printf injection queries

---

queries/nix/highlights.scm
queries/nix/injections.scm
tests/query/highlights/nix/test.nix

This PR gives two changes:
1. First commit fixes an issue where strings inside string interpolations weren't working:
```nix
{
test = "this ${would + "not work"}";
}
```
It does this by only applying the string highlights to the fragments themselves (which do not include the 
interpolations) and the quote delimiters.
2. Second commit removes the special `derivation` query, lumping it in as a `@function.builtin` (as it is defined [here](https://nixos.org/manual/nix/stable/language/derivations)), and it also applies the `@keyword.import` queries at the end of the file so as to remove any need for using `priority` workarounds.
It also adds tests.

Nix cleanups

---

lua/nvim-treesitter/parsers.lua

Neovim prerelease builds contain the filetype "trace32" for PRACTICE scripts (see [neovim#23967](https://github.com/neovim/neovim/pull/23967)). I would like to claim it for the `t32` parser.

feat(t32): use filetype "trace32"

---

.github/workflows/test-queries.yml

This gives better error messages on an often flaky platform as well as better coverage (nightly on windows was not tested before).

ci(tests): use nvim nightly for win+cl

---

lua/nvim-treesitter/install.lua
tests/query/highlights/wing/class.w
tests/query/highlights/wing/nested_method.w

These are irrelevant for us and may lead to conflicts with outdated committed bindings (e.g., wing).
Re-enable wing tests.

fix(install): do not generate bindings with parser

---

lockfile.json
queries/julia/highlights.scm
queries/julia/indents.scm
queries/julia/injections.scm
queries/julia/locals.scm
tests/query/highlights/julia/test.jl

This PR removes all patterns for parameters, but otherwise doesn't really change syntax highlighting.
See tree-sitter/tree-sitter-julia#135

fix(julia): Update queries

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/wing/highlights.scm
tests/query/highlights/wing/class.w

Thanks for dealing with the annoying constant updates from https://github.com/winglang/wing 🙏 
https://github.com/winglang/tree-sitter-wing should now only be updated when there is a change to the grammar (still sourced from the wing monorepo), and all the files are already committed so there should be no need to `generate`.
Also updated the queries/tests to match the current state of the repo

fix(wing): move wing to new repo

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/wit/highlights.scm
queries/wit/injections.scm

Added a parser for the [WIT](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md) format.
Guide to WIT [here](https://cosmonic.com/blog/engineering/wit-cheat-sheet).

feat(wit): Add wit parser

---

queries/r/highlights.scm

Missing comma separators for parameters, array elements
EDIT: This PR also `chmod -x`'s the R highlights file, which for some reason was marked as executable for all groups
Before:
After:

fix(r): highlight comma separators

---

queries/python/highlights.scm

Closes: https://github.com/nvim-treesitter/nvim-treesitter/issues/6451
Related: https://github.com/neovim/neovim/issues/28365
In short, the `r"` portion of the string is related to Python's syntax and shouldn't be counted as a target for spellchecking. This PR makes only the inside of the string considered for spellchecking.

fix(python) - @spell now captures inner string contents

---

queries/vim/highlights.scm

- Highlights the `abort` keyword
- Moves `is(not)?` from `@operator` to `@keyword.operator`
- Highlights the `->` operator

fix(vimscript): miscellaneous fixups

---

lockfile.json
queries/astro/injections.scm

The Astro parser's extension logic has been almost entirely rewritten to match up with the actual Astro compiler; these are the new injections after the rewrite.

feat: change astro injections to match parser rewrite

---

lua/nvim-treesitter/install.lua
lua/nvim-treesitter/parsers.lua
runtime/queries/rust/indents.scm

Problem: Using `url` for both remote repo and local path complicates the code.
Solution: Add `path` field that overrides `url` and bypasses git-specific manipulations, i.e., the contents of the `path` are used as-is (no git repo needed).
This means `:TSUpdate` will skip such parsers; use `:TSInstall!` instead after making local changes.
Notes:
* includes some minor refactor of the install module for consistency
* Doc updates are left for the final, complete, rewrite
@lewis6991

feat!: add explicit path field to parser info

---

queries/php_only/folds.scm

- It has no effect in Neovim's `vim.treesitter.foldexpr()` before https://github.com/neovim/neovim/commit/5e6240ffc24e55ecf7721fd9dc3f33c6f178be8c
- It has no effect for the current `nvim_treesitter#foldexpr()`

feat(php): fold consecutive imports

---

CONTRIBUTING.md
README.md
SUPPORTED_LANGUAGES.md
lua/nvim-treesitter/health.lua
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/parsers.lua
scripts/update-readme.lua

Problem: Many parsers require node/npm to evaluate the `grammar.js` before being able to generate a parser from it.
Solution: Generate from `grammar.json` instead, which is fully resolved. Drops `node` and `npm` as (optional) requirements for nvim-treesitter.
Note that this requires parsers to commit the generated json **iff** the grammar requires evaluation (which is currently the case for all tracked languages).
Part #2 of my series of PRs simplifying the install code. While testing this, I found out that a good 20% of the listed parsers actually fail to generate from grammar, mostly due to breaking changes in `tree-sitter` that parsers didn't adapt to. The failures roughly fall into three classes:
* **Invalid regex:** Upstream switched to Rust regex, so the common `escape_sequence` …

feat(install)!: generate from json instead of requiring node

---

queries/qmljs/highlights.scm
queries/qmljs/injections.scm

Fixed after the grammar dependencies were updated. This time inheritance is given to the injections queries also.

feat(qml): add back `ecma` inheritance

---

queries/php_only/highlights.scm
tests/query/highlights/php/types.php
tests/query/highlights/php/variables.php

Using italics to show capture ranges easier. Basically the parameter and ternary highlights were being too generous (and also not specific enough so they were being overridden)
Before:
After:

fix(php): parameter and operator touch-ups

---

queries/vue/injections.scm

The reason for this patch is that I found it to be impossible to find instructions in internet on how to enable `sass` syntax highlight for `vue` files.
I spent couple of hours both googling it and asking chart-gpt-4 how to do this. 
Since there is no `sass` parser for Treesitter lets use `css` or `scss` if such is available. It is not ideal solution, but it is so much better to have it this way than to have no syntax highlighting at all.
before patch
after patch

make sass to be highlighted in vue files

---

queries/angular/highlights.scm

Added fixes for the highlights corresponding to the following:
```
Updated {minutes, plural,
=0 {just now}
=1 {one minute ago}
other {some minutes ago}}
---
(fragment
(text)
(icu_expression
(expression
(identifier))
(icu_clause)
(icu_case
(icu_category)
(text))
(icu_case
(icu_category)
(text))
(icu_case
(icu_category)
(text))))
```
This PR also fixes broken highlights with two-way-binding syntax `[(name)]="something"`

feat(angular): add highlights for ICU expressions

---

queries/c/folds.scm
queries/c_sharp/folds.scm
queries/css/folds.scm
queries/ecma/folds.scm
queries/haskell/folds.scm
queries/java/folds.scm
queries/python/folds.scm
queries/rust/folds.scm

Some fold queries for import statements (or the equivalent) across some common languages. Pre-0.9 nvim is unaffected by these queries, except in cases (like the rust one) where the quantifier was added to a node already in the fold set. In these cases the fold will no longer apply to that node. I think this isn't too big a deal, but feel free to suggest only partially merging if it is :+1:
Also I think these are the only additions needed for the parsers bundled in neovim, so once they are upstreamed, there should be nothing left to do

feat: import statement folds for common languages

---

queries/awk/highlights.scm
queries/bash/highlights.scm
queries/cmake/highlights.scm
queries/fish/highlights.scm
queries/latex/highlights.scm
queries/perl/highlights.scm
queries/python/highlights.scm
queries/query/highlights.scm
queries/r/highlights.scm
queries/starlark/highlights.scm
queries/tablegen/highlights.scm
queries/thrift/highlights.scm

This deactivates spell checking in the following languages' shebangs:
- awk
- bash
- cmake
- fish
- perl
- python
- r
- starlark
Also it activates spelling in perl comments in the first place.

Deactivate spelling in shebangs

---

queries/ecma/injections.scm

Closes #5537
Note: this is only a fix for non-method calls (i.e., it will fix `` await sql`...` `` but not `` await client.sql`...` ``). This is because that would require more drastic changes to the queries and so I am leaving it for a future commit/PR. Of course, if you feel those changes would be better suited to this PR, please let me know.

fix(javascript): Injections into tagged templates now work with 'await'

---

queries/java/highlights.scm

This makes the record name in record constructors highlight properly because they are currently highlighted as `@variable` and not `@type`

Fix compact constructor highlights for Java

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/tact/folds.scm
queries/tact/highlights.scm
queries/tact/indents.scm
queries/tact/injections.scm
queries/tact/locals.scm

This adds support for [Tact](https://github.com/tact-lang/tact) language using [tree-sitter-tact](https://github.com/tact-lang/tree-sitter-tact).
The following queries are included (formatted according to [format-queries.lua](https://github.com/nvim-treesitter/nvim-treesitter/blob/main/scripts/format-queries.lua)):
* highlights.scm
* folds.scm
* indents.scm
* injections.scm
* locals.scm

feat: add support for Tact

---

queries/inko/highlights.scm

Inko allows for syntax such as `some_value.42.to_string`, where `42` is a method name. Similar to other languages that allow this (e.g. Rust), these numeric names should be highlighted as numbers instead of identifiers.
To fix this, the query to highlight call names is adjusted to only highlight "name" and "constant" nodes as the function group, ensuring the remaining possible node ("integer") continues to use the same group as regular numbers.

fix(inko): fix highlighting of numeric call names

---

queries/markdown_inline/highlights.scm

Right now there is a discrepancy between regular inline links and inline image link highlights: basically for something like
```markdown
[**link**](https://website.com/)
```
For the image link, the `@markup.strong` will take priority. For the regular link, `@markup.link.label` takes priority. This PR makes it so that in both cases the strong highlight will take precedence, and it also deduplicates some highlights by using underscore-prefixed captures

fix(markdown): align link with image highlights

---

queries/lalrpop/folds.scm
queries/lalrpop/highlights.scm
queries/lalrpop/injections.scm

Adds a lot of missing highlights that weren't covered by rust injections. Reference file: https://github.com/vosen/ZLUDA/blob/bdc652f9ebcac9a79849eeee84a391a4ac107913/ptx/src/ptx.lalrpop

feat(lalrpop): highlight touchups, folds

---

queries/ecma/injections.scm

This PR fixes a regression that used to work before #6550.
| Before (#6550) | After (This PR) |
| ![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/4299733/01b0b847-daf5-48d4-b6c8-37e47108e789) | ![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/4299733/c923594f-2c29-4990-b1bc-d32ac0dc4c6a) |

fix(ecma): template string injections

---

queries/rust/highlights.scm

Some missing `_` highlights. Reference:
```rust
fn test(_: i32) {
//
}
fn main() {
if let Some(_) = x {};
let p = (1, 2);
let mut a = 0;
(_, a) = p;
let _ = 8;
match p {
"hi" => {}
_ => {}
}
}
```
Note that this will still not highlight the underscore in `(_, a) = p;`. This could be done with an `eq?` query but I left it out because most everywhere else exposes that as a `"_"` node so maybe the parser should do it there too

feat(rust): underscore match arms, parameters

---

queries/inko/indents.scm

This ensures that when you add a new call line in the middle of a call chain, the line is indented like so:
foo
.bar
.new_line_here
.baz
Instead of it being indented like so:
foo
.bar
.new_line_here
.baz

fix(inko): indent call nodes

---

queries/query/injections.scm

Gives `regex` and `luap` injections to the new 0.10 predicates.
Sorry, this should have been done before https://github.com/neovim/neovim/commit/3d4eb9d544cbbe39544586890b5de83a48de3680 :grimacing:

feat(query): pattern injections for new predicates

---

CONTRIBUTING.md
queries/bash/highlights.scm
queries/ecma/highlights.scm
queries/gdscript/highlights.scm
queries/hare/highlights.scm
queries/luau/highlights.scm
queries/make/highlights.scm
queries/qmljs/highlights.scm
queries/slint/highlights.scm
queries/typescript/highlights.scm
queries/zig/highlights.scm

Many export keywords are captured as `@keyword.import`. This commit makes it so they are all captured like that, and mentions it in the documentation.

feat: standardize and document export keywords

---

queries/zig/highlights.scm

Moves some keyword highlights around, highlights parameter types and `=>`, and specifies only the `|` brackets in a payload receive the bracket highlight

feat(zig): misc improvements

---

queries/php_only/highlights.scm
tests/query/highlights/php/variables.php

Hello!
I noticed that scoped_property_access expressions weren't being highlighted:
This PR adds those highlights:
I had to use two separate queries in order to get recursive expression to work, with one query `$bar` wasn't getting highlighted.
Thanks!

feat(php): add highlights for scoped_property_access

---

queries/slint/highlights.scm

```slint
export enum CardSuit { clubs, diamonds, hearts, spade }
// vim: ft=slint
```

feat(slint): highlight enum members as constants

---

lockfile.json
queries/diff/highlights.scm

More highlights for complicated diffs. Reference file:
```diff
diff --git a/CONTRIBUTING.md b/CONTRIBUTING_HERE.md
similarity index 100%
rename from CONTRIBUTING.md
rename to CONTRIBUTING_HERE.md
diff --git a/LICENSE b/LICENSE
old mode 100644
new mode 100755
diff --git a/Makefile b/Makefile
deleted file mode 100644
index 338c7546..00000000
--- a/Makefile
+++ /dev/null
@@ -1,7 +0,0 @@
-# https://github.com/luarocks/luarocks/wiki/Creating-a-Makefile-that-plays-nice-with-LuaRocks
-build:
-	echo "Do nothing"
-
-install:
-	mkdir -p $(INST_LUADIR)
-	cp -r lua/* $(INST_LUADIR)
diff --git a/hi.txt b/hi.txt
new file mode 100644
index 00000000..45b983be
--- /dev/null
+++ b/hi.txt
@@ -0,0 +1 @@
+hi
diff --git a/queries/rust/highlights.scm b/queries/rust/highlights.scm
index c392c030..1609a81a 100644 …
```

feat(diff): more comprehensive highlights

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/typespec/highlights.scm
queries/typespec/indents.scm
queries/typespec/injections.scm

This adds support for the [typespec](https://typespec.io/) language with [happenslol/tree-sitter-typespec](https://github.com/happenslol/tree-sitter-typespec).
I've been using this for a few weeks through `TSInstallGrammar` and linking the queries manually into my nvim config, so I can confirm this to be working correctly. I haven't added any folds yet, I hope it's alright if I amend that at a later date.
I've tried to keep to the best practices listed in the contribution guidelines, but this is my first time working with treesitter so I'm open to any suggestions.

feat(typespec): add support for typespec

---

README.md
SUPPORTED_LANGUAGES.md
lua/nvim-treesitter/_meta/parsers.lua
lua/nvim-treesitter/config.lua
lua/nvim-treesitter/health.lua
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/parsers.lua
scripts/convert-lockfile.lua
scripts/update-readme.lua

quick test to compare build times on CI:
* ubuntu: 2:09 vs 1:50
* macos: 1:40 vs 1:20 (locally, 95s vs 85s)
*  windows: 3:55 vs 5:09
network/load adds large variance, but the windows improvement is significant (and welcome on CI).
Also, adding or removing scanners is no longer a breaking change.
Also also, look at those diffstats 🤩 
Notes on possible (upstream) improvements:
1. Ideally, we could build directly into the target location, obviating the need for the move task, but `ts b` litters debug symbols in the build directory.
2. We could combine `generate` and `build` step if `ts b` generated if necessary. For our purposes, though, we'd need more control:
* `ts b` builds from `parser.c`
* `ts b src/grammar.json` calls `ts g src/grammar.json` first
* `ts b grammar.js` calls `ts g` first …

feat!: use tree-sitter build

---

queries/odin/highlights.scm

Odin's [naming convention](https://github.com/odin-lang/Odin/wiki/Naming-Convention) calls for types to be in Ada_Case. It therefore makes sense for types with underscores to also be highlighted as such.

fix(odin): highlight types with underscores

---

lua/nvim-treesitter/query_predicates.lua
queries/c/indents.scm
queries/ecma/indents.scm
queries/groovy/indents.scm
queries/ispc/indents.scm
queries/ocaml/indents.scm
queries/swift/indents.scm
scripts/format-queries.lua

No point in having a different name for the same predicate.
(Helix uses quotes for the second argument even though those are not literals. I prefer that, to be honest.)

feat(predicates)!: rename `has-type` to `kind-eq` to align with Helix

---

queries/jq/highlights.scm

This updates the list of known `@function.builtin` for the `jq` parser as some new functions have been added, and deprecated ones have been removed.
The list is generated with the command  `jq -n 'builtins | map(split("/")[0]) | unique | .[]'`
To compare before and after:
```
diff <(echo "IN" "INDEX" "JOIN" "abs" "acos" "acosh" "add" "all" "any" "arrays" "ascii_downcase" "ascii_upcase" "asin" "asinh" "atan" "atan2" "atanh" "booleans" "bsearch" "builtins" "capture" "cbrt" "ceil" "combinations" "contains" "copysign" "cos" "cosh" "debug" "del" "delpaths" "drem" "empty" "endswith" "env" "erf" "erfc" "error" "exp" "exp10" "exp2" "explode" "expm1" "fabs" "fdim" "finites" "first" "flatten" "floor" "fma" "fmax" "fmin" "fmod" "format" "frexp" "from_entries" "fromdate" "fromdateiso8601" "fromjson" …
```

chore(jq): update builtin functions

---

README.md

I've encountered an `Invalid node type` error on Neovim 0.10.0 using the latest nvim-treesitter.
This issue occurred because my `parser_install_dir` was **appended** to my `runtimepath`, causing Neovim to use its own parsers instead of those from nvim-treesitter.

Fix example of the parser install directory

---

queries/commonlisp/highlights.scm

the previous queries caused issues like highlighting `(quoting_lit)` and `(format_directive_type "'")` twice which made them really annoying to overwrite.

fix(commonlisp): correctly highlight quotes

---

queries/swift/highlights.scm

Did not recognize Shebang lines, added a highlight for them. Reference: 
```swift
#!/usr/bin/env swift
let args = CommandLine.arguments
var out = "y"
if args.count > 1 {
out = args[1...args.count-1].joined(separator: " ")   
}
while true { print(out) }
```

fix(swift): recognize shebang lines

---

queries/snakemake/folds.scm

A `rule_inheritance` is on the same hierarchical level as a `rule_definition`.
I forgot to add it before.

feat(snakemake): add rule_inheritance to folds

---

queries/gitcommit/highlights.scm

I think this is a leftover from the great capture migration, and there wasn't really a file path capture. Reference:
```gitcommit
feat(hi): msg right here
#
#	renamed:    CONTRIBUTING.md -> CONTRIBUTING_HERE.md
#	modified:   LICENSE
#	new file:   hi.txt
#	modified:   queries/rust/highlights.scm
```

fix(gitcommit): correct the file path capture

---

queries/markdown/highlights.scm

Very small change that highlights the space(s) in-between the `#` and the heading content. Nice to have when captures are given a background color, underline, etc.

fix(markdown): capture entire heading line

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/roc/highlights.scm
queries/roc/locals.scm

Upstream also does not contain symlinks which break unextracting on Windows.
@nat-418

feat(roc): switch to active upstream

---

queries/scala/highlights.scm

```scala
/*
* Copyright (C) 2009-2023 Lightbend Inc. <https://www.lightbend.com>
*/
package akka
import sbt._
import sbt.Keys._
import java.io.File
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.*
import com.lightbend.sbt.publishrsync.PublishRsyncPlugin.autoImport.publishRsyncHost
import sbt.Def
import com.geirsson.CiReleasePlugin
import com.jsuereth.sbtpgp.PgpKeys.publishSigned
object Publish extends AutoPlugin {
val defaultPublishTo = settingKey[File]("Default publish directory")
override def trigger = allRequirements
lazy val beforePublishTask = taskKey[Unit]("setup before publish")
lazy val beforePublishDone = new AtomicBoolean(false)
def beforePublish(snapshot: Boolean) = {
if (beforePublishDone.compareAndSet(false, true)) { …
```

feat(scala): add some missing highlights

---

queries/markdown_inline/highlights.scm

This fixes indentations being lost in hover documentation that use the html entity `nbsp` when they are concealed by nvim (https://github.com/neovim/neovim/blob/20a7eebec086129e605041d32916f36df50890de/runtime/lua/vim/lsp/util.lua#L1638)

fix: retain nonbreaking spaces as spaces when concealed

---

queries/gleam/highlights.scm
tests/query/highlights/gleam/function.gleam
tests/query/highlights/gleam/type.gleam

Hello!
I'm the creator and lead developer of Gleam. Neovim has been highlighting Gleam types slightly incorrectly, and this has been identified as the issue.
I'm not very familiar with this configuration, so please do let me know if this is not the right way to correct this.
Thanks,
Louis

Remove incorrect builtin highlight for Gleam

---

queries/apex/highlights.scm

This changes the order of how the constant variable is recognized. Without this, it applies property highlights to constant types. 
Kindly review & share the feedback.

fix(apex): highlights: change the constant variable order to recognize it correctly

---

queries/cooklang/highlights.scm

Reference:
```cook
>> source: https://www.kingarthurbaking.com/recipes/golden-pita-bread-recipe
>> total time: 2 hours
>> serves: 8
>> vim: ft=cooklang
Weigh your flour; or measure it by gently spooning it into a cup, then sweeping off any excess. Combine @all-purpose flour{360%g}, @instant yeast{2%tsp}, @King Arthur Easy Roll Dough Improver optional{2%tsp}, @granulated sugar{2%tsp}, @salt{9%g}, @water{227%g}, @vegetable oil{25%g}, mixing to form ligmma a shaggy/rough dough.
-- Don't burn the roux!
Knead the dough, by hand (~hi{10%minutes}) or by mixer (5 minutes) or by bread machine (set on the dough cycle) until it's smooth.
Place the dough in a lightly greased #bowl{2}, and allow it to rest for ~{1%hour}; it'll become quite puffy, though it may not double in bulk. If you've used a …
```

fix(cooklang): add some missing highlights

---

queries/verilog/highlights.scm

Some fixes for verilog. Reference file:
```verilog
typedef enum {ONE, TWO, THREE} myenum;
typedef union packed
{
my_opcode_struct_t opcode_s; // "fields view" to the struct
logic[1:0][31:0] dword; // "dword view" to the struct
} my_opcode_union_t;
typedef struct packed
{
my_opcode_t  opcode; // 16-bit opcode, enumerated type
my_dest_t    dest; // 16-bit destination, enumerated type
logic [15:0] opA;
//logic [15:0] opB;
} my_opcode_struct_t;
class MyClass;
int number;
function new (int num = 0);
number = num;
endfunction
endclass
MyClass a_class = new();
module function_auto ();
function automatic [7:0] factorial;
input [7:0] i_Num;
begin
if (i_Num == 1)
factorial = 1;
else
factorial = i_Num * factorial(i_Num-1);
end
endfunction
initial
begin
$display("Factorial of 1 = %d", factorial(1)); …
```

fix(verilog): various touch-ups

---

queries/v/highlights.scm

Adds the shebang line as `@keyword.directive`(the default used for shebang queries).
|Current|Updated|
|-|-|
|![Screenshot_20240626_095720](https://github.com/nvim-treesitter/nvim-treesitter/assets/34311583/f506d66f-dfd2-4f44-a1e9-411cd9c75bdb)|![Screenshot_20240626_095744](https://github.com/nvim-treesitter/nvim-treesitter/assets/34311583/a9068af6-1ac8-40aa-a3fc-79eaa2fcd597)|

feat(v): add shebang query

---

queries/gitcommit/highlights.scm

This commit remove the highlight of the overflow node in gitcommit syntax introduced [by this PR](https://github.com/nvim-treesitter/nvim-treesitter/pull/6222). 
This node will be removed when [this PR](https://github.com/gbprod/tree-sitter-gitcommit/pull/68) will be merge.
I've tried to explain the reasons [here](https://github.com/gbprod/tree-sitter-gitcommit/pull/68#issue-2333012970).

feat(gitcommit): remove overflow rule

---

queries/v/highlights.scm

This PR fixes a huge performance impairment related to doc comments. This is particularly noticeable with larger files.
To give an example that can be locally tested: with the current highlight query it is barely possible to work in https://github.com/vlang/v/blob/094c30c34785597de7238e06895d153d8d121e4d/vlib/builtin/string.v - even on good machines. With the changes, things work smoothly.
The `source_file` parent node is what e.g. the Go queries use for doc comments too.

fix(v): use `source_file` as parent node for comment highlight query

---

lua/nvim-treesitter/parsers.lua

Resolves #6465 
I change nvim config to my repo:
```lua
return { "opa-oz/nvim-treesitter", branch = "feat/6465-add-tfvars", build = ":TSUpdate" }
```
Result:

feat: add terraform-vars parser

---

queries/r/indents.scm
tests/indent/r_spec.lua

- Anchor parameter query. There's no need for multiple indent.align captures
- Narrow down binary_operator indent.begin. From tree-sitter-r corpus and highlight tests, this seems to be appropriate.

fix(r): adapt indent queries

---

queries/r/highlights.scm
tests/query/highlights/r/test.r

Reverts highlights to the state they were before the parser update, where accurate (at least in the context of the test and my own observations)

fix(r): resolve highlight regressions

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/robots/highlights.scm
queries/robots/injections.scm

Hello, it's me again 🙇
Brought to you lang support for [robots.txt](https://en.wikipedia.org/wiki/Robots.txt)
**Before**
**After**

feat: Robots.txt support

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/problog/folds.scm
queries/problog/highlights.scm
queries/problog/indents.scm
queries/problog/injections.scm
queries/prolog/folds.scm
queries/prolog/highlights.scm
queries/prolog/indents.scm
queries/prolog/injections.scm

Added Prolog and ProbLog parsers and queries. The two languages do not have proper scopes or injections, as far as I know (used the ISO standard to implement the parsers), so those queries are intentionally missing.

Feat: Pro(b)log support

---

queries/ecma/indents.scm
tests/indent/ecma/if_else.js
tests/indent/javascript_spec.lua

Fixes #5898. Currently only works after-the-fact, i.e. indentation will not work with `o`.

fix(ecma): indent single-line if statements

---

queries/jsdoc/highlights.scm

Some missing bracket and delimiter highlights, and nicer identifier highlights for certain tags. [Reference](https://jsdoc.app/)

feat(jsdoc): add missing highlights

---

queries/html_tags/highlights.scm

Unlike the `href` attribute, the inner text of the `a` tag is the label of the link, not the actual URL.

fix(html): correct the link label highlight

---

queries/jsx/highlights.scm

Queries adapted from `html_tags`

feat(jsx): apply HTML-based highlight improvements

---

queries/ruby/highlights.scm

Add highlight groups for ruby special methods
Before
After

feat(ruby): add highlights

---

queries/hurl/injections.scm

This is a suggested fix for #6882 and https://github.com/pfeiferj/tree-sitter-hurl/issues/10.

fix(hurl): multiline injection query needs injection.combined

---

queries/ruby/highlights.scm

Highlight `&.` as `@punctuation.delimiter` in Ruby. Typescript highlights do the same thing for Javascript's safe navigation operator.

fix(ruby): highlight "&." as `@punctuation.delimiter`

---

lua/nvim-treesitter/parsers.lua

Problem: Cannot use short-hands for @injection.language (e.g., `py` for
Python).
Solution: Register common short-hand as filetypes for some languages.
List taken from https://github.com/helix-editor/helix/blob/master/languages.toml
Also remove deprecated custom filetype->parser mapping.

feat(parser): register common short-hand as filetypes

---

queries/python/indents.scm
tests/indent/python/aligned_indent.py
tests/indent/python/parenthesized_conditions.py

The existing python indentation query has a few quirks around parameter lists and parenthesized expressions.
Current behavior:
```python
def foo(
a,
b,
c
):  # I think this is a bug in indent.avoid_last_matching_next, this line should not be indented.
if (
True
or 1
or False
):
pass
if (
True
or 1
or False):
pass
```
Fixed indentation:
```python
def foo(
a,
b,
c
):
if (
True
or 1
or False
):
pass
if (
True
or 1
or False):
pass
```

feat(python): Improved python indentation

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/angular/highlights.scm
queries/angular/indents.scm
tests/indent/angular/defer.html
tests/indent/angular/for.html
tests/indent/angular/if-else.html
tests/indent/angular/switch-case.html
tests/indent/angular_spec.lua

Angular filetype detection has been added to [vim](https://github.com/vim/vim/commit/c03f631b7b01e672787b222a55898f8dcac8d859) and [neovim nightly](https://github.com/neovim/neovim/commit/afbe7736a4966f22146d857f246eac01cd080773)
So this PR changes the filetype of the Angular parser to `htmlangular`
It also updates the parser to a new version, with changed capture groups for Control Flow statements.
It also adds indentation queries (with tests)

feat(angular)!: Change filetype of angular parser and add indentation queries

---

lua/nvim-treesitter/parsers.lua

~~There are several [Chart.js](https://github.com/chartjs/Chart.js) Markdown previewing plugins, and they all (or all I have seen) take JSON data passed to a `chart` codeblock to generate the graphs. Since the chart info string isn't recognized in any way, it would be nice to alias it to JSON to get nice injections still.~~

feat: register aliases defined for set-lang-from-info-string

---

lua/nvim-treesitter/ts_utils.lua

Otherwise the warning message leads to a misleading not existing get_node_text

chore: fix deprecation note leading to confusion

---

queries/latex/highlights.scm

These were recognized by `latex` grammar, but not highlighted.

feat(latex): add additional include highlights

---

queries/gitignore/highlights.scm

Capture regular, non-special characters (as `@string.special.path`) allowing them to be highlighted.

fix(gitignore): hl/capture non-special pattern chars

---

queries/snakemake/highlights.scm

Wildcard interpolations support the `:q` flag to quote list/tuple elements with whitespace.
```snakemake
rule x:
input: 
"the first file.txt",
"the second file.txt"
output: "output.txt"
shell:
"""
cat {input:q} > {output}
"""
```
With `{input:q}`, this expands to `cat 'the first file.txt' 'the second file.txt' > output.txt`
With `{input}`, this expands to `cat the first file.txt the second file.txt > output.txt`
The `(wildcard (flag))` node was added in the latest version of the `snakemake` parser.

feat(snakemake): add wildcard flag

---

queries/latex/highlights.scm

Additionally, add `\bm` (bold symbols in maths mode).

feat(latex): simplify captures of font changing

---

queries/lua/highlights.scm

`@property` should be used for key-value pairs, while `@variable.member` is used for field-access/index-expressions. Using different captures also provides the benefit of allowing the two to be highlighted differently.

fix(lua): use @property for keys in table literals

---

queries/gotmpl/folds.scm
queries/gotmpl/locals.scm
queries/helm/folds.scm
queries/helm/locals.scm

I'm not sure about the ~~indents~~ and locals as I could not tests them, maybe something is still wrong about them.
Edit: I guess indents are not required for the language.
Regarding locals, here are some examples, where I would expect it to work:
```
{{ $test := 1}}
{{ $test }}
```
creating this tree:
```query
(variable_definition) ; [1:4 - 13]
variable: (variable) ; [1:4 - 8]
name: (identifier) ; [1:5 - 8]
value: (int_literal) ; [1:13 - 13]
(text) ; [1:16 - 2:0]
(variable) ; [2:4 - 8]
name: (identifier) ; [2:5 - 8]
(text) ; [2:12 - 5:0]
```

feat(gotmpl,helm): add folds and locals

---

queries/latex/highlights.scm

There is no need to capture `declaration` field when defining new commands, since it is already captured by `(command_name)`.
Supersedes #6954.

fix(latex): refactor highlights

---

queries/zig/highlights.scm

```zig
pub const args = @import("clap/args.zig");
pub const parsers = @import("clap/parsers.zig");
pub const streaming = @import("clap/streaming.zig");
pub const Values = enum {
none,
one,
many,
};
fn testParseParams(str: []const u8, expected_params: []const Param(Help)) !void {
for (expected_params, 0..) |_, i|
try expectParam(expected_params[i], actual_params[i]);
}
```

fix(zig): add some missing highlights

---

queries/latex/highlights.scm

Apply `@nospell` to command/label names, paths, etc. Where appropriate, turn spelling off for the whole node.
Fixes #6785.

fix(latex): more `@nospell`

---

queries/latex/highlights.scm

Before:
After:
Also, `(brack_group)` appeared in different contexts (optional arguments for environments), where it definitely wasn't `@variable.parameter`. What do you think?

feat(latex): improve parameters

---

queries/markdown_inline/highlights.scm

Setting the url attribute on actual URLs will cause Nvim to use the OSC 8 sequence on the entire URL, which enables terminal emulators to detect the URL even when it is wrapped.
The (uri_autolink) node must use an #offset! directive to strip the surrounding <> characters from the URL.

feat(markdown): set url attribute on plain URLs

---

queries/html_tags/highlights.scm

See the justification in https://github.com/nvim-treesitter/nvim-treesitter/pull/6971:
>Setting the url attribute on actual URLs will cause Nvim to use the OSC 8 sequence on the entire URL, which enables terminal emulators to detect the URL even when it is wrapped.

feat(html): set url attribute for HTML URLs

---

queries/julia/injections.scm

This PR adds markdown syntax highlighting and bash command line syntax highlighting for the appropriate Julia expressions.
bash syntax highlighting:
markdown syntax highlighting:
This PR also adds a comment for each injection.

feat(julia): Add syntax highlighting for markdown and bash `prefixed_string_literals`

---

queries/latex/highlights.scm

Environment names are captured as `@label` in `(begin)` and `(end)` nodes, and so should they be when we are defining environments.
Before:
After:

fix(latex): environment name should be label

---

queries/query/highlights.scm

Setting any property like `injection.language` or `injection.language` doesn't highlight it. This fixes it.

feat(query): Highlight key in set! directive

---

queries/query/injections.scm
tests/query/injections/query/test-query-injections.scm

I think these have been broken since the query parser update. Basically the inner node for the string content was preventing injections because include-children was not set.

fix(query): properly apply predicate injections

---

lua/nvim-treesitter/shell_command_selectors.lua

This is a small follow-up to https://github.com/nvim-treesitter/nvim-treesitter/pull/6960

Fix typo in comment in shell_command_selectors.lua

---

queries/latex/highlights.scm

<del>
Capture math delimiter commands such as `\left` and `\right`.
Not sure wheter it should be `@function.macro` or `@function` or perhaps something else. I am open to suggestions.
Before:
After:
</del>
Edit:
Capture math delimiters provided by commands such as
`\left` and `\right`.

feat(latex): capture left/right math delimiters

---

queries/r/indents.scm
tests/indent/r/incomplete_pipe.R
tests/indent/r_spec.lua

`special` and `|>` are both binary operators, so `@indent.begin` is defined in two places for them.
This leads to a double indentation:
```r
mtcars %>%
head() %>%
tail() %>%
head()
```
After the changes proposed in this pull request, this indents as:
```r
mtcars %>%
head() %>%
tail() %>%
head()
```

fix(r): prevent double indent from pipes

---

queries/powershell/highlights.scm
queries/powershell/locals.scm

added highlight for variable name in data section definition
```powershell
Data TextMsgs {
^---- highlight "data" as @keyword.modifier
^---- highlights variable definition as @constant
"Message"
"Another message"
}
```
data sections can be used to isolate read-only data and text strings so I think `@constant` is most suitable tag for this
docs: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_data_sections?view=powershell-7.4

feat(powershell): added data section name highlights

---

queries/ecma/injections.scm

Added injection into tagged templates for SQL method calls (e.g., `` client.sql`...` ``) in order to add compatibility with Vercel's PostgreSQL SDK.
This is a continuation of https://github.com/nvim-treesitter/nvim-treesitter/pull/6555 which I inadvertently closed. That was originally opened to address the issue raised in mentioned in https://github.com/nvim-treesitter/nvim-treesitter/pull/6550.

feat(ecma): inject sql template methods

---

queries/julia/injections.scm

Inject markdown in macro definition docstrings.
---
Closes https://github.com/tree-sitter/tree-sitter-julia/issues/145

fix(julia): macro definition docstrings

---

queries/perl/folds.scm
queries/perl/highlights.scm

Adds highlights and fold patterns for the new `try/catch`, `defer` and `class` syntax now recognised by tree-sitter-perl. Also adds recognition of `eval` which we somehow missed doing last time.

Add extra highlights and fold patterns for recent additions to tree-sitter-perl

---

lua/nvim-treesitter/shell_command_selectors.lua

Problem: [#6960](https://github.com/nvim-treesitter/nvim-treesitter/pull/6960) introduced a fix to bail installs if an active git session is detected. An error message is supposed to be printed using `string.format`. However, the error message has two placeholder %s args but only one provided argument. This causes a runtime error.
Solution: Add project_name again as a third argument to string.format to hydrate the second %s. This fixes the issue and the error message prints as-expected.

Fix missing format argument in shell_command_selectors

---

lockfile.json
queries/liquid/highlights.scm

Adding highlight for `custom_upaired_statement` keyword re: [this update](https://github.com/hankthetank27/tree-sitter-liquid/commit/4f1b43625924c11ec99d79a0f2ddbb94c4e393d7)
Edit: forgot to add the highlight for `include_relative` keyword as part of the initial commit, which was part of the same updates (adding support for some Jekyll specific syntax).

feat(liquid): add highlight

---

queries/inko/highlights.scm

This query was missing, resulting in patterns such as `case Ok(true)` not being highlighted correctly.

feat(inko): add highlight for boolean patterns

---

queries/rust/highlights.scm

This highlights shorthand field identifiers in struct patterns like this:
```rs
let lsp_types::InitializeParams {
root_uri,
capabilities,
workspace_folders,
initialization_options,
client_info,
..
} = from_json::<lsp_types::InitializeParams>("InitializeParams", &initialize_params)?;
```

feat(rust): add highlight for shorthand_field_identifier

---

queries/matlab/highlights.scm

This PR capture the "section" comments of matlab, a way to define code sections to run separately, for more info [see](https://www.mathworks.com/help/matlab/matlab_prog/create-and-run-sections.html). The sections are captured as keyword.directive since they provide some kind of preprocessing command. Before and after images:
Thank you for your contribution!

feat(matlab): capture comment sections

---

queries/make/highlights.scm

Test text:
```make
lib/%.js.flow: src/%.js
@echo "Building $(@)"
@mkdir -p $(@D)
@cp $(<) $(@)
```

feat(make): highlight more special characters

---

queries/http/injections.scm

Updated `http/injections.scm` file following latest release of [tree-sitter-http](https://github.com/rest-nvim/tree-sitter-http).
This enables response handler script language injections for cases like:
```http
GET example.com
{%
-- lua code
%}
```

feat(http): update injections queries

---

queries/query/highlights.scm

For something like `(supertype/regularnode) @cap`

feat(query): highlight supertype "/" delimiters

---

queries/latex/highlights.scm

Just a sidenote: after https://github.com/neovim/neovim/commit/9762c5e3406cab8152d8dd161c0178965d841676, using `gx` binding anywhere on `\href{URL}{description}` will open `URL`.

feat(latex): set url attribute for hyperlinks

---

lua/nvim-treesitter/query_predicates.lua

This is a "fix" for the recent upstream change that makes `all=true` the default.
Backwards compatible using a shim (thanks @gpanders!)

fix(query): force all=false in add_{predicate,directive}

---

scripts/format-queries.lua

After https://github.com/neovim/neovim/pull/30193/, the formatter was broken due to changes in the way node data is passed to predicates. Now the script will be compatible both ways

fix(formatter): adapt formatter for nightly

---

queries/latex/highlights.scm

Before:
After:
Can possibly capture commands which are not conditionals in the purest sense shown above, but generally it works pretty well. In case someone has macro/command starting on `if` which doesn't have anything with conditionals, and is bothered by such false positive capture, they are free to overwrite it with another tailor-made capture.

feat(latex): capture conditionals

---

queries/rust/highlights.scm

fix(rust): comment marker should not be `@operator`

---

queries/ruby/highlights.scm

Only highlight `include`, `extend`, `prepend`, `refine`, and `using` as built-ins if they are not called on an explicit object.
Before:
After:

feat(ruby): improve identifiers highlighting

---

queries/lua/highlights.scm

Already highlighted below as `@variable.parameter.builtin`

fix(lua): remove duplicate ellipsis highlight

---

queries/ruby/highlights.scm

Detect the shebang directive similarly to what Bash [does](https://github.com/nvim-treesitter/nvim-treesitter/blob/b6a6d8997c46dc15682020ce4fddc5a89ee1ac0d/queries/bash/highlights.scm#L236-L239).

feat(ruby): detect shebang directive

---

queries/htmldjango/highlights.scm

In Django templates `{{` and `{%` are interpolations so they should be highlighted as `@punctuation.special`.
Don't highlight quotes as delimiters (consistency) and add missing comma delimiter.

feat(htmldjango): improve punctuation highlighting

---

queries/c_sharp/highlights.scm
queries/elm/highlights.scm
queries/gdscript/highlights.scm
queries/haskell/highlights.scm
queries/java/highlights.scm
queries/menhir/highlights.scm
queries/ocaml/highlights.scm
queries/purescript/highlights.scm
queries/python/highlights.scm
queries/query/highlights.scm
queries/roc/highlights.scm
queries/rust/highlights.scm
queries/scala/highlights.scm

Some languages use `_` as a wildcard pattern to match anything, which should be highlighted as `@character.special`. Is possible that other languages use a different character for the same purpose, but I don't know of any.
I got a list of grammars that use an underscore with this command:
```sh
rg '"_"|underscore' queries/
```
and just checked which ones use it for pattern matching, with the following results:
just a regular symbol in the grammar, so it would need a special and
complicated query for highlighting.
Grammars that use `_` for other purposes:
- `blueprint`
- `cue`
- `elvish`
- `fish`
- `hare`
- `lalrpop`
- `latex`
- `perl`
- `uxntal`
- `wit`
- `zig`
Please tell me if I miss anything.

feat(highlights): capture wildcard patterns as `@character.special`

---

queries/markdown_inline/highlights.scm

**Problem:** Neovim's `gx` will not work when the cursor is on the first `[` of an inline Markdown link.
**Solution:** Set the `url` metadata property on the link parent node, rather than just the link label node

fix(markdown): broader link recognition

---

queries/markdown_inline/highlights.scm

Otherwise the same link will be opened twice when the cursor is on the link text itself.
I checked `grammar.js` before this change to make sure there are no other instances of `link_destination` that would no longer be covered by this change

fix(markdown): don't set link metadata twice

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/fsharp/highlights.scm
queries/fsharp/injections.scm

This adds support for the [fsharp parser](https://github.com/ionide/tree-sitter-fsharp) along with highlighting and injection queries. 
I have not been able to make satisfactory indentation queries so they are left out for now.

feat(fsharp): add parser and queries

---

lua/nvim-treesitter/parsers.lua

In Nvim 0.11, `vim.treesitter.lang.get_lang(filetype)` falls back to `filetype` by default, so filetypes no longer have to be registered for languages with the same name.
https://github.com/neovim/neovim/pull/30379
Also, bye-bye metatable!

fix(parsers): adapt to upstream change in Nvim 0.11

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/superhtml/highlights.scm
queries/superhtml/injections.scm

SuperHTML is a templating language used by the zine static site
generator.

feat(superhtml): add superhtml parser and queries

---

queries/latex/highlights.scm

Color can be changed by directly passing color `model` and `spec`, so make the `name` field optional.
This is possible since https://github.com/latex-lsp/tree-sitter-latex/pull/151.

fix(latex): capture nameless color change

---

queries/slang/highlights.scm

The `auto` rule is removed from slang, so inheriting the C++ highlight queries is disallowed, instead C is inherited, with C++ and HLSL copied sans the `auto` rule.

fix(slang): adapt to parser changes

---

queries/regex/highlights.scm

Better highlights for count quantifiers, e.g. `asdf{1,2}`

feat(regex): better count quantifier highlights

---

queries/gdscript/highlights.scm
queries/helm/highlights.scm
queries/ispc/highlights.scm
queries/nix/highlights.scm
queries/powershell/highlights.scm
scripts/format-queries.lua

This commit simplifies much of the formatter code, removing the need for break statements, removing some unused captures, and merging some redundant `if` cases. The formatter output is the same except in some cases where a (seemingly unintentional) line break is now no longer added.

fix(formatter): simplify code, remove odd line break

---

queries/rust/highlights.scm
queries/rust/injections.scm

**Problem:** Rust's regex injections were not applied since the string content is behind a `(string_content)` node, and the injections were applied to the parent node without the `include-children` directive.
**Solution:** Apply the injections to the string content. Also highlight them accordingly.

fix(rust): regex injections, highlights

---

queries/bash/highlights.scm

Commands:
- `.`
- `:`
- `true`
- `false`

feat(bash): highlight more builtin commands

---

queries/thrift/folds.scm
queries/thrift/highlights.scm

Less capture duplication by separating queries, include folds, move `@variable.member` to `@property`

feat(thrift): small improvements

---

queries/rst/highlights.scm

Left: before, Right: after.
<image src="https://github.com/user-attachments/assets/1289ec04-4340-472f-be2c-19cd873cddac"  width="45%" />
<image src="https://github.com/user-attachments/assets/94d9f84b-2e6e-430a-a385-f4cf4e52d617"  width="45%" />

fix(rst): adornment should be captured as @markup.heading

---

queries/regex/highlights.scm

Highlights the "?" following .* and the \k backreference operator in a
pattern like the following: title=(?<quote>["'])(.*?)\k<quote>

feat(regex): highlights for lazy quantifiers, \k

---

lua/nvim-treesitter/parsers.lua

`Cooklang` files are recognized as `cook` in vim. This prevents the parser from attaching since it is looking for `cooklang` files, so we have to specify the `filetype` here.

fix(cooklang): apply correct filetype

---

queries/zig/indents.scm

The curly braces contained in the `struct_declaration` are not included by the `block`. Indentation should also start here.
Before this PR:
After this PR:

fix(zig): begin indent at `struct_declaration`

---

queries/bash/highlights.scm

feat(bash): highlight redirections

---

queries/julia/injections.scm

This patch fixes the julia `(string_literal)` injection queries after
the breaking changes in
https://github.com/tree-sitter/tree-sitter-julia/pull/153. The queries
are simplified by the fact that string content is now directly available
as a separate `(content)` child node.

fix(julia): fix injection queries

---

queries/julia/highlights.scm
queries/julia/injections.scm

This patch enables `@string.documentation` capturing, and markdown
injection, for strings attached to `(call_expression)` and
`(identifier)` nodes. For example
```julia
"docs"
foo(::Int, ::Float64)
"docs"
bar
```

fix(julia): capture docstrings in more cases

---

queries/julia/highlights.scm

This fixes the macro identifier highlight query after the breaking
changes in https://github.com/tree-sitter/tree-sitter-julia/pull/153.
See also
https://github.com/tree-sitter/tree-sitter-julia/pull/158/commits/9f2fb3b9a8c73ef0d2ec005c97f91274b492d48d.

fix(julia): fix macro identifier highlight query

---

queries/julia/highlights.scm

This patch fixes two issues related to `@type` capturing (split out from
https://github.com/nvim-treesitter/nvim-treesitter/pull/7392):
- Capture the RHS of `<:` and `>:` as `@type` in `(unary_expression)`s
similarly to what is already done for `(binary_expression)`s with
these operators.
- Capture children of `(curly_expression)`s inside of
`(where_expression)`s as `@type` similarly how they are handled in
`(parametrized_type_expression)`.

fix(julia): misc fixes to type highlighting

---

queries/astro/highlights.scm

For Astro, adds highlighting to self-closing custom component tags, e.g `<Navigation />`.
Before this would be highlighted like a regular HTML tag, unless it was not self closing.

fix(astro): highlight self-closing component tags

---

queries/julia/highlights.scm
tests/query/highlights/julia/test.jl

This patch removes `::` from `@punctuation.delimiter` and instead treat
it as `@operator` within `(unary_typed_expression)` and
`(typed_expression)`. I believe these are the only places where `::` can
show up, so maybe it is simpler to just capture it as `@operator`
globally `::`. (Note that `<:` and `>:` already are `@operator`s
globally since they are parsed into the `(operator)` node.)
Edit: I split out the non-controversial parts into #7396

fix(julia): treat :: as operator

---

queries/verilog/highlights.scm

1. Add "string" as a keyword
2. Fix issue where non-type.builtin fields are highlighted when using (data_type) as type.builtin
3. Add generate label

fix(verilog): fix some tpye.builtin highlights error

---

lockfile.json
queries/inko/highlights.scm

The parser added support for the "inline" keyword in a few places. This ensures a highlight is present for the keyword.

feat(inko): highlight "inline" keyword

---

queries/julia/highlights.scm

This patch adds `$` to the `@punctuation.special` capture group. `$` is
used for string interpolation (`"hello $name"`) and expression
interpolation (`:(hello $name)`) and for both of these cases the
`@punctuation.special` category seem appropriate.

feat(julia): highlight interpolation operator

---

queries/nu/highlights.scm

Currently it is not highlighted for e.g.
```nushell
use activate
```
I have checked the `grammar.js` and there are no other occurrences of `"use"` that could be incorrectly overridden by this change.

fix(nu): highlight all occurrences of "use"

---

queries/gomod/highlights.scm

```gomod
module github.com/klauspost/reedsolomon
go 1.21
require github.com/klauspost/cpuid/v2 v2.2.8
require golang.org/x/sys v0.24.0 // indirect
retract (
v1.12.2 // https://github.com/klauspost/reedsolomon/pull/283
v1.11.6 // https://github.com/klauspost/reedsolomon/issues/240
[v1.11.3, v1.11.5] // https://github.com/klauspost/reedsolomon/pull/238
v1.11.2 // https://github.com/klauspost/reedsolomon/pull/229
)
```

feat(gomod): punctuation, toolchain highlights

---

queries/julia/highlights.scm

This patch fixes an inprecise `@string.documentation` query introduced
in https://github.com/nvim-treesitter/nvim-treesitter/pull/7391.
Specifically, the pattern `(string_literal) . (identifier)` matches also
for example `"hello"` in
```julia
foo("hello", world)
@info "hello" world
```
To fix this, this patch limits the pattern to top-level statements.

fix(julia): fix incorrect documentation query

---

queries/inko/highlights.scm

This keyword is added as part of the upcoming 0.18.0 release. The Tree sitter commit is already included as part of 3edea87978b2ee93b197513e5cdf86012d33b7fa.

feat(inko): highlight the "copy" keyword

---

queries/go/highlights.scm
queries/go/injections.scm

Injections were hidden due to a string content child node

Fix go regex injections, add string regex highlights

---

queries/zig/indents.scm

This PR improves indentation for Zig.
* enum and union declarations are indented
* if, while, and for expressions are indented

improve indent queries for zig

---

lockfile.json
queries/inko/highlights.scm

This keyword will be released in 0.18.0 and deprecate the "class" keyword, which in turn will be removed in 0.19.0.

feat(inko): highlight the "type" keyword

---

queries/ruby/injections.scm
tests/query/injections/ruby/test-ruby-debugger.rb

The [ruby debugger](https://github.com/ruby/debug?tab=readme-ov-file#bindingbreak-method) allows passing a String that gets executed as ruby code before dropping into the debugger.
This PR adds support for marking the string content as ruby code.
```ruby
binding.b(pre: "puts 'run this ruby code before dropping me into the debugger'")
binding.break(do: "puts 'run this ruby code and continue executing'")
```

feat: add injection for ruby debugger command strings

---

queries/leo/highlights.scm
queries/leo/indents.scm

feat(leo): highlights casting and record expressions added
fix(leo): '}' now dedents correctly, sorted indents to alphabetical order

feat(leo): highlights casting and record expressions added, fix(leo): '}' now dedents correctly

---

queries/xml/indents.scm

Confusing as it is, https://github.com/heurist/nvim-treesitter/blob/master/CONTRIBUTING.md?plain=1#L394 says:
```query
@indent.dedent      ; dedent children when matching this node
@indent.branch      ; dedent itself when matching this node
```
@indent.branch is therefore the appropriate choice for de-indenting.

fix(xml): properly indent closing tags

---

queries/bash/injections.scm

`printf` injection includes raw string quotes from bash. Leads to incorrect highlighting for `%` at the end of the string.
Capture both regular and raw strings with quotes and offset the range to remove them.
Before and after:
<details>
<summary>minimal.lua</summary>
```lua
for name, url in pairs {
nvim_treesitter = 'https://github.com/nvim-treesitter/nvim-treesitter.git',
} do
local install_path = vim.fn.fnamemodify('nvim_issue/' .. name, ':p')
if vim.fn.isdirectory(install_path) == 0 then
vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
end
vim.opt.runtimepath:append(install_path)
end
require'nvim-treesitter.configs'.setup {
sync_install = true,
ensure_installed = { 'bash', 'printf' },
highlight = { enable = true },
}
vim.api.nvim_set_hl(0, '@character.printf', { fg = …
```

fix(bash): offset injection content

---

queries/php_only/highlights.scm
tests/query/highlights/php/keywords.php

Hello!
This fixes highlighting for grouped functions and constants like:
```php
use function Foo\{bar, baz};
use const Foo\{FOO, BAR};
```
Thanks!

fix(php): properly highlight grouped imported functions and constants

---

queries/rbs/highlights.scm

Some rbs highlight definitions are missing.
This is reported by https://github.com/joker1007/tree-sitter-rbs/issues/15
I apply the fixes to this repository.

fix(rbs): fix highlight queries of rbs that is missing some definitions

---

queries/matlab/indents.scm

Fixes https://github.com/acristoffers/tree-sitter-matlab/issues/19

fix(matlab): indentation of arguments statement

---

queries/hyprlang/injections.scm

Example:
```
bind = SHIFT, Print, exec, slurp | grim -g - - | wl-copy
bind = $mod, P, exec, uwsm app -- hyprpicker --autocopy --format=hex
```
Before:
After:

feat(hyprlang): bash injections for exec keybindings

---

queries/nix/highlights.scm

Functions in Nix are only highlighted when they aren't part of a set. This may be intentional since GitHub highlights them the same way (see below), though.
```nix
someFunc 32;
lib.someOtherFunc 48;
lib.hello.someOtherFunc { };
```
There probably is a more efficient way to do this, but I don't know Scheme. More specifically, I couldn't figure out how to select the last node and had to write two different queries (one for `a.b.func` and one for `a.func`).

feat(nix): Fix function highlights when part of a set

---

queries/css/highlights.scm

I'm not sure what the best capture would be here, I used `@variable` because it's the most generic capture for an identifier.

feat(css): highlight @keyframes name

---

lua/nvim-treesitter/shell_command_selectors.lua

While tracking down the cause of Windows-specific CI failures on https://github.com/nvim-treesitter/nvim-treesitter/pull/7481, I found two improvements to make.
1. `:TSInstallSync` didn't report failures on Windows because it was checking the return code of `popd` instead of the actual command.
2. The root cause of the failure is a `_Static_assert` statement, which is a C11 feature. This project should set the C standard version to C11, since [tree-sitter always does that](https://github.com/tree-sitter/tree-sitter/blob/201b41cf11fb217a1f1ce03ea25b83e62b7b48cb/cli/loader/src/lib.rs#L821).

Improve parser build reliability

---

queries/verilog/highlights.scm

Add missing highlight for Verilog/SystemVerilog non-integer type like real to queries/verilog/highlights.scm

Add highlight for non-integer type (real)

---

scripts/ci-install.sh

Old name can be removed after 0.10.4 release

ci(install): adapt to new Neovim release artefact names

---

queries/typescript/highlights.scm

Default values for parameters are being highlighted as parameters when the default value is an `identifier`, so use the field names to distinguish them and only highlight the parameter.
Test
```typescript
function foo(bar: Type = value) {}
function foo(bar?: Type = value) {}
``` 
Tree
```scheme
((program
(function_declaration
name: (identifier)
parameters: (formal_parameters
(required_parameter
pattern: (identifier)
type: (type_annotation
(type_identifier))
value: (identifier)))
body: (statement_block))
(function_declaration
name: (identifier)
parameters: (formal_parameters
(optional_parameter
pattern: (identifier)
type: (type_annotation
(type_identifier))
value: (identifier)))
body: (statement_block)))
```

feat(typescript): don't highlight default values as parameters

---

queries/query/highlights.scm

Highlight support for the new `MISSING` syntax

feat(query): highlights for missing nodes

---

scripts/format-queries.lua

This prevents the formatter for appending a space after the "." in a predicate prefix, and changes it to a "#" to match all other occurrences in the codebase.

fix(formatter): prefer #-prefixed predicates

---

scripts/format-queries.lua

This commit makes missing nodes take formatting identical to that of regular named nodes, with the only exception being that a newline will not be prepended to a node name. E.g. this pattern:
```query
(MISSING identifier)
```
will *not* be changed to:
```query
(MISSING
(identifier))
```

feat(formatter): support formatting missing nodes

---

lockfile.json
queries/nu/highlights.scm

The nu parser is about to make a [breaking change](https://github.com/nushell/tree-sitter-nu/pull/181).

feat(nu): added some new operators, removed deprecated keyword `register`

---

queries/hyprlang/injections.scm

Fixes #7596 by adding an optional node. There is still an edge case if the keybind description is exactly `exec`, but I don't expect people to write their config like that. Solved by anchoring the injection injection to the last node.
```
bindd = MODS, key, exec, exec, params
```

feat(hyprlang): bash injection for bindings with descriptions

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/enforce/folds.scm
queries/enforce/highlights.scm
queries/enforce/indents.scm
queries/enforce/injections.scm
queries/enforce/locals.scm

Add `enforce` parser.
> Enforce Script is the language that is used by the [Enfusion](https://community.bistudio.com/wiki/Enfusion) engine first introduced in [DayZ](https://community.bistudio.com/wiki/Category:DayZ) Standalone. It is a Object-Oriented Scripting Language (OOP) that works with objects and classes and is similar to C# programming language.
[Official documentation](https://community.bistudio.com/wiki/DayZ:Enforce_Script_Syntax)

feat: add enforce

---

lua/nvim-treesitter/parsers.lua

See https://github.com/tree-sitter/tree-sitter/actions/runs/13217922261/job/36899406179#step:10:588
The razor grammar has a dependency on the c-sharp grammar, so npm is required to generate this from source.

fix(razor): mark `npm` as required for generating from source

---

queries/sparql/injections.scm

This adds an injection for the `REGEX()` function documented [here](https://www.w3.org/TR/sparql11-query/#func-regex)
Before:
After:

feat(sparql): add regex injection

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua

The parser has neither queries nor a listed maintainer here and hasn't
seen updates in two years.

feat(parsers)!: drop org

---

lua/nvim-treesitter/install.lua

Every now and then when a parser is renamed/removed or something, it will fail with `trying to index `parser_config` a nil value because we are not just continuing to execute even if it is nil or not

fix(install): early return if parser_info does not exist

---

lockfile.json
queries/inko/highlights.scm

This keyword is deprecated as of 0.18.1 (released on February 12, 2025) and is being removed as part of the upcoming 0.19.0 release.

Remove the "class" keyword

---

queries/gomod/highlights.scm

New version of Go (1.24) introduces a new directive, `tool` into go.mod file: https://tip.golang.org/doc/modules/managing-dependencies#tools.
This PR adds the tool directive support to highlights for `gomod`.

feat(gomod): support `tool`

---

queries/yaml/highlights.scm

**Problem**  
In yaml there are some strings that, when not unquoted, are evaluated as boolean values instead of strings, for example `off` or `no`. This is also known as [yaml's Norway problem](https://www.bram.us/2022/01/11/yaml-the-norway-problem/), and results in easy to overlook bugs since the syntax highlighting of those tokens as string is quite misleading.
**Solution**  
The PR changes the highlight group of those strings to `@boolean`. It does not affect quoted strings. The specific strings this highlight-group-change is triggered on are taken from [yamllint's related `truthy` rule](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.truthy).
---
before
after

feat(yaml): highlighting to help deal with yaml's Norway problem

---

queries/java/injections.scm

Since Java 23, java documentation supports markdown.
It is supported by a `///` line comment followed by mandatory white space: https://openjdk.org/jeps/467
Before:
After:
I wasn't able to figure out a way to use `injection.combined` alongside `#offset!` such that the prefix was removed from ALL lines in the "block" (not just the first one) to treat as one markdown document, which is what I wanted. As a workaround it uses `markdown_inline` for now, which seems ok a start. Any ideas?
Thank you for nvim-treesitter.

feat(java): add injections for markdown documentation comments

---

queries/promql/highlights.scm
queries/promql/injections.scm
scripts/minimal_init.lua
tests/query/highlights/promql/regex.promql
tests/query/highlights/yaml/promql-on-prometheus-rules.yaml
tests/query/injections/promql/regex.promql

In Prometheus, label values are treated as strings when used with the `=` and `!=` operators, and as regular expressions when used with the `=~` and `!~` operators.
Injecting and then highlighting all label values as regex leads to a situation where entirely valid **string** label values containing regex special characters are mistakenly parsed and highlighted as regex. This results in syntax errors, causing labels to be highlighted incorrectly.
For example, in `foo{bar=~"[a-z]{1,3}"}`, `{` and `}` are regex special characters, so regex highlighting is expected. However, in `foo{path="/foo/{id}"}`, `{` and `}` are just part of the string and have no special meaning, so the whole value should be highlighted as a string.
---
Before:
After:

feat(promql): do not use regex for string labels

---

lockfile.json
queries/liquid/highlights.scm
queries/liquid/injections.scm

Adds highlights and injections for `front_matter` node.
Follows the same convention as the Markdown queries ([injections](https://github.com/nvim-treesitter/nvim-treesitter/blob/bf18d4dc8d9a7a61e855190bc154df12d6536741/queries/markdown/injections.scm#L12), [highlights](https://github.com/nvim-treesitter/nvim-treesitter/blob/bf18d4dc8d9a7a61e855190bc154df12d6536741/queries/markdown/highlights.scm#L108)), as this does more or less the same thing.

feat(liquid): Add queries for front_matter

---

queries/typst/folds.scm

for 'for' blocks and 'if/else' expressions.
Actually I would like the folds to be more fine grained, but the treesitter grammar doesn't give me the information I need for that. I can't seem to make it fold individual if/else branches (see below, it folds the entire expression) nor can I distinguis multiline content blocks like this one:
```
#[
Inlined content here
]
```
Perhaps I'll invest some time into that another day, but for the moment being able to fold large `for`/`if/else` expressions is a big win in my opinion.

feat(typst): add more folds

---

queries/gleam/indents.scm

The current `import` indent causes an indentation to trigger after a line with `import ...`.  I _think_ the more correct is to only begin indentation when doing an `unqualified_imports`, i.e. 
```gleam
// don't  indent from _just_ this
import my_library.{
// but indent for this
type Something
}
```
Obviously could very well be wrong about this, but I've been getting indentation bugs with what's on `master`.  It does
```gleam
import gleam/result
|
```
which feels wrong.

fix(gleam): indent on unqualified imports rather than import

---

queries/markdown/highlights.scm

Required to make https://github.com/neovim/neovim/pull/31324 work with
nvim-treesitter.

feat(markdown): completely conceal codeblock fences on nightly

---

queries/make/folds.scm

Makes `define`-statements in Makefiles fold. Previously they didn't, which made them stand out in between rule statements, requiring unnecessary amounts of scrolling.

feat(make): fold `define` statements.

---

queries/kdl/highlights.scm

Fixes the highlighting queries for KDL so everything isn't highlighted as a variable due to the order of the queries previously meaning several queries were ignored.
I also changed the node names to be highlighted as `@tag` since KDL is an xml-like format so @tag seemed more appropriate than `@type` and it differentiates it from the type annotations.
This does NOT update to the latest KDL version 2, that would need grammar changes. It does "mostly" work with
KDL 2 though (notably unquoted strings seem to throw the grammar off.).
(Everything that's white is `@variable` due to the broad `(identifier) @variable` that was after the queries that were targeting specific identifiers)

fix(kdl): Highlight query order

---

queries/markdown/folds.scm

Turns out we can use plain old `#trim!` here rather than `#trim! 1 1 1 1` due to the slight improvements to the default trim functionality on nightly
Supercedes #3442

feat(markdown): fold sublists

---

queries/jsx/highlights.scm

References https://github.com/folke/ts-comments.nvim/blob/1bd9d0ba1d8b336c3db50692ffd0955fe1bb9f0c/lua/ts-comments/config.lua#L33; the `jsx_attribute` query is for the inside of tags, and works nicely in my testing

feat(jsx): commentstring query

---

lua/nvim-treesitter/install.lua

Problem: cannot run `:TSUpdate synchronously`
Solution: pass callback used after exiting jobs
(like in `install-parsers`).

feat(install): allow pass callback to `update()`

---

queries/python/locals.scm
queries/snakemake/locals.scm

This enables fuzzy finder such as snacks.picker to match snakemake rules as treesitter symbols

Add snakemake rules to locals

---

queries/rust/injections.scm

This properly injects html and json in `json!`, `serde_json::json!` and `html!` etc. macro invocations. Before rust was being injected at the same time which caused the injection to break.
Before:
After:

fix(rust): inject html and json in macro invocations

---

queries/rust/injections.scm

inject regex into the [regex::RegexBuilder](https://docs.rs/regex/latest/regex/struct.RegexBuilder.html) and [regex::bytes::RegexBuilder](https://docs.rs/regex/latest/regex/bytes/struct.RegexBuilder.html) as i couldn't find any mention of a `ByteRegexBuilder` outside of this repo.
before:
after:

fix(rust): inject regex into RegexBuilder instead of ByteRegexBuilder

---

queries/bibtex/highlights.scm

- I think `@property` fits better since those are key/value pairs.
- `@markup.link.label` fits with latex's captures for citations using `@markup.link`.

feat(bibtex): use better captures

---

queries/python/highlights.scm
tests/query/highlights/python/fields.py

assigned higher highlight priority to `@variable.member` over `@type.builtin` to correctly highlight `type` since it is a regular attribute in this context

fix(python): don't highlight attribute name as builtin

---

queries/python/highlights.scm
tests/query/highlights/python/fields.py
tests/query/highlights/python/functions.py

same as #7712 but for parameters

fix(python): don't highlight parameter name as builtin

---

runtime/queries/commonlisp/highlights.scm
runtime/queries/racket/highlights.scm
scripts/format-queries.lua

Problem: Some very long patterns were not formatted correctly.
Solution: Increase the match limit when iterating to 1024.

fix(formatter): increase match limit

---

queries/typst/highlights.scm

Test code:
~~~typst
Adding `rbx` to `rcx` gives
the desired result.
What is ```rust fn main()``` in Rust
would be ```c int main()``` in C.
```rust
fn main() {
println!("Hello World!");
}
```
This has ``` `backticks` ``` in it
(but the spaces are trimmed). And
``` here``` the leading space is
also trimmed.
~~~

feat(typst): highlight language name as @label

---

queries/perl/highlights.scm
queries/perl/injections.scm

- **feat(perl): highlight newer nodes**
- **fix(perl): injections for s///e should fully re-parse**
- **feat(perl): bump the parser**
This is bundled with some new features i just did for the parser. only open question i
have is if globs (`*foo{THING}`) which represent package tables should get the highlight
for `variable` or `module`, b/c it kinda is a namespace (tho pivoted from the usual
meaning). For now i was conservative and made it variable

more perl syntax

---

queries/python/highlights.scm
tests/query/highlights/python/functions.py

`@functon.method.call` currently overrides `@functon.builtin`.
Reorder builtin functions after other function calls.

fix(python): reorder builtin functions after other function calls

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/caddy/folds.scm
queries/caddy/highlights.scm
queries/caddy/indents.scm
queries/caddy/injections.scm

⚠️⚠️⚠️ This PR requires Vim PR to be merged, waiting for https://github.com/vim/vim/pull/16525
Helloooo! It's me again
Thanks to Caddy documentation, this was the easy one:
_Warning: Screenshot is an image_

feat: Added Caddyfile support

---

queries/dhall/highlights.scm

The dhall language `highlights.scm` queries are missing several builtins. I used the [language reference](https://docs.dhall-lang.org/references/Built-in-types.html) and the [treesitter implementation](https://github.com/jbellerb/tree-sitter-dhall/blob/master/queries/highlights.scm) as references:
- highlight builtin type [`Bool`](https://docs.dhall-lang.org/references/Built-in-types.html#bool)
- highlight import [`... as Bytes`](https://docs.dhall-lang.org/references/Built-in-types.html#keyword-as-bytes) and the bytes literal (ie. [`0x"deadbeef"`](https://docs.dhall-lang.org/references/Built-in-types.html#keyword-as-bytes))
- highlight builtin functions [`Date/show`](https://docs.dhall-lang.org/references/Built-in-types.html#function-date-show), …

fix(dhall): highlight several missing builtins

---

.github/workflows/tests.yml

plenary.busted seems to be broken (you could even say... "busted" 😬 ) on Nvim 0.11, so stick with v0.10.4 on `master`.

ci(tests): run tests on v0.10.4

---

queries/python/highlights.scm
tests/query/highlights/python/docstrings.py

I read [PEP 257](https://peps.python.org/pep-0257/#what-is-a-docstring) again. It says:
> A docstring is a string literal that occurs as the first statement in a module, function, class, or method definition. Such a docstring becomes the `__doc__` special attribute of that object.
but also in the paragraph after the next:
> String literals occurring elsewhere in Python code may also act as documentation.
So, *every* string literal can be treated as a docstring (and is valid for Python as long as the indentation is correct), even with single quotes.
Since we are not distinguishing between
- docstrings that become the `__doc__` special attribute,
- package / module / class / function / attribute docstrings and 
- additional docstrings,
my suggestions is to just say: Every standalone string …

fix(python): Highlight all types of docstrings

---

queries/yaml/injections.scm
tests/query/injections/yaml/bash-on-taskfiles.yml

This change would inject bash for yaml [Taskfiles](https://taskfile.dev/) like is currently done for yaml Gitlab/Github pipeline configs. I found it helpful in my config so I thought it could be nice to share with others (especially since it's a simple change to the current injections).
Before:
After:

feat(yaml): inject bash for Taskfiles

---

queries/yaml/injections.scm
tests/query/injections/yaml/bash-on-taskfiles.yml

This builds on the excellent addition bash injections in taskfiles in #7804 
I saw that `cmd` was missing both with and without multiline.
Before:
After:

More bash injection support for Taskfile

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/brightscript/folds.scm
queries/brightscript/highlights.scm
queries/brightscript/indents.scm
queries/brightscript/injections.scm

[brightscript language reference](https://developer.roku.com/docs/references/brightscript/language/brightscript-language-reference.md)
> Roku BrightScript is a powerful scripting language that makes it easy and quick to build media and networked applications for embedded devices. 
I built this parser + queries largely last year, and have been using it myself for awhile now, and thought it might be time to make this the official brightscript language parser and queries for nvim-treesitter! The Roku dev community is quite small, but it does exist and I hope this parser can help those that want to use neovim for brightscript development!

feat(brightscript): Addition of brightscript parser and queries

---

queries/fish/highlights.scm

Improve `fish` highlights for `$` by highlighting it as `@punctuation.special` and highlighting the special variables as builtins.

feat(fish): improve fish highlights

---

queries/nu/folds.scm
queries/nu/indents.scm

Fixes indents/folds for match statements, e.g.
```nushell
match $foo {
true => 0
_ => 1
}
```

fix(nu): add missing `ctrl_match` to query files

---

queries/blade/injections.scm

Injecting php was broken upstream so this is a temporary fix until upstream fixes it.
See https://github.com/nvim-treesitter/nvim-treesitter/issues/7842
CC: @ribru17

fix(blade): fix blade highlighting

---

runtime/queries/inko/locals.scm

This way tooling that makes use of these queries (e.g. snacks.nvim) is aware of the scoping of Inko types and methods.

feat(inko): add scoping to the locals queries

---

.github/workflows/test-core.yml

Poor Windows runners can't handle unthrottled parallel install 😞

ci(test): throttle all install steps

---

runtime/queries/bash/highlights.scm

```bash
printf -v var 'hello\nworld'
```

feat(bash): highlight variable argument for `printf -v`

---

runtime/queries/haskell/injections.scm

fix(haskell): properly set inline-python injection language

---

runtime/queries/just/highlights.scm

An issue with trying to only highlight known built-ins is that more recent versions will include new functions that won't be correctly highlighted. Better to be permissive and let a linter or LSP (or user running the justfile) determine what is a valid function.

feat(just): Change function.call to match anything in function position

---

doc/nvim-treesitter.txt
lua/nvim-treesitter/install.lua
plugin/nvim-treesitter.lua
scripts/install-parsers.lua

Problem: People complain about noisy `install()`.
Solution: Gate operation summary behind `summary` install option
(default false, set to true for interactive `:TS*` commands).

fix(install): don't print operation summary by default

---

runtime/queries/git_config/highlights.scm
runtime/queries/git_config/injections.scm

Git config's sections, variable names, and (often) subsections are case-insensitive.
Source: https://github.com/git/git/blob/master/Documentation/config.adoc (`git help config`)
---
Instead of doing a full case-insensitive matching in the (few) places where we'd put the non-normalised variable names, I went for `#any-of?` because:
1. What are the chances anybody would use any casing other than `lowerCamelCase` or `lowercase`?
2. Nobody wants to read `(#lua-match? @keyword.import "^[iI][nN][cC][lL][uU][dD][eE][Ii][fF]$"))`
3. `#any-of` is generally cheaper (read: faster) to run
Oh, and it's a rule in the `CONTRIBUTING` guildelines!
I also ran `luacheck` and `stylua`.

fix(git_config): match full-lowercase Git config variables

---

runtime/queries/bash/highlights.scm

This commit aligns the shebang highlighting in bash syntax to what the Linux kernel will recognise as a valid shebang construct.
In summary, the kernel will accept both headers:
#!/usr/bin/env lua
#! /usr/bin/env lua
The second one is quite prominently used throughout documentation online, such as on Wikipedia's page for Shebang (Unix) [1].
Some sources are adamant it wouldn't be supported at a kernel level, but it looks to me, upon closer inspection of the current kernel code [2], that it is indeed quite evidently valid.  It'll simply skip over to the first character that's neither a space 0x20 nor a tab 0x09.
[1] https://en.wikipedia.org/wiki/Shebang_(Unix)
[2] https://github.com/torvalds/linux/blob/ec7714e4947909190ffb3041a03311a975350fe0/fs/binfmt_script.c#L44-L71

fix(bash): highlight shebang also when spaced

---

runtime/queries/vue/highlights.scm

I saw other queries setting the comment string (https://github.com/nvim-treesitter/nvim-treesitter/pull/7704)
Given that inside a <script> and <style> tag I can comment a line (I think this is due to @injection.language), I would expect the same to be applied to the vue file when commenting html.
IMO given that the default vue content is html this should be the default functionality. If there is a more correct approach please LMK.
See full context: https://github.com/nvim-treesitter/nvim-treesitter/pull/7954

feat(vue): add template commentstring metadata

---

runtime/queries/fish/highlights.scm

builtin commands:
* `abbr` [source](https://fishshell.com/docs/current/cmds/abbr.html)
* `path` [source](https://fishshell.com/docs/current/cmds/path.html)
builtin variables:
* `fish_cursor_*` [source](https://fishshell.com/docs/current/interactive.html#vi-mode-commands)
See:
* #7970

fish parser: adds additional builtin commands and variables

---

runtime/queries/http/folds.scm

Folding sections is often "too much" and "lacks semantics", i.e., a section is a broad concept. Here's an example:
Original file:
Current behavior (zM):
New behavior (zM):

fix(http): prefer folding requests directly

---

.tsqueryrc.json

I assume we already check this elsewhere, is it worth removing that logic?

ci: ensure parsers have a supported ABI version

---

runtime/queries/jinja_inline/highlights.scm
tests/query/highlights/jinja/filters.jinja
tests/query/highlights/jinja/tests.jinja
tests/query/highlights/jinja/variables.jinja

The majority of jinja variables aren't assigned any highlights at all. Assign `@variable` to all identifiers.
Jinja filters without parameters are not highlighted as functions: add a query for these.
Refine the existing `@variable.member` to only capture identifiers instead of broader nodes.
Background: I configure yaml to inject this parser for ansible highlighting. But due to the missing highlight captures, most jinja is instead highlighted as yaml string (green), which is confusing. Additionally you can see another bug `abc.list_two` with the overly broad `@variable.member` capture.
Before:
After:
cc: @cathaysia (and thank you for this parser)

fix(jinja): assign highlights to all variables and functions

---

lua/nvim-treesitter/parsers.lua
runtime/queries/chatito/highlights.scm

node `(eq)` is replaced by field `eq: _`

feat(chatito)!: update parser and queries

---

lua/nvim-treesitter/install.lua

Currently once the `install_status` is set for a language installing will never proceed, even when `force` is set. For my current setup this prevents updating, some info below in the `Updating` section if it matters.
Regardless of my specific issue I believe the notion of `force` should trigger an install / update when possible. To make this happen I've updated `install_status` so that it is only set for a language while an installation is in progress. After the task is completed `install_status` is cleared for the language. As a consequence of this `install_status` should really only be accessed in the `install_lang` function and can no longer be used to get the result of an installation.
What I currently do is always trigger `install` for a list of languages in my config using:
```lua …
```

fix(install): clear status after install

---

lua/nvim-treesitter/config.lua

Follow up to: https://github.com/nvim-treesitter/nvim-treesitter/pull/8021
More info on why duplicate dependencies can cause problems: https://github.com/nvim-treesitter/nvim-treesitter/pull/8021#issuecomment-3114962375
Tests without `--max-jobs`:  https://github.com/nvim-treesitter/nvim-treesitter/actions/runs/16518667608

fix(install): skip duplicate dependencies

---

plugin/filetypes.lua

It looks like this mapping got lost in the migration to the main branch.
Related #4189

fix(ini): register dosini and confini filetypes

---

SUPPORTED_LANGUAGES.md
lua/nvim-treesitter/parsers.lua
runtime/queries/sproto/folds.scm
runtime/queries/sproto/highlights.scm
runtime/queries/sproto/indents.scm
runtime/queries/sproto/injections.scm

https://github.com/cloudwu/sproto
<details>
<summary>Representative code sample</summary>
```sproto
.Person {	# . means a user defined type 
name 0 : string	# string is a build-in type.
id 1 : integer
email 2 : string
.PhoneNumber {	# user defined type can be nest.
number 0 : string
type 1 : integer
}
phone 3 : *PhoneNumber	# *PhoneNumber means an array of PhoneNumber.
height 4 : integer(2)	# (2) means a 1/100 fixed-point number.
data 5 : binary		# Some binary data
weight 6 : double   # floating number
}
.AddressBook {
person 0 : *Person(id)	# (id) is optional, means Person.id is main index.
}
foobar 1 {	# define a new protocol (for RPC used) with tag 1
request Person	# Associate the type Person with foobar.request
response {	# define the foobar.response type
ok 0 : boolean
}
}
``` …

feat(sproto): add parser

---

runtime/queries/fennel/highlights.scm

Highlights the dollar symbol properly in multi-symbol contexts like `$.some.properties`.

fix(fennel): highlight $ in multi-symbol context properly

---

runtime/queries/snakemake/highlights.scm
runtime/queries/snakemake/indents.scm
runtime/queries/snakemake/locals.scm
tests/indent/snakemake/blocks.smk
tests/indent/snakemake/directive_parameters.smk
tests/indent/snakemake_spec.lua

This PR updates indents, locals and highlights queries for snakemake, and adds tests for indent queries.
PS: To run tests for python/snakemake only, I deleted all *_spec.lua files except for snakemake_spec.lua via `find tests/ -depth -name '*python*' -prune -o -name '*_spec*' -print -delete`. Is there a less drastic way to select which tests to run via `make tests`?

feat(snakemake): update queries

---

runtime/queries/glimmer_javascript/folds.scm
runtime/queries/glimmer_typescript/folds.scm

small one -- noticed I was missing a fold.
Preview:

Add glimmer_template to folds list for glimmer_javascript and glimmer_typescript

---

lua/nvim-treesitter/parsers.lua
runtime/queries/koto/highlights.scm

Breaking changes: `call`, `index`, `lookup` fields removed

feat(koto)!: update parser and queries

---

runtime/queries/cylc/highlights.scm
runtime/queries/earthfile/highlights.scm
runtime/queries/make/highlights.scm
runtime/queries/matlab/highlights.scm
runtime/queries/python/highlights.scm

These should be `@punctuation.special`. Added the highlight for python, cylc, and make. Corrected it for earthfile and matlab.

fix: align line continuation highlights 

---

runtime/queries/python/highlights.scm

feat(python): highlight special brackets in `format_expression`

---

lua/nvim-treesitter/parsers.lua
runtime/queries/nu/highlights.scm

Breaking change, `param_cmd` renamed to `param_completer`.

feat(nu)!: update parser and queries
