nvim-treesitter/nvim-treesitter

queries/rust/highlights.scm
tests/query/highlights/rust/for.rs

Fixes #3641
@Trard Can you test, please?

highlights(rust): distinguish between "for" in loops and impl_item

---

lua/nvim-treesitter/install.lua

fix: explain what's wrong when installing a non-existing parser

---

lua/nvim-treesitter/parsers.lua
queries/gitattributes/highlights.scm
tests/query/highlights/gitattributes/test.gitattributes

This also removes the `experimental` flag.

test(gitattributes): add tests for highlights

---

queries/lua/locals.scm

locals(lua): fix directive not applying

---

CONTRIBUTING.md

I used `scheme` as the language marker so that GitHub can highlight the comments properly.

docs: document all the captures in CONTRIBUTING.md

---

lua/nvim-treesitter/parsers.lua
queries/nickel/highlights.scm

Add nickel parser: https://github.com/nickel-lang/tree-sitter-nickel
Nickel lang: https://nickel-lang.org/
The highlights.scm file is from: https://github.com/nickel-lang/tree-sitter-nickel/blob/main/queries/highlights.scm (I asked the author and he is ok with upstreaming it)

parsers: add nickel parser

---

queries/nickel/highlights.scm

As suggested by @theHamsta : https://github.com/nvim-treesitter/nvim-treesitter/commit/470b872d5747819623c7b3a98eb320dc3cab95b4#r87323447

nickel: use @boolean

---

README.md
lua/nvim-treesitter/parsers.lua
queries/git_rebase/highlights.scm
queries/git_rebase/injections.scm

Grammar from : https://github.com/the-mikedavis/tree-sitter-git-rebase

feat(git_rebase): add git_rebase parser

---

lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/fold.lua
lua/nvim-treesitter/highlight.lua
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/parsers.lua
lua/nvim-treesitter/query.lua
lua/nvim-treesitter/shell_command_selectors.lua
lua/nvim-treesitter/utils.lua

Very incomplete but it is a start.

feat(emmy): add emmylua annotations

---

CONTRIBUTING.md
queries/rust/highlights.scm

fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/3647

`@type.qualifier` and `@storageclass` in rust

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/vhs/highlights.scm

[VHS](https://github.com/charmbracelet/vhs) is a tool that generates terminal gifs from code, like asciicinema, but with actual gifs as result, and instead of recoding it, you generate them from code.
`.tape` is the extension of those files.
First time doing this, not sure if I did everything right... 
- TS: https://github.com/charmbracelet/tree-sitter-vhs
- "compiler": https://github.com/charmbracelet/vhs
cc/ @maaslalani

adding vhs (.tape) support

---

lua/nvim-treesitter/parsers.lua
queries/awk/highlights.scm
queries/awk/injections.scm

Requested in https://github.com/nvim-treesitter/nvim-treesitter/issues/2282#issuecomment-1235334660

feat: add awk

---

CONTRIBUTING.md

docs: add `@nospell` to contributing.md

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/mermaid/highlights.scm
scripts/update-readme.lua

The grammar is incomplete so I marked it as experimental.

feat: add mermaid

---

README.md
lua/nvim-treesitter/parsers.lua
queries/gitcommit/highlights.scm
queries/gitcommit/injections.scm

Here is the parser: https://github.com/gbprod/tree-sitter-gitcommit
I use it from days without any problem :)

feat: add gitcommit parser

---

queries/gitcommit/highlights.scm

feat(gitcommit): add spell checking

---

lua/nvim-treesitter/install.lua

Fixes #3631
@rstacruz could you test, please?

fix(install): don't auto-install ignored parsers

---

queries/r/indents.scm
tests/indent/r/pipe.R
tests/indent/r_spec.lua

indents(r): support special operator

---

queries/twig/highlights.scm

This commit adds better highlighting on twig operators

feat(twig): improve twig highlights

---

queries/c/highlights.scm
queries/cpp/highlights.scm
tests/query/highlights/cpp/test.cpp

- make `primitive_type`  `@type.builtin` 
- make `auto` `@type.builtin`

C, Cpp, highlight little improvements

---

lua/nvim-treesitter/install.lua
lua/nvim-treesitter/shell_command_selectors.lua
lua/nvim-treesitter/utils.lua

shell: respect shellslash option on Windows

---

.github/workflows/update-lockfile.yml

ci: Add name of updated parsers to commit message

---

queries/yaml/highlights.scm
queries/yaml/injections.scm

injections(yaml): fix injections

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/t32/folds.scm
queries/t32/highlights.scm
queries/t32/injections.scm
queries/t32/locals.scm
tests/query/highlights/t32/comments.cmm
tests/query/highlights/t32/keywords.cmm
tests/query/highlights/t32/literals.cmm
tests/query/highlights/t32/var.cmm

TRACE32 is a debugger for embedded software development that comes with a scripting language for automation. Here is a request to integrate the existing parser.

feat(t32): initial support

---

lockfile.json
queries/julia/highlights.scm

- Replace `scoped_identifier` with `field_expression` in function names
- Replace true and false with `boolean_literal`
See https://github.com/tree-sitter/tree-sitter-julia/pull/85

Update Julia highlights

---

queries/nix/highlights.scm
queries/nix/injections.scm

follow up to #3842, now that I'm more familiar with this

improve nix highlights and injections

---

lua/nvim-treesitter/ts_utils.lua

At the moment, the regular `vim.keymap.set` does not work with nvim-treesitter-textobjects mappings because of side effects interference in `update_selection` function (I suspect `vim.cmd "normal! o"`).
Also related to https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/342.
This patch aims at having no side effects when updating selection.
I've only tested it manually and it seems to be working fine. Someone could help me with more robust tests?

fix(ts_utils): Remove side effects from `update_selection`

---

README.md

Preview: https://github.com/theHamsta/nvim-treesitter/tree/matrix-badge

docs: link to Matrix instead of Zulip

---

queries/elm/highlights.scm

| ![image](https://user-images.githubusercontent.com/4299733/210155076-4e757b78-eab8-4f68-827c-74381026b7be.png) | ![image](https://user-images.githubusercontent.com/4299733/210155091-cbf32aec-0085-4b32-be42-aa91afabd6c8.png) |

highlights(elm): improve highlights

---

queries/ecma/indents.scm
queries/jsx/indents.scm
tests/indent/jsx/element_attributes.jsx
tests/indent/jsx/issue-3986.jsx
tests/indent/jsx/jsx_expression.jsx
tests/indent/jsx_spec.lua

Resolves #3986
(cannot really test auto correction for error nodes cause it breaks too much)

fix jsx tsx indents

---

.github/workflows/update-lockfile.yml

ci: properly fix lockfile action

---

tests/query/injection_spec.lua
tests/query/injections/html/test-html-injections.html
tests/query/injections/svelte/test-svelte-injections.svelte
tests/query/injections/vue/negative-assertions.vue
tests/query/injections/vue/test-vue-injections.vue

Use new negative assertion in tests to make sure typescript/scss injection are not also injected as javascript/css

allow negative assertion in injection tests

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/smali/highlights.scm
queries/smali/injections.scm

This PR will add smali support, which I've forked from https://git.sr.ht/~yotam/tree-sitter-smali to https://github.com/amaanq/tree-sitter-smali, and have updated to fix a couple bugs. 
Thanks @ObserverOfTime for the queries, they seem good to me and I'm still all-too-new to this, so if whenever I notice something feels a bit off, I'll edit the query appropriately.
Paging @theHamsta for a review as he was the one that gave me the courage to maintain smali myself and submit a new PR from #3839 :)
Also, obvious note but it is of course experimental :laughing: 
-Amaan

feat: add smali

---

CONTRIBUTING.md
queries/markdown/highlights.scm
queries/markdown_inline/highlights.scm

markdown: add strikethrough and blockquote captures

---

queries/kotlin/highlights.scm

| ![image](https://user-images.githubusercontent.com/4299733/212458341-96716139-7fc3-4f81-b27e-9ae662369c31.png) | ![image](https://user-images.githubusercontent.com/4299733/212458365-24728e75-7f65-473a-8ec3-e4c90bdfa640.png) |

highlights(kotlin): package keyword and declaration

---

lockfile.json
queries/c_sharp/highlights.scm

Update and fix the C# parser.
@clason Here is the fix in question.

Update and fix c_sharp parser

---

lockfile.json
queries/scala/highlights.scm

Note this can supersede https://github.com/nvim-treesitter/nvim-treesitter/pull/4174 since I also wanted to sync the queries.

chore: update Scala parser and add in new query

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/fsh/highlights.scm

Language Info: https://build.fhir.org/ig/HL7/fhir-shorthand/overview.html
TS Grammar: https://github.com/mgramigna/tree-sitter-fsh
Developed the grammar alongside some developers of the language itself. It seems to work/be correct! Let me know if I did this contribution right.. first time contributing to `nvim-treesitter`. Thanks :)

parsers: Add FHIR Shorthand (FSH)

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/thrift/highlights.scm

This PR adds a thrift parser+queries
cc: @leaxoy since they first brought up thrift in #2282
I'm a little iffy on the queries, so I'd like a few pairs of eyes to review that, but the actual grammar [here](https://github.com/duskmoon314/tree-sitter-thrift/blob/main/grammar.js) is very solid imo and is extensively tested.
Thanks!
-Amaan

feat: add thrift

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/htmldjango/folds.scm
queries/htmldjango/highlights.scm
queries/htmldjango/indents.scm
queries/htmldjango/injections.scm

It's not perfect but it works.
Closes #3402.

feat: add htmldjango

---

queries/json/highlights.scm

Also improved the formatting a little. :)

highlights(json): conceal escaped quote

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/thrift/highlights.scm

I refactored the grammar a bit, which is reflected in the queries.

Bump thrift

---

lockfile.json
queries/thrift/highlights.scm

Fixes bugs where certain ones went past where they should've ended

feat(thrift): refactor queries for better highlights

---

lockfile.json
queries/julia/highlights.scm

- Add `if_clause` highlighting
- Update Julia revision. See https://github.com/tree-sitter/tree-sitter-julia/pull/93

fix(julia/highlights): Add `if_clause`

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/capnp/folds.scm
queries/capnp/highlights.scm
queries/thrift/folds.scm
queries/thrift/highlights.scm

Apologies for the rapid flurry of PR's, I hadn't been able to get local highlights to reflect their change on demand after a parser/query update. Finally figured that out today and I've gotten a lot more improvements done as a result.
Thanks!
-Amaan

refactor(capnp, thrift): improve grammar & queries to stable for the foreseeable future

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/poe_filter/folds.scm
queries/poe_filter/highlights.scm
queries/poe_filter/indents.scm
queries/poe_filter/injections.scm

This adds support for [PoE item filters](https://www.pathofexile.com/item-filter/about).
If you think that's too niche, you can close the PR.

feat: add poe_filter

---

queries/php/highlights.scm

| ![image](https://user-images.githubusercontent.com/4299733/215255179-bea07ee1-f8c8-4a0f-88ca-bdcb55c7f872.png) | ![image](https://user-images.githubusercontent.com/4299733/215255144-fa4d33e2-c3f2-4d49-acce-3b09c15a339a.png) |

highlights(php): `instanceof` operand

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/kdl/folds.scm
queries/kdl/highlights.scm

https://github.com/kdl-org/kdl/blob/main/SPEC.md
Grammar/Parser: https://github.com/amaanq/tree-sitter-kdl
~~Not sure why, but whoever requested it in #2282 seems to have deleted their comment, which is unfortunate.~~
cc: @MultisampledNight since they requested it first in #2282
(dunno why I couldn't find the comment before, oops)
Only thing missing is having the special slashdash comments actually be commented out. Still working on that as this was a pain to begin with.
I would also like someone to go over my `@number/@float` queries, float is embedded into number so I'm not sure if I separated them properly.
Thanks!
-Amaan

feat: add kdl

---

queries/beancount/highlights.scm

changes to highlighting on the newest commit that will land on the next lock file update

highlights(beancount): update on latest updates

---

lua/nvim-treesitter/ts_utils.lua

Fixes https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/373
Note that this changes `ts_utils.update_selection()` which has been changed several times recently (#4015, #4114 using `gv`) and we're reverting it back to the older style using `o`.
It may introduce the side effects described in the older issues/PRs but for me this version works well. If more people can test this that would be very helpful!

Fix artefact in change mode (textobjects)

---

lockfile.json
queries/thrift/highlights.scm

I recently added support for a large extension of thrift, this PR addresses the query updates for that

chore: update thrift queries

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/elsa/highlights.scm

https://github.com/ucsd-progsys/elsa
cc: @glapa-grossklag since he requested it first in #2282 and since it's his grammar
Thanks!
-Amaan

feat: add elsa

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/smithy/highlights.scm

https://smithy.io/2.0/index.html
cc: @justinmk as he requested it in #2282, @keynmol as he is co-maintaining with me
This PR adds support for smithy.
Closes #4055
Thanks!
-Amaan

feat: add smithy

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/func/highlights.scm

cc: @liketurbo since he first requested it in #2282 
This PR adds support for FunC: https://ton.org/docs/develop/func/overview
Unfortunately the original parser I forked from seems to be inactive, so for now I'll point to my fork until my PR fixing a bunch of issues is merged.
Thanks,
Amaan

feat: add func

---

lua/nvim-treesitter/parsers.lua

chore: organize languages in parsers.lua

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/gosum/highlights.scm

https://go.dev/ref/mod#go-sum-files

feat: add gosum

---

queries/ecma/highlights.scm

highlights(ecma): limit constructor highlight

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/chatito/folds.scm
queries/chatito/highlights.scm
queries/chatito/indents.scm
queries/chatito/injections.scm
queries/chatito/locals.scm

[Chatito](https://github.com/rodrigopivi/Chatito) is a DSL for chatbot datasets.

feat: add chatito

---

queries/markdown_inline/injections.scm

added in https://github.com/MDeiml/tree-sitter-markdown/pull/71

feat(markdown): add latex injections

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/kdl/folds.scm
queries/kdl/highlights.scm
queries/kdl/indents.scm
queries/kdl/injections.scm
queries/kdl/locals.scm

This PR adds injections, indents, and locals to the queries and improves on folds

feat: improve KDL queries

---

queries/svelte/injections.scm

injections(svelte): add pug injection

---

queries/astro/injections.scm

This adds injections for SCSS, which resolves part of https://github.com/virchau13/tree-sitter-astro/issues/9.

astro: add injections for scss

---

queries/php/highlights.scm

This PR could have been a discussion thread, but I wanted to show the code.
This PR refines the queries related to namespaces and scoping.
Mainly for consistency with other languages' namespace-related highlights.
| ![image](https://user-images.githubusercontent.com/4299733/215266731-e1f83c64-873e-4118-8991-f9555d0d5eab.png) | ![image](https://user-images.githubusercontent.com/4299733/215266669-3a464344-8052-41f6-b284-118b93fee1f8.png) |
| ![image](https://user-images.githubusercontent.com/4299733/215267188-2957896a-41f2-466a-83f5-2143122cf804.png) | ![image](https://user-images.githubusercontent.com/4299733/215267208-e5156433-4bf3-4aba-b2ac-6e218dca6ce1.png) |
| ![image](https://user-images.githubusercontent.com/4299733/215267262-6ad87ce3-a912-4cd4-a2 …

highlights(php): fix queries related to namespaces

---

lockfile.json
queries/fish/highlights.scm

Updated `highlights.scm` to reflect breaking changes from https://github.com/ram02z/tree-sitter-fish/pull/19

chore(fish): update test command highlight query

---

doc/nvim-treesitter.txt
lua/nvim-treesitter/indent.lua
tests/query/highlights_spec.lua
tests/query/injection_spec.lua

Fix: Properly replace deprecated tsutils functions

---

lockfile.json
queries/ada/folds.scm
queries/ada/highlights.scm
queries/ada/locals.scm

ada(highlights,folds,locals): update to parser changes

---

lockfile.json
queries/fortran/highlights.scm

See https://github.com/stadelmanma/tree-sitter-fortran/commit/3738e8cf97a49d0dda735f3c55f5af68229825e1

Fix fortran highlights

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/highlighting_issue.yml
.github/workflows/lint.yml
.github/workflows/test-queries.yml
.github/workflows/tests.yml
.github/workflows/update-lockfile.yml
CONTRIBUTING.md
README.md

Apply `prettier` formatting on some documents and yml github action files.

Prettier formatting yml and md

---

queries/zig/highlights.scm

Recently I rearranged the keywords. This PR brings the highlights query file up to date with that.

Update Zig highlights

---

queries/gomod/highlights.scm

[gomod] highlight for module path

---

lockfile.json
queries/gosum/highlights.scm
queries/thrift/highlights.scm

feat: add @text.uri where applicable to thrift and gosum

---

lockfile.json
queries/sql/highlights.scm

Add recently added keywords
restructures usage of nodes a bit. Most of them where just used as `@keyword`
I have grouped some keywords as `@attributes` and `@conditionals`

SQL highlights update

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/smali/folds.scm
queries/smali/highlights.scm
queries/smali/indents.scm
queries/smali/locals.scm

cc: @ObserverOfTime as he helped me with Smali initially when I was new :) would def like an eyeball or two over the query changes. The grammar was about half-rewritten as it wasn't complete nor correct in its broader statements and organization
Also note that I am a contributor to the sourcehut repo since @yotamN and I agreed to co-maintain the parser over there, no need to worry about that going stale or out of date

feat(smali): improve queries

---

lockfile.json
queries/elsa/folds.scm
queries/elsa/indents.scm
queries/elsa/injections.scm
queries/elsa/locals.scm

This PR adds folds, indents, injections, and locals to Elsa.

feat(elsa): improve queries

---

lockfile.json
queries/capnp/highlights.scm
queries/capnp/indents.scm
queries/capnp/injections.scm
queries/capnp/locals.scm

I rewrote the grammar a bit to distinguish escape sequences and fix a couple bugs; those changes are reflected in the highlights
I also added indents, injections, and locals

feat(capnp): improve queries

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/cpon/folds.scm
queries/cpon/highlights.scm
queries/cpon/indents.scm
queries/cpon/injections.scm
queries/cpon/locals.scm

https://github.com/silicon-heaven/libshv/wiki/ChainPack-RPC#cpon-chainpack-object-notation
This PR adds ChainPack Object Notation (CPON) support

feat: add cpon

---

README.md
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/parsers.lua

Requires https://github.com/neovim/neovim/pull/22207

feat: use vim.treesitter.language.add()

---

.github/workflows/release.yml

which invalidates the action see https://github.com/nvim-treesitter/nvim-treesitter/actions/runs/4261226329

fix(ci): remove double 'uses'

---

queries/dart/indents.scm
tests/indent/dart/class.dart
tests/indent/dart_spec.lua

Thx for replying for fixing the indentation issue for dart

fix(dart): add `@indent_end` to  }

---

README.md

I got myself very confused over this, see #3621.  This is a small update to the readme that will hopefully prevent others from running into this.

docs: add small note in README clarifying custom parser installation

---

lua/nvim-treesitter/parsers.lua

Title, shouldn't reduce perf much at all I hope

feat(health): sort parser list for clarity

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/bicep/folds.scm
queries/bicep/highlights.scm
queries/bicep/indents.scm
queries/bicep/injections.scm
queries/bicep/locals.scm

feat: add bicep

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/ungrammar/folds.scm
queries/ungrammar/highlights.scm
queries/ungrammar/indents.scm
queries/ungrammar/injections.scm
queries/ungrammar/locals.scm

Adds support for [ungrammar](https://github.com/rust-analyzer/ungrammar)

feat: add ungrammar

---

queries/dart/folds.scm

Closes #3844
This PR adds distinct folds to dart.
Side note: I am not a fan of the grammar in its current state (much like Kotlin), but rewriting that would be a huge task - I'll save that for another day :)
Thanks,
Amaan

feat(dart): add folds

---

queries/html_tags/injections.scm

Fixes https://www.reddit.com/r/neovim/comments/y62tr4/javascript_lit_html_syntax_highlighting_ts/
Before
After

feat(html): lit attr binding interpolation

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/yuck/folds.scm
queries/yuck/highlights.scm
queries/yuck/indents.scm
queries/yuck/injections.scm
queries/yuck/locals.scm

feat: add yuck

---

README.md
lua/nvim-treesitter/parsers.lua
queries/fortran/highlights.scm

Better alternative to #4342, also fills in the missing blanks

feat(fortran): update highlight queries

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/matlab/folds.scm
queries/matlab/highlights.scm
queries/matlab/injections.scm

This PR adds Matlab support...
But I'm not a fan of the grammar in its current state (when I do rewrite it and if the PR is merged I'll add locals & indents as I'd rather not spend time on that now)

feat: add matlab

---

lockfile.json
queries/starlark/highlights.scm

feat(starlark): improve assertion parsing

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/passwd/highlights.scm

Pretty much just /etc/passwd in Linux

feat: add passwd

---

README.md
lockfile.json
queries/qmldir/highlights.scm
queries/qmldir/injections.scm

https://doc.qt.io/qt-6/qtqml-modules-qmldir.html
cc: @Decodetalkers

feat: add qmldir

---

lua/nvim-treesitter/parsers.lua

fix(qmldir): add to parsers.lua

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/po/folds.scm
queries/po/highlights.scm
queries/po/injections.scm

https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

feat: add PO

---

lockfile.json
queries/kdl/highlights.scm

Actual parser update didn't break anything, but I tuned the highlights query a bit

feat(kdl): update parser & queries fixing the comment bug

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/prql/highlights.scm
queries/prql/injections.scm

Adds a parser highlights and injections for PRQL. I am willing to maintain this parser.

feat: add prql

---

lua/nvim-treesitter/caching.lua

fix: remove wrong/pointless tostring

---

lua/nvim-treesitter/parsers.lua
queries/gdscript/folds.scm
queries/gdscript/highlights.scm
queries/gdscript/indents.scm
queries/gdscript/locals.scm

Updates highlights, locals, and indents and adds folds. Also add myself as maintainer.

Update gdscript queries

---

lockfile.json
lua/nvim-treesitter/parsers.lua

ridding the world of C++, one scanner at a time

markdown!: switch to scanner.c

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/cue/folds.scm
queries/cue/highlights.scm
queries/cue/indents.scm
queries/cue/injections.scm
queries/cue/locals.scm

:8ball:
cc: @eonpatapon @psliwka

feat: add cue

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/lua/injections.scm
queries/luap/highlights.scm
queries/query/injections.scm

Alternative to #3578 
I sort of dislike having the classes be `@keyword`, and the grammar isn't all that great...(I can fork it if anyone thinks the queries would be better handled that way since the current one uses inline/hidden rules annoyingly)

feat: add lua patterns

---

queries/vue/indents.scm
tests/indent/vue/template_indent.vue
tests/indent/vue_spec.lua

indents(vue): fix indents on new line after <template>

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/uxntal/folds.scm
queries/uxntal/highlights.scm
queries/uxntal/indents.scm
queries/uxntal/injections.scm
queries/uxntal/locals.scm

https://wiki.xxiivv.com/site/uxntal.html

feat: add Uxn Tal

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/squirrel/folds.scm
queries/squirrel/highlights.scm
queries/squirrel/indents.scm
queries/squirrel/injections.scm
queries/squirrel/locals.scm

feat: add Squirrel

---

lockfile.json
queries/sql/highlights.scm

* adds new and missing datatypes
* some more attributes

highlights(sql): add new keywords and datatypes

---

lockfile.json
queries/yuck/highlights.scm

Improves yuck highlighting, see https://github.com/helix-editor/helix/pull/6242 how it looks like in helix

feat: improve yuck highlighting

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/gleam/folds.scm
queries/gleam/highlights.scm
queries/gleam/indents.scm
tests/query/highlights/gleam/assert.gleam
tests/query/highlights/gleam/function.gleam
tests/query/highlights/gleam/import.gleam
tests/query/highlights/gleam/pipe.gleam
tests/query/highlights/gleam/try.gleam
tests/query/highlights/gleam/type.gleam

fix(gleam): add scanner.c to parsers list & update lockfile

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/git_config/highlights.scm

feat: add gitconfig

---

queries/prql/highlights.scm

As discussed in #4468
`loop` will be `@repeat` and
`case` will be `@conditional`

highlights(prql): change `loop` and `case` highlight

---

queries/git_config/highlights.scm

refactor(gitconfig): use lua-match instead of match

---

queries/typescript/highlights.scm

| ![image](https://user-images.githubusercontent.com/4299733/224368475-bec9db50-37b9-4833-b5ca-78968abbacd4.png) | ![image](https://user-images.githubusercontent.com/4299733/224368317-69e22539-3cb5-4553-9f6d-ec346f4b7b5b.png) |

highlights(typescript): `infer`, template literal type & punctuations

---

queries/lua/highlights.scm

feat(lua): add more builtin variables per lua_ls

---

lua/nvim-treesitter/parsers.lua
lua/nvim-treesitter/shell_command_selectors.lua

chore: clean up parsers.lua

---

lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/install.lua

refactor!: remove setting the update strategy

---

lockfile.json
queries/thrift/folds.scm
queries/thrift/highlights.scm
queries/thrift/indents.scm
queries/thrift/locals.scm

Went from 1400/1400 - 920/3 state count and as a result the binary went from 1.1mb to 125kb in size :)

feat(thrift): update queries based on upstream changes

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/tablegen/folds.scm
queries/tablegen/highlights.scm
queries/tablegen/indents.scm
queries/tablegen/injections.scm
queries/tablegen/locals.scm

https://llvm.org/docs/TableGen/ProgRef.html
Any LLVM fans out there...? :)

feat: add LLVM TableGen

---

lua/nvim-treesitter/install.lua

Noticed this issue when developing locally.. (for wat/wast)

fix: check if repo location exists for local paths

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/lua/injections.scm
queries/luadoc/highlights.scm

Mix of EmmyLua and what I noticed commonly seen in lua repos (and what lua_ls recognized)

feat: add Luadoc

---

lockfile.json
queries/sql/highlights.scm

* adds keywords for view configuration
* add `current_timestamp` used as a default for column configuration

highlights(sql): add new keywords for views and defaults

---

lockfile.json
queries/luadoc/highlights.scm

Related: https://github.com/amaanq/tree-sitter-luadoc/issues/1
cc @chrisgrieser

feat(luadoc): add more annotations

---

queries/vue/injections.scm
tests/query/injections/vue/test-vue-injections.vue

Closes #4549 
@amaanq @qumn have a check
(Yet to add test)

feat(vue): add tsx/jsx injection queries

---

lua/nvim-treesitter/compat.lua
lua/nvim-treesitter/configs.lua
lua/nvim-treesitter/health.lua
lua/nvim-treesitter/query.lua
lua/nvim-treesitter/query_predicates.lua
queries/lua/injections.scm

Changes for https://github.com/neovim/neovim/pull/22761

fix: shim 0.9 deprecations

---

queries/python/indents.scm
tests/indent/python/break_continue.py
tests/indent/python/match_case.py
tests/indent/python_spec.lua

~raise Exception dedent~ moved to discussion in #4557 
~fix return dedent~ moved to discussion in #4557

feat(python): add more edge-case indent pattern

---

lockfile.json
queries/kotlin/highlights.scm
queries/kotlin/injections.scm

I'm writing my own Kotlin parser but I'm a bit busy atm & Kotlin is a very annoying language..it only gets worse with every parser I write :expressionless: hopefully it'll be done soon :)
This is just a hotfix so the lockfile updates don't break till I get my more permanent solution done.

feat(kotlin): update queries from upstream changes

---

queries/scala/locals.scm

This syncs the queries that were updated in https://github.com/tree-sitter/tree-sitter-scala/pull/196.

feat(scala): add in local variables queries

---

queries/clojure/highlights.scm
queries/commonlisp/highlights.scm
queries/fennel/highlights.scm
queries/racket/highlights.scm
queries/scheme/highlights.scm

Hello,
Here is a small PR to add spell feature to commonlisp, scheme, racket, clojure and fennel.
Regards,
Kawas

feat(spell): support lisp like languages

---

lockfile.json
queries/sql/highlights.scm

https://github.com/DerekStride/tree-sitter-sql/pull/127

update sql parser and highlights

---

queries/c/indents.scm
tests/indent/c/issue-4525.c
tests/indent/c_spec.lua

Closes #4525 
@amaanq @scienceplease have a check

fix(c_indents): fix expression leaking indents

---

queries/ecma/highlights.scm

javascript: highlight more builtins

---

queries/ecma/indents.scm

fix(ecma): comment should be `@indent.auto`

---

lockfile.json
queries/smali/highlights.scm
queries/smali/locals.scm

refactor(smali): refactor queries from upstream

---

README.md
lockfile.json
queries/http/highlights.scm
queries/http/injections.scm

Would've hoped someone else would've fixed it by now..

feat(http): update parser queries from upstream

---

queries/ledger/highlights.scm

This is a reboot of https://github.com/nvim-treesitter/nvim-treesitter/pull/4328, which apparently stalled due to some setup issues on @afh's side.
Highlights are currently slightly broken for ledger, so unless the other PR sees new activity, I think that this should be merged.

Update ledger highlight queries

---

queries/lua/injections.scm

injections(lua): highlight Lua code in vim.rpcrequest and vim.rpcnotify

---

queries/lua/injections.scm

- Make it similar to other queries in the file
- No change needed once https://github.com/MunifTanjim/tree-sitter-lua/pull/20#discussion_r1176509444 is merged

injections(lua): tweak query to capture string content

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/puppet/folds.scm
queries/puppet/highlights.scm
queries/puppet/indents.scm
queries/puppet/injections.scm
queries/puppet/locals.scm

feat: add puppet

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/lua/highlights.scm
queries/luau/folds.scm
queries/luau/highlights.scm
queries/luau/indents.scm
queries/luau/injections.scm
queries/luau/locals.scm

cc @leaxoy, @williamboman you might be interested as well :)

feat: add luau

---

queries/python/indents.scm
tests/indent/python/if_else.py
tests/indent/python_spec.lua

not guarantee to work, just testing the waters 
- If this doesn't work so well, maybe changing the indent algo instead
- Does not support multiline elif statement

Add Python else elif dedent

---

queries/starlark/highlights.scm

fix(starlark): fields should not match uppercase-beginning names

---

queries/lua/injections.scm

Was suggested in #4703 but not applied for some reason

fix(lua_inject): remove need for surrounding quote

---

queries/ocaml/indents.scm
queries/ocaml_interface/indents.scm

Testing with code from:
- https://www.cs.umd.edu/class/spring2016/cmsc330/lectures/examples.pdf
- https://v2.ocaml.org/learn/taste.html
- https://v2.ocaml.org/manual
Edit: Oh my, there's a LOT of ERROR nodes, which isn't handled

feat: add ocaml indents

---

queries/html_tags/injections.scm

perf(html): onevent attrs

---

queries/markdown/injections.scm
queries/markdown_inline/injections.scm

| Before  | After   |
| ------- | ------- |
| ![image](https://user-images.githubusercontent.com/29790821/235932939-e36efec4-36cc-4356-ab04-5386bbcb667e.png) | ![image](https://user-images.githubusercontent.com/29790821/235932812-02696450-3ec1-4f39-92f8-b835eef6f67a.png) |

fix: add @combined to markdown html

---

queries/erlang/folds.scm
queries/erlang/highlights.scm

update some new keyword highlights in Erlang otp25.

feat(erlang): add keyword and operator suppored by otp25

---

queries/rust/highlights.scm

Closes #3610
@MultisampledNight try these changes out please :slightly_smiling_face:

Rust improvements

---

queries/typescript/highlights.scm

It's in ecma already (added a missing operator too now)

fix(typescript): remove duplicate capture

---

queries/comment/highlights.scm

comment: remove user mention highlight

---

queries/java/folds.scm

update java folds to include class body and constructor as well 
check sample:
https://github.com/nvim-treesitter/nvim-treesitter/assets/639806/6cc937d4-44aa-416f-b91f-dbe6a0db6d17

update to java folds

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/odin/folds.scm
queries/odin/highlights.scm
queries/odin/indents.scm
queries/odin/injections.scm
queries/odin/locals.scm

cc: @laytan @WillEhrendreich
@laytan Give this a shot :grin:

feat: add Odin

---

lua/nvim-treesitter/ts_utils.lua

@lewis6991 suggested this should fix the memleak, and from personal testing, the memory increase with a pace much lesser compared to without the fix.

fix indent/fold memleak

---

lua/nvim-treesitter/indent.lua

* replace ts_utils.memoize_by_buftick by simpler implementation
* simplify construction of hash map
* prefer Neovim APIs

refactor(indent): backport improvements from main

---

lua/nvim-treesitter/indent.lua

fixup: use correct require syntax

---

queries/swift/indents.scm

Also add enum_class_body
cc @Saafo

refactor: add notes for swift

---

queries/ecma/highlights.scm

| ![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/4299733/5ff72a7a-1b6c-41d8-808b-826dae778a62) | ![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/4299733/fd4914d5-ad89-4a9a-8098-36481b20911a) |

highlights(typescript): `:` in `switch` statement

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/objc/folds.scm
queries/objc/highlights.scm
queries/objc/indents.scm
queries/objc/injections.scm
queries/objc/locals.scm

All I can say is I see why this was deprecated in favor of Swift
Objective-C++ is another hell to endure after this :grin:

feat: add Objective-C

---

lua/nvim-treesitter/parsers.lua
queries/ispc/folds.scm
queries/ispc/highlights.scm
queries/ispc/indents.scm
queries/ispc/injections.scm
queries/ispc/locals.scm

- Add ISPC parser config
- Add ISPC queries
The two commits add grammar and queries for the Intel implicit SPMD program
compiler ([ISPC](https://ispc.github.io/ispc.html)).

Add ISPC language support

---

lockfile.json
queries/sql/highlights.scm

Add highlighting to the keyword `overwrite` added in https://github.com/DerekStride/tree-sitter-sql/pull/148

highlights(sql): add keyword `overwrite`

---

lua/nvim-treesitter/indent.lua

fix(indent): return early if query doesn't exist

---

lua/nvim-treesitter/parsers.lua
queries/corn/folds.scm
queries/corn/highlights.scm
queries/corn/indents.scm
queries/corn/locals.scm

Adds queries and a parser mapping for the [Corn](https://github.com/jakestanger/corn) configuration language.

feat: add language support for corn

---

queries/go/highlights.scm

fix(go): properly highlight chan/map

---

lockfile.json
queries/ocamllex/highlights.scm

Update ocamllex parser and highlights

---

lockfile.json
queries/ocaml/highlights.scm

Changes required because of tree-sitter/tree-sitter-ocaml#77.

highlights(ocaml): update operators

---

lockfile.json
queries/comment/highlights.scm

http and https links are recognized now
ref https://github.com/stsewd/tree-sitter-comment/pull/21

Comment: add support for URIs

---

CONTRIBUTING.md
queries/c/highlights.scm
queries/markdown/highlights.scm
queries/vimdoc/highlights.scm

fix(highlights): lower priority for codeblocks with injections

---

queries/comment/highlights.scm

see also: https://github.com/stsewd/tree-sitter-comment/issues/22

feat(comment): Add some common comment tags

---

queries/dart/locals.scm

Currently we only have scope for Dart locals.
This PR adds references, function, parameter and variable definitions
And also if/for/while scope

feat(dart): improve locals query

---

queries/clojure/highlights.scm

I created #4865 originally to add these and then missed them. Here they are.

feat(clojure): Add update-keys, update-vals

---

queries/glimmer/folds.scm
queries/glimmer/indents.scm
queries/glimmer/locals.scm

* add indents, locals and folds

add more support for glimmer

---

lua/nvim-treesitter/health.lua
lua/nvim-treesitter/install.lua
lua/nvim-treesitter/locals.lua
lua/nvim-treesitter/parsers.lua

Does the same as #4950, but without the rebase issue.

Fix locals

---

lockfile.json

Fix crashes when opening CMake files

chore: update cmake

---

lockfile.json
queries/sql/highlights.scm

Adds highlights for new keywords like:
* compute stats
* optimize
* vacuum
* analyze
* MariaDB rename staements
https://github.com/DerekStride/tree-sitter-sql/pull/153
https://github.com/DerekStride/tree-sitter-sql/pull/152

highlights(sql): add new keywords for optimization statements

---

lockfile.json
queries/sql/highlights.scm

the `table_reference` node will be changing soon once https://github.com/DerekStride/tree-sitter-sql/pull/150 lands

fix(sql): table_reference -> object_reference

---

lockfile.json
queries/sql/indents.scm

a little more reorganizing; we've copied the indents file into tree-sitter-sql and it tests okay there.

fix(sql): compound_statement -> block

---

lua/nvim-treesitter/parsers.lua
queries/groovy/highlights.scm
queries/groovy/injections.scm

I want to add groovy support ,because I am learning android now, so... it is a simple parse, and for me , it is enough to develop android program

feat: add groovy support

---

lockfile.json
queries/sql/highlights.scm

Adds highlighting to the new keyword `filter` 
See https://github.com/DerekStride/tree-sitter-sql/pull/168

highlights(sql): add `filter` keyword

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/wing/folds.scm
queries/wing/highlights.scm
queries/wing/locals.scm
scripts/minimal_init.lua
tests/query/highlights/wing/class.w
tests/query/highlights/wing/nested_method.w

Add a parser for [Wing](https://github.com/winglang/wing)
I've copied the queries from the upstream repo. This is my first contribution here, let me know if I got it right.

feat(wing): add parser

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/hoon/folds.scm
queries/hoon/highlights.scm
queries/hoon/locals.scm

Adding a parser for the language [hoon](https://developers.urbit.org/reference/hoon)

feat: add Hoon language support

---

queries/javascript/highlights.scm
queries/typescript/highlights.scm

| ![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/4299733/b68ab743-e399-421c-b887-163e338aa06f) | ![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/4299733/a1e27258-6c07-4bbd-8afc-f2d5553aae6f) |
| ![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/4299733/3c6a2c41-fbfc-47b8-8789-d30673ca187d) | ![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/4299733/57317162-4094-423d-806f-0f6608bef314) |

highlights(javascript): parameter destructuring

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/v/highlights.scm
queries/v/indents.scm
queries/v/injections.scm
queries/v/locals.scm

Old one had a memory leak and was archived
relevant convo https://github.com/vlang/vls/pull/446

refactor(v)!: update repository

---

lua/nvim-treesitter/install.lua

I had `static_assert` compiled in as an unresolved symbol which caused nvim to exit (not crash) when opening a python file: https://github.com/tree-sitter/tree-sitter-python/blob/master/src/scanner.c#L474
Actual issue was my bad dev env, but we need to catch this stuff.

fix: add stricter cc options

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/cairo/folds.scm
queries/cairo/highlights.scm
queries/cairo/indents.scm
queries/cairo/injections.scm
queries/cairo/locals.scm

It supports both Cairo 0.x and 1.0 syntax

feat: add Cairo

---

lockfile.json
queries/julia/highlights.scm
queries/julia/injections.scm

See https://github.com/tree-sitter/tree-sitter-julia/pull/106

Update Julia queries

---

lockfile.json
queries/jsx/highlights.scm
queries/jsx/indents.scm
queries/regex/highlights.scm

@lucario387 you might be interested in checking out indents, but I adjusted to what I thought seemed right

Update javascript, typescript, & regex

---

queries/uxntal/highlights.scm

fix(uxntal): move `@variable` query higher

---

queries/sql/highlights.scm
queries/sql/indents.scm

Added upstream in https://github.com/DerekStride/tree-sitter-sql/pull/182

highlights(sql): queries for newly added keywords

---

lockfile.json
queries/c/folds.scm
queries/c/highlights.scm
queries/c/indents.scm
queries/c/injections.scm
queries/cpp/highlights.scm
tests/indent/c/if_else.c

chore(c): update queries from upstream

---

lockfile.json
queries/prql/highlights.scm

* prql has changes `func` to `let` for function declarations
* new regex operator has been implemented

feat(prql): change `func` to `let` for prql 0.9.x

---

queries/perl/highlights.scm

Mainly heredocs and builtin functions.

feat(perl): improve highlights

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/requirements/highlights.scm
queries/requirements/injections.scm

Experimental because it's incomplete.

feat: add requirements parser

---

plugin/query_predicates.lua
runtime/queries/php/highlights.scm
runtime/queries/php/injections.scm
runtime/queries/ruby/injections.scm

fix downcase

---

runtime/queries/bash/injections.scm

feat(bash): add heredoc injection

---

lockfile.json
queries/arduino/injections.scm
queries/c/highlights.scm
queries/c/injections.scm
queries/cpp/injections.scm
queries/cuda/injections.scm
queries/glsl/injections.scm
queries/hlsl/injections.scm

This includes some changes I've been meaning to add for a while but always forgot about

feat(c): update highlights

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/pymanifest/highlights.scm
queries/pymanifest/injections.scm

feat: add pymanifest parser

---

queries/heex/injections.scm

Fixes #5191
copied from https://github.com/phoenixframework/tree-sitter-heex/tree/main/queries

Fix HEEx directive injections

---

queries/lua/injections.scm

fix(lua): injections for comment and luadoc

---

queries/python/injections.scm

fix(python): right content for regex injection

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/bitbake/folds.scm
queries/bitbake/highlights.scm
queries/bitbake/indents.scm
queries/bitbake/injections.scm
queries/bitbake/locals.scm

Just a note that this language allows for python function definitions annoyingly, hence the major overlap

feat: add BitBake

---

.github/workflows/test-queries.yml
.github/workflows/update-lockfile.yml
.github/workflows/update-readme.yml
scripts/check-queries.lua
scripts/ci-install-macos-latest.sh
scripts/ci-install-ubuntu-latest.sh
scripts/ci-install-windows-2022.sh
scripts/update-readme.lua
scripts/write-lockfile.lua

Using the ci-install script and `nvim -l` where possible. ~~Hopefully nothing breaks.~~

ci: add shebangs to scripts & update workflows

---

.gitignore

Should fix the issue in #5280.

chore: ignore ci artifacts

---

.github/workflows/update-lockfile.yml

ci: fix update lockfile workflow

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/strace/highlights.scm
queries/strace/injections.scm

feat: add strace

---

queries/heex/injections.scm

Fix HEEx partial expressions

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/c/injections.scm
queries/go/injections.scm
queries/re2c/folds.scm
queries/re2c/highlights.scm
queries/re2c/indents.scm
queries/re2c/injections.scm
queries/re2c/locals.scm
queries/rust/injections.scm

Needs https://github.com/neovim/neovim/pull/24831

feat: add re2c

---

queries/dart/highlights.scm

fix(dart): update queries from upstream

---

lockfile.json
queries/bash/folds.scm
queries/bash/highlights.scm
queries/bash/injections.scm
tests/query/highlights/bash/double-parens.sh

Waiting for tree-sitter/tree-sitter-bash#193 to land.

feat(bash): improve highlights

---

SUPPORTED_LANGUAGES.md
lockfile.json
lua/nvim-treesitter/parsers.lua
runtime/queries/awk/injections.scm
runtime/queries/bash/injections.scm
runtime/queries/c/injections.scm
runtime/queries/go/injections.scm
runtime/queries/java/injections.scm
runtime/queries/kotlin/injections.scm
runtime/queries/lua/injections.scm
runtime/queries/printf/highlights.scm
runtime/queries/python/injections.scm
runtime/queries/teal/highlights.scm
runtime/queries/teal/injections.scm

Replaces #3573. I forked the parser so it's no longer limited to double-quoted strings.

feat(injections): add printf format strings

---

queries/clojure/highlights.scm
tests/query/highlights/clojure/test.clj

Fixes error introduced in #5307.
Add tests for Clojure highlighting.

[clojure] Fix @field highlighting bug

---

queries/typescript/folds.scm

folds(typescript): add `enum_declaration`

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/nqc/folds.scm
queries/nqc/highlights.scm
queries/nqc/indents.scm
queries/nqc/injections.scm
queries/nqc/locals.scm

[Not Quite C](https://bricxcc.sourceforge.net/nqc/) :smile:

feat: add NQC

---

queries/ecma/injections.scm

fix(ecma_injections): limit function names to alphanumeric characters only

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/kconfig/folds.scm
queries/kconfig/highlights.scm
queries/kconfig/indents.scm
queries/kconfig/injections.scm
queries/kconfig/locals.scm

[Linux Kernel Configuration](https://www.kernel.org/doc/html/next/kbuild/kconfig-language.html)

feat: add Kconfig

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/unison/highlights.scm
queries/unison/injections.scm

Attempting to add unison
Appreciate this tool thanks for the help!

Feat: Add unison

---

queries/lua/highlights.scm

- https://github.com/MunifTanjim/tree-sitter-lua/issues/39
- https://github.com/MunifTanjim/tree-sitter-lua/pull/40

fix(lua): highlights for attribute

---

lockfile.json
queries/swift/highlights.scm

- Update parsers: swift
- fix(swift): Fix property highlighting in value arguments

fix(swift): Fix property highlighting in value arguments after latest upstream PR

---

queries/yaml/injections.scm
tests/query/injections/yaml/promql-on-prometheus-rules.yaml

Properly inject promql in blocks.

fix(yaml): promql injections block

---

queries/lua/injections.scm

injections(lua): add various vim api highlights

---

lua/nvim-treesitter/ts_utils.lua

See https://github.com/neovim/neovim/issues/25191

fix: trees() may not be list-like

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/agda/highlights.scm

tree-sitter-agda has merge that pr, so now switch to origin upstream

chore: twick agda upstream

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/ssh_config/folds.scm
queries/ssh_config/highlights.scm
queries/ssh_config/indents.scm
queries/ssh_config/injections.scm

feat: add ssh config

---

README.md
lua/nvim-treesitter/parsers.lua
queries/haskell/highlights.scm

- Re-add (module) @namespace
- Exception handling
- Debugging
- `otherwise` = boolean `True`
- `qq` string quasiquotes
- Documentation comments (draft)
- Function/lambda parameters
- Remove recently added @ (already defined as an operator)

feat(highlights): some haskell additions

---

queries/haskell/highlights.scm
tests/query/highlights/haskell/test.hs

This adds a test file for Haskell highlights + some improvements to the highlight queries.

feat(haskell): highlights improvements + tests

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/authzed/highlights.scm
queries/authzed/injections.scm

I've spoken with the author of the repository referenced in this PR to get permission (https://github.com/mleonidas/tree-sitter-authzed/issues/2), if that's important in this context.

feat(authzed): add parser and highlight queries.

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/nasm/highlights.scm
queries/nasm/injections.scm

I'm not very familiar with (N)ASM so the highlights can probably be improved.

feat: add nasm parser

---

queries/haskell/highlights.scm
tests/query/highlights/haskell/test.hs

fix(haskell): prevent segfault due to anchorless queries

---

queries/nix/highlights.scm
tests/query/highlights/nix/test.nix

@leo60228
- functions
- builtin functions with prefix
- add test file

feat(nix): some highlight improvements

---

queries/unison/highlights.scm

Let me know if I need to improve anything!

Improve Unison highlights.scm queries

---

README.md

I thought that this functionality was not possible but there's actually an API for it. This seems like a useful place for others to find more information on it.

Advanced setup: add hint on configuring custom filetypes

---

CONTRIBUTING.md

docs: improve description of @type.definition capture

---

queries/prisma/folds.scm

feat(prisma): folding queries

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/leo/highlights.scm
queries/leo/injections.scm

LEO language parser and queries
[www.aleo.com/](https://developer.aleo.org/leo/language)
The formal grammar that this parser was based on was:
https://github.com/AleoHQ/grammars/blob/master/leo.abnf

feat: leo parser and queries

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/gn/folds.scm
queries/gn/highlights.scm
queries/gn/indents.scm
queries/gn/injections.scm
queries/gn/locals.scm

https://gn.googlesource.com/gn/+/main/docs/reference.md#grammar

feat: add GN (Generate Ninja)

---

lockfile.json
queries/perl/highlights.scm

little bugfixes - one highlight query needed to be updated

Update parser: perl

---

lockfile.json
queries/perl/highlights.scm

highlighting for `sort` and `state` and some bugfixes

feat: bump perl

---

queries/sql/highlights.scm

I'm hoping this should fix the issues with the highlights file in https://github.com/nvim-treesitter/nvim-treesitter/pull/5602
@lucario387

Update highlights with latest from derekstride/tree-sitter-sql

---

queries/perl/highlights.scm
queries/pod/highlights.scm

- perl: fix highlights for builtins
- pod: fix highlights

fix highlights for perl/pod

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/kusto/highlights.scm
queries/kusto/injections.scm

Experimental parser for kusto. Doesn't cover the full language, but a big improvement over nothing.

feat(kusto): add kusto parser and highlights

---

queries/cpp/highlights.scm

fix(cpp): highlight constexpr

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/templ/highlights.scm
queries/templ/injections.scm

This adds the [tree-sitter-templ](https://github.com/vrischmann/tree-sitter-templ) parser.

Add the templ parser

---

queries/soql/highlights.scm

See https://github.com/nvim-treesitter/nvim-treesitter/pull/5678#issuecomment-1816749967

chore(apex): update apex queries

---

queries/dtd/locals.scm
queries/gitattributes/locals.scm
queries/jq/highlights.scm
queries/jq/locals.scm
queries/ssh_config/locals.scm
queries/udev/locals.scm
queries/xcompose/locals.scm
queries/xml/locals.scm

- xcompose
- udev
- ssh_config
- gitattributes
- xml & dtd
- jq

feat: add more locals queries

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/linkerscript/folds.scm
queries/linkerscript/highlights.scm
queries/linkerscript/indents.scm
queries/linkerscript/injections.scm
queries/linkerscript/locals.scm

https://sourceware.org/binutils/docs/ld/

feat: add Linkerscript

---

lockfile.json
queries/poe_filter/highlights.scm

Also changed `(file)` to `@string.special`.

feat(poe_filter): add new Import statement

---

lockfile.json
queries/leo/highlights.scm
queries/leo/indents.scm

Added indents. Added someminor changes to highlights.scm.

leo - indents added new language highlights added

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/v/highlights.scm

V had a massive parser update which breaks our queries @kkharji @amaanq

fix(v): adapt to removed  scanner.c

---

lockfile.json
queries/nim/folds.scm
queries/nim/highlights.scm
queries/nim/locals.scm

- fix(nim): bump parser again to include minor fix
- fix(nim): shifting around for precedence
- fix(nim): added new fields from recent parser version

fix(nim): minor improvements to queries and parser

---

queries/luau/highlights.scm

Sorry, these are the luau queries that I was meant to also fix up in #5820. I must have missed them...

fix(luau): align `@string.regex` to the injections

---

README.md
lua/nvim-treesitter/health.lua

required for empty injection fix

feat!: bump minimum Nvim version to 0.9.2

---

queries/python/highlights.scm

feat(python): support typed (kw)args

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/zathurarc/highlights.scm
queries/zathurarc/injections.scm

feat: add the zathurarc parser included in tree-sitter-zathurarc

---

lockfile.json
queries/luau/highlights.scm

chore(luau): update highlights and parser

---

lockfile.json
queries/odin/highlights.scm

new language features and all that jazz

chore(Odin): update highlights

---

lua/nvim-treesitter/incremental_selection.lua

Fixes the issue described in https://github.com/neovim/neovim/issues/27234.
This is the solution proposed by @luukvbaal in https://github.com/neovim/neovim/issues/27234#issuecomment-1913332244.

fix(incremental-selection): use cmd instead of :lua for command

---

lua/nvim-treesitter/incremental_selection.lua

I was a bit too eager with #6001. As mentioned in there, the change doesn't fully fix the issue anyway (it does get rid of the error though) and it also seems to cause other problems (like https://github.com/nvim-treesitter/nvim-treesitter/pull/6001#issuecomment-1913719917).
This solution is the one proposed by @monkoose

fix(incremental-selection): second attempt at fixing command

---

queries/svelte/indents.scm

fix(svelte): correct indents, add key block

---

queries/go/injections.scm

I added new injections to cover more functions from standard library. I provided links to additional functions below: 
https://pkg.go.dev/fmt#Fscanf
https://pkg.go.dev/fmt#Appendf
https://pkg.go.dev/fmt#Sscanf
https://pkg.go.dev/testing#T.Skipf
https://pkg.go.dev/testing#F.Logf
https://pkg.go.dev/testing#B.Errorf
The problem covered here:
https://github.com/nvim-treesitter/nvim-treesitter/issues/2917

feat(go): printf injections

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/bicep/highlights.scm
queries/bicep/locals.scm

...actually decided to fill out every experimental feature upstream bicep supports now (with poor docs on it, sigh)

chore(bicep): update queries

---

queries/java/injections.scm

https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html#formatted(java.lang.Object...)

feat(java): inject printf in String.formatted

---

lua/nvim-treesitter/incremental_selection.lua

Follow up of #6014. After looking at the code I realized that the if-statement looked a bit odd. I also added a notification message for better error messages in cases like #6025.
EDIT: Also including the changes from #5963

refactor(inc-selection): simplify keymap and add error messages

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/readline/folds.scm
queries/readline/highlights.scm
queries/readline/indents.scm
queries/readline/injections.scm

Made a parser for [GNU Readline init files](https://www.gnu.org/software/bash/manual/html_node/Readline-Init-File-Syntax.html) (`~/.inputrc`) instead of studying, pls add

feat(readline): add parser tree-sitter-readline

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/d/folds.scm
queries/d/highlights.scm
queries/d/indents.scm
queries/d/injections.scm
queries/d/locals.scm

feat(d)!: switch upstream parser to `gdamore/tree-sitter-d`

---

lockfile.json
lua/nvim-treesitter/parsers.lua

chore(ruby): adapt to scanner rewrite

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/hyprlang/folds.scm
queries/hyprlang/highlights.scm
queries/hyprlang/indents.scm

Added [hyprlang](https://github.com/luckasRanarison/tree-sitter-hyprlang/) parser and queries. 
It's my first contribution to nvim-treesitter, feedbacks are welcome!

feat: add hyprlang parser & queries

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/rust/injections.scm
queries/slint/folds.scm
queries/slint/highlights.scm
queries/slint/indents.scm
queries/slint/injections.scm
queries/slint/locals.scm

This is a continuation of #5985. Check over there to see what happened so far :-)

feat(slint)!: change to the official parser

---

queries/ecma/highlights.scm

| ![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/4299733/cad622a0-38da-4d15-b868-2f609fdb9ff3) | ![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/4299733/e15fe711-5e14-4b22-9681-c6cbf1c7a3c0) |

feat(ecma): highlight decorator and destructuring

---

lockfile.json
queries/bash/highlights.scm

totally not an excuse to update the parser early

chore(bash): update parser and highlights

---

queries/jsx/highlights.scm

I have very little idea about the implications of this and if it is what I want.
closes #6082

feat(jsx): spell check text nodes

---

queries/yuck/indents.scm
tests/indent/yuck/indent.yuck
tests/indent/yuck_spec.lua

fixes https://github.com/Philipp-M/tree-sitter-yuck/issues/7

fix(yuck): comment out start-of-line parens

---

lockfile.json
queries/rust/highlights.scm

replace old lua-match patterns with newly added nodes

feat(rust): add doc comments

---

lua/nvim-treesitter/parsers.lua
queries/typst/folds.scm
queries/typst/highlights.scm
queries/typst/indents.scm
queries/typst/injections.scm

This adds basic folding and indenting queries for typst to make it more bearable to work with.
I plan on adding more w time.
I believe I should also add comment injections for spellsitter.

feat: add the typst parser

---

queries/dart/highlights.scm
scripts/format-queries.lua

Related: https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/523#discussion_r1493043485

fix(format): fix nested grouping indentation

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/svelte/folds.scm
queries/svelte/highlights.scm
queries/svelte/indents.scm
queries/svelte/injections.scm
queries/svelte/locals.scm

no more memory leaks, actively maintained, correctly parses every upstream svelte file that is valid, and supports Svelte 5 features

feat(svelte)!: switch upstream parser

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/tmux/highlights.scm
queries/tmux/injections.scm

feat: add the tmux parser

---

.github/workflows/lint.yml
scripts/format-queries.lua

makes it easier to run the script in an autocommand

fix(scripts): format-queries defaults to cwd

---

lockfile.json
queries/faust/highlights.scm

Better highlighting of function calls, built-in variables, and member access.

feat(faust): Better highlighting of function calls, built-in variables, and member access

---

lockfile.json
lua/nvim-treesitter/parsers.lua

feat(beancount): refactor scanner to c

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/gdshader/highlights.scm
queries/gdshader/injections.scm

Added parser + highlight support + updated readme to reflect changes.

feat: add support for gdshader

---

lua/nvim-treesitter/parsers.lua

feat: map automake to make

---

scripts/update-lockfile.sh
scripts/write-lockfile.lua

fix(scripts): actually skip lockfile updates

---

lockfile.json
lua/nvim-treesitter/parsers.lua

no more C++, abi 14, and maintained

feat(yaml)!: switch upstream parser

---

queries/hyprlang/injections.scm

Added bash injections to highlight commands.

feat(hyprlang): add bash injections

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/vento/highlights.scm
queries/vento/injections.scm

Adds support for the [Vento](https://vento.js.org/) template language
Grammar can be found here: https://github.com/ventojs/tree-sitter-vento

feat: add vento support

---

queries/swift/highlights.scm

Improved highlighting for Swift

fix(swift): highlights

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/liquid/highlights.scm
queries/liquid/injections.scm

~~experimental~~ parser for liquid template language

feat(liquid): add new parser tree-sitter-liquid

---

queries/snakemake/indents.scm

This PR adds indentation queries to snakemake.

feat(snakemake): add indentation queries

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/roc/highlights.scm
queries/roc/injections.scm
queries/roc/locals.scm

Parser for the [Roc] programming language.
[Roc]: https://www.roc-lang.org/

feat(roc): add new parser tree-sitter-roc

---

queries/djot/folds.scm
queries/djot/highlights.scm
queries/djot/indents.scm
queries/djot/locals.scm

I went through the query files for Djot and improved and updated them:
- Fill in some missing highlights
- Adjust some highlights to fit context better
- Conceal inline content
- Add locals
- Add folds
- Add indents
@NoahTheDuke

feat(djot): update queries

---

lockfile.json
queries/cuda/highlights.scm

See https://github.com/tree-sitter-grammars/tree-sitter-cuda/pull/68

highlights(cuda): add support for `__managed__`

---

queries/c_sharp/highlights.scm

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/raw-string
Now everything is fine xD

Fix Highlight raw_string_literal in c_sharp

---

queries/java/highlights.scm

Add `when` operator so that it gets highlighted inside the switch guard.

feat(java): highlight when operator

---

lua/nvim-treesitter/parsers.lua
scripts/minimal_init.lua

This is the actual name of the detected filetype.

fix(textproto): use 'pbtxt' filetype

---

lockfile.json
queries/t32/highlights.scm
queries/t32/indents.scm
tests/query/highlights/t32/keywords.cmm

Adds support for new node type `elif_block`.

fix(t32): update queries from upstream

---

lockfile.json
queries/julia/highlights.scm

See https://github.com/tree-sitter/tree-sitter-julia/pull/139

Julia outer keyword

---

queries/templ/highlights.scm

Added highlights to delimiters and to docktype to match HTML highlights.

feat(templ): add highlights

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/dockerfile/highlights.scm
queries/dockerfile/injections.scm

feat(dockerfile): adapt for parser update

---

lockfile.json
queries/astro/injections.scm

This also updates a highlight to be more accurate and bumps the lockfile to fix a few bugs.

feat(astro): add backtick string injections

---

lockfile.json
queries/asm/highlights.scm

feat(asm): update queries from upstream

---

queries/svelte/injections.scm

solves https://github.com/nvim-treesitter/nvim-treesitter/issues/6538

feat(svelte): add javascript highlight to svelte script

---

queries/html_tags/indents.scm

fix(html_tags): stop indenting void elements

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/inko/folds.scm
queries/inko/highlights.scm
queries/inko/indents.scm
queries/inko/injections.scm
queries/inko/locals.scm

This adds support for [Inko](https://inko-lang.org/) using [tree-sitter-inko](https://github.com/inko-lang/tree-sitter-inko/).

Add support for Inko

---

lockfile.json
lua/nvim-treesitter/parsers.lua

same grammar, same queries, so not a breaking change

feat(toml): switch to upstream fork

---

lockfile.json
queries/haskell/folds.scm
queries/haskell/highlights.scm
queries/haskell/locals.scm
tests/query/highlights/haskell/test.hs
tests/query/highlights_spec.lua

#6577, but based on `master`, as requested in https://github.com/nvim-treesitter/nvim-treesitter/pull/6577#issuecomment-2094883010

fix(haskell): update queries and tests for rewritten parser

---

queries/odin/highlights.scm

PR originally made and merged upstream here: https://github.com/tree-sitter-grammars/tree-sitter-odin/pull/15

feat(odin): more lenient towards different function naming convention

---

queries/idl/highlights.scm

here is a idl file for test new queries:
```idl
home a manages B {};
home A: B manages B {};
home A: B manages B {
void func1();
void func1() raises(A);
void func1() raises(A,B,C);
void func1(in u8 attr, out u16 attr);
void func1(in u8 attr, out u16 attr) raises(A);
void func1(in u8 attr, out u16 attr) raises(A,B,C);
readonly attribute u8 attr1, attr2, attr3;
readonly attribute u8 attr1 raises(A);
readonly attribute u8 attr1 raises(A, B, C);
attribute u8 attr1, attr2, attr3;
attribute u8 attr1 getraises(A);
attribute u8 attr1 getraises(A, B, C) setraises(A);
attribute u8 attr1 setraises(A);
factory A ();
factory A (in B a);
factory A (in B a) raises(A);
factory A (in B a) raises(A,B,C);
};
typeid A::A "bbb";
typeprefix A "ccc";
import "aaaa";
import A::A;
local interface A {
attribute …
```

feat(queries): update idl hightlight

---

queries/luau/highlights.scm

feat(luau): update queries from upstream

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/bp/folds.scm
queries/bp/highlights.scm
queries/bp/indents.scm
queries/bp/injections.scm
queries/bp/locals.scm

I couldn't run the `update-lockfile.sh` script due to it trying to write to my read-only dotfiles, but I believe this should be correct.

Add support for Android Blueprint

---

.github/workflows/lint.yml
lockfile.json
queries/query/highlights.scm
scripts/format-queries.lua

pending https://github.com/tree-sitter-grammars/tree-sitter-query/pull/36

feat(query)!: upstream changes

---

lockfile.json
queries/cpp/highlights.scm

arduino and the others probably need to update

feat(cpp): update highlights

---

queries/php_only/indents.scm

fix(php): remove recursive member_call_expression indent branch

---

queries/rust/folds.scm

feat(rust): fold block expressions

---

queries/lua/indents.scm

remove duplicated node in https://github.com/nvim-treesitter/nvim-treesitter/blob/f29c2d9867004151f9417f2f19b068fb973c29cc/queries/lua/indents.scm#L15

chore: clean duplicated node

---

queries/corn/highlights.scm
queries/corn/injections.scm

```corn
let {
$base = {
greeting = 12.0e+2
subject.hi.adsf = "world"
}
} in {
..$base
subject = "github"
hey = null
}
// vim: ft=corn
// TODO: corn
```

feat(corn): more highlights, comment injections

---

lockfile.json
queries/latex/highlights.scm

Use latest grammar after https://github.com/latex-lsp/tree-sitter-latex/commit/08d8b885a3fa67a6e8aa8edd8988eaa55db46ba4.

feat(latex): improve hyperlinks

---

.github/workflows/tests.yml
README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/r/highlights.scm
queries/r/indents.scm
queries/r/locals.scm
tests/indent/r_spec.lua
tests/query/highlights/r/test.r

Adapt to breaking rewrite @echasnovski
Not sure about the indent changes, and likely all the test will have to be adapted.

feat(r)!: update parser and queries

---

lockfile.json
queries/idl/highlights.scm

breaking changes since <https://github.com/cathaysia/tree-sitter-idl/commit/2831737ee4187af867b2febce6f35d0475a3a3ca>

feat(idl): update highlight

---

lockfile.json
queries/idl/highlights.scm
queries/idl/indents.scm

feat(idl): update idl highlight

---

queries/nix/indents.scm
tests/indent/nix/conds.nix
tests/indent/nix/general.nix
tests/indent/nix_spec.lua

Tests taken from [nixpkgs-fmt](https://github.com/nix-community/nixpkgs-fmt) and shortened.

feat(nix): indentation queries

---

lua/nvim-treesitter/indent.lua
queries/go/indents.scm

Also incorporate empty lines indent commit for testing

fix(go): narrow indent usage

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/goctl/folds.scm
queries/goctl/highlights.scm
queries/goctl/injections.scm

Added support for the goctl framework.
link: https://github.com/nvim-treesitter/nvim-treesitter/issues/6874

feat(goctl): add goctl language support. 

---

queries/templ/folds.scm

Add folds queries for tree-sitter-templ

templ: add folds queries

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/nginx/folds.scm
queries/nginx/highlights.scm
queries/nginx/injections.scm

Hello, it's me again 🙇
(this week I went to edit nginx.conf, heh)

feat: tree-sitter-nginx

---

queries/wit/folds.scm
queries/wit/highlights.scm

References:
- https://github.com/liamwh/tree-sitter-wit/blob/main/grammar.js 
- https://github.com/zed-industries/zed/blob/79f364632535ef85c190fcf1be9834bbffc19c95/crates/extension_api/wit/since_v0.0.4/extension.wit
- https://github.com/fermyon/spin/blob/436ad589237c02f7aa4693e984132808fd80b863/wit/mqtt.wit 
- https://github.com/bytecodealliance/wasmtime/blob/a068bfe06435a048502bf4afc426451dab5294af/crates/wasi-nn/wit/wasi-nn.wit

feat(wit): add folds, missing highlights

---

lockfile.json
queries/latex/highlights.scm

feat(latex): update delimiter capture (#6697)

---

lua/nvim-treesitter/shell_command_selectors.lua

Problem: Installing a parser using git in an active git session (e.g., when editing a commit message) can corrupt the corresponding repository.
Solution: Check for typical environment variables first and abort installation if found.
Closes #5353

fix(install): abort installation using git in active git session

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/powershell/folds.scm
queries/powershell/highlights.scm
queries/powershell/indents.scm
queries/powershell/injections.scm
queries/powershell/locals.scm

This adds parser and queries for powershell
I've used parser available in [List of parsers](https://github.com/nvim-treesitter/nvim-treesitter/wiki/List-of-parsers) - https://github.com/airbus-cert/tree-sitter-powershell
I didn't clearly get what I supposed to do - create issue or create discussion in order to track this.. so I found old issue asking about powershell support:  #2673

feat(powershell): add parser and queries

---

queries/vimdoc/highlights.scm

Ref: https://github.com/nvim-treesitter/nvim-treesitter/pull/6971
Ref: https://github.com/nvim-treesitter/nvim-treesitter/pull/6972

feat(vimdoc): set url attribute for URLs

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/rescript/folds.scm
queries/rescript/highlights.scm
queries/rescript/indents.scm
queries/rescript/injections.scm
queries/rescript/locals.scm
tests/indent/rescript/basic.res
tests/indent/rescript/complex.res
tests/indent/rescript/conditional.res
tests/indent/rescript_spec.lua

Adds [rescript](https://rescript-lang.org/) parser. Queries adapted/improved from the base repo (which currently doesn't track `parser.c`, but there is a PR for it).

feat: rescript parser and queries

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/vrl/folds.scm
queries/vrl/highlights.scm
queries/vrl/indents.scm
queries/vrl/injections.scm
queries/vrl/locals.scm

Add [VRL](https://vrl.dev) support for nvim-treesitter

Add VRL support for nvim-treesitter

---

lockfile.json
queries/leo/highlights.scm

Added the new `async` keyword to syntax.

async keyword added

---

lockfile.json
queries/leo/highlights.scm

Adding strings to Leo.
Sorry for the separate PR, getting late.

string type, and literals added

---

queries/ruby/highlights.scm

Test file:
```rb
#!/usr/bin/env ruby
#
#
#
#
#
require 'yaml'
require 'fileutils'
require 'elasticsearch'
require 'optparse'
CONFIGURATION_FILE = File.expand_path('~/.elman.yml')
INDEX_NAME = 'elman'
APROPOS_REGEX = /(.*)\s\(\d*.*\)\s*-\s*(.*)/
def create_default_configuration_file
puts 'Creating the default configuration'
FileUtils.touch(CONFIGURATION_FILE)
configuration = YAML::load_file(CONFIGURATION_FILE) || {}
configuration[:elasticsearch] = { host: 'localhost',
port: '9200',
search_results_size: 10 }
File.write(CONFIGURATION_FILE, configuration.to_yaml)
end
def delete_index
client.indices.delete index: INDEX_NAME rescue false
end
def create_index
return if client.indices.exists? index: INDEX_NAME
puts "Creating index: #{INDEX_NAME}"
client.indices.create  index: INDEX_NAME,
body: { …
```

feat(ruby): string/punctuation highlight improvements

---

.github/workflows/lint.yml
.github/workflows/test-core.yml
.github/workflows/test-generate.yml
lua/nvim-treesitter/install.lua
scripts/install-parsers.lua

run on PR by adding label `ci:generate` or manually via workflow dispatch

ci(tests): add optional workflow for generating grammars

---

lockfile.json
queries/leo/highlights.scm

small bugfixes for leo language variables, records, and structs

leo/bugfix small bugfixes of variables, records, and struct highlighting

---

queries/ini/highlights.scm

feat(ini): highlight setting value as `@string`

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/gap/folds.scm
queries/gap/highlights.scm
queries/gap/injections.scm
queries/gap/locals.scm
queries/gaptst/folds.scm
queries/gaptst/highlights.scm
queries/gaptst/injections.scm

[GAP](https://www.gap-system.org/) is an interpreted programming language for computational discrete algebra. This PR adds support for the GAP system programming language (filetype `gap`) and the GAP system test file format (filetype `gaptst`).

feat(gap): Add gap and gaptst parser and queries

---

queries/wing/folds.scm
queries/wing/highlights.scm
queries/wing/injections.scm
tests/query/highlights/wing/class.w

...as well as some fold and injection queries.
Test code:
```wing
bring expect;
let then: datetime = datetime.utcNow();
let now: datetime = then;
let isOlderOrEqual = inflight (x: datetime, y: datetime) => {
return y.timestampMs >= x.timestampMs;
}; 
test "datetime is a valid type" {
let later: datetime = datetime.fromComponents({
day: now.dayOfMonth, 
hour: now.hours, 
year: now.year + 1, 
min: now.min, 
month: now.month, 
ms: now.ms, 
sec: now.sec, 
tz: now.timezone
});
expect.ok(isOlderOrEqual(then, now));
expect.ok(isOlderOrEqual(now, later));
hi += 5;
}
let decimal: regex = regex.compile("^[0-9]*$");
let testString = inflight (re: regex, s: str) => {
return re.test(s);
};
test "regex is valid type" {
let binary: regex = regex.compile("^[0-1]*$");
expect.equal(testString(decimal, …
```

feat(wing): add many missing highlights

---

queries/mermaid/folds.scm
queries/mermaid/indents.scm

Alternative to #6100.
Thanks @aareman for the PR

feat(mermaid): indents and folds

---

queries/swift/highlights.scm

Test files:
- https://github.com/jasonjmcghee/rem/blob/f4f68049a064557bddeb93753f82aa41af776b98/rem/DB.swift#L316
- https://github.com/xxxAIRINxxx/Cmg/blob/586be7e8862c8d4d83bc5b900a86181d4f517ac5/Proj/Demo/Benchmark.swift#L17
- https://github.com/alex-pinkus/tree-sitter-swift/blob/032930d6218d8ae23bde074cf29ce8d276b87533/test/corpus/literals.txt#L362

feat(swift): add many missing highlights

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/ziggy/highlights.scm
queries/ziggy/indents.scm
queries/ziggy_schema/highlights.scm
queries/ziggy_schema/indents.scm

Add support for both ziggy and ziggy-schema parsers and queries.
Reference: https://ziggy-lang.io/

feat(ziggy): add ziggy and ziggy-schema parsers and queries

---

lua/nvim-treesitter/parsers.lua

@ribru17 (but proper review this time ;))

fix(parsers): register explicit filetypes unconditionally

---

queries/angular/highlights.scm

updated angular highlight query to support `@let` expressions

feat(angular): update highlight query

---

queries/dart/folds.scm
queries/dart/highlights.scm

Reference code:
```dart
import 'package:atsign_atmosphere_pro/view_models/file_download_checker.dart';
import 'package:atsign_atmosphere_pro/desktop_routes/desktop_routes.dart';
import 'package:atsign_atmosphere_pro/view_models/file_progress_provider.dart';
import 'package:atsign_atmosphere_pro/view_models/internet_connectivity_checker.dart';
import 'package:atsign_atmosphere_pro/view_models/my_files_provider.dart';
import 'package:atsign_atmosphere_pro/view_models/side_bar_provider.dart';
import 'package:atsign_atmosphere_pro/view_models/switch_atsign_provider.dart';
import 'package:atsign_atmosphere_pro/view_models/trusted_sender_view_model.dart';
import 'package:atsign_atmosphere_pro/view_models/welcome_screen_view_model.dart';
import 'package:flutter/material.dart';
import …
```

fix(dart): more highlight coverage, import folds

---

queries/diff/highlights.scm

fix(diff): delta highlights override punctuation

---

queries/toml/highlights.scm

Follow up of https://github.com/nvim-treesitter/nvim-treesitter/pull/7108
I've used `@markup.heading` for now since that was the original idea, but this should be discussed further.

refactor(toml): highlight queries

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/gren/highlights.scm
queries/gren/injections.scm

[tree-sitter-gren](https://github.com/MaeBrooks/tree-sitter-gren) (TS Grammar)
[Gren](https://gren-lang.org/) (Target Language)
> A programming language for simple and correct applications
> 
> Gren is a functional programming language with carefully managed side-effects and a strong static type system. The language consists of a few concepts with human readable names that compose well together, so you can do more with less.
This is my first time contributing, and I couldn't find any specific instructions on how to contribute a new language grammar. Please let me know if I need to change anything.

feat(gren): Addition of gren parser and queries

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/xresources/folds.scm
queries/xresources/highlights.scm
queries/xresources/injections.scm
queries/xresources/locals.scm

Parser for `.Xresources` or `.Xdefaults` files.

feat(xresources): xresources parser and queries

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/desktop/folds.scm
queries/desktop/highlights.scm
queries/desktop/injections.scm

Parser for `.desktop` and `.directory` files as defined by the [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/latest/index.html).

feat(desktop): desktop parser and queries

---

.luarc.json

Now writing indent tests is easier because the language server recognizes the necessary functions

chore: recognize busted functions

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/sway/folds.scm
queries/sway/highlights.scm
queries/sway/indents.scm
queries/sway/injections.scm
queries/sway/locals.scm
tests/indent/sway/main.sw
tests/indent/sway_spec.lua

https://github.com/FuelLabs/sway

feat: sway programming language

---

.github/workflows/update-lockfile.yml
lockfile.json
queries/julia/highlights.scm
queries/julia/locals.scm

Queries synced with upstream (preserving obvious local additions, but there could be regressions; most but not all of the diff are reshuffles).

feat(julia): update parser and queries

---

.github/workflows/update-lockfile.yml
lockfile.json
queries/unison/folds.scm
queries/unison/highlights.scm
queries/unison/injections.scm

Also adds indents and folds in separate commits!

refactor(unison): update and improve queries for latest grammar

---

queries/gdscript/highlights.scm

Add a couple new export annotations for Godot v4.3

feat(gdscript): add new export annotations

---

queries/http/highlights.scm
tests/query/highlights/http/test.http
tests/query/injections/http/injections.http

Sample code shown in the added tests

feat(http): more comprehensive highlights

---

queries/robot/highlights.scm

Related issue: https://github.com/Hubro/tree-sitter-robot/issues/8

Additions to Robot highlights

---

queries/sxhkdrc/injections.scm

feat(sxhkd): highlight command

---

queries/leo/indents.scm

Function call and mathematical parentheses indenting was fixed.

fix(leo): intentation fix of parenthesis

---

queries/idris/highlights.scm

fix(idris): correct keyword captures

---

queries/hyprlang/highlights.scm

feat(hyprlang): add missing highlights

---

queries/hyprlang/injections.scm

Reference: https://wiki.hyprland.org/Hypr-Ecosystem/hypridle/#general

feat(hyprlang): bash injection for hypridle variables

---

lockfile.json
queries/djot/highlights.scm

Updates the djot grammar to breaking changes introduced in https://github.com/treeman/tree-sitter-djot/pull/56

feat(djot): update djot queries

---

queries/typst/highlights.scm

In this PR multi-level headings are captured. Generally, the implementation is similar with markdown, which inspired typst to a great extend. Lastly, if there are any recommendations I am totally open.

feat(typst): capture multilevel headings

---

lockfile.json
queries/nu/folds.scm
queries/nu/highlights.scm

Add support of the new attribute syntax.
https://github.com/nushell/tree-sitter-nu/pull/182

feat(nu): new attribute syntax and add folds.scm

---

queries/pascal/injections.scm

I noticed there is an asm grammar now, so we can uncomment this.

feat(pascal): Add asm language injection for Pascal

---

lockfile.json
queries/inko/folds.scm
queries/inko/highlights.scm

These will be introduced as part of the 0.19.0 release. This commit updates the lockfile as well as the relevant queries to accommodate the new expression and "in" now being a keyword.

feat(inko): add support for "for" loops

---

queries/just/highlights.scm

- Default attribute highlight
- Highlight more builtin attributes
- Highlight special attribute arguments
Before:
After:

feat(just): improve attribute highlights

---

queries/sql/folds.scm

feat(sql): add folds

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/kcl/folds.scm
queries/kcl/highlights.scm
queries/kcl/injections.scm

This PR adds highlighting support for the [KCL language](https://www.kcl-lang.io/)
Please let me know if any other action is needed to get this added to the project.

feat: added tree-sitter-kcl

---

queries/gleam/highlights.scm

Hello! I am the lead maintainer of Gleam.
This keyword was added in Gleam v1.9.0. Thank you.

Add missing Gleam keyword

---

lockfile.json
lua/nvim-treesitter/parsers.lua
queries/tera/highlights.scm
queries/tera/injections.scm

Adds support for the [Tera](https://keats.github.io/tera/) templating language, using my https://github.com/uncenter/tree-sitter-tera parser/grammar. Please let me know if I have made any mistakes in adding this, I was struggling a bit due to the lack of clear documentation on this process.

feat: add tera

---

lockfile.json
queries/roc/highlights.scm
queries/roc/indents.scm
queries/roc/injections.scm
queries/roc/locals.scm

Adapt to https://github.com/faldor20/tree-sitter-roc/pull/30
Also synchronize queries with upstream and add indents

feat(roc)!: bump parser and queries

---

queries/python/highlights.scm
tests/query/highlights/python/decorators.py
tests/query/highlights/python/functions.py

fix(python): highlight function calls correctly

---

lockfile.json
queries/tact/folds.scm
queries/tact/highlights.scm
queries/tact/indents.scm
queries/tact/locals.scm

There were a couple of breaking changes in the queries, so here I am

feat(tact): update parser and queries

---

README.md
lockfile.json
lua/nvim-treesitter/parsers.lua
queries/blade/folds.scm
queries/blade/highlights.scm
queries/blade/indents.scm
queries/blade/injections.scm

Hello!
This add the [Laravel Blade](https://github.com/EmranMR/tree-sitter-blade) grammar to the list
Thanks!

feat(blade): add laravel blade grammar

---

.github/workflows/test-queries.yml
.github/workflows/update-lockfile.yml
lockfile.json

- **ci(tests): check queries on 0.10.4**
- **fix(rust): revert to ABI 14 parser**

ci: test parsers on 0.10.4

---

queries/haskell/injections.scm

See https://hackage-content.haskell.org/package/inline-python-0.1.1.1/docs/Python-Inline-QQ.html

feat(haskell): injections for inline-python quasiquotes

---

.github/PULL_REQUEST_TEMPLATE/new_language.md
.github/pull_request_template.md
.tsqueryrc.json
CONTRIBUTING.md
README.md
TODO.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/health.lua

This updates
* README
* CONTRIBUTING
* the `:h nvim-treesitter` documentation
to the current state of `main`. It also adds a pull request template for adding a new language.
(Which I still need to test and see how to best link here.)

docs: update to rewrite

---

.github/workflows/test-core.yml
runtime/queries/c/injections.scm
runtime/queries/cpp/injections.scm
runtime/queries/fsharp/highlights.scm
runtime/queries/hcl/highlights.scm
runtime/queries/idl/injections.scm
runtime/queries/powershell/highlights.scm
runtime/queries/sql/highlights.scm
runtime/queries/systemtap/highlights.scm

Some of these may actually need _additional_ backslashes to work as intended.

fix(queries): remove unnecessary escapes

---

README.md
doc/nvim-treesitter.txt
lua/nvim-treesitter/config.lua
lua/nvim-treesitter/install.lua

This was only useful for no longer supported `auto_install` option.

feat(config)!: remove `ignore_install`

---

runtime/queries/erlang/highlights.scm
runtime/queries/linkerscript/injections.scm
runtime/queries/nim_format_string/highlights.scm

Revealed by the capture-less patterns lint

fix: tidy up some query mistakes

---

doc/nvim-treesitter.txt
lua/nvim-treesitter/config.lua

fix(config): prepend install_dir to rtp

---

SUPPORTED_LANGUAGES.md
lua/nvim-treesitter/parsers.lua
runtime/queries/c3/folds.scm
runtime/queries/c3/highlights.scm
runtime/queries/c3/indents.scm
runtime/queries/c3/injections.scm

Picking up #7832
https://c3-lang.org/
<details>
<summary>Representative code sample</summary>
```
module hello_world;
import std::io;
fn void main()
{
io::printn("Hello, world!");
}
```
</details>
https://github.com/c3lang/tree-sitter-c3/
<details>
<summary>Parsed tree for code sample</summary>
```
(source_file [0, 0] - [7, 0]
(module_declaration [0, 0] - [0, 19]
path: (path_ident [0, 7] - [0, 18]
(ident [0, 7] - [0, 18])))
(import_declaration [1, 0] - [1, 15]
path: (path_ident [1, 7] - [1, 14]
(module_resolution [1, 7] - [1, 12]
(ident [1, 7] - [1, 10]))
(ident [1, 12] - [1, 14])))
(func_definition [3, 0] - [6, 1]
(func_header [3, 3] - [3, 12]
return_type: (type [3, 3] - [3, 7]
(base_type_name [3, 3] - [3, 7]))
name: (ident [3, 8] - [3, 12]))
(func_param_list [3, 12] - [3, 14])
body: …
```

feat(parsers): add c3

---

lua/nvim-treesitter/config.lua
lua/nvim-treesitter/health.lua
lua/nvim-treesitter/install.lua
plugin/nvim-treesitter.lua
scripts/check-parsers.lua
scripts/check-queries.lua

- **fix(install): only install queries for bundled parsers**
- **fix(install): don't skip un-tiered parsers**
Follow-up: Allow copying queries for custom parser (needs some careful refactoring)

fix(install): user parsers

---

lua/nvim-treesitter/parsers.lua
runtime/queries/powershell/highlights.scm

removed nodes: `"class"`, `"enum"`

feat(powershell)!: update parser and queries

---

runtime/queries/javascript/locals.scm
runtime/queries/tsx/locals.scm

There are no JSX locals (yet...?)
Changes detected by the LSP

fix: remove import references to jsx/locals.scm

---

lua/nvim-treesitter/parsers.lua
runtime/queries/ziggy_schema/highlights.scm

Breaking change: ziggy-schema removed "map" node
@rockorager

feat(ziggy,ziggy-schema): update parser and queries

---

SUPPORTED_LANGUAGES.md
lua/nvim-treesitter/parsers.lua
runtime/queries/wit/folds.scm
runtime/queries/wit/highlights.scm
runtime/queries/wit/injections.scm

feat(wit)!: update parser and queries

---

lua/nvim-treesitter/config.lua
lua/nvim-treesitter/indent.lua
lua/nvim-treesitter/install.lua

Also fix some emmyluals warnings

refactor(config): prefer `vim.list.unique` for normalization

---

lua/nvim-treesitter/parsers.lua
runtime/queries/php_only/highlights.scm

feat(php): update php and php_only parsers to v0.24.0

---

lua/nvim-treesitter/parsers.lua

…go, html, java, javascript, json, json5, pkl, rust, supercollider

feat(parsers): update bash, c, clojure, cpp, embedded_template, gap, go, html, java, javascript, json, json5, pkl, rust, supercollider

---

SUPPORTED_LANGUAGES.md
lua/nvim-treesitter/parsers.lua
runtime/queries/wxml/folds.scm
runtime/queries/wxml/highlights.scm
runtime/queries/wxml/indents.scm
runtime/queries/wxml/injections.scm

https://developers.weixin.qq.com/miniprogram/en/dev/framework/view/wxml/
<details>
<summary>Representative code sample</summary>
```wxml
<view wx:if="{{showFlag}}">Show content</view>
<view wx:elif="{{!showFlag && list.length > 0}}">Alternative content</view>
<view wx:else>Default content</view>
<view
wx:for="{{items}}"
wx:for-item="row"
wx:for-index="idx"
wx:key="id"
class="container"
>
<text>{{idx}}: {{row.title}}</text>
</view>
<input model:value="{{inputValue}}" />
<view data-id="{{item.id}}" data-name="{{item.name}}">Item</view>
<view style="{{forceWidth ? `width: ${10 - 5}rpx` : ''}}" />
<text>{{message}}</text>
<button bindtap="onTap">Click me</button>
<view catchtouchstart="onTouchStart">Catch event</view>
<button mut-bind:click="onMutClick">Mutual binding</button>
<import …
```

feat(wxml): add parser and queries

---

runtime/queries/proto/folds.scm
runtime/queries/proto/highlights.scm
tests/query/highlights/proto/test.proto

More delimiter highlights, property/variable highlights, and folds for import statements (see commits). Added test file for clarity

Proto features

---

SUPPORTED_LANGUAGES.md
lua/nvim-treesitter/parsers.lua
runtime/queries/rifleconf/highlights.scm
runtime/queries/rifleconf/injections.scm

A tree-sitter parser for `rifle.conf`, the configuration file format for the `rifle`, part of the `ranger` file  manager:
<https://github.com/ranger/ranger>
A sample configuration file: <https://github.com/ranger/ranger/blob/master/ranger/config/rifle.conf>
The script that parses the configuration: <https://github.com/ranger/ranger/blob/master/ranger/ext/rifle.py>
<details>
<summary>Representative code sample</summary>
```
#-------------------------------------------
#-------------------------------------------
ext x?html?, has firefox, X, flag f = firefox --new-tab "$1"
#-------------------------------------------
#-------------------------------------------
directory = ranger "$1"
mime ^text, label editor = $VISUAL -- "$@"
mime ^text, label pager = less -- "$@"
mime ^video = ask
mime …
```

feat(rifleconf): new language

---

lua/nvim-treesitter/parsers.lua
runtime/queries/inko/indents.scm

Breaking change: `(array_pattern)` rule and node was removed again.

feat(inko)!: update parser and queries

---

SUPPORTED_LANGUAGES.md
lua/nvim-treesitter/parsers.lua

Significant upstream breaking changes are not adapted to.
@PrestonKnopp

chore(gdscript): mark as unmaintained
