lua/nvim-treesitter/install.lua
=> feat/refacto: improve installer

lua/nvim-treesitter/install.lua
Fixes #5.
There are still parsers to add like typescript and c-sharp that breaks the install logic.
=> feat: add most parsers

lua/nvim-treesitter/utils.lua
Some little functions to help out when using treesitter nodes, there will definitely be more to come.
=> Node manipulation utilities

autoload/health/nvim_treesitter.vim, lua/nvim-treesitter/health.lua, lua/nvim-treesitter/install.lua, lua/nvim-treesitter/locals.lua
Add health checks.
The goal is that each module performs its own health check, which is call by the main healthcheck runner.
This is kind of a duplicate of #11
=> Checkhealth

lua/nvim-treesitter.lua, lua/nvim-treesitter/install.lua
this is a draft, the parser list could be prettier but i don't want to spend too much time on this.
Also i'm not sure about the location of the function.
=> feat: add parser list

README.md
Finally adds a real README to the project, with some infos on how to add parsers, and installtion steps.
=> Add proper README

queries/lua/highlights.scm, queries/lua/locals.scm
Little PR to fix lua highlights and queries.
=> Fix lua queries

lua/nvim-treesitter/health.lua, lua/nvim-treesitter/highlight.lua, lua/nvim-treesitter/locals.lua
Really tiny PR just to add `highlight` module to healthchecks as it requires a custom query.
=> Add highlight to healthchecks

lua/nvim-treesitter/install.lua
=> fix install by changing cc arguments position

README.md
- commands descriptions
- list of supported languages
=> edit: add information to the readme

lua/nvim-treesitter/configs.lua
I added some more the parsers, some of them maintained by the community. Not sure whether to add them right now or wait a bit longer for this project to be even more mature.
The haskell one really takes long to compile...
=> Add some more community parsers

lua/nvim-treesitter/configs.lua, lua/nvim-treesitter/incremental_selection.lua
As suggested in #37, rename the textobj module to incremental_selection.
Also adds a utility function to get the config of a module.
=> Move textobj module to incremental_selection.

lua/nvim-treesitter/install.lua
This allow commands like so :
```vim
:TSInstall c rust lua python
```
This is basically used for convenience and consistency, as calling `TSInstall` multiple times has not a great interest.
=> Allow installing multiple parsers at once

CONTRIBUTING.md, README.md, queries/c/highlights.scm, queries/c/locals.scm
Also add a missing `field` capture in locals query.
Fixes partially #52.
=> Add C queries

lua/nvim-treesitter/health.lua, lua/nvim-treesitter/incremental_selection.lua, lua/nvim-treesitter/state.lua
=> Remove postspaces and avoid one global

CONTRIBUTING.md, README.md, lua/nvim-treesitter/highlight.lua, queries/python/highlights.scm, queries/python/locals.scm
In Python, it's a bit tricky to define scopes.
Normal control structures like `if`, `for`, `while` don't define scopes
```python
i = 5
for i in range(3):
pass
print(i)
#>>> 2
```
=> Add python locals.scm

README.md, lua/nvim-treesitter/configs.lua, queries/regex/highlights.scm
This might be interesting for injected highlighting. So we could wait for that to come.
=> Add tree-sitter-regex

lua/nvim-treesitter/highlight.lua, queries/python/highlights.scm
Probably best to review each commit separately.
=> Updated python highlights

lua/nvim-treesitter/parsers.lua
Not sure if this was on purpose or if it was a mistake
=> Fix bash parser url

lua/nvim-treesitter/configs.lua, lua/nvim-treesitter/info.lua, lua/nvim-treesitter/install.lua, lua/nvim-treesitter/locals.lua
i forgot to rename some vars @theHamsta thanks again.
=> rename and finish ft->lang migration

README.md, queries/bash/highlights.scm
Some things still aren't highlighted properly, but they seem to be known issues in treesitter-bash. 
I'll be keeping track of any fixes that will affect highlighting.
=> add highlight queries for bash

lua/nvim-treesitter/query.lua
Attempts to fix #94.
@JoosepAlviste, does this fix the issue ?
=> Separate queries with newlines

plugin/nvim-treesitter.vim
Should fix #120, and also help fixing #119.
=> highlights: declare links as defaults

doc/nvim-treesitter.txt
I would love to add also a documentation here how to deactivate the error highlighting here. But I don't know how.
=> Extend documentation for TSError

queries/python/highlights.scm
=> add python async

lua/nvim-treesitter/configs.lua, lua/nvim-treesitter/info.lua, lua/nvim-treesitter/install.lua
- add sync method for installing using `system`
- remove `descriptions` in command configs
- use install(lang) in ensure_installed and make it compatible
fixes #111 
fixes #124 (the function call is ugly but idk right now)
=> update installer with sync and some fixes

lua/nvim-treesitter/install.lua
=> fix ask install

doc/tags
=> Renerate doc/tags

LICENSE
This is to match neovim's licence.
=> docs: add apache Licence

queries/lua/highlights.scm, queries/lua/locals.scm
=> Lua: update queries

.gitignore, .luacheckrc, .travis.yml, lua/nvim-treesitter/configs.lua, lua/nvim-treesitter/fold.lua, lua/nvim-treesitter/health.lua, lua/nvim-treesitter/incremental_selection.lua, lua/nvim-treesitter/locals.lua, lua/nvim-treesitter/refactor/highlight_definitions.lua, lua/nvim-treesitter/refactor/navigation.lua, lua/nvim-treesitter/refactor/smart_rename.lua, lua/nvim-treesitter/ts_utils.lua, lua/nvim-treesitter/utils.lua
Some style checking would be useful. Some issues are already fixed in #100 
Luacheck is happy now: https://travis-ci.org/github/theHamsta/nvim-treesitter/builds/704953331
Edit: ooops, it was only checking one file on bash.
=> Add Travis CI with luacheck

lua/nvim-treesitter/locals.lua
This is a preparation for `textobject` queries. Maybe a bit easier to review #100 in smaller pieces.
=> Allow arbitrary query files in locals.lua

CONTRIBUTING.md
Add a notice in the contributing that we provide a template repo to create modules.
Hopefully that will help people getting into the treesitter train easily.
=> docs: advertise module-template in CONTRIBUTING.md

queries/lua/highlights.scm, queries/lua/locals.scm
This avoids those annoying flickering highlights for now
=> Lua fix overlap

CONTRIBUTING.md, queries/c/locals.scm, queries/cpp/locals.scm, queries/rust/locals.scm
I will try to use the existing work in the discussion #57
=> Add rust locals.scm

README.md, lua/nvim-treesitter/configs.lua, lua/nvim-treesitter/refactor/highlight_current_scope.lua, lua/nvim-treesitter/refactor/highlight_definitions.lua, lua/nvim-treesitter/ts_utils.lua, plugin/nvim-treesitter.vim
Highlights current scope. Should this be a built-in module or should I publish it as separate plugin? Then, I would just try to merge the first commit of this PR that adds a `highlight_node` utility function.
=> Highlight current scope

queries/cpp/locals.scm
@vigoux @steelsojka Could you please merge?
=> Cpp locals: Fix syntax

.github/workflows/check_query_files.yml, scripts/check-queries.lua
Tests fails if some queries can not be loaded: https://github.com/theHamsta/nvim-treesitter/runs/869791835?check_suite_focus=true
~~I don't know yet why compiling the parsers does not produce any artifacts.~~ <- Upload before compiling
=> Add workflow to check query files

lua/nvim-treesitter/configs.lua
Abuse a bit of tbl_extend and tbl_deep_extend.
We might want to continue this effort, and simplify this part of the
plugin.
Fixes #178
=> Simplify module setup process

lua/nvim-treesitter/parsers.lua
=> Use C++ parser for "cuda" filetype

lua/nvim-treesitter/parsers.lua
Fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/181
=> Add additional typescript filetype to tsx parser

queries/c/highlights.scm, queries/lua/highlights.scm
Add `goto` keyword for C.
Fix typo for lua.
=> highlights: some fixes

queries/go/textobjects.scm
- function and methods as function textobject
- struct and struct literals as class textobject
- interface declaration as class textobject
- basic support for blocks, statements, and comments.
is this ok?
=> textobject support for golang

README.md, lua/nvim-treesitter/parsers.lua
I did not register as a maintainer since it's probably only interesting for JS (@steelsojka) and after implementation of language injection.
=> Add jsdoc parser

README.md, queries/go/textobjects.scm, queries/rust/textobjects.scm
Golang:
- added function literal (for anonymous function / go blocks)
- added (for) loop
Rust:
I think it's fairly complete, a bit unsure about what you guys think should quantify as class textobject in Rust.
=> Go loop and func literal, Rust textobject support

queries/bash/locals.scm
=> bash: add locals.scm for use with definition highlighting

queries/python/highlights.scm
Also highlight __init__/__new__ as constructor
=> Python highlights: highlight functions with self as methods

queries/javascript/textobjects.scm
This should be the same for typescript as well since ts extends js.
=> add js textobject queries

CONTRIBUTING.md, README.md, doc/nvim-treesitter.txt, lua/nvim-treesitter/highlight.lua, lua/nvim-treesitter/parsers.lua, plugin/nvim-treesitter.vim, queries/rst/highlights.scm, queries/rst/locals.scm, queries/rst/textobjects.scm
Hi everyone, thanks for such great work with this plugin, I'm really enjoying it!
I'm writing a rst grammar (<https://github.com/stsewd/tree-sitter-rst>), still wip, so feel free to not merge this till it's more complete (if you merge this now I'll make sure to keep the queries updated).
A screenshot with the current state
I'm not sure about some highlight groups, took some inspiration from https://github.com/neovim/neovim/blob/master/runtime/syntax/rst.vim
=> Parsers: add reStructuredText

lua/nvim-treesitter/configs.lua, lua/nvim-treesitter/parsers.lua, lua/nvim-treesitter/ts_utils.lua
=> configs: attach on unknown parsers too

CONTRIBUTING.md, README.md, doc/nvim-treesitter.txt
Format the docs to be consisted and some typos.
=> Docs: format and fixes

queries/rst/highlights.scm
I just added support for roles on the grammar
=> rst: update highlight queries

lua/nvim-treesitter/query_predicates.lua
Adds the adjacent predicate. Allows to match nodes that are directly followed by one or more match or type. Here are some examples.
Matches a comment node that is directly followed by a function definition.
```scheme
(
(comment) @function.doc
(function_declaration) @function.definition
(adjacent? @function.doc @function.definition)
)
```
Matches any comment that is direclty followed by a variable declaration or function declaration
```scheme
(
(comment) @comment
(adjacent? @comment "function_declaration" "lexical_declaration")
)
```
Matches a block of comments adjacent to a function declaration.
```scheme
(
(comment) @function.doc
(function_declaration) @function.definition
(adjacent_block? @function.doc @function.definition)
)
```
The above would match this.
```javascript
// This comment …
```
=> feat(predicates): add adjacent predicate

lua/nvim-treesitter/incremental_selection.lua
=> fix decremental selection

README.md, queries/html/locals.scm, queries/javascript/locals.scm, queries/php/highlights.scm, queries/php/locals.scm, queries/toml/highlights.scm, queries/toml/locals.scm
I added query for some languages.
If you would like, can you merge this pull request?
=> Add queries for PHP, TOML and HTML

queries/python/textobjects.scm
Just getting ahead of https://github.com/nvim-treesitter/nvim-treesitter/pull/218/
=> Python: update textobjects queries

queries/rst/highlights.scm
I have implemented some new nodes into the grammar.
=> RST: update queries

README.md
This should be merged after https://github.com/nvim-treesitter/nvim-treesitter/pull/243
=> Docs: add troubleshooting for when a parser changes

CONTRIBUTING.md, lua/nvim-treesitter/highlight.lua, plugin/nvim-treesitter.vim, queries/dart/highlights.scm
Update dart highlights, copying over a few things from the upstream `highlights.scm` and add new `const_builtin` and `final_builtin` queries.
=> Dart highlights II

lua/nvim-treesitter/configs.lua
=> configs: actually enable and disable on setup

lua/nvim-treesitter/install.lua, lua/nvim-treesitter/parsers.lua
This speeds up starting time by quite a lot.
=> perf: cache parser file list for performance

lua/nvim-treesitter/highlight.lua, lua/nvim-treesitter/query.lua, lua/nvim-treesitter/query_predicates.lua
Tiny tiny PR just to adapt to latest upstream/nvim changes.
=> fix: refactor after upstream refactor

CONTRIBUTING.md, lua/nvim-treesitter/locals.lua, queries/javascript/locals.scm
This should fix #170 
I still have to go and update the language files for all applicable use cases.
=> feat(defintions): allow setting of scope

queries/python/locals.scm
This makes use of https://github.com/nvim-treesitter/nvim-treesitter/pull/295
=> Python: update locals

README.md, lua/nvim-treesitter/parsers.lua, queries/fennel/highlights.scm, queries/fennel/locals.scm
additions:
- tree-sitter-fennel to parser list
- locals and highlights
- update to the readme indicating support for the language
=> Add fennel support

queries/c/highlights.scm, queries/javascript/highlights.scm, queries/lua/highlights.scm, queries/python/highlights.scm
This is until we can solve some of the performance issues around this.
=> chore(highlights): remove is predicate usage

queries/javascript/jsx.scm
i forgot these. Jsx should be working great now :)
=> add jsx fragment and jsx self closing element highlights

queries/python/highlights.scm
- Fix "as" outside imports
- Add builtin classes and constants
=> Python: update highlights

queries/python/highlights.scm
These aren't valid lua patterns
=> Python: fix some highlights

README.md, doc/nvim-treesitter.txt
=> Docs: fix textobjects

scripts/update-readme.lua
This should explain a bit better what to do when README CI fails.
=> feat(CI): print text what went wrong when README CI fails

README.md
=> docs: document foldmethod workarounds

.github/workflows/update-readme.yml, README.md, scripts/update-readme.lua
Experiment to make the README CI rather auto-update the PRs instead of making them fail. See: https://github.com/neovim/nvim-lspconfig/blob/master/.github/workflows/docgen.yml
=> feat(CI): auto-update README.md

README.md, doc/nvim-treesitter.txt, lua/nvim-treesitter/refactor/navigation.lua
=> Lsp fallback for goto_definition

ftdetect/query.vim
Add a little `ftdetect` just to trigger `query` filetype for queries.
=> feat: add query filetype

.github/CODEOWNERS
This will allow to trigger reviewers automatically, we will have to think about it and add people as
we go.
=> docs: Add CODEOWNERS file

CONTRIBUTING.md, lua/nvim-treesitter/fold.lua, lua/nvim-treesitter/query.lua, queries/c/fold.scm, queries/lua/fold.scm
Move fold into a module, and update it a bit to fix some issues.
=> fix(fold): revamp fold into a module

lua/nvim-treesitter/query_predicates.lua
This will avoid us some warnings after https://github.com/neovim/neovim/pull/12826
=> preds: declare set! predicate

queries/python/fold.scm
=> Python: update folds

autoload/nvim_treesitter.vim, lua/nvim-treesitter/configs.lua, lua/nvim-treesitter/info.lua, lua/nvim-treesitter/install.lua, plugin/nvim-treesitter.vim
Didn't see any improvement in startup, but if felt weird having those functions in there.
=> Refactor: move completion functions to autoload

queries/query/highlights.scm
=> Query: update highlights

lua/nvim-treesitter/configs.lua
=> use nvim_treesitter#available_modules

autoload/nvim_treesitter.vim, lua/nvim-treesitter/configs.lua, lua/nvim-treesitter/info.lua, lua/nvim-treesitter/install.lua
Fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/396
=> Completion: use custom instead of customlist

README.md, doc/nvim-treesitter.txt, plugin/nvim-treesitter.vim
This provides a better experience for users without any extra config. I think there was some discussion around this but I don't think anyone decided in anything, let me know what you think.
=> Highlights: default TSError to Normal

queries/lua/highlights.scm
=> Lua: fix loop and conditional keywords highlights

queries/bash/highlights.scm
=> fix bash highlight

queries/rst/highlights.scm
This is causing an error.
ref https://github.com/nvim-treesitter/nvim-treesitter/issues/387#issuecomment-687842331
=> rst: remove unused captures

lua/nvim-treesitter/fold.lua
Right now we will fold all nodes we find, but this can result in so many nested folds. Neovim has the `foldnestmax` (local to window, default to 20) option to control this when using `indent` or `syntax`. I'm reusing that option here, let me know if this should be another setting instead.
- docs
=> [RFC] Fold: respect max_fold_level from 'foldnestmax'

lua/nvim-treesitter/incremental_selection.lua
The range from ts nodes are a little different than
neovim's nodes. They start at 0 and the end is exclusive.
For example, a nvim range (1, 3, 2, 4) is the equivalent to the ts
range (0, 2, 1, 4).
Since we may hit parent nodes that have the same range as its child,
we skip those till we find one that actually changes the selection
(since this is the relevant part for the user).
Fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/232
=> Incremental selection: fix skipping some nodes

README.md, doc/nvim-treesitter.txt
=> Fold: update docs

lua/nvim-treesitter/query.lua
These two are doing the same currently.
=> Queries: merge query_extensions into base_language_map

lua/nvim-treesitter/configs.lua, lua/nvim-treesitter/query.lua
Some numbers
```
186.298  000.003: --- NVIM STARTED ---
179.851  000.004: --- NVIM STARTED ---
196.774  000.007: --- NVIM STARTED ---
201.460  000.003: --- NVIM STARTED ---
197.011  000.003: --- NVIM STARTED ---
190.126  000.003: --- NVIM STARTED ---
188.211  000.003: --- NVIM STARTED ---
199.551  000.003: --- NVIM STARTED ---
```
```
172.590  000.004: --- NVIM STARTED ---
176.226  000.004: --- NVIM STARTED ---
167.962  000.003: --- NVIM STARTED ---
170.539  000.003: --- NVIM STARTED ---
170.572  000.004: --- NVIM STARTED ---
170.122  000.005: --- NVIM STARTED ---
173.517  000.004: --- NVIM STARTED ---
176.183  000.003: --- NVIM STARTED ---
```
=> Improve startup performance

lua/nvim-treesitter/configs.lua
This check shouldn't have been here :bug:
=> Allow to call setup on already enabled modules.

doc/nvim-treesitter.txt
Ref https://github.com/nvim-treesitter/nvim-treesitter/issues/435
=> Highlight definition: mention updatetime in docs

queries/php/fold.scm, queries/php/locals.scm
- Add fold query
- Remove scope definition that not create scope
- Sprit reference queries by kind
- Adjusted some definition queries scope to right hierarchy
=> Update PHP query

queries/bash/highlights.scm
Fixes https://github.com/nvim-treesitter/nvim-treesitter/issues/387
=> Bash: fix hl capture groups

queries/rst/locals.scm
A title is an implicit target.
=> RST: update locals

queries/ruby/highlights.scm
=> update require statements to use TSInclude

plugin/nvim-treesitter.vim
=> use TSnone instead of linking to Normal

queries/java/locals.scm
=> chore(java): remove duplicate line

lua/nvim-treesitter/install.lua
Compilers are selectable via `'nvim-treesitter.install'.compilers` (list of compilers) or environment variable CC
Addresses #502
=> feat(install): make compiler selectable

queries/dart/locals.scm
This is an initial stab at this since I don't know much about how this
should work but this seems to at least allow incremental selection of
most blocks of code.
I will look into doing fancier more granular stuff in the future but atm there is no selection in dart and this is an improvement
=> Add locals.scm for dart

queries/python/locals.scm
https://github.com/tree-sitter/tree-sitter-python/pull/83 (was only merged a few minutes ago)
BREAKING CHANGE!
=> Python locals: account for expression_list -> left_hand_side

queries/dart/highlights.scm
Only just realised I'd missed out a few more keywords for dart highlighting
=> Add extension and on keywords

README.md
=> [docgen] Update README.md

lua/nvim-treesitter/install.lua
https://nvim-treesitter.zulipchat.com/#narrow/stream/252338-help/topic/TSInstall.20stuck.20at.20.22Compiling.2E.2E.2E.22/near/212230739
=> Fix: fallback git-installation (list of commands is expected)

lua/nvim-treesitter/parsers.lua, queries/teal/folds.scm, queries/teal/highlights.scm, queries/teal/locals.scm
[Teal](https://github.com/teal-language/tl) is a typed dialect of lua that's starting to gain some traction.
I also maintain the actual parser for it and use neovim, so I can maintain the queries and such too as the language evolves. :)
Everything appears to work (as in "works on my machine"), but if there's anything else needed let me know!
=> Add teal parser

autoload/nvim_treesitter.vim, doc/nvim-treesitter.txt, lua/nvim-treesitter.lua
This is the implementation for https://github.com/nvim-treesitter/nvim-treesitter/issues/545.
=> Add implementation for improved statusline. Closes #545.

lua/nvim-treesitter/highlight.lua, lua/nvim-treesitter/query.lua
After the runtime queries addition, tidy up our side and adapt to new interface.
This should also fix #573
=> Fixes after upstream runtime query implementation

queries/lua/folds.scm
Add repeat_statement to lua folds
=> feat: Add more lua folds

queries/javascript/folds.scm
Adds some additional folds for Javascript to allow folding on if statements, try catch blocks, and objects
- queries/javascript/folds.scm
Just thought I'd open a PR to add these folds for JS. I tested them locally and it was working well. Please let me know if I need to do anything else. Thanks!
=> feat: add more javascript folds

README.md, lua/nvim-treesitter/parsers.lua, queries/verilog/highlights.scm
A start of verilog/SystemVerilog support.
I've added some queries for highlighting, but there are still some rough edges and unsupported parts.
=> Verilog support

lua/nvim-treesitter/configs.lua
https://nvim-treesitter.zulipchat.com/#narrow/stream/252271-general/topic/Random/near/210929394
=> feat: add TSConfigInfo to display current config

lua/nvim-treesitter/languagetree.lua
This fixes some issues with language injection I've noticed.
Currently, we only get the lines that changed (not including the column), but injections that don't start at 0 never match the range given for the line change. This runs all highlighters that exist for the given line. This fixes code like this:
=> fix(languagetree): highlight children regardless of starting column

lua/nvim-treesitter/install.lua
This is mainly thought as an internal feature for parser developers to install them from a local path
E.g. when you are working on a Lisp parser:
```
require "nvim-treesitter.parsers".get_parser_configs().lisp = {
install_info = {
url = "~/projects/tree-sitter-lisp",
files = {"src/parser.c"}
}
}
```
and then `:TSInstall lisp`/`:TSUpdate lisp` to compile and install the parser and `:TSInstallFromGrammar lisp` to run `tree-sitter generate` before compiling.
Depends on #503 (only because I edited the same code region).
=> Install parsers with `repo.url` as a local path

lua/nvim-treesitter/parsers.lua, queries/clojure/highlights.scm, queries/clojure/locals.scm
There is a preliminary highlights.scm file and a blank locals.scm file (to enable incremental selection to work).
=> Add initial clojure support

queries/javascript/highlights.scm, queries/typescript/highlights.scm
=> typescript: Add optional_parameter ?

README.md, lua/nvim-treesitter/parsers.lua, queries/nix/folds.scm, queries/nix/highlights.scm, queries/nix/locals.scm
I've added pretty detailed comments, since I'm assuming most people working on nvim-treesitter don't use Nix.
I tried to add an indents.scm as well, though I got absolutely awful results. Since that currently only exists for Lua, I'm guessing that indent support is a work in progress?
=> Initial Nix queries

lua/nvim-treesitter.lua
@vigoux sorry, for telling you the wrong code.
=> fix: make version check work on non-CI environments

queries/javascript/injections.scm, queries/markdown/injections.scm, queries/ocamllex/injections.scm
=> fix(injections): update to new API

README.md, lua/nvim-treesitter/parsers.lua, queries/graphql/highlights.scm
This adds a GraphQL grammar for tree-sitter
=> feat: add graphql grammar

queries/graphql/highlights.scm, queries/javascript/injections.scm
=> graphql: add injection to javascript and add comment query

lockfile.json
There was another commit after the push of our PR bot.
=> Update Ruby parser

README.md, lua/nvim-treesitter/parsers.lua, queries/kotlin/highlights.scm
does have the most of the basics, but has some issues as well. I'll look at scoping next. any tips are welcome :)
=> Add kotlin

lockfile.json
No new nodes only a fix for trailing spaces
=> Update Elm parser

lua/nvim-treesitter/parsers.lua
=> fix erlang parser installation

queries/javascript/highlights.scm, queries/typescript/highlights.scm
Move unary expressions to operator.
https://tc39.es/ecma262/#sec-conditional-operator
[old punctuation.special screenshot](https://user-images.githubusercontent.com/15027/100382449-65fe9280-2fe9-11eb-8834-6da0b7f550b1.png)
=> Javascript unary expression

queries/lua/locals.scm
=> Capture anonymous functions assigned to variables

queries/teal/folds.scm, queries/teal/highlights.scm, queries/teal/locals.scm
Teal just updated to 0.9 with some minor new syntax and I've been reworking the parser and tagged a new release, these queries should accommodate that.
=> Update for teal-0.9

queries/python/indents.scm
=> Create indents.scm for python

queries/bash/folds.scm, queries/bash/highlights.scm
Add missing fold queries
Add "function" to keywords highlights
=> feat: Add more bash queries

README.md, lua/nvim-treesitter/parsers.lua, queries/gdscript/highlights.scm, queries/gdscript/locals.scm
=> add gdscript

README.md, lua/nvim-treesitter/parsers.lua, queries/julia/highlights.scm, queries/julia/injections.scm, queries/julia/locals.scm
Maybe I'm gonna do this Advent of Code in Julia. I already added some highlights and plan to iteratively add more.
Julia beautiful tree sitter: https://www.sarahbeekmans.com/julia-hill/
=> Julia highlights

README.md
Thanks @David-Else for the suggestion.
Fixes #270
=> docs: mention running packadd in README.md

lockfile.json, queries/query/highlights.scm
Needs https://github.com/nvim-treesitter/tree-sitter-query/pull/5
=> Query: add string.escape

lockfile.json, queries/teal/highlights.scm
accommodates the changes in syntax for teal introduced in 0.10
=> Update teal syntax for 0.10

lockfile.json, queries/python/highlights.scm, queries/python/locals.scm
Account for updates of tree-sitter-python: https://github.com/tree-sitter/tree-sitter-python/compare/65b486b42f...f568dfabf7
=> Python locals: Add new node with_clause

lua/nvim-treesitter/highlight.lua
Remove unneeded query management code.
Fix detach issues, and simplify it.
=> Various highlight things

queries/ruby/highlights.scm
Distinguish from @constant. Closes #874
=> Highlight ruby symbols as @property

queries/lua/highlights.scm, queries/lua/locals.scm
Issue raised on gitter by @bfredl.
=> lua: handle do_statement

queries/cpp/highlights.scm
=> highlights(cpp): fix constructor call highlighting

doc/nvim-treesitter.txt, lua/nvim-treesitter/configs.lua
This PR adds toggle (enable if disabled, disable if enabled) commands `TSBufToggle` and `TSToggleAll`. They should act exactly like enable and disable commands depending on the state of module.
I also took the liberty of making small fixes to documentation of existing commands (sync command names, tweak style).
Fixes #259.
=> Implement toggle commands

lockfile.json, queries/ledger/highlights.scm
Cleanly solve the issue in https://github.com/nvim-treesitter/nvim-treesitter/pull/910.
@theHamsta this should be fine :)
=> Update lockfile.json and `amount` query for ledger

queries/lua/locals.scm
- Set scope to parent
- Group all scopes
- Use the . operator
=> Lua: improve scope queries

lua/nvim-treesitter/parsers.lua, queries/supercollider/folds.scm, queries/supercollider/highlights.scm, queries/supercollider/indents.scm, queries/supercollider/locals.scm
This adds support for the supercollider programming language. See https://github.com/nvim-treesitter/nvim-treesitter/issues/902
=> Supercollider

queries/yaml/locals.scm
This is so incremental selection works
=> YAML: add locals

queries/c/injections.scm, queries/cpp/injections.scm
Closes https://github.com/nvim-treesitter/nvim-treesitter/issues/663
=> C/CPP: add injections for macros

lockfile.json
Adds support for multi-word commodities.
=> Bump ledger version

lockfile.json, lua/nvim-treesitter/parsers.lua, queries/nix/highlights.scm
This is the update-lockfile-pr
=> Fix nix compilation

lockfile.json
Till we figure out what's happening.
Ref:
- https://github.com/tree-sitter/tree-sitter-c/commits/master
- https://github.com/nvim-treesitter/nvim-treesitter/issues/948
=> C: downgrade parser

queries/json/folds.scm
=> Json: update folds

lua/nvim-treesitter/parsers.lua
Based on feedback on https://github.com/nvim-treesitter/nvim-treesitter/pull/953#pullrequestreview-591742636
=> Update README data for JSONC

README.md, lua/nvim-treesitter/health.lua
=> chore: rewrite healthcheck

README.md, lua/nvim-treesitter/parsers.lua, queries/svelte/folds.scm, queries/svelte/highlights.scm, queries/svelte/indents.scm, queries/svelte/injections.scm
~~we'll need to wait until https://github.com/Himujjal/tree-sitter-svelte/pull/3 got merged but I thought I'll put this here so everyone could comment on this.~~ It has been merged
also, I don't know who to put in the maintainer field, is it someone who maintains the query or is it the one who maintains the parser? or both? I can only maintain the queries since I don't know much about C to make the scanner for the parser :laughing:
~~edit: should wait for #926 because I added some stuff from there (the reason why the test failed), Svelte is like HTML afterall so they have similar queries~~. It's ready now.
=> feat: add support for svelte

README.md, lua/nvim-treesitter/configs.lua, lua/nvim-treesitter/health.lua, lua/nvim-treesitter/install.lua, lua/nvim-treesitter/locals.lua, lua/nvim-treesitter/parsers.lua, lua/nvim-treesitter/query.lua, lua/nvim-treesitter/shell_command_selectors.lua, lua/nvim-treesitter/ts_utils.lua, lua/nvim-treesitter/tsrange.lua, lua/nvim-treesitter/utils.lua
This PR is not that useful but at least code is indented properly.
I also removed some code in `parsers.lua` that wasn't needed/used anymore.
=> Chore: ident files and remove some useless code

queries/svelte/highlights.scm
=> svelte: also capture src as text.uri

queries/c/highlights.scm
See https://en.wikipedia.org/wiki/Register_(keyword)
=> Add 'register' as c-keyword

README.md, lua/nvim-treesitter/parsers.lua
=> fix: used by config

queries/query/indents.scm, queries/rust/indents.scm, queries/toml/indents.scm
- added indent for query files
- indent for `rust` match
- toml indent fixes
=> feat: indent additions

README.md, lockfile.json, lua/nvim-treesitter/parsers.lua, lua/nvim-treesitter/shell_command_selectors.lua, queries/c/highlights.scm
- @stsewd @bool3max #948 Still problems with C parser with this change?
- Address #972:
- pin jsonc parser
- add tar download support for Gitlab
=> Mother of all parser updates

README.md, lua/nvim-treesitter/parsers.lua, lua/nvim-treesitter/shell_command_selectors.lua
https://github.com/nvim-treesitter/nvim-treesitter/pull/950#discussion_r585691800
=> Fix: Allow repo.url to end in ".git"

queries/ruby/folds.scm, queries/ruby/indents.scm
=> folds support and somewhat better indents for ruby

queries/go/highlights.scm
Add builtin-functions for Go: https://golang.org/pkg/builtin/
=> go: add builtin functions

.github/workflows/update-parsers-pr.yml, lockfile.json, lua/nvim-treesitter/parsers.lua
It's a lot faster to do this in a automated way.
@sogaiou could you create a PR when you merge your 0.19.X branch?
=> Lockfile post 19.2

lockfile.json, lua/nvim-treesitter/parsers.lua
@bkegley just updated his parser
=> Graphql, Turtle, SparQL 0.19.3

queries/glimmer/highlights.scm
Maybe there is a way to read this file from the plugin directly?
=> Update glimmer queries from plugin

lockfile.json
Follow up discussion here: https://github.com/nvim-treesitter/nvim-treesitter/pull/893#issuecomment-782294813
=> Add comment parser to js

lockfile.json
fixed bug https://github.com/Himujjal/tree-sitter-svelte/issues/7
=> updated svelte repo

lua/nvim-treesitter/parsers.lua, queries/beancount/folds.scm, queries/beancount/highlights.scm, queries/beancount/locals.scm
I have written a tree-sitter parser for beancount that I would like added to this repo, thanks
=> add support for beancount files

README.md, lua/nvim-treesitter/parsers.lua
@clason suggested to use those. The parsing results look really good. Let's add some queries for highlights/folding (also textobjects will be cool)
=> Add LaTeX/Bibtex parser

lua/nvim-treesitter/health.lua
=> use health#report_warn for treesitter version check

README.md, lockfile.json, lua/nvim-treesitter/parsers.lua, queries/zig/folds.scm, queries/zig/highlights.scm, queries/zig/indents.scm, queries/zig/locals.scm
Added Zig grammar support for neovim.
=> Added Zig grammar

README.md, lua/nvim-treesitter/parsers.lua
Since TSX is so close to typescript I will go ahead and officially maintain it... mostly to check the box.
=> chore(parsers): add tsx maintainer

doc/nvim-treesitter.txt, lua/nvim-treesitter/fold.lua, lua/nvim-treesitter/indent.lua, lua/nvim-treesitter/locals.lua, lua/nvim-treesitter/parsers.lua, lua/nvim-treesitter/query.lua, lua/nvim-treesitter/ts_utils.lua, lua/nvim-treesitter/tsrange.lua, lua/nvim-treesitter/utils.lua
This integrates the language tree into most of the features. This also fixes some other issues I discovered. Memoizing was really messed up and performing a crazy amount of unneeded computations. This will greatly effect the performance of definition lookup, indents, and folds. Indents still aren't working yet. I will continue looking at it.
=> refactor(all): language tree adaption

lua/nvim-treesitter/health.lua
=> Add tree-sitter ABI version to health check

lockfile.json, queries/zig/folds.scm, queries/zig/highlights.scm, queries/zig/indents.scm, queries/zig/injections.scm, queries/zig/locals.scm
I have done some improvements upon zig queries and the grammar. Please do merge.
=> Improved zig grammars and queries

lua/nvim-treesitter/health.lua
This should help users @przepompownia 
Ref: https://github.com/nvim-treesitter/nvim-treesitter/issues/1110#issuecomment-811775871
=> ABI healthcheck

lua/nvim-treesitter/incremental_selection.lua
So, there are two problems:
- There was an infinite loop when inc selection was initiated
from an injection.
- The comparison was wrong when the whole file was selected,
this is because ts matches the EOF.
This is an extra line with one char (EOF).
I put a workaround to try to select the node from the main
tree, but we should try to select the node from the parent tree of the
injection, but I wasn't able to get the parent tree from the node.
You can test the problem with this same file, init the incremental selection on a comment.
=> Fix incremental selection

lua/nvim-treesitter/query.lua, lua/nvim-treesitter/utils.lua
This is required to make theHamsta/nvim-treesitter-pairs work
=> Fix: allow empty path in utils.get_at_path

queries/glimmer/highlights.scm
Copied latest updates from: https://github.com/alexlafroscia/tree-sitter-glimmer/blob/main/queries/highlights.scm
=> glimmerjs: Sync with upstream package

lua/nvim-treesitter/health.lua
=> fix(health): let CC check behave like in real installation

queries/go/highlights.scm, queries/go/locals.scm
=> highlights(go): Highlight const_declaration

README.md, lua/nvim-treesitter/parsers.lua, queries/scss/highlights.scm, queries/scss/indents.scm, queries/svelte/injections.scm, queries/vue/injections.scm
The parser from this tree-sitter-scss repo seems to be working good enough, haven't use it for daily though since I barely work with scss.
Also, please suggest me the proper capture group, I just picked whatever makes sense to me and make the result looks colourful enough :laughing: 
cc @cloggier @euoia @timsofteng
=> feat: add scss parser

queries/java/highlights.scm, queries/java/locals.scm
Ref: https://github.com/tree-sitter/tree-sitter-java/pull/73
=> Add support for Java records

autoload/nvim_treesitter.vim, doc/nvim-treesitter.txt, lua/nvim-treesitter/configs.lua, lua/nvim-treesitter/query.lua
~~This is currently affected by the runtime file duplication bug:
https://github.com/neovim/neovim/issues/14294~~
EDIT: used the upstream method that does the dedup and include inherited languages.
=> feat: Add TSEditQuery

queries/ledger/highlights.scm
I have updated the highlights in the upstream repo in
https://github.com/cbarrete/tree-sitter-ledger/commit/941bbf609858e0fb355b663ccc7bbd6f9bc8863e.
=> ledger: update highlights

queries/java/highlights.scm
https://github.com/tree-sitter/tree-sitter-java/pull/78 added support
for enhanced switch statements
=> highlights(java): add new keyword "yield"

README.md, lockfile.json, lua/nvim-treesitter/parsers.lua, queries/yaml/highlights.scm, queries/yaml/locals.scm
Closes https://github.com/nvim-treesitter/nvim-treesitter-refactor/issues/18
=> YAML: update queries

lockfile.json, queries/svelte/highlights.scm
Update parsers and remove one letter from svelte queries. @elianiva
=> Fix svelte queries

lua/nvim-treesitter/configs.lua, lua/nvim-treesitter/incremental_selection.lua
As suggested [here](https://github.com/nvim-treesitter/nvim-treesitter/pull/956#discussion_r577363050).
=> feat(incremental_selection): don't require locals

.github/FUNDING.yml, doc/nvim-treesitter.txt
Adds the new maintainers (that were actually added a long time ago), fix inconsistent formatting, and unneeded or old/wrong docs.
I think we could also start to include some sponsoring notes to the
repo, as suggested in https://github.com/nvim-treesitter/nvim-treesitter/pull/1142#issuecomment-819753698
=> docs: Update vimdoc file

.github/FUNDING.yml
Maybe there is an issue with our dash in the name, we'll see.
=> fix: use correct name in FUNDING.yml

queries/tsx/injections.scm
=> injections(tsx): inherit injections from ecma

queries/julia/highlights.scm
We forgot them? How?
For operators we could wait for `any-of?` https://github.com/neovim/neovim/pull/14344
=> highlights(julia): add punctuation

doc/nvim-treesitter.txt, lua/nvim-treesitter/highlight.lua
- Add "comment" to `hlmap`
- Update the `nvim-treesitter-highlights` docs
=> Tweak Highlight Groups

plugin/nvim-treesitter.vim
Fix https://github.com/nvim-treesitter/nvim-treesitter/issues/1246
=> Link TSComment to Comment

queries/cpp/highlights.scm
Try to avoid overwriting C_CONSTANTS
=> C constants

queries/python/highlights.scm
Maybe wait a bit until this feature has stabilized a bit.
=> highlights(python): use any-of?

README.md, lua/nvim-treesitter/parsers.lua, queries/clojure/folds.scm, queries/clojure/highlights.scm, queries/commonlisp/folds.scm, queries/commonlisp/highlights.scm, queries/commonlisp/locals.scm
Since everything is very WIP I don't plan to merge this any time soon since it requires really a lot more work and I need to make some decision how stuff is supposed to work. But suggestions are always welcome.
The parser is an extension of @sogaiu 's tree-sitter-clojure with some rules overwritten.
~~TODO: use `@symbol`~~
=> Support for Common Lisp

lockfile.json, queries/fish/highlights.scm
Updates the lock file and update fish highlight query accordingly.
=> Update fish parser

lockfile.json, queries/supercollider/highlights.scm
Hello
This is a tiny pull request to make highlighting changes to match a minor highlight change in upstream. Thanks
=> supercollider: simplify method

README.md, queries/php/highlights.scm
=> fix(php): highlights function call expression

queries/dart/highlights.scm
Since a new version of dart was released a few keywords were added. This PR adds the two main ones I'm aware of. There might be more but I'll add those as I discover them in the future
=> feat(dart): add late & required keywords

lockfile.json, queries/fortran/highlights.scm, queries/fortran/indents.scm
=> Improve fortran highlighting and add support for indentation

lua/nvim-treesitter/install.lua
Collect stdout/stderr of commands and only show them on command failure
Looks like this:
I don't know why the users has to press `<cr>` an additional time after we show the error
Before:
Disclaimer: I have very little experience with `luv`
=> chore: show errors output during async installation

queries/c_sharp/highlights.scm
=> Improve c sharp

lua/nvim-treesitter/health.lua
=> Fix #1359: nil check for version in health-check

README.md
Stabilization of treesitter has been postponed, so we are going to
require people to follow master for a bit longer.
=> docs: notify that treesitter stabilization in planned for 0.6

README.md
- Fixes #1439 (refer that thread for discussion)
- Also added a note saying that the page is community maintained
=> doc: link Installation wiki page in the README

queries/fortran/highlights.scm
I some how lost the permissions to push on @oponkork master I pushed a wrong commit. The update of the lockfile.json caused the conflict.
=> Fortran update

README.md, queries/zig/highlights.scm
=> highlights(zig): use `@string.escape` for escape sequences

lua/nvim-treesitter/health.lua
Fix https://github.com/nvim-treesitter/nvim-treesitter/issues/1459
=> Checkhealth: include injections

lockfile.json, queries/ledger/highlights.scm
=> Update ledger highlights

lua/nvim-treesitter/parsers.lua
=> [HCL] remove packer and nomad used_by

README.md, doc/nvim-treesitter.txt, lua/nvim-treesitter/fold.lua
=> Folds: support 'foldminlines'

README.md
Also updated troubleshooting section with similar instructions.
Fixes #1478
=> Add info about queries and filetype detection to Adding Parsers section of README

lockfile.json, lua/nvim-treesitter/configs.lua, lua/nvim-treesitter/tsrange.lua
Stylua has updated to a new version and the workflow also automatically updated. Should fix the version update
=> New stylua version

lockfile.json, queries/query/highlights.scm
This is to match https://github.com/nvim-treesitter/tree-sitter-query/pull/15
=> Query: update highlight queries

.github/mergify.yml
As discussed internally, we setup mergify.
=> Setup mergify 

lua/nvim-treesitter/configs.lua
Requires https://github.com/neovim/neovim/pull/14995
Closes https://github.com/nvim-treesitter/nvim-treesitter/issues/1249
Closes https://github.com/nvim-treesitter/nvim-treesitter/issues/1544
Closes https://github.com/nvim-treesitter/nvim-treesitter/issues/1574
=> Re-attach module when the file type is changed

.github/mergify.yml
This will avoid merging too rapidly.
=> feat(mergify): delay mergify merging by one day

README.md, lua/nvim-treesitter/parsers.lua
Repository was transferred to @ram02z.
=> Update transferred fish repository info

scripts/ci-install-macos-latest.sh
Installation before: 7m 56s 
After: 36s
=> Change install command on Mac

lockfile.json, queries/yang/highlights.scm
Numerous parsing improvements and fixes, updated highlights query to make more semantic sense and to highlight new symbols from the parser.
=> Update YANG parser revision and highlights query

queries/clojure/highlights.scm
Fix https://github.com/sogaiu/tree-sitter-clojure/issues/14
=> highlights(clojure): fix highlighting of #_

README.md, ftdetect/gdresource.vim, lua/nvim-treesitter/parsers.lua
Follow-up of my other PR https://github.com/nvim-treesitter/nvim-treesitter/pull/1636
=> feature: make godotResource compatible with gdresource filetype & add ftdetect

ftdetect/fish.vim, ftdetect/graphql.vim, ftdetect/julia.vim, ftdetect/ledger.vim, ftdetect/nix.vim, ftdetect/ql.vim, ftdetect/teal.vim
I started adding Nix and Fish, which I use, but I decided to add some others that I didn't find in the Neovim runtime by looking at how support plugins do it
=> Add some missing ftdetect files

lua/nvim-treesitter/install.lua
Ref https://github.com/nvim-treesitter/nvim-treesitter/pull/1661#issuecomment-894722369
=> CI: fix update lockfile job

README.md, queries/ecma/highlights.scm
Highlight shebang's as comments.
=> Enable to highlight shebang on JS/TS

queries/zig/highlights.scm
=> highlights(zig): label, switch item, operator, punctuation, property

queries/query/highlights.scm
=> Query: highlight numbers

README.md, lua/nvim-treesitter/parsers.lua, queries/vim/highlights.scm, queries/vim/injections.scm
As asked in #1187 this PR will be tracking the progress in supporting
VimL.
As the parser is not yet finished, this is really just a draft branch,
so that people can subscribe to it and have updates on the progress.
=> feat: add support for viml

README.md, queries/php/highlights.scm
Add missing `instanceof` keyword
=> highlights(php): add `instanceof` as `@keyword`

lua/nvim-treesitter/query.lua
Useful to get different captures for the same range without having to call this function for each capture.
=> Query: allow to pass a list to get_capture_matches

README.md, scripts/update-lockfile.sh
This allows to repin a language by simply doing:
```
./scripts/update-lockfile.sh [mylang]
```
=> Add an update script

lua/nvim-treesitter/shell_command_selectors.lua
=> fix(dowload): don't display curl progress

queries/scala/highlights.scm
* add type highlights
* add call expression highlights
* add function definition highlights
* add expression highlights
* add literals highlights
* add operator highlights
* add punctuation highlights
* add comment highlights
=> update scala highlights

queries/tlaplus/highlights.scm
These queries are compatible with tree-sitter-tlaplus 0.2.0
=> Update highlight queries for tlaplus

queries/scala/folds.scm, queries/scala/highlights.scm, queries/scala/injections.scm
Add scala folds
Update scala highlights
* add highlights for imports
* add highlights for type constructors
* add highlights for constants
* add highlights for interpolation string
* add highlights for comments through injection
=> Update scala queries

lua/nvim-treesitter/parsers.lua
=> fix(lang): only use first part in multi-lang

lockfile.json, lua/nvim-treesitter/parsers.lua, queries/kotlin/highlights.scm
This PR replaces the old ~~stinky~~ kotlin parser for a new and improved one, with emphasis on simplicity and performance.
Hopefully fixes #1643
=> New kotlin parser

README.md, queries/c/highlights.scm, queries/cpp/highlights.scm
@jdrouhard did I forget some things?
=> C/C++  Highlight updates

ftdetect/hjson.vim, lua/nvim-treesitter/parsers.lua, queries/hjson/folds.scm, queries/hjson/highlights.scm, queries/hjson/indents.scm, queries/hjson/injections.scm, queries/hjson/locals.scm
Provide support for hjson, originated from https://github.com/nvim-treesitter/nvim-treesitter/pull/1657
@theHamsta It should be good this time.
=> Support hjson

lua/nvim-treesitter/parsers.lua, queries/perl/highlights.scm
This PR adds support for the perl language courtesy of the hard work of @ganezdragon.
https://github.com/ganezdragon/tree-sitter-perl
=> Add support for Perl 

lua/nvim-treesitter/incremental_selection.lua, lua/nvim-treesitter/ts_utils.lua
https://github.com/nvim-treesitter/nvim-treesitter/pull/1829
half fixed incremental selection for the vim parser,
but other bugs still remain (infinite selection and skip selecting the
root node).
Problems can be replicated with these two files:
(missing selecting the root node)
```vim
set scrolloff=7
set scrolloff=7
```
(infinite loop)
```vim
set scrolloff=7
```
The main problem is that we try to map
the current selection range to a TS range,
but the TS range of a node could include the EOL/EOL marks
so it's impossible to know when to change the vim range
to match the TS range, is more easy to transform the
TS range to a vim range and do the comparison.
There are a few other places where we could use get_vim_range, but for now I'm replacing it in all code involved in the incremental …
=> Use vim-range style (1-index based) when possible

README.md, queries/lua/injections.scm, queries/teal/injections.scm
=> injections(lua): fix cdef injection

lockfile.json, queries/cpp/highlights.scm, queries/cpp/locals.scm
These are fixes for the breaking changes in tree-sitter/tree-sitter-cpp#133
=> cpp: fix for breaking changes in tree-sitter-cpp

queries/vim/highlights.scm
This was just added some days ago.
=> Vim: highlight setlocal

queries/vim/highlights.scm
Rebased version of https://github.com/nvim-treesitter/nvim-treesitter/pull/1776/
=> fix(vim): support syntax command and update parser

queries/rust/highlights.scm
Closes https://github.com/nvim-treesitter/nvim-treesitter/issues/1856
=> Rust: fix some highlights

README.md, lua/nvim-treesitter/install.lua, lua/nvim-treesitter/shell_command_selectors.lua
=> feat(install): add options `prefer_git` and `command_extra_args`

queries/rust/highlights.scm
Closes https://github.com/nvim-treesitter/nvim-treesitter/issues/1891
=> Rust: highlight loop labels

queries/toml/highlights.scm
Merge from https://github.com/ikatyang/tree-sitter-toml/blob/master/queries/highlights.scm
=> Update toml highlight queries

ftdetect/fennel.vim
A simple fennel ftdetect file.
=> Add fennel ftdetect file

queries/python/highlights.scm
Reverts nvim-treesitter/nvim-treesitter#1955
=> Revert "Add `del` keyword to python highlights"

queries/svelte/injections.scm
=> feat(svelte): inject JS on `each` expression

README.md, lua/nvim-treesitter/configs.lua, lua/nvim-treesitter/install.lua
=> feat: sync install for `ensure_installed`

queries/r/highlights.scm
=> R new operator

lua/nvim-treesitter/parsers.lua, queries/http/highlights.scm, queries/http/injections.scm
All credit goes to @NTBBloodbath.
See: https://github.com/NTBBloodbath/rest.nvim/issues/75#issuecomment-960447966
Co-authored-by: NTBBloodbath <bloodbathalchemist@protonmail.com>
=> feat: add http parser

lua/nvim-treesitter/parsers.lua
CI is failing for stylua due to this.
=> Format with stylua

.github/ISSUE_TEMPLATE/bug_report.yml, README.md
We have had many of these recently...
=> Add `query error: invalid node type at position` to the troubleshooing section

queries/ecma/highlights.scm, tests/query/highlights/ecma/test.ts
=> ecma: highlight private properties and methods

doc/nvim-treesitter.txt, lua/nvim-treesitter/configs.lua
=> Add documentation for condition setting

README.md, ftdetect/prisma.vim, lua/nvim-treesitter/parsers.lua, queries/prisma/highlights.scm, tests/query/highlights/prisma/test.prisma
Still need to wait for https://github.com/LumaKernel/tree-sitter-prisma/pull/2, in the meantime we can use my fork to make it easier for those who want to try this out.
=> feat: add prisma support

queries/elm/highlights.scm, queries/elm/injections.scm
i took highlights from [the main repo](https://github.com/elm-tooling/tree-sitter-elm/blob/main/queries/highlights.scm) and adapted them, fixed some things that i considered a bit better :) @razzeee if in any way you are interested.
=> feat(elm): add first elm highlight

queries/ecma/injections.scm
Hi,
This is my first attempt at a contribution, any feedback welcome.
I've been monitoring #1111 and decided to try it myself.
I have more detailed messages in the commits, including which cases I've attempted to support.
I'm sure there are plenty of cases missing but I'm hoping this will be a good start.
If there is an easier, more generic way to handle more cases, please let me know.
=> Styled components injection

.github/workflows/update-readme.yml
Create a PR instead of pushing to unrelated PRs
=> ci: open PRs to update README

CONTRIBUTING.md
It was also missing Injections
=> Fix misleading text in `CONTRIBUTING.md`

scripts/minimal_init.lua, tests/query/injection_spec.lua, tests/query/injections/cuda/macro-self-injection.cu, tests/query/injections/yaml/bash-on-github-actions.yml
Based on #2061 (should be merged first)
=> Injection tests

lockfile.json, lua/nvim-treesitter/parsers.lua, queries/fusion/highlights.scm, tests/query/highlights/fusion/afx.fusion, tests/query/highlights/fusion/basic.fusion, tests/query/highlights/fusion/expressions.fusion
* introduces afx support
* fix highlights and queries
=> update fusion to version 1.1.1

queries/php/highlights.scm
Similar to https://github.com/tree-sitter/tree-sitter-php/blob/57f855461aeeca73bd4218754fb26b5ac143f98f/grammar.js#L130-L132
Closes https://github.com/nvim-treesitter/nvim-treesitter/issues/2156
=> PHP: highlight unset

lockfile.json, lua/nvim-treesitter/parsers.lua, queries/fusion/folds.scm, queries/fusion/highlights.scm, queries/fusion/indents.scm, queries/fusion/locals.scm
added some queries for 
* fold
* indent
* better highlight
I also removed the experimental flag, because to me it feels initially 'complete' now
=> feat(fusion): add indent and fold module

lua/nvim-treesitter/parsers.lua, queries/rasi/highlights.scm
Closes #2187
Signed-off-by: Fymyte <pierguill@gmail.com>
=> Add rasi parser

lockfile.json
=> fix(fusion): update lockfile to latest

queries/markdown/highlights.scm, tests/query/highlights/markdown/test.md
=> highlights(markdown): link and image enhancements

README.md, ftdetect/ninja.vim, lua/nvim-treesitter/parsers.lua, queries/ninja/folds.scm, queries/ninja/highlights.scm, queries/ninja/indents.scm
[Ninja build format](https://github.com/ninja-build/ninja).
Note. I used `string.special` for the paths.
=> Add ninja parser

queries/go/highlights.scm
Follow upstream change
https://github.com/tree-sitter/tree-sitter-go/commit/beb36fc9be211046d43a165eb8d885bcde6004a1
=> highlights(go): highlights "~"

lockfile.json, queries/llvm/highlights.scm
=> Update lockfile and import updated llvm highlights

after/ftdetect/foam.vim
Addresses #2224 as suggested there.
=> Force-ignore ignorecase option

lockfile.json, queries/java/highlights.scm, queries/java/indents.scm, queries/java/injections.scm
https://github.com/tree-sitter/tree-sitter-java/pull/93 introduced `line_comment` and `block_comment`
=> Update lockfile and apply necessary update for Java

README.md
Use all possible options to illustrate their usage
=> docs(readme): make custom parser example more explicit about options

scripts/check-queries.lua
Will add some more serious benchmarks later (also about parsing)
=> ci: print query loading times

README.md
[Neovim 0.5](https://github.com/neovim/neovim/commit/a5ac2f45ff84a688a09479f357a9909d5b914294) is shipped with experimental tree-sitter support, this should be reflected in the README as well.
=> Reword Neovim version requirement from README

lockfile.json, queries/cpp/highlights.scm, queries/cpp/locals.scm, tests/query/highlights/cpp/concepts.cpp
Requires https://github.com/tree-sitter/tree-sitter-cpp/pull/138
=> highlights(cpp): add support for concepts

queries/cpp/highlights.scm
This also bring full concepts support by bumping the C++ parser.
=> highlights(cpp): add support for "<=>", "constinit", "consteval"

CONTRIBUTING.md
- Mention Zulip instead of Gitter
- Use query filetype instead of scheme
=> docs: refresh CONTRIBUTING.md

CONTRIBUTING.md
As suggested here:
https://github.com/nvim-treesitter/nvim-treesitter/pull/2288#issuecomment-1015163267
=> docs(CONTRIBUTING.md): mention Neovim's tree-sitter Matrix channel

lua/nvim-treesitter/parsers.lua, queries/php/injections.scm, queries/phpdoc/highlights.scm
The parser already creates quite good results. It's definitely better than the current `comments` parser which does not really fit well with PHP.
=> Add phpdoc parser (experimental)

queries/vim/highlights.scm
Update vim highlights to include @Fymyte changes.
Also update the vim parser to ABI 14.
=> Update vim highlights

README.md
This seems to have been a problem for many people recently.
=> doc: stress need to :TSUpdate after lockfile change

queries/php/indents.scm, tests/indent/php/example.php, tests/indent/php_spec.lua
@JSteitz can you test this please?
I might add more advanced stuff like aligned parenthesis in #2333
=> Fix #2357: align PHP indents with what C does

queries/r/highlights.scm
1. highlight `string_escape`
2. change `parameter` priority
3. update pipe `operator` https://github.com/r-lib/tree-sitter-r/pull/27
=> highlights(r): update

lockfile.json, queries/python/highlights.scm, queries/python/locals.scm, tests/query/highlights/python/pattern_matching.py
Fixes #2080
Depends on https://github.com/tree-sitter/tree-sitter-python/pull/140
=> highlights(python): add support for pattern matching

lua/nvim-treesitter/health.lua
A more advanced version would use a similar strategy like the query linter to find the problematic s-expression
=> health: check which file caused an error

queries/d/highlights.scm
=> highlights(d): highlight ":"

.github/workflows/check-query-files-and-compilation.yml, .github/workflows/lint.yml
=> ci: only fix major version of vulnerable action

lua/nvim-treesitter/parsers.lua
* Add `scanner.c` 
* Move phpdoc config down to injected parsers
=> update(phpdoc) Add scanner.c

lua/nvim-treesitter/ts_utils.lua
Logic is incorrect (off-by-one error due to indexing I suppose?)
=> fix(utils): adjust truncation condition

lockfile.json, lua/nvim-treesitter/parsers.lua, queries/tlaplus/highlights.scm
Added @susliko to maintainers list.
=> Updated TLA+ version, queries, maintainers

queries/latex/injections.scm
=> injections(latex): minted package

tests/indent/graphql/issue-1981.graphql, tests/indent/graphql_spec.lua
Issue #1981
Test for issue that already has been solved.
=> tests: add indent test for graphql

tests/indent/c/issue-1568.c, tests/indent/c_spec.lua
Also this issue has already been fixed
#1568
=> tests: Add test for #1568

README.md
=> Update 'troubleshooting' for using mirror.

lua/nvim-treesitter/indent.lua, queries/python/indents.scm, tests/indent/c/issue-2086.c, tests/indent/c_spec.lua, tests/indent/common.lua, tests/indent/python_spec.lua
This shows that #2086 is resolved but shows some Problems with Python were we don't re-parser on new-line ~~and one test for Lua~~.
=> Add test for #2086 and test entering a new line when in insert mode

README.md
The title is descriptive, thanks for the work!
=> fix: readme typo, removing deprecated docs

lockfile.json, queries/python/locals.scm
=> Update python as_pattern

queries/vim/highlights.scm
Add queries for recently added keyword in parser
Closes: https://github.com/vigoux/tree-sitter-viml/issues/75
Signed-off-by: Fymyte <pierguill@gmail.com>
=> Vim: add highlight for more keyword

README.md, doc/nvim-treesitter.txt
=> chore: remove lua heredocs in documentation and readme

queries/php/indents.scm, tests/indent/php/issue-2497.php, tests/indent/php/unfinished-call.php, tests/indent/php_spec.lua
Fixes #2497
Can you test this please @yaegassy?
=> indents(php): don't use aligned_indent for php

lockfile.json, queries/vala/highlights.scm
Simplified grammar syntax, update highlights to reflect changes
=> highlights(vala): Coloring fixes

lockfile.json, queries/gleam/highlights.scm
=> fix(gleam): update parser and queries

.github/workflows/update-lockfile.yml
just to get the ball rolling again
@connorlay
=> ci: ignore gleam for lockfile update

lockfile.json, lua/nvim-treesitter/parsers.lua, queries/slint/highlights.scm, queries/slint/indents.scm
Is there anything else that needs to be changed to have this merged?
=> Add slint parser configuration and queries

lua/nvim-treesitter/shell_command_selectors.lua
=> Use gmake when available

lua/nvim-treesitter/install.lua
Alternative to #2627
We should still think of following just upstream with solidtiy
=> Follow install info branch

queries/fish/highlights.scm
Requires https://github.com/ram02z/tree-sitter-fish/pull/11
=> highlight(fish): dollar command substitution

ftdetect/cooklang.vim, lua/nvim-treesitter/parsers.lua, queries/cooklang/highlights.scm
I created a grammar for [cooklang](https://cooklang.org/), and I was wondering if I could merge it into nvim-treesitter?
Let me know if there's anything I should do/modify for best practices.
Thanks for this fantastic project!
=> Add Cooklang

queries/php/highlights.scm
=> highlights(php): argument name as parameter

.github/workflows/update-lockfile.yml
fixup for 739fefa8fa0c024a89b961bef14822f87fc13692
=> fixup: lock nix, not norg

README.md
...instead of `ftdetect` additions
=> doc: mention `vim.filetype.add()` in README

queries/r/indents.scm, tests/indent/r/func.R, tests/indent/r_spec.lua
```
Found:                                       Expected:
|foo <- function(x) {                        |foo <- function(x) {
|  bar <- function(a, b, c) {                |  bar <- function(a, b, c) {
|    return(a + b + c)                       |    return(a + b + c)
|  }                                         |  }
|  return(                                   |  return(
|    bar(                                    |    bar(
|      x,                                    |      x,
|      1,                                    |      1,
|      2                                     |      2
|    )                                       |    )
|  )                                         |  )
|}                                           |}
|                                            |
|baz <- …
```
=> r(indents): fix brace_list alignment

queries/python/highlights.scm, tests/query/highlights/python/yield_from.py
=> highlights(python): "from" in yield should be `@keyword.return`

README.md, lua/nvim-treesitter/parsers.lua, queries/rego/highlights.scm, queries/rego/injections.scm
Hi!
Here's a basic support for rego language 
https://www.openpolicyagent.org/docs/latest/policy-language/
=> Added the initial version for the support of rego language

queries/bash/highlights.scm
As per [#2732](https://github.com/nvim-treesitter/nvim-treesitter/issues/2732)
=> highlights(bash): add more builtins

lua/nvim-treesitter/parsers.lua, queries/astro/folds.scm, queries/astro/highlights.scm, queries/astro/indents.scm, queries/astro/injections.scm, queries/astro/locals.scm
This adds a parser for the Astro web framework. Fixes #1763.
=> feat: add astro parser

queries/json/highlights.scm
=> highlights(json): highlight ":"

README.md, lua/nvim-treesitter/parsers.lua, queries/scheme/folds.scm, queries/scheme/highlights.scm, queries/scheme/injections.scm
I added Scheme language support.
The query files can also get improved highlights automatically.
=> Add scheme support

README.md, ftdetect/wgsl.vim, lua/nvim-treesitter/parsers.lua, queries/wgsl/folds.scm, queries/wgsl/highlights.scm
I've added support for my [WebGPU Shading Language](https://www.w3.org/TR/WGSL/) parser.
I've created the `highlights` and `folds` queries.
=> Add WGSL parser

queries/latex/folds.scm, queries/latex/highlights.scm
Make use of parser updates
* add `\{re}newenvironment`
* add `\DeclarePairedDelimiter{X}`
* add `\title` and `\author`
* add optional arguments to sectioning commands
* use builtin nodes for math environments
=> latex: update queries

.github/ISSUE_TEMPLATE/highlighting_issue.yml
=> Fix backtick typo in highlighting issue template

.github/workflows/test-queries.yml, scripts/check-queries.lua
I think this was a nvim 0.6 issue
=> ci: don't skip swift anymore

queries/markdown/highlights.scm
@clason you were one second too fast :-)
=> highlights(markdown): fix conceal capture

queries/julia/highlights.scm
Add queries for NaNs, Infs and missing
Remove highlight to identifiers in coefficient expressions.
-------
@clason beat me to it in #2791, but there were still some changes I wanted to make. 🙃
=> highlights(julia): Update literals

.github/workflows/test-queries.yml
=> ci: remove all swift skips

.github/workflows/test-queries.yml, .github/workflows/tests.yml
@theHamsta now you were too fast :)
=> ci: bump tree-sitter to 0.20.6

queries/vim/highlights.scm
=> feat(vim): highlight unknown commands

lockfile.json, lua/nvim-treesitter/parsers.lua
=> feat(swift): switch to branch with generated files

lua/nvim-treesitter.lua
=> fix(statusline): don't use deprecated function

lua/nvim-treesitter.lua
Just a quick fix before the refactor recommended by @clason
=> fix(statusline): adjust to the new API (query)

lockfile.json, lua/nvim-treesitter/parsers.lua, queries/m68k/folds.scm, queries/m68k/highlights.scm, queries/m68k/injections.scm, queries/m68k/locals.scm
Adding my parser for Motorola 68000 assembly.
=> feat: add m68k parser and queries

lua/nvim-treesitter/parsers.lua, queries/proto/folds.scm, queries/proto/highlights.scm
Related to #2307.
First time doing this, so let me know if I did anything wrong. I did notice that the parser has some [queries predefined](https://github.com/mitchellh/tree-sitter-proto/tree/main/queries), so I wonder if we could use those?
=> feat(proto): add parser

.github/FUNDING.yml
=> chore: add github sponsors to FUNDING.yml

queries/vim/highlights.scm
Follows the latest changes in the VimL parser.
=> feat(vim): add support for const

queries/python/highlights.scm, tests/query/highlights/python/future_import.py
looks like future imports have their own node :man_shrugging:
=> Python: highlight future import

lua/nvim-treesitter/utils.lua
=> fix(commands): add -bar to allow other commands

queries/slint/highlights.scm
=> highlights(slint): highlight operators and more punctuation

queries/julia/highlights.scm
See tree-sitter/tree-sitter-julia#34
=> feat(highlights/julia): make operators visible

lua/nvim-treesitter/parsers.lua
should add the possibility to use this function with csharp files
=> make ft_to_lang work for csharp

queries/vim/folds.scm
(Vim) Add basic folding for if statements and functions 
Tested locally and looks good.
=> vim: add basic folding 

queries/yaml/indents.scm, tests/indent/yaml/autoindent-mapping-pair.yaml, tests/indent/yaml/indent-sequence-items.yaml, tests/indent/yaml_spec.lua
I believe this fixes the issues reported at #1377.
=> Fix some YAML indentation issues

lockfile.json, lua/nvim-treesitter/parsers.lua, queries/beancount/folds.scm
change folding queries to support folding org headers for beancount files
=> fix(beancount): support folding org headers

queries/haskell/highlights.scm
=> fix(haskell): priority 101 for infix function precedence over variable

queries/qmljs/folds.scm
=> add fold support to qml

queries/c/highlights.scm
Test program:
Comma punctuator highlight group:
Comma operator highlight group:
=> highlights(c): highlight `,` operator as operator

README.md, doc/nvim-treesitter.txt, lua/nvim-treesitter/configs.lua, lua/nvim-treesitter/install.lua
Just putting this out here for further discussion. I tested it and it seems to work fine.
Closes #2108.
=> feat: add option to auto-install missing parsers

queries/haskell/folds.scm
support fold method of haskell
=> support the fold of haskell

queries/hcl/injections.scm
Add a heredoc language injection similar to Ruby for HCL. This allows terraform resources like this to be properly highlighted
```hcl
resource "aws_iam_role" "sample" {
name               = "sample"
assume_role_policy = <<JSON
{
"Version": "2012-10-17",
"Statement": [
{
"Action": "sts:AssumeRole",
"Principal": {
"AWS": "*"
},
"Effect": "Allow",
"Sid": ""
}
]
}
JSON
}
```
Screenshot of the above code:
and the parse tree generate by treesitter
<details>
<summary>Parse tree</summary>
```
body [0, 0] - [17, 1]
block [0, 0] - [17, 1]
identifier [0, 0] - [0, 8]
string_lit [0, 9] - [0, 23]
quoted_template_start [0, 9] - [0, 10]
template_literal [0, 10] - [0, 22]
quoted_template_end [0, 22] - [0, 23]
string_lit [0, 24] - [0, 32]
quoted_template_start [0, 24] - [0, 25]
template_literal [0, 25] - …
```
=> Add heredoc language injection for HCL

queries/erlang/folds.scm, queries/erlang/highlights.scm
=> feat(erlang highlight): support erlang highlight

queries/erlang/folds.scm
I have foget to let (module_export) can be fold
=> add (module_export) to folds

queries/erlang/highlights.scm
move try catch throw to exception
=> fix(exception): erlang exception

lockfile.json, lua/nvim-treesitter/parsers.lua, queries/vala/highlights.scm
Use the grammar from https://github.com/vala-lang/tree-sitter-vala
This grammar seems to work better on more inputs and is maintained more frequently.
=> vala: use grammar from @vala-lang

.github/workflows/update-lockfile.yml, lockfile.json
=> Fix dart crash

queries/qmljs/folds.scm
I have foget add ui_binding to fold
=> add ui_binding to fold

autoload/nvim_treesitter.vim, lua/nvim-treesitter.lua, lua/nvim-treesitter/statusline.lua
just a small refactor to put things in the right place. This is non breaking.
=> chore: cleanup main file, move statusline in module

queries/clojure/highlights.scm
=> Change to using an explicit list of "def-likes" for clojure

lua/nvim-treesitter/incremental_selection.lua
=> fix: node_incremental for incremental selection jumping around

.github/workflows/update-lockfile.yml, lockfile.json
Segfault seems to be fixed in
https://github.com/UserNobody14/tree-sitter-dart/commit/c667fd401c736e208c73b7bb9267557b67b23491
After 30min of fuzzing no Segfault found so far.
=> parsers(dart): unlock dart parser

queries/vala/folds.scm
New highlight is good enough
so I just add folds support
=> add folds.scm to vala

lua/nvim-treesitter/health.lua
=> chore: trim space in check-health

queries/go/injections.scm
=> injections(go): avoid running queries on all comments

lockfile.json, queries/ql/highlights.scm
Follow upstream refactor in https://github.com/tree-sitter/tree-sitter-ql/commit/13155b740d4040e74727a9a698277805498a6a85
=> Update ql for update in module expressions

queries/swift/highlights.scm
Introduced in https://github.com/alex-pinkus/tree-sitter-swift/commit/07bdffb5e6f34fb1e578f31b653479d7c4d6306c
@alex-pinkus
=> highlights(swift): add keywords "actor", "nonisolated"

lua/nvim-treesitter/parsers.lua, queries/hlsl/folds.scm, queries/hlsl/highlights.scm, queries/hlsl/indents.scm, queries/hlsl/injections.scm, queries/hlsl/locals.scm
WIP I have little experience with HLSL. So I'm exploring the features for while...
=> parsers: add HLSL

lockfile.json, queries/ecma/highlights.scm, queries/javascript/highlights.scm, queries/typescript/highlights.scm
Follow upstream change in https://github.com/tree-sitter/tree-sitter-javascript/pull/225
Let's see whether TS already has this change
=> Update JS for upstream "Optional chain" change

queries/lua/injections.scm
=> injections(lua): highlight string as `query` if starts with `;; query`

lockfile.json, queries/dot/highlights.scm
Sync changes from the upstream repo.
=> highlights(DOT): update keywords

queries/markdown/folds.scm
relative issue https://github.com/nvim-treesitter/nvim-treesitter/issues/2145
=> feat: allow to fold markdown sections

lua/nvim-treesitter/parsers.lua, queries/meson/folds.scm, queries/meson/highlights.scm
I write a treesitter for meson build, and I have tried it myself, I think the treesitter works good
=> feat(meson): add support for meson

queries/meson/injections.scm
add comment as injections as other languages like bash
Log: add injections for meson
=> chore(meson): add injections for meson

queries/agda/highlights.scm
Add highlight for bool
add highlight for function
Log: better highlight
=> feat(agda): better highlight

queries/qmljs/highlights.scm
boolean is not in the right color, so fix it
Log: fix the color of boolean for qmljs
=> feat(qmljs): boolean

lockfile.json, lua/nvim-treesitter/parsers.lua
tree-sitter-verilog was updated to a more recent tree-sitter version
=> feat(verilog): update version

queries/meson/highlights.scm
| Before                                                                                                         | After                                                                                                          |
| -------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------- |
| ![image](https://user-images.githubusercontent.com/4299733/188704216-e4cf59df-a00e-4587-9192-a67f175592f1.png) | ![image](https://user-images.githubusercontent.com/4299733/188704134-efdcf475-7a82-43a5-b4e4-63777da5c772.png) |
=> highlights(meson): delimiter and operatorunit

CONTRIBUTING.md, queries/ruby/highlights.scm
Adds global variable highlights to ruby.
=> [Ruby] Add global variable highlighting

queries/css/highlights.scm
Apply fix as suggested by https://github.com/binhtran432k in https://github.com/nvim-treesitter/nvim-treesitter/issues/3395
Fixes #3395
Co-authored-by: Trần Đức Bình <binhtran432k@users.noreply.github.com>
=> highlights(css): fix property highlighting

lua/nvim-treesitter/parsers.lua, queries/blueprint/highlights.scm
You can find the parser [in this repo](https://gitlab.com/gabmus/tree-sitter-blueprint).
=> parsers: add blueprint parser

lockfile.json, queries/sql/highlights.scm
* added keywords for pattern matching
* remove duplicate keywords
* added hashing functions as `@function.call`
=> highlights(sql): include new keywords

lua/nvim-treesitter/parsers.lua
The grammar is missing most [language features](https://pugjs.org/api/getting-started.html).
=> chore(pug): mark as experimental

README.md, lua/nvim-treesitter/parsers.lua, queries/twig/highlights.scm, queries/twig/injections.scm
Add [twig](https://github.com/twigphp/Twig) parser.
Twig website : https://twig.symfony.com
Parser is [here](https://github.com/gbprod/tree-sitter-twig)
:)
=> Introduce twig parser

lua/nvim-treesitter/highlight.lua
This is just being a good citizen for people that already define highlights :wink:
=> fix: don't overwrite highlights when defining

queries/php/folds.scm
Some php folds was missing, I think it' almost complete now :)
=> feat(php): improve php folds

queries/php/injections.scm
This commit allows to inject bash syntax into relevant function arguments and shell expression.
=> feat(php): add queries for bash injections
